Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_context_wrapper.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_context_wrapper.h File Reference
#include <vector>
#include <memory>
#include <nan.h>
#include <stdlib.h>
#include <sass_context.h>
#include "custom_function_bridge.h"
#include "custom_importer_bridge.h"
Data Structures
struct sass_context_wrapper
Functions
void compile_data (struct Sass_Data_Context *dctx)
void compile_file (struct Sass_File_Context *fctx)
void compile_it (uv_work_t *req)
struct sass_context_wrapper * sass_make_context_wrapper (void)
void sass_free_context_wrapper (struct sass_context_wrapper *)
Function Documentation
void compile_data (struct Sass_Data_Context * dctx)
Definition at line 17 of file sass_context_wrapper.cpp.
References sass_compile_data_context().
Referenced by compile_it(), and NAN_METHOD().
void compile_file (struct Sass_File_Context * fctx)
Definition at line 21 of file sass_context_wrapper.cpp.
References sass_compile_file_context().
Referenced by compile_it(), and NAN_METHOD().
void compile_it (uv_work_t * req)
Definition at line 6 of file sass_context_wrapper.cpp.
References compile_data(), compile_file(), sass_context_wrapper::dctx, sass_context_wrapper::fctx, and if.
Referenced by NAN_METHOD().
void sass_free_context_wrapper (struct sass_context_wrapper *)
Definition at line 29 of file sass_context_wrapper.cpp.
References sass_context_wrapper::dctx, sass_context_wrapper::error_callback, sass_context_wrapper::fctx, sass_context_wrapper::function_bridges, sass_context_wrapper::importer_bridges, sass_context_wrapper::include_path, sass_context_wrapper::indent, sass_context_wrapper::linefeed, sass_context_wrapper::out_file, p(), PersistentBase< T >::Reset(), sass_context_wrapper::result, sass_delete_data_context(), sass_delete_file_context(), sass_context_wrapper::source_map, sass_context_wrapper::source_map_root, and sass_context_wrapper::success_callback.
Referenced by MakeCallback(), and NAN_METHOD().
struct sass_context_wrapper* sass_make_context_wrapper (void) [read]
Definition at line 25 of file sass_context_wrapper.cpp.
Referenced by NAN_METHOD().