Emeraldion Lodge (codename Zelda): Plugins Class Reference
Plugins Class Reference
#include <plugins.hpp>
Public Member Functions
Plugins (void)
~Plugins (void)
bool load_plugin (const string &path)
size_t load_plugins (const string &path)
const vector< Sass_Importer_Entry > get_headers (void)
const vector< Sass_Importer_Entry > get_importers (void)
const vector< Sass_Function_Entry > get_functions (void)
Private Attributes
vector< Sass_Importer_Entry > headers
vector< Sass_Importer_Entry > importers
vector< Sass_Function_Entry > functions
Detailed Description
Definition at line 32 of file plugins.hpp.
Constructor & Destructor Documentation
Plugins (void)
Definition at line 18 of file plugins.cpp.
~Plugins (void)
Definition at line 19 of file plugins.cpp.
Member Function Documentation
const vector<Sass_Function_Entry> get_functions (void) [inline]
Definition at line 47 of file plugins.hpp.
const vector<Sass_Importer_Entry> get_headers (void) [inline]
Definition at line 45 of file plugins.hpp.
References Plugins::headers.
const vector<Sass_Importer_Entry> get_importers (void) [inline]
Definition at line 46 of file plugins.hpp.
References Plugins::importers.
bool load_plugin (const string & path)
Definition at line 44 of file plugins.cpp.
References CLOSE_LIB, Sass::compatibility(), Plugins::functions, Plugins::headers, Plugins::importers, LOAD_LIB, and LOAD_LIB_FN.
Referenced by Plugins::load_plugins().
size_t load_plugins (const string & path)
Definition at line 98 of file plugins.cpp.
References Sass::UTF_8::convert_from_utf16(), Sass::UTF_8::convert_to_utf16(), Sass::ends_with(), and Plugins::load_plugin().
Field Documentation
vector<Sass_Function_Entry> functions [private]
Definition at line 52 of file plugins.hpp.
Referenced by Plugins::load_plugin().
vector<Sass_Importer_Entry> headers [private]
Definition at line 47 of file plugins.hpp.
Referenced by Plugins::get_headers(), and Plugins::load_plugin().
vector<Sass_Importer_Entry> importers [private]
Definition at line 51 of file plugins.hpp.
Referenced by Plugins::get_importers(), and Plugins::load_plugin().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/plugins.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/plugins.cpp