Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/json.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/json.cpp File Reference
#include "json.hpp"
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct SB
Defines
#define out_of_memory()
#define sb_need(sb, need)
#define sb_putc(sb, c)
#define is_space(c) ((c) == '\t' || (c) == '\n' || (c) == '\r' || (c) == ' ')
#define is_digit(c) ((c) >= '0' && (c) <= '9')
#define problem(...)
Functions
static char * json_strdup (const char *str)
static void sb_init (SB *sb)
static void sb_grow (SB *sb, int need)
static void sb_put (SB *sb, const char *bytes, int count)
static void sb_puts (SB *sb, const char *str)
static char * sb_finish (SB *sb)
static void sb_free (SB *sb)
static int utf8_validate_cz (const char *s)
static bool utf8_validate (const char *s)
static int utf8_read_char (const char *s, uint32_t *out)
static int utf8_write_char (uint32_t unicode, char *out)
static bool from_surrogate_pair (uint16_t uc, uint16_t lc, uint32_t *unicode)
static void to_surrogate_pair (uint32_t unicode, uint16_t *uc, uint16_t *lc)
static bool parse_value (const char **sp, JsonNode **out)
static bool parse_string (const char **sp, char **out)
static bool parse_number (const char **sp, double *out)
static bool parse_array (const char **sp, JsonNode **out)
static bool parse_object (const char **sp, JsonNode **out)
static bool parse_hex16 (const char **sp, uint16_t *out)
static bool expect_literal (const char **sp, const char *str)
static void skip_space (const char **sp)
static void emit_value (SB *out, const JsonNode *node)
static void emit_value_indented (SB *out, const JsonNode *node, const char *space, int indent_level)
static void emit_string (SB *out, const char *str)
static void emit_number (SB *out, double num)
static void emit_array (SB *out, const JsonNode *array)
static void emit_array_indented (SB *out, const JsonNode *array, const char *space, int indent_level)
static void emit_object (SB *out, const JsonNode *object)
static void emit_object_indented (SB *out, const JsonNode *object, const char *space, int indent_level)
static int write_hex16 (char *out, uint16_t val)
static JsonNode * mknode (JsonTag tag)
static void append_node (JsonNode *parent, JsonNode *child)
static void prepend_node (JsonNode *parent, JsonNode *child)
static void append_member (JsonNode *object, char *key, JsonNode *value)
static bool tag_is_valid (unsigned int tag)
static bool number_is_valid (const char *num)
JsonNode * json_decode (const char *json)
char * json_encode (const JsonNode *node)
char * json_encode_string (const char *str)
char * json_stringify (const JsonNode *node, const char *space)
void json_delete (JsonNode *node)
bool json_validate (const char *json)
JsonNode * json_find_element (JsonNode *array, int index)
JsonNode * json_find_member (JsonNode *object, const char *name)
JsonNode * json_first_child (const JsonNode *node)
JsonNode * json_mknull (void)
JsonNode * json_mkbool (bool b)
static JsonNode * mkstring (char *s)
JsonNode * json_mkstring (const char *s)
JsonNode * json_mknumber (double n)
JsonNode * json_mkarray (void)
JsonNode * json_mkobject (void)
void json_append_element (JsonNode *array, JsonNode *element)
void json_prepend_element (JsonNode *array, JsonNode *element)
void json_append_member (JsonNode *object, const char *key, JsonNode *value)
void json_prepend_member (JsonNode *object, const char *key, JsonNode *value)
void json_remove_from_parent (JsonNode *node)
bool json_check (const JsonNode *node, char errmsg[256])
Define Documentation
#define is_digit (c) ((c) >= '0' && (c) <= '9')
Definition at line 356 of file json.cpp.
Referenced by parse_number().
#define is_space (c) ((c) == '\t' || (c) == '\n' || (c) == '\r' || (c) == ' ')
Definition at line 355 of file json.cpp.
Referenced by skip_space().
#define out_of_memory ()
Value:
do {                    \
    fprintf(stderr, "Out of memory.\n");    \
    exit(EXIT_FAILURE);                     \
  } while (0)
Definition at line 62 of file json.cpp.
Referenced by json_strdup(), mknode(), Sass::sass_strdup(), sb_grow(), and sb_init().
#define problem (...)
Value:
do { \
      if (errmsg != NULL) \
        snprintf(errmsg, 256, __VA_ARGS__); \
      return false; \
    } while (0)
Referenced by json_check().
#define sb_need (sb, need)
Value:
do {                  \
    if ((sb)->end - (sb)->cur < (need))     \
      sb_grow(sb, need);                  \
  } while (0)
Definition at line 96 of file json.cpp.
Referenced by emit_string(), parse_string(), and sb_put().
#define sb_putc (sb, c)
Value:
do {         \
    if ((sb)->cur >= (sb)->end) \
      sb_grow(sb, 1);         \
    *(sb)->cur++ = (c);         \
  } while (0)
Definition at line 124 of file json.cpp.
Referenced by emit_array(), emit_array_indented(), emit_object(), and emit_object_indented().
Function Documentation
static void append_member (JsonNode * object, char * key, JsonNode * value) [static]
Definition at line 589 of file json.cpp.
References append_node(), and JsonNode::key.
Referenced by json_append_member(), and parse_object().
static void append_node (JsonNode * parent, JsonNode * child) [static]
Definition at line 563 of file json.cpp.
References JsonNode::children, JsonNode::next, JsonNode::parent, and JsonNode::prev.
Referenced by append_member(), and json_append_element().
static void emit_array (SB * out, const JsonNode * array) [static]
Definition at line 1055 of file json.cpp.
References emit_value(), json_foreach, JsonNode::next, and sb_putc.
Referenced by emit_value().
static void emit_array_indented (SB * out, const JsonNode * array, const char * space, int indent_level) [static]
Definition at line 1068 of file json.cpp.
References JsonNode::children, emit_value_indented(), JsonNode::next, sb_putc, and sb_puts().
Referenced by emit_value_indented().
static void emit_number (SB * out, double num) [static]
Definition at line 1252 of file json.cpp.
References number_is_valid(), and sb_puts().
Referenced by emit_value(), and emit_value_indented().
static void emit_object (SB * out, const JsonNode * object) [static]
Definition at line 1092 of file json.cpp.
References emit_string(), emit_value(), json_foreach, JsonNode::key, JsonNode::next, and sb_putc.
Referenced by emit_value().
static void emit_object_indented (SB * out, const JsonNode * object, const char * space, int indent_level) [static]
Definition at line 1107 of file json.cpp.
References emit_string(), emit_value_indented(), JsonNode::key, JsonNode::next, sb_putc, and sb_puts().
Referenced by emit_value_indented().
void emit_string (SB * out, const char * str) [static]
Definition at line 1133 of file json.cpp.
References SB::cur, s(), sb_need, to_surrogate_pair(), Sass::Prelexer::unicode(), utf8_read_char(), utf8_validate(), utf8_validate_cz(), and write_hex16().
Referenced by emit_object(), emit_object_indented(), emit_value(), emit_value_indented(), and json_encode_string().
static void emit_value (SB * out, const JsonNode * node) [static]
Definition at line 1001 of file json.cpp.
References JsonNode::bool_, emit_array(), emit_number(), emit_object(), emit_string(), JSON_ARRAY, JSON_BOOL, JSON_NULL, JSON_NUMBER, JSON_OBJECT, JSON_STRING, JsonNode::number_, sb_puts(), JsonNode::string_, JsonNode::tag, and tag_is_valid().
Referenced by emit_array(), emit_object(), and json_stringify().
void emit_value_indented (SB * out, const JsonNode * node, const char * space, int indent_level) [static]
Definition at line 1028 of file json.cpp.
References JsonNode::bool_, emit_array_indented(), emit_number(), emit_object_indented(), emit_string(), JSON_ARRAY, JSON_BOOL, JSON_NULL, JSON_NUMBER, JSON_OBJECT, JSON_STRING, JsonNode::number_, sb_puts(), JsonNode::string_, JsonNode::tag, and tag_is_valid().
Referenced by emit_array_indented(), emit_object_indented(), and json_stringify().
static bool expect_literal (const char ** sp, const char * str) [static]
Definition at line 1279 of file json.cpp.
References s().
Referenced by parse_value().
static bool from_surrogate_pair (uint16_t uc, uint16_t lc, uint32_t * unicode) [static]
Definition at line 329 of file json.cpp.
Referenced by parse_string().
void json_append_element (JsonNode * array, JsonNode * element)
Definition at line 595 of file json.cpp.
References append_node(), JSON_ARRAY, JsonNode::parent, and JsonNode::tag.
Referenced by SourceMap::generate_source_map(), and parse_array().
void json_append_member (JsonNode * object, const char * key, JsonNode * value)
Definition at line 611 of file json.cpp.
References append_member(), JSON_OBJECT, json_strdup(), JsonNode::parent, and JsonNode::tag.
Referenced by SourceMap::generate_source_map(), and handle_errors().
bool json_check (const JsonNode * node, char errmsg[256])
Definition at line 1340 of file json.cpp.
References JsonNode::bool_, JsonNode::children, JSON_ARRAY, JSON_BOOL, json_check(), JSON_OBJECT, JSON_STRING, JsonNode::key, JsonNode::next, JsonNode::prev, problem, JsonNode::string_, JsonNode::tag, tag_is_valid(), and utf8_validate().
Referenced by json_check().
JsonNode* json_decode (const char * json)
Definition at line 388 of file json.cpp.
References json_delete(), parse_value(), s(), and skip_space().
void json_delete (JsonNode * node)
Definition at line 434 of file json.cpp.
References JsonNode::children, JSON_ARRAY, json_delete(), JSON_OBJECT, json_remove_from_parent(), JSON_STRING, JsonNode::next, utf8::unchecked::next(), JsonNode::string_, and JsonNode::tag.
Referenced by SourceMap::generate_source_map(), handle_errors(), json_decode(), json_delete(), parse_array(), and parse_object().
char* json_encode (const JsonNode * node)
Definition at line 406 of file json.cpp.
References json_stringify().
char* json_encode_string (const char * str)
Definition at line 411 of file json.cpp.
References emit_string(), sb_finish(), and sb_init().
JsonNode* json_find_element (JsonNode * array, int index)
Definition at line 475 of file json.cpp.
References JSON_ARRAY, json_foreach, and JsonNode::tag.
JsonNode* json_find_member (JsonNode * object, const char * name)
Definition at line 492 of file json.cpp.
References json_foreach, JSON_OBJECT, JsonNode::key, and JsonNode::tag.
JsonNode* json_first_child (const JsonNode * node)
Definition at line 506 of file json.cpp.
References JsonNode::children, JSON_ARRAY, JSON_OBJECT, and JsonNode::tag.
JsonNode* json_mkarray (void)
Definition at line 553 of file json.cpp.
References JSON_ARRAY, and mknode().
Referenced by SourceMap::generate_source_map(), and parse_array().
JsonNode* json_mkbool (bool b)
Definition at line 527 of file json.cpp.
References JsonNode::bool_, JSON_BOOL, and mknode().
Referenced by parse_value().
JsonNode* json_mknull (void)
Definition at line 522 of file json.cpp.
References JSON_NULL, and mknode().
Referenced by parse_value().
JsonNode* json_mknumber (double n)
Definition at line 546 of file json.cpp.
References JSON_NUMBER, mknode(), and JsonNode::number_.
Referenced by SourceMap::generate_source_map(), handle_errors(), and parse_value().
JsonNode* json_mkobject (void)
Definition at line 558 of file json.cpp.
References JSON_OBJECT, and mknode().
Referenced by SourceMap::generate_source_map(), handle_errors(), and parse_object().
JsonNode* json_mkstring (const char * s)
Definition at line 541 of file json.cpp.
References json_strdup(), and mkstring().
Referenced by SourceMap::generate_source_map(), and handle_errors().
void json_prepend_element (JsonNode * array, JsonNode * element)
Definition at line 603 of file json.cpp.
References JSON_ARRAY, JsonNode::parent, prepend_node(), and JsonNode::tag.
void json_prepend_member (JsonNode * object, const char * key, JsonNode * value)
Definition at line 619 of file json.cpp.
References JSON_OBJECT, json_strdup(), JsonNode::key, JsonNode::parent, prepend_node(), and JsonNode::tag.
void json_remove_from_parent (JsonNode * node)
Definition at line 628 of file json.cpp.
References JsonNode::children, JsonNode::key, JsonNode::next, JsonNode::parent, and JsonNode::prev.
Referenced by json_delete().
static char* json_strdup (const char * str) [static]
Definition at line 68 of file json.cpp.
References out_of_memory.
Referenced by json_append_member(), json_mkstring(), and json_prepend_member().
char* json_stringify (const JsonNode * node, const char * space)
Definition at line 421 of file json.cpp.
References emit_value(), emit_value_indented(), sb_finish(), and sb_init().
Referenced by SourceMap::generate_source_map(), handle_errors(), and json_encode().
bool json_validate (const char * json)
Definition at line 460 of file json.cpp.
References parse_value(), s(), and skip_space().
static JsonNode * mknode (JsonTag tag) [static]
Definition at line 513 of file json.cpp.
References out_of_memory, and JsonNode::tag.
Referenced by json_mkarray(), json_mkbool(), json_mknull(), json_mknumber(), json_mkobject(), and mkstring().
static JsonNode* mkstring (char * s) [static]
Definition at line 534 of file json.cpp.
References JSON_STRING, mknode(), and JsonNode::string_.
Referenced by json_mkstring(), and parse_value().
static bool number_is_valid (const char * num) [static]
Definition at line 1274 of file json.cpp.
References parse_number().
Referenced by emit_number().
static bool parse_array (const char ** sp, JsonNode ** out) [static]
Definition at line 720 of file json.cpp.
References json_append_element(), json_delete(), json_mkarray(), parse_value(), s(), and skip_space().
Referenced by parse_value().
static bool parse_hex16 (const char ** sp, uint16_t * out) [static]
Definition at line 1295 of file json.cpp.
References s().
Referenced by parse_string().
bool parse_number (const char ** sp, double * out) [static]
Definition at line 945 of file json.cpp.
References is_digit, and s().
Referenced by number_is_valid(), and parse_value().
static bool parse_object (const char ** sp, JsonNode ** out) [static]
Definition at line 764 of file json.cpp.
References append_member(), json_delete(), json_mkobject(), parse_string(), parse_value(), s(), and skip_space().
Referenced by parse_value().
bool parse_string (const char ** sp, char ** out) [static]
Definition at line 820 of file json.cpp.
References SB::cur, from_surrogate_pair(), parse_hex16(), s(), sb_finish(), sb_free(), sb_init(), sb_need, Sass::Prelexer::unicode(), utf8_validate_cz(), and utf8_write_char().
Referenced by parse_object(), and parse_value().
static bool parse_value (const char ** sp, JsonNode ** out) [static]
Definition at line 650 of file json.cpp.
References expect_literal(), json_mkbool(), json_mknull(), json_mknumber(), mkstring(), parse_array(), parse_number(), parse_object(), parse_string(), and s().
Referenced by json_decode(), json_validate(), parse_array(), and parse_object().
static void prepend_node (JsonNode * parent, JsonNode * child) [static]
Definition at line 576 of file json.cpp.
References JsonNode::children, JsonNode::next, JsonNode::parent, and JsonNode::prev.
Referenced by json_prepend_element(), and json_prepend_member().
static char* sb_finish (SB * sb) [static]
Definition at line 135 of file json.cpp.
References SB::cur, and SB::start.
Referenced by json_encode_string(), json_stringify(), and parse_string().
static void sb_free (SB * sb) [static]
Definition at line 142 of file json.cpp.
References SB::start.
Referenced by parse_string().
static void sb_grow (SB * sb, int need) [static]
Definition at line 101 of file json.cpp.
References SB::cur, SB::end, out_of_memory, and SB::start.
static void sb_init (SB * sb) [static]
Definition at line 86 of file json.cpp.
References SB::cur, SB::end, out_of_memory, and SB::start.
Referenced by json_encode_string(), json_stringify(), and parse_string().
static void sb_put (SB * sb, const char * bytes, int count) [static]
Definition at line 117 of file json.cpp.
References SB::cur, and sb_need.
Referenced by sb_puts().
static void sb_puts (SB * sb, const char * str) [static]
Definition at line 130 of file json.cpp.
References sb_put().
Referenced by emit_array_indented(), emit_number(), emit_object_indented(), emit_value(), and emit_value_indented().
static void skip_space (const char ** sp) [static]
Definition at line 993 of file json.cpp.
References is_space, and s().
Referenced by json_decode(), json_validate(), parse_array(), and parse_object().
static bool tag_is_valid (unsigned int tag) [static]
Definition at line 1269 of file json.cpp.
References JSON_OBJECT.
Referenced by emit_value(), emit_value_indented(), and json_check().
static void to_surrogate_pair (uint32_t unicode, uint16_t * uc, uint16_t * lc) [static]
Definition at line 344 of file json.cpp.
Referenced by emit_string().
static int utf8_read_char (const char * s, uint32_t * out) [static]
Definition at line 253 of file json.cpp.
References utf8_validate_cz().
Referenced by emit_string().
static bool utf8_validate (const char * s) [static]
Definition at line 233 of file json.cpp.
References utf8_validate_cz().
Referenced by emit_string(), and json_check().
static int utf8_validate_cz (const char * s) [static]
Definition at line 178 of file json.cpp.
Referenced by emit_string(), parse_string(), utf8_read_char(), and utf8_validate().
static int utf8_write_char (uint32_t unicode, char * out) [static]
Definition at line 292 of file json.cpp.
Referenced by parse_string().
static int write_hex16 (char * out, uint16_t val) [static]
Definition at line 1328 of file json.cpp.
References Sass::Prelexer::hex().
Referenced by emit_string().