Emeraldion Lodge (codename Zelda): SassValueWrapper< T > Class Template Reference
SassValueWrapper< T > Class Template Reference
#include <sass_value_wrapper.h>
Inherits SassTypes::Value.
Public Member Functions
SassValueWrapper (Sass_Value *)
virtual ~SassValueWrapper ()
Sass_Value * get_sass_value ()
v8::Local< v8::Object > get_js_object ()
Static Public Member Functions
static char const * get_constructor_name ()
static v8::Local< v8::Function > get_constructor ()
static v8::Local
< v8::FunctionTemplate > get_constructor_template ()
static NAN_METHOD (New)
static Sass_Value * fail (const char *, Sass_Value **)
Static Protected Member Functions
static T * unwrap (v8::Local< v8::Object >)
Protected Attributes
Sass_Value * value
Private Attributes
Nan::Persistent< v8::Object > js_object
Static Private Attributes
static Nan::Persistent
< v8::Function > constructor
Detailed Description
template<class T>
class SassTypes::SassValueWrapper< T >
Definition at line 15 of file sass_value_wrapper.h.
Constructor & Destructor Documentation
SassValueWrapper (Sass_Value * v) [inline]
Definition at line 43 of file sass_value_wrapper.h.
References sass_clone_value(), and SassValueWrapper< T >::value.
~SassValueWrapper () [inline, virtual]
Definition at line 48 of file sass_value_wrapper.h.
References SassValueWrapper< T >::js_object, PersistentBase< T >::Reset(), sass_delete_value(), and SassValueWrapper< T >::value.
Member Function Documentation
Sass_Value * fail (const char * reason, Sass_Value ** out) [inline, static]
Definition at line 126 of file sass_value_wrapper.h.
References sass_make_error().
v8::Local< v8::Function > get_constructor () [inline, static]
Definition at line 82 of file sass_value_wrapper.h.
References SassValueWrapper< T >::constructor, Nan::GetFunction(), PersistentBase< T >::IsEmpty(), New(), and PersistentBase< T >::Reset().
static char const* get_constructor_name () [inline, static]
Reimplemented in Color, Error, List, Map, Number, and String.
Definition at line 17 of file sass_value_wrapper.h.
v8::Local< v8::FunctionTemplate > get_constructor_template () [inline, static]
Definition at line 71 of file sass_value_wrapper.h.
References EscapableHandleScope::Escape(), and New().
v8::Local< v8::Object > get_js_object () [inline, virtual]
Implements Value.
Definition at line 59 of file sass_value_wrapper.h.
References Nan::GetInternalFieldPointer(), PersistentBase< T >::IsEmpty(), SassValueWrapper< T >::js_object, New(), NewInstance(), PersistentBase< T >::Reset(), and Nan::SetInternalFieldPointer().
Sass_Value * get_sass_value () [inline, virtual]
Implements Value.
Definition at line 54 of file sass_value_wrapper.h.
References sass_clone_value(), and SassValueWrapper< T >::value.
static NAN_METHOD (New) [static]
T * unwrap (v8::Local< v8::Object > obj) [inline, static, protected]
Definition at line 120 of file sass_value_wrapper.h.
Field Documentation
Nan::Persistent< v8::Function > constructor [inline, static, private]
Definition at line 35 of file sass_value_wrapper.h.
Referenced by SassValueWrapper< T >::get_constructor().
Nan::Persistent<v8::Object> js_object [private]
Definition at line 36 of file sass_value_wrapper.h.
Referenced by SassValueWrapper< T >::get_js_object(), and SassValueWrapper< T >::~SassValueWrapper().
Sass_Value* value [protected]
Definition at line 31 of file sass_value_wrapper.h.
Referenced by SassValueWrapper< T >::get_sass_value(), SassValueWrapper< T >::SassValueWrapper(), and SassValueWrapper< T >::~SassValueWrapper().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/sass_value_wrapper.h