Emeraldion Lodge (codename Zelda): Maybe< T > Class Template Reference
Maybe< T > Class Template Reference
#include <nan_maybe_pre_43_inl.h>
Public Member Functions
NAN_INLINE bool IsNothing () const
NAN_INLINE bool IsJust () const
NAN_INLINE T FromJust () const
NAN_INLINE T FromMaybe (const T &default_value) const
NAN_INLINE bool operator== (const Maybe &other) const
NAN_INLINE bool operator!= (const Maybe &other) const
Private Member Functions
Maybe ()
Maybe (const T &t)
Private Attributes
bool has_value_
T value_
Friends
template<typename U >
Maybe< U > Nothing ()
template<typename U >
Maybe< U > Just (const U &u)
Detailed Description
template<typename T>
class Maybe< T >
Definition at line 50 of file nan_maybe_pre_43_inl.h.
Constructor & Destructor Documentation
Maybe () [inline, private]
Definition at line 76 of file nan_maybe_pre_43_inl.h.
Maybe (const T & t) [inline, explicit, private]
Definition at line 77 of file nan_maybe_pre_43_inl.h.
Member Function Documentation
NAN_INLINE T FromJust () const [inline]
Definition at line 55 of file nan_maybe_pre_43_inl.h.
References Maybe< T >::IsJust(), and Maybe< T >::value_.
Referenced by Maybe< T >::operator==().
NAN_INLINE T FromMaybe (const T & default_value) const [inline]
Definition at line 62 of file nan_maybe_pre_43_inl.h.
References Maybe< T >::has_value_, and Maybe< T >::value_.
NAN_INLINE bool IsJust () const [inline]
Definition at line 53 of file nan_maybe_pre_43_inl.h.
References Maybe< T >::has_value_.
Referenced by Maybe< T >::FromJust(), and Maybe< T >::operator==().
NAN_INLINE bool IsNothing () const [inline]
Definition at line 52 of file nan_maybe_pre_43_inl.h.
References Maybe< T >::has_value_.
NAN_INLINE bool operator!= (const Maybe< T > & other) const [inline]
Definition at line 71 of file nan_maybe_pre_43_inl.h.
References Maybe< T >::operator==().
NAN_INLINE bool operator== (const Maybe< T > & other) const [inline]
Definition at line 66 of file nan_maybe_pre_43_inl.h.
References Maybe< T >::FromJust(), and Maybe< T >::IsJust().
Referenced by Maybe< T >::operator!=().
Friends And Related Function Documentation
Maybe<U> Just (const U & u) [friend]
Maybe<U> Nothing () [friend]
Definition at line 863 of file nan.h.
Field Documentation
bool has_value_ [private]
Definition at line 78 of file nan_maybe_pre_43_inl.h.
Referenced by Maybe< T >::FromMaybe(), Maybe< T >::IsJust(), and Maybe< T >::IsNothing().
T value_ [private]
Definition at line 79 of file nan_maybe_pre_43_inl.h.
Referenced by Maybe< T >::FromJust(), and Maybe< T >::FromMaybe().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_maybe_pre_43_inl.h