Emeraldion Lodge (codename Zelda): Output Class Reference
Output Class Reference
#include <output.hpp>
Inherits Sass::Inspect.
Public Member Functions
Output (Context *ctx)
virtual ~Output ()
OutputBuffer get_buffer (void)
virtual void operator() (Ruleset *)
virtual void operator() (Feature_Block *)
virtual void operator() (Media_Block *)
virtual void operator() (At_Rule *)
virtual void operator() (Keyframe_Rule *)
virtual void operator() (Import *)
virtual void operator() (Comment *)
virtual void operator() (String_Quoted *)
virtual void operator() (String_Constant *)
void fallback_impl (AST_Node *n)
Protected Attributes
string charset
vector< AST_Node * > top_nodes
Detailed Description
Definition at line 22 of file output.hpp.
Constructor & Destructor Documentation
Output (Context * ctx)
Definition at line 8 of file output.cpp.
~Output () [virtual]
Definition at line 14 of file output.cpp.
Member Function Documentation
void fallback_impl (AST_Node * n)
Reimplemented from Inspect.
Definition at line 16 of file output.cpp.
OutputBuffer get_buffer (void)
Reimplemented from Emitter.
Definition at line 26 of file output.cpp.
References Emitter::append_mandatory_linefeed(), Emitter::append_string(), OutputBuffer::buffer, Output::charset, Sass::COMPRESSED, Emitter::ctx, Sass::ends_with(), Emitter::finalize(), Context::linefeed, Emitter::output(), Emitter::output_style(), Emitter::prepend_output(), Emitter::prepend_string(), Output::top_nodes, and Emitter::wbuf.
Referenced by Context::compile_block().
void operator() (String_Constant * s) [virtual]
Reimplemented from Inspect.
Definition at line 384 of file output.cpp.
References Emitter::append_token(), Sass::COMPRESSED, Emitter::in_comment, Output::operator()(), Emitter::output_style(), and Sass::string_to_output().
void operator() (String_Quoted * s) [virtual]
Reimplemented from Inspect.
Definition at line 373 of file output.cpp.
References Emitter::append_token(), Emitter::in_comment, Sass::quote(), and Sass::string_to_output().
void operator() (Comment * c) [virtual]
Reimplemented from Inspect.
Definition at line 68 of file output.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_linefeed(), Emitter::append_optional_linefeed(), Emitter::buffer(), Sass::COMPRESSED, Emitter::ctx, Sass::Prelexer::important(), Emitter::in_comment, Emitter::indentation, Emitter::output_style(), Sass::to_string, and Output::top_nodes.
void operator() (Import * imp) [virtual]
Reimplemented from Inspect.
Definition at line 21 of file output.cpp.
References Output::top_nodes.
void operator() (Keyframe_Rule * r) [virtual]
Reimplemented from Inspect.
Definition at line 166 of file output.cpp.
References Emitter::append_colon_separator(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_special_linefeed(), Statement::block(), Statement::is_hoistable(), and Vectorized< T >::length().
void operator() (At_Rule * a) [virtual]
Reimplemented from Inspect.
Definition at line 322 of file output.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_special_linefeed(), Emitter::append_string(), Emitter::append_token(), Statement::block(), Emitter::in_wrapped, Statement::is_hoistable(), Statement::is_invisible(), Vectorized< T >::length(), and s().
void operator() (Media_Block * m) [virtual]
Reimplemented from Inspect.
Definition at line 261 of file output.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_special_linefeed(), Emitter::append_token(), Statement::block(), Emitter::in_media_block, Emitter::indentation, Statement::is_hoistable(), Media_Block::is_invisible(), Sass::Util::isPrintable(), Vectorized< T >::length(), Sass::NESTED, and Emitter::output_style().
void operator() (Feature_Block * f) [virtual]
Reimplemented from Inspect.
Definition at line 199 of file output.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_special_linefeed(), Emitter::append_token(), Statement::block(), Emitter::indentation, Statement::is_hoistable(), Statement::is_invisible(), Sass::Util::isPrintable(), Vectorized< T >::length(), Sass::NESTED, and Emitter::output_style().
void operator() (Ruleset * r) [virtual]
Reimplemented from Inspect.
Definition at line 91 of file output.cpp.
References Emitter::append_indentation(), Emitter::append_optional_linefeed(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_string(), Statement::block(), Emitter::ctx, Emitter::indentation, Statement::is_hoistable(), Expression::is_invisible(), Sass::Util::isPrintable(), Vectorized< T >::length(), Expression::LIST, Sass::NESTED, Emitter::output_style(), s(), Context::source_comments, and Expression::STRING.
Referenced by Output::operator()().
Field Documentation
string charset [protected]
Definition at line 32 of file output.hpp.
Referenced by Output::get_buffer().
vector<AST_Node*> top_nodes [protected]
Definition at line 33 of file output.hpp.
Referenced by Output::get_buffer(), and Output::operator()().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/output.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/output.cpp