Emeraldion Lodge (codename Zelda): Antispam Class Reference
Antispam Class Reference
Helper class to perform basic Antispam checks.
Static Public Member Functions
static random_comment ()
Returns a variable message to alert the user that she's failed the math test.
static init_math_test ()
Initializes the mathematical test to tell humans and machines apart.
static check_math ()
Verifies if the math test has been successful.
static get_spam_signature ($text)
Returns the spam signature for a string of text.
static check_spam_signature ($text)
Checks whether the string of text has a recognized spam signature.
static store_spam_signature ($text)
Stores the spam signature for the string of text.
Static Public Attributes
static $first_operand = 0
The first operand for the math test.
static $second_operand = 0
The second operand for the math test.
Detailed Description
Helper class to perform basic Antispam checks.
Definition at line 8 of file antispam.php.
Member Function Documentation
check_math () static
Verifies if the math test has been successful.
The math test consists in filling a form field with the result of a simple arithmetical operation (e.g. a sum) between two operands. This method checks that the user has answered with the correct result.
Returns
TRUE if the math test has been answered correctly, FALSE otherwise.
Definition at line 53 of file antispam.php.
Referenced by SoftwareController\post_comment(), DiarioController\post_comment(), LoginController\request_password(), and ContactController\send().
check_spam_signature ($text) static
Checks whether the string of text has a recognized spam signature.
Parameters
$text The text that is used to calculate the spam signature.
Definition at line 81 of file antispam.php.
References $conn, Db\close_connection(), and Db\get_connection().
Referenced by BackendController\software_comment_mark_as_spam().
get_spam_signature ($text) static
Returns the spam signature for a string of text.
Parameters
$text The text that is used to calculate the spam signature.
Definition at line 69 of file antispam.php.
init_math_test () static
Initializes the mathematical test to tell humans and machines apart.
Definition at line 38 of file antispam.php.
Referenced by DiarioController\init_math_test(), LoginController\lost_password(), AntispamUnitTest\test_check_math(), and AntispamUnitTest\test_init_math_test().
random_comment () static
Returns a variable message to alert the user that she's failed the math test.
Definition at line 26 of file antispam.php.
References $comments, and l().
Referenced by SoftwareController\post_comment(), DiarioController\post_comment(), LoginController\request_password(), and ContactController\send().
store_spam_signature ($text) static
Stores the spam signature for the string of text.
Parameters
$text The text that is used to calculate the spam signature.
Definition at line 100 of file antispam.php.
Referenced by BackendController\software_comment_mark_as_spam().
Field Documentation
$first_operand = 0 static
The first operand for the math test.
first_operand
Definition at line 14 of file antispam.php.
Referenced by AntispamUnitTest\test_check_math().
$second_operand = 0 static
The second operand for the math test.
second_operand
Definition at line 20 of file antispam.php.
Referenced by AntispamUnitTest\test_check_math().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/antispam.php