Emeraldion Lodge (codename Zelda): Color Class Reference
Color Class Reference
#include <color.h>
Inherits SassValueWrapper< Color >.
Public Member Functions
Color (Sass_Value *)
Static Public Member Functions
static char const * get_constructor_name ()
static Sass_Value * construct (const std::vector< v8::Local< v8::Value >>, Sass_Value **)
static void initPrototype (v8::Local< v8::FunctionTemplate >)
static NAN_METHOD (GetR)
static NAN_METHOD (GetG)
static NAN_METHOD (GetB)
static NAN_METHOD (GetA)
static NAN_METHOD (SetR)
static NAN_METHOD (SetG)
static NAN_METHOD (SetB)
static NAN_METHOD (SetA)
Detailed Description
Definition at line 9 of file color.h.
Constructor & Destructor Documentation
Color (Sass_Value * v)
Definition at line 6 of file color.cpp.
Member Function Documentation
Sass_Value * construct (const std::vector< v8::Local< v8::Value >> raw_val, Sass_Value ** out) [static]
Definition at line 8 of file color.cpp.
References a(), SassValueWrapper< Color >::fail(), and sass_make_color().
static char const* get_constructor_name () [inline, static]
Reimplemented from SassValueWrapper< Color >.
Definition at line 12 of file color.h.
void initPrototype (v8::Local< v8::FunctionTemplate > proto) [static]
Definition at line 53 of file color.cpp.
References Nan::SetPrototypeMethod().
static NAN_METHOD (SetA) [static]
static NAN_METHOD (SetB) [static]
static NAN_METHOD (SetG) [static]
static NAN_METHOD (SetR) [static]
static NAN_METHOD (GetA) [static]
static NAN_METHOD (GetB) [static]
static NAN_METHOD (GetG) [static]
static NAN_METHOD (GetR) [static]
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/color.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/color.cpp