Emeraldion Lodge (codename Zelda): Argument Class Reference
Argument Class Reference
#include <ast.hpp>
Inherits Sass::Expression.
Public Member Functions
Argument (ParserState pstate, Expression *val, string n="", bool rest=false, bool keyword=false)
virtual bool operator== (Expression &rhs) const
virtual size_t hash ()
ATTACH_OPERATIONS ()
Private Member Functions
ADD_PROPERTY (Expression *, value)
ADD_PROPERTY (string, name)
ADD_PROPERTY (bool, is_rest_argument)
ADD_PROPERTY (bool, is_keyword_argument)
Private Attributes
size_t hash_
Detailed Description
Definition at line 953 of file ast.hpp.
Constructor & Destructor Documentation
Argument (ParserState pstate, Expression * val, string n = "", bool rest = false, bool keyword = false) [inline]
Definition at line 960 of file ast.hpp.
References Sass::error().
Member Function Documentation
ADD_PROPERTY (bool , is_keyword_argument) [private]
ADD_PROPERTY (bool , is_rest_argument) [private]
ADD_PROPERTY (string , name) [private]
ADD_PROPERTY (Expression * , value) [private]
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
virtual size_t hash () [inline, virtual]
Reimplemented from Expression.
Definition at line 983 of file ast.hpp.
References Argument::hash_, and Sass::Prelexer::name().
virtual bool operator== (Expression & rhs) const [inline, virtual]
Reimplemented from Expression.
Definition at line 968 of file ast.hpp.
References Sass::Prelexer::name().
Field Documentation
size_t hash_ [private]
Definition at line 958 of file ast.hpp.
Referenced by Argument::hash().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp