Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/callback_bridge.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/callback_bridge.h File Reference
#include <vector>
#include <nan.h>
#include <algorithm>
#include <uv.h>
Data Structures
class CallbackBridge< T, L >
Defines
#define COMMA ,
Functions
template<typename T , typename L >
NAN_METHOD (CallbackBridge< T COMMA L >::ReturnCallback)
template<typename T , typename L >
NAN_METHOD (CallbackBridge< T COMMA L >::New)
Define Documentation
#define COMMA ,
Definition at line 9 of file callback_bridge.h.
Referenced by debug_ast(), and Eval::interpolation().
Function Documentation
NAN_METHOD (CallbackBridge< T COMMA L >::New) [inline]
Definition at line 216 of file callback_bridge.h.
NAN_METHOD (CallbackBridge< T COMMA L >::ReturnCallback) [inline]
Definition at line 170 of file callback_bridge.h.
References Nan::FatalException(), Nan::GetInternalFieldPointer(), TryCatch::HasCaught(), and CallbackBridge< T, L >::post_process_return_value().