Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_superselector.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_superselector.cpp File Reference
#include "../ast.hpp"
#include "../context.hpp"
#include "../parser.hpp"
#include "../to_string.hpp"
#include <string>
Functions
Compound_Selector * compound_selector (string src)
Complex_Selector * complex_selector (string src)
void check_compound (string s1, string s2)
void check_complex (string s1, string s2)
int main ()
Variables
Context ctx = Context(Context::Data())
To_String to_string
Function Documentation
void check_complex (string s1, string s2)
Definition at line 29 of file test_superselector.cpp.
References complex_selector(), and Complex_Selector::is_superselector_of().
Referenced by main().
void check_compound (string s1, string s2)
Definition at line 18 of file test_superselector.cpp.
References compound_selector(), and Compound_Selector::is_superselector_of().
Referenced by main().
Complex_Selector* complex_selector (string src)
Definition at line 15 of file test_superselector.cpp.
Referenced by check_complex().
Compound_Selector* compound_selector (string src)
Definition at line 12 of file test_superselector.cpp.
Referenced by check_compound().
int main ()
Definition at line 40 of file test_superselector.cpp.
References check_complex(), and check_compound().
Variable Documentation
Context ctx = Context(Context::Data())
Definition at line 9 of file test_superselector.cpp.
To_String to_string
Definition at line 10 of file test_superselector.cpp.