Emeraldion Lodge (codename Zelda): utf8 Namespace Reference
utf8 Namespace Reference
Namespaces
namespace internal
namespace unchecked
Data Structures
class exception
class invalid_code_point
class invalid_utf8
class invalid_utf16
class not_enough_room
class iterator
Typedefs
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef unsigned int uint32_t
Functions
template<typename octet_iterator >
octet_iterator append (uint32_t cp, octet_iterator result)
The library API - functions intended to be called by the users.
template<typename octet_iterator , typename output_iterator >
output_iterator replace_invalid (octet_iterator start, octet_iterator end, output_iterator out, uint32_t replacement)
template<typename octet_iterator , typename output_iterator >
output_iterator replace_invalid (octet_iterator start, octet_iterator end, output_iterator out)
template<typename octet_iterator >
uint32_t next (octet_iterator &it, octet_iterator end)
template<typename octet_iterator >
uint32_t peek_next (octet_iterator it, octet_iterator end)
template<typename octet_iterator >
uint32_t prior (octet_iterator &it, octet_iterator start)
template<typename octet_iterator >
uint32_t previous (octet_iterator &it, octet_iterator pass_start)
Deprecated in versions that include "prior".
template<typename octet_iterator , typename distance_type >
void advance (octet_iterator &it, distance_type n, octet_iterator end)
template<typename octet_iterator >
std::iterator_traits
< octet_iterator >
::difference_type distance (octet_iterator first, octet_iterator last)
template<typename u16bit_iterator , typename octet_iterator >
octet_iterator utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result)
template<typename u16bit_iterator , typename octet_iterator >
u16bit_iterator utf8to16 (octet_iterator start, octet_iterator end, u16bit_iterator result)
template<typename octet_iterator , typename u32bit_iterator >
octet_iterator utf32to8 (u32bit_iterator start, u32bit_iterator end, octet_iterator result)
template<typename octet_iterator , typename u32bit_iterator >
u32bit_iterator utf8to32 (octet_iterator start, octet_iterator end, u32bit_iterator result)
template<typename octet_iterator >
octet_iterator find_invalid (octet_iterator start, octet_iterator end)
template<typename octet_iterator >
bool is_valid (octet_iterator start, octet_iterator end)
template<typename octet_iterator >
bool starts_with_bom (octet_iterator it, octet_iterator end)
template<typename octet_iterator >
bool is_bom (octet_iterator it)
Variables
const uint8_t bom [] = {0xef, 0xbb, 0xbf}
The library API - functions intended to be called by the users.
Typedef Documentation
typedef unsigned short uint16_t
Definition at line 39 of file core.h.
typedef unsigned int uint32_t
Definition at line 40 of file core.h.
typedef unsigned char uint8_t
Definition at line 38 of file core.h.
Function Documentation
void utf8::advance (octet_iterator & it, distance_type n, octet_iterator end) [inline]
Definition at line 190 of file checked.h.
References next().
octet_iterator utf8::append (uint32_t cp, octet_iterator result) [inline]
The library API - functions intended to be called by the users.
Definition at line 73 of file checked.h.
References utf8::internal::is_code_point_valid().
Referenced by replace_invalid(), utf16to8(), and utf32to8().
std::iterator_traits<octet_iterator>::difference_type utf8::distance (octet_iterator first, octet_iterator last) [inline]
Definition at line 198 of file checked.h.
References next().
octet_iterator utf8::find_invalid (octet_iterator start, octet_iterator end) [inline]
Definition at line 288 of file core.h.
References utf8::internal::UTF8_OK, and utf8::internal::validate_next().
Referenced by is_valid().
bool utf8::is_bom (octet_iterator it) [inline]
Definition at line 317 of file core.h.
References bom, and utf8::internal::mask8().
bool utf8::is_valid (octet_iterator start, octet_iterator end) [inline]
Definition at line 300 of file core.h.
References find_invalid().
uint32_t utf8::next (octet_iterator & it, octet_iterator end) [inline]
Definition at line 137 of file checked.h.
References utf8::internal::INCOMPLETE_SEQUENCE, utf8::internal::INVALID_CODE_POINT, utf8::internal::INVALID_LEAD, utf8::internal::NOT_ENOUGH_ROOM, utf8::internal::OVERLONG_SEQUENCE, utf8::internal::UTF8_OK, and utf8::internal::validate_next().
Referenced by advance(), distance(), iterator< octet_iterator >::operator*(), iterator< octet_iterator >::operator++(), peek_next(), previous(), utf8to16(), and utf8to32().
uint32_t utf8::peek_next (octet_iterator it, octet_iterator end) [inline]
Definition at line 157 of file checked.h.
References next().
Referenced by prior().
uint32_t utf8::previous (octet_iterator & it, octet_iterator pass_start) [inline]
Deprecated in versions that include "prior".
Definition at line 179 of file checked.h.
References utf8::internal::is_trail(), and next().
uint32_t utf8::prior (octet_iterator & it, octet_iterator start) [inline]
Definition at line 163 of file checked.h.
References utf8::internal::is_trail(), and peek_next().
Referenced by iterator< octet_iterator >::operator--().
output_iterator utf8::replace_invalid (octet_iterator start, octet_iterator end, output_iterator out) [inline]
Definition at line 130 of file checked.h.
References utf8::internal::mask16(), and replace_invalid().
output_iterator utf8::replace_invalid (octet_iterator start, octet_iterator end, output_iterator out, uint32_t replacement) [inline]
Definition at line 99 of file checked.h.
References append(), utf8::internal::INCOMPLETE_SEQUENCE, utf8::internal::INVALID_CODE_POINT, utf8::internal::INVALID_LEAD, utf8::internal::is_trail(), utf8::internal::NOT_ENOUGH_ROOM, utf8::internal::OVERLONG_SEQUENCE, utf8::internal::UTF8_OK, and utf8::internal::validate_next().
Referenced by replace_invalid().
bool utf8::starts_with_bom (octet_iterator it, octet_iterator end) [inline]
Definition at line 306 of file core.h.
References bom, and utf8::internal::mask8().
octet_iterator utf8::utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result) [inline]
Definition at line 207 of file checked.h.
References append(), utf8::internal::is_lead_surrogate(), utf8::internal::is_trail_surrogate(), utf8::internal::mask16(), and utf8::internal::SURROGATE_OFFSET.
octet_iterator utf8::utf32to8 (u32bit_iterator start, u32bit_iterator end, octet_iterator result) [inline]
Definition at line 249 of file checked.h.
References append().
u16bit_iterator utf8::utf8to16 (octet_iterator start, octet_iterator end, u16bit_iterator result) [inline]
Definition at line 234 of file checked.h.
References utf8::internal::LEAD_OFFSET, next(), and utf8::internal::TRAIL_SURROGATE_MIN.
u32bit_iterator utf8::utf8to32 (octet_iterator start, octet_iterator end, u32bit_iterator result) [inline]
Definition at line 258 of file checked.h.
References next().
Variable Documentation
const uint8_t bom[] = {0xef, 0xbb, 0xbf}
The library API - functions intended to be called by the users.
Definition at line 285 of file core.h.
Referenced by is_bom(), and starts_with_bom().