Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_interface.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_interface.cpp File Reference
#include <unistd.h>
#include <string>
#include <cstdlib>
#include <cstring>
#include <sstream>
#include <iostream>
#include "util.hpp"
#include "context.hpp"
#include "inspect.hpp"
#include "error_handling.hpp"
#include "sass_interface.h"
Defines
#define LFEED "\n"
Functions
sass_context * sass_new_context ()
static const char * safe_str (const char *str)
static void copy_strings (const std::vector< std::string > &strings, char ***array, int skip=0)
static void free_string_array (char **arr)
void sass_free_context (sass_context *ctx)
sass_file_context * sass_new_file_context ()
void sass_free_file_context (sass_file_context *ctx)
sass_folder_context * sass_new_folder_context ()
void sass_free_folder_context (sass_folder_context *ctx)
int sass_compile (sass_context *c_ctx)
int sass_compile_file (sass_file_context *c_ctx)
int sass_compile_folder (sass_folder_context *c_ctx)
Define Documentation
#define LFEED "\n"
Definition at line 6 of file sass_interface.cpp.
Function Documentation
static void copy_strings (const std::vector< std::string > & strings, char *** array, int skip = 0) [static]
Definition at line 33 of file sass_interface.cpp.
static void free_string_array (char ** arr) [static]
Definition at line 47 of file sass_interface.cpp.
static const char* safe_str (const char * str) [static]
Definition at line 29 of file sass_interface.cpp.
int sass_compile (sass_context * c_ctx)
Definition at line 96 of file sass_interface.cpp.
References sass_context::c_functions, copy_strings(), sass_context::error_message, sass_context::error_status, sass_options::include_paths, sass_context::included_files, sass_options::indent, sass_context::input_path, Sass_Options::input_path, sass_options::is_indented_syntax_src, LFEED, sass_options::linefeed, Sass_Error::message, sass_options::omit_source_map_url, sass_context::options, sass_context::output_path, Sass_Options::output_path, sass_context::output_string, sass_options::output_style, sass_options::plugin_paths, sass_options::precision, safe_str(), Sass::sass_strdup(), sass_options::source_comments, sass_options::source_map_contents, sass_options::source_map_embed, sass_options::source_map_file, sass_options::source_map_root, sass_context::source_map_string, and sass_context::source_string.
int sass_compile_file (sass_file_context * c_ctx)
Definition at line 190 of file sass_interface.cpp.
References sass_file_context::c_functions, copy_strings(), sass_file_context::error_message, sass_file_context::error_status, sass_options::include_paths, sass_file_context::included_files, sass_options::indent, sass_file_context::input_path, Sass_Options::input_path, sass_options::is_indented_syntax_src, LFEED, sass_options::linefeed, Sass_Error::message, sass_options::omit_source_map_url, sass_file_context::options, sass_file_context::output_path, Sass_Options::output_path, sass_file_context::output_string, sass_options::output_style, Sass_Options::output_style, sass_options::plugin_paths, sass_options::precision, safe_str(), Sass::sass_strdup(), sass_options::source_comments, sass_options::source_map_contents, sass_options::source_map_embed, sass_options::source_map_file, sass_options::source_map_root, and sass_file_context::source_map_string.
int sass_compile_folder (sass_folder_context * c_ctx)
Definition at line 282 of file sass_interface.cpp.
void sass_free_context (sass_context * ctx)
Definition at line 60 of file sass_interface.cpp.
References sass_context::c_functions, sass_context::error_message, free_string_array(), sass_context::included_files, sass_context::output_string, and sass_context::source_map_string.
void sass_free_file_context (sass_file_context * ctx)
Definition at line 75 of file sass_interface.cpp.
References sass_file_context::c_functions, sass_file_context::error_message, free_string_array(), sass_file_context::included_files, sass_file_context::output_string, and sass_file_context::source_map_string.
void sass_free_folder_context (sass_folder_context * ctx)
Definition at line 90 of file sass_interface.cpp.
References free_string_array(), and sass_folder_context::included_files.
sass_context* sass_new_context (void) [read]
Definition at line 25 of file sass_interface.cpp.
sass_file_context* sass_new_file_context (void) [read]
Definition at line 72 of file sass_interface.cpp.
sass_folder_context* sass_new_folder_context (void) [read]
Definition at line 87 of file sass_interface.cpp.