Emeraldion Lodge (codename Zelda): Environment< T > Class Template Reference
Environment< T > Class Template Reference
#include <environment.hpp>
Public Member Functions
Environment ()
void link (Environment &env)
void link (Environment *env)
bool is_lexical () const
bool is_root_scope () const
map< string, T > & local_frame ()
bool has_local (const string &key) const
T & get_local (const string &key)
void set_local (const string &key, T val)
void del_local (const string &key)
Environment * global_env ()
bool has_global (const string &key)
T & get_global (const string &key)
void set_global (const string &key, T val)
void del_global (const string &key)
bool has_lexical (const string &key) const
void set_lexical (const string &key, T val)
bool has (const string &key) const
T & operator[] (const string &key)
Data Fields
Memory_Manager< AST_Node > mem
Private Member Functions
ADD_PROPERTY (Environment *, parent)
Private Attributes
map< string, T > local_frame_
Detailed Description
template<typename T>
class Sass::Environment< T >
Definition at line 19 of file environment.hpp.
Constructor & Destructor Documentation
Environment () [inline]
Definition at line 26 of file environment.hpp.
Member Function Documentation
ADD_PROPERTY (Environment< T > * , parent) [private]
void del_global (const string & key) [inline]
Definition at line 88 of file environment.hpp.
References Environment< T >::global_env(), and Environment< T >::local_frame_.
void del_local (const string & key) [inline]
Definition at line 63 of file environment.hpp.
References Environment< T >::local_frame_.
Referenced by Expand::operator()(), and Eval::operator()().
T& get_global (const string & key) [inline]
Definition at line 82 of file environment.hpp.
References Environment< T >::global_env().
Referenced by Expand::operator()(), and Eval::operator()().
T& get_local (const string & key) [inline]
Definition at line 57 of file environment.hpp.
References Environment< T >::local_frame_.
Referenced by Expand::operator()(), Eval::operator()(), and Environment< T >::operator[]().
Environment* global_env () [inline]
Definition at line 70 of file environment.hpp.
References Environment< T >::is_lexical().
Referenced by Environment< T >::del_global(), Environment< T >::get_global(), Environment< T >::has_global(), and Environment< T >::set_global().
bool has (const string & key) const [inline]
Definition at line 122 of file environment.hpp.
Referenced by Environment< T >::has_global(), Eval::interpolation(), Expand::operator()(), and Eval::operator()().
bool has_global (const string & key) [inline]
Definition at line 79 of file environment.hpp.
References Environment< T >::global_env(), and Environment< T >::has().
Referenced by Expand::operator()(), and Eval::operator()().
bool has_lexical (const string & key) const [inline]
Definition at line 94 of file environment.hpp.
Referenced by Expand::operator()(), and Eval::operator()().
bool has_local (const string & key) const [inline]
Definition at line 54 of file environment.hpp.
References Environment< T >::local_frame_.
Referenced by Sass::bind(), Expand::operator()(), and Eval::operator()().
bool is_lexical () const [inline]
Definition at line 34 of file environment.hpp.
Referenced by Environment< T >::global_env(), Expand::operator()(), and Eval::operator()().
bool is_root_scope () const [inline]
Definition at line 43 of file environment.hpp.
void link (Environment< T > * env) [inline]
Definition at line 30 of file environment.hpp.
void link (Environment< T > & env) [inline]
Definition at line 29 of file environment.hpp.
Referenced by Expand::operator()(), Eval::operator()(), and Cssize::operator()().
map<string, T>& local_frame () [inline]
Definition at line 50 of file environment.hpp.
References Environment< T >::local_frame_.
Referenced by Sass::bind(), Expand::operator()(), and Eval::operator()().
T& operator[] (const string & key) [inline]
Definition at line 135 of file environment.hpp.
References Environment< T >::get_local().
void set_global (const string & key, T val) [inline]
Definition at line 85 of file environment.hpp.
References Environment< T >::global_env(), and Environment< T >::local_frame_.
Referenced by Expand::operator()(), and Eval::operator()().
void set_lexical (const string & key, T val) [inline]
Definition at line 107 of file environment.hpp.
References Environment< T >::set_local().
Referenced by Expand::operator()(), and Eval::operator()().
void set_local (const string & key, T val) [inline]
Definition at line 60 of file environment.hpp.
References Environment< T >::local_frame_.
Referenced by Expand::operator()(), Eval::operator()(), and Environment< T >::set_lexical().
Field Documentation
map<string, T> local_frame_ [private]
Definition at line 21 of file environment.hpp.
Referenced by Environment< T >::del_global(), Environment< T >::del_local(), Environment< T >::get_local(), Environment< T >::has_local(), Environment< T >::local_frame(), Environment< T >::set_global(), and Environment< T >::set_local().
Memory_Manager<AST_Node> mem
Definition at line 25 of file environment.hpp.
Referenced by Expand::operator()(), and Eval::operator()().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/environment.hpp