Emeraldion Lodge (codename Zelda): Expand Class Reference
Expand Class Reference
#include <expand.hpp>
Inherits Operation_CRTP< Statement *, Expand >.
Public Member Functions
Expand (Context &, Eval *, Contextualize_Eval *, Env *, Backtrace *)
virtual ~Expand ()
Statement * operator() (Block *)
Statement * operator() (Ruleset *)
Statement * operator() (Propset *)
Statement * operator() (Media_Block *)
Statement * operator() (Feature_Block *)
Statement * operator() (At_Root_Block *)
Statement * operator() (At_Rule *)
Statement * operator() (Declaration *)
Statement * operator() (Assignment *)
Statement * operator() (Import *)
Statement * operator() (Import_Stub *)
Statement * operator() (Warning *)
Statement * operator() (Error *)
Statement * operator() (Debug *)
Statement * operator() (Comment *)
Statement * operator() (If *)
Statement * operator() (For *)
Statement * operator() (Each *)
Statement * operator() (While *)
Statement * operator() (Return *)
Statement * operator() (Extension *)
Statement * operator() (Definition *)
Statement * operator() (Mixin_Call *)
Statement * operator() (Content *)
template<typename U >
Statement * fallback (U x)
void append_block (Block *)
Private Member Functions
Statement * fallback_impl (AST_Node *n)
Private Attributes
Context & ctx
Eval * eval
Contextualize_Eval * contextualize_eval
Env * env
vector< Block * > block_stack
vector< String * > property_stack
vector< Selector * > selector_stack
vector< Selector * > at_root_selector_stack
bool in_at_root
bool in_keyframes
Backtrace * backtrace
Detailed Description
Definition at line 23 of file expand.hpp.
Constructor & Destructor Documentation
Expand (Context & ctx, Eval * eval, Contextualize_Eval * contextualize_eval, Env * env, Backtrace * bt)
Definition at line 15 of file expand.cpp.
References Expand::selector_stack.
virtual ~Expand () [inline, virtual]
Definition at line 41 of file expand.hpp.
Member Function Documentation
void append_block (Block * b) [inline]
Definition at line 567 of file expand.cpp.
References Expand::block_stack, and Vectorized< T >::length().
Referenced by Expand::operator()().
Statement* fallback (U x) [inline]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 71 of file expand.hpp.
References Expand::fallback_impl().
Statement * fallback_impl (AST_Node * n) [inline, private]
Definition at line 560 of file expand.cpp.
References Expand::backtrace, Expand::ctx, Sass::error(), and Context::mem.
Referenced by Expand::fallback().
Statement * operator() (Content * c) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 550 of file expand.cpp.
References Expand::ctx, Expand::env, Environment< T >::has(), and Context::mem.
Statement * operator() (Mixin_Call * c) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 513 of file expand.cpp.
References Expand::append_block(), Expand::backtrace, Sass::bind(), Statement::block(), Expand::ctx, Expand::env, Sass::error(), Expand::eval, Environment< T >::has(), Environment< T >::link(), Environment< T >::local_frame(), Context::mem, Definition::MIXIN, p(), Expand::selector_stack, and Eval::with().
Statement * operator() (Definition * d) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 503 of file expand.cpp.
References Expand::ctx, Expand::env, Environment< T >::local_frame(), Context::mem, and Definition::MIXIN.
Statement * operator() (Extension * e) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 471 of file expand.cpp.
References Expand::backtrace, Expand::contextualize_eval, Expand::ctx, Vectorized< T >::elements(), Expand::env, Sass::error(), Expand::eval, Vectorized< T >::length(), Subset_Map< K, V >::put(), Expand::selector_stack, Context::subset_map, Compound_Selector::to_str_vec(), Sass::to_string, and Contextualize_Eval::with().
Statement * operator() (Return * r) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 465 of file expand.cpp.
References Expand::backtrace, and Sass::error().
Statement * operator() (While * w) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 455 of file expand.cpp.
References Expand::append_block(), Expand::backtrace, Statement::block(), Expand::env, Expand::eval, and Eval::with().
Statement * operator() (Each * e) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 385 of file expand.cpp.
References Expand::append_block(), Hashed::at(), Expand::backtrace, Statement::block(), List::COMMA, Expand::ctx, Environment< T >::del_local(), Expand::env, Expand::eval, Environment< T >::get_local(), Environment< T >::has_local(), Hashed::keys(), Vectorized< T >::length(), Expression::LIST, Expression::MAP, Context::mem, Environment< T >::set_local(), List::SPACE, Sass::Prelexer::variable(), and Eval::with().
Statement * operator() (For * f) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 331 of file expand.cpp.
References Expand::append_block(), Expand::backtrace, Statement::block(), Environment< T >::del_local(), Expand::env, Sass::error(), Expand::eval, Environment< T >::get_local(), Environment< T >::has_local(), Environment< T >::mem, Expression::NUMBER, Environment< T >::set_local(), Number::unit(), Sass::Prelexer::variable(), and Eval::with().
Statement * operator() (If * i) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 317 of file expand.cpp.
References Expand::append_block(), Expand::backtrace, Expand::env, Expand::eval, and Eval::with().
Statement * operator() (Comment * c) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 311 of file expand.cpp.
References Expand::backtrace, Expand::ctx, Expand::env, Expand::eval, Context::mem, and Eval::with().
Statement * operator() (Debug * d) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 304 of file expand.cpp.
References Expand::backtrace, Expand::env, Expand::eval, and Eval::with().
Statement * operator() (Error * e) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 297 of file expand.cpp.
References Expand::backtrace, Expand::env, Expand::eval, and Eval::with().
Statement * operator() (Warning * w) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 290 of file expand.cpp.
References Expand::backtrace, Expand::env, Expand::eval, and Eval::with().
Statement * operator() (Import_Stub * i) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 284 of file expand.cpp.
References Expand::append_block(), Expand::ctx, and Context::style_sheets.
Statement * operator() (Import * imp) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 275 of file expand.cpp.
References Expand::backtrace, Expand::ctx, Expand::env, Expand::eval, Context::mem, Import::urls(), and Eval::with().
Statement * operator() (Assignment * a) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 214 of file expand.cpp.
References Expand::backtrace, Expand::env, Expand::eval, Environment< T >::get_global(), Environment< T >::has_global(), Environment< T >::has_lexical(), Environment< T >::is_lexical(), Expression::NULL_VAL, p(), Expand::selector_stack, Environment< T >::set_global(), Environment< T >::set_lexical(), Environment< T >::set_local(), and Eval::with().
Statement * operator() (Declaration * d) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 199 of file expand.cpp.
References Expand::backtrace, Expand::ctx, Expand::env, Expand::eval, Expression::is_invisible(), Context::mem, p(), Expand::selector_stack, and Eval::with().
Statement * operator() (At_Rule * a) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 180 of file expand.cpp.
References Expand::backtrace, Block::block(), Statement::block(), Expand::contextualize_eval, Expand::ctx, Expand::env, Expand::eval, Expand::in_keyframes, At_Rule::is_keyframes(), Context::mem, Eval::with(), and Contextualize_Eval::with().
Statement * operator() (At_Root_Block * a) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 163 of file expand.cpp.
References Expand::at_root_selector_stack, Expand::backtrace, Block::block(), Statement::block(), Expand::ctx, Expand::env, Expand::eval, Expand::in_at_root, Context::mem, and Eval::with().
Statement * operator() (Feature_Block * f) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 140 of file expand.cpp.
References Expand::backtrace, Block::block(), Statement::block(), Expand::ctx, Expand::env, Expand::eval, Context::mem, Expand::selector_stack, and Eval::with().
Statement * operator() (Media_Block * m) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 150 of file expand.cpp.
References Expand::backtrace, Block::block(), Statement::block(), Expand::ctx, Expand::env, Expand::eval, Parser::from_c_str(), Context::mem, Expand::selector_stack, Sass::to_string, and Eval::with().
Statement * operator() (Propset * p) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 105 of file expand.cpp.
References Expand::backtrace, Block::block(), Statement::block(), Expand::block_stack, Expand::ctx, Sass::error(), Vectorized< T >::length(), Context::mem, and Expand::property_stack.
Statement * operator() (Ruleset * r) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 42 of file expand.cpp.
References Expand::backtrace, Block::block(), Statement::block(), Expand::contextualize_eval, Expand::ctx, Expand::env, Emitter::get_buffer(), Expand::in_at_root, Expand::in_keyframes, Context::mem, p(), Expand::selector_stack, Sass::to_string, and Contextualize_Eval::with().
Statement * operator() (Block * b) [virtual]
Reimplemented from Operation_CRTP< Statement *, Expand >.
Definition at line 29 of file expand.cpp.
References Expand::append_block(), Expand::block_stack, Expand::ctx, Expand::env, Vectorized< T >::length(), Environment< T >::link(), and Context::mem.
Field Documentation
vector<Selector*> at_root_selector_stack [private]
Definition at line 32 of file expand.hpp.
Referenced by Expand::operator()().
Backtrace* backtrace [private]
Definition at line 35 of file expand.hpp.
Referenced by Expand::fallback_impl(), and Expand::operator()().
vector<Block*> block_stack [private]
Definition at line 29 of file expand.hpp.
Referenced by Expand::append_block(), and Expand::operator()().
Contextualize_Eval* contextualize_eval [private]
Definition at line 27 of file expand.hpp.
Referenced by Expand::operator()().
Context& ctx [private]
Definition at line 25 of file expand.hpp.
Referenced by Expand::fallback_impl(), and Expand::operator()().
Env* env [private]
Definition at line 28 of file expand.hpp.
Referenced by Expand::operator()().
Eval* eval [private]
Definition at line 26 of file expand.hpp.
Referenced by Expand::operator()().
bool in_at_root [private]
Definition at line 33 of file expand.hpp.
Referenced by Expand::operator()().
bool in_keyframes [private]
Definition at line 34 of file expand.hpp.
Referenced by Expand::operator()().
vector<String*> property_stack [private]
Definition at line 30 of file expand.hpp.
Referenced by Expand::operator()().
vector<Selector*> selector_stack [private]
Definition at line 31 of file expand.hpp.
Referenced by Expand::Expand(), and Expand::operator()().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/expand.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/expand.cpp