Emeraldion Lodge (codename Zelda): CustomFunctionBridge Class Reference
CustomFunctionBridge Class Reference
#include <custom_function_bridge.h>
Inherits CallbackBridge< Sass_Value * >.
Public Member Functions
CustomFunctionBridge (v8::Local< v8::Function > cb, bool is_sync)
Private Member Functions
Sass_Value * post_process_return_value (v8::Local< v8::Value >) const
Detailed Description
Definition at line 8 of file custom_function_bridge.h.
Constructor & Destructor Documentation
CustomFunctionBridge (v8::Local< v8::Function > cb, bool is_sync) [inline]
Definition at line 10 of file custom_function_bridge.h.
Member Function Documentation
Sass_Value * post_process_return_value (v8::Local< v8::Value > val) const [private, virtual]
Implements CallbackBridge< Sass_Value * >.
Definition at line 7 of file custom_function_bridge.cpp.
References Value::get_sass_value(), sass_make_error(), and Factory::unwrap().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/custom_function_bridge.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/custom_function_bridge.cpp