Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/posix/getopt.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/posix/getopt.h File Reference
#include <crtdefs.h>
Data Structures
struct option
Defines
#define __GETOPT_LONG_H__
#define HAVE_DECL_GETOPT 1
Enumerations
enum { no_argument = 0, required_argument, optional_argument }
Functions
int getopt (int nargc, char *const *nargv, const char *options)
int getopt_long (int nargc, char *const *nargv, const char *options, const struct option *long_options, int *idx)
int getopt_long_only (int nargc, char *const *nargv, const char *options, const struct option *long_options, int *idx)
Variables
int optind
int optopt
int opterr
char * optarg
Define Documentation
#define __GETOPT_LONG_H__
Definition at line 56 of file getopt.h.
#define HAVE_DECL_GETOPT 1
Definition at line 88 of file getopt.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
no_argument
required_argument
optional_argument
Definition at line 70 of file getopt.h.
Function Documentation
int getopt (int nargc, char *const * nargv, const char * options)
Definition at line 523 of file getopt.c.
References getopt_internal().
int getopt_long (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx)
Definition at line 543 of file getopt.c.
References FLAG_PERMUTE, and getopt_internal().
int getopt_long_only (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx)
Definition at line 556 of file getopt.c.
References FLAG_LONGONLY, FLAG_PERMUTE, and getopt_internal().
Variable Documentation
char* optarg
Definition at line 69 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
int opterr
Definition at line 63 of file getopt.c.
int optind
DISCLAIMER This file has no copyright assigned and is placed in the Public Domain. This file is a part of the w64 mingw-runtime package.
The w64 mingw-runtime package and its code is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY. ALL WARRANTIES, EXPRESSED OR IMPLIED ARE HEREBY DISCLAIMED. This includes but is not limited to warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Definition at line 64 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
int optopt
Definition at line 65 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().