Emeraldion Lodge (codename Zelda): Expression Class Reference
Expression Class Reference
#include <ast.hpp>
Inherits Sass::AST_Node.
Inherited by Argument, Arguments, At_Root_Expression, Binary_Expression, Boolean, Color, Feature_Query, Feature_Query_Condition, Function_Call, Function_Call_Schema, List, Map, Media_Query, Media_Query_Expression, Null, Number, Parent_Selector, String, Textual, Thunk, Unary_Expression, and Variable.
Public Types
enum Concrete_Type {
NONE, BOOLEAN, NUMBER, COLOR,
STRING, LIST, MAP, SELECTOR,
NULL_VAL, NUM_TYPES
}
Public Member Functions
Expression (ParserState pstate, bool d=false, bool e=false, bool i=false, Concrete_Type ct=NONE)
virtual operator bool ()
virtual ~Expression ()
virtual string type ()
virtual bool is_invisible ()
virtual bool is_false ()
virtual bool operator== (Expression &rhs) const
virtual void set_delayed (bool delayed)
virtual size_t hash ()
Static Public Member Functions
static string type_name ()
Private Member Functions
ADD_PROPERTY (bool, is_delayed)
ADD_PROPERTY (bool, is_expanded)
ADD_PROPERTY (bool, is_interpolant)
ADD_PROPERTY (Concrete_Type, concrete_type)
Detailed Description
Definition at line 80 of file ast.hpp.
Member Enumeration Documentation
enum Concrete_Type
Enumerator:
NONE
BOOLEAN
NUMBER
COLOR
STRING
LIST
MAP
SELECTOR
NULL_VAL
NUM_TYPES
Definition at line 82 of file ast.hpp.
Constructor & Destructor Documentation
Expression (ParserState pstate, bool d = false, bool e = false, bool i = false, Concrete_Type ct = NONE) [inline]
Definition at line 101 of file ast.hpp.
virtual ~Expression () [inline, virtual]
Definition at line 110 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (Concrete_Type , concrete_type) [private]
ADD_PROPERTY (bool , is_interpolant) [private]
ADD_PROPERTY (bool , is_expanded) [private]
ADD_PROPERTY (bool , is_delayed) [private]
virtual size_t hash () [inline, virtual]
Reimplemented in List, Map, Binary_Expression, Unary_Expression, Argument, Function_Call, Variable, Textual, Number, Color, Boolean, String_Schema, String_Constant, and Null.
Definition at line 117 of file ast.hpp.
Referenced by Map::hash(), and hash< Sass::Expression * >::operator()().
virtual bool is_false () [inline, virtual]
Reimplemented in Boolean, and Null.
Definition at line 114 of file ast.hpp.
virtual bool is_invisible () [inline, virtual]
Reimplemented in List, Map, and Null.
Definition at line 112 of file ast.hpp.
Referenced by Output::operator()(), Inspect::operator()(), and Expand::operator()().
virtual operator bool () [inline, virtual]
Reimplemented in Boolean, and Null.
Definition at line 109 of file ast.hpp.
virtual bool operator== (Expression & rhs) const [inline, virtual]
Reimplemented in List, Map, Binary_Expression, Unary_Expression, Argument, Function_Call, Variable, Textual, Number, Color, Boolean, String_Schema, String_Constant, and Null.
Definition at line 115 of file ast.hpp.
virtual void set_delayed (bool delayed) [inline, virtual]
Reimplemented in List, and Binary_Expression.
Definition at line 116 of file ast.hpp.
Referenced by Eval::operator()().
virtual string type () [inline, virtual]
Reimplemented in List, Map, Number, Color, Boolean, String_Schema, String_Constant, Null, and Parent_Selector.
Definition at line 111 of file ast.hpp.
Referenced by debug_ast(), Sass::op_numbers(), Inspect::operator()(), Eval::operator()(), Textual::operator==(), Unary_Expression::operator==(), Binary_Expression::operator==(), and Parser::parse_factor().
static string type_name () [inline, static]
Reimplemented in List, Map, Binary_Expression, Unary_Expression, Number, Color, Boolean, String, String_Schema, String_Constant, Null, and Parent_Selector.
Definition at line 113 of file ast.hpp.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp