Emeraldion Lodge (codename Zelda): Vectorized< T > Class Template Reference
Vectorized< T > Class Template Reference
#include <ast.hpp>
Public Member Functions
Vectorized (size_t s=0)
virtual ~Vectorized ()=0
size_t length () const
bool empty () const
T last ()
T & operator[] (size_t i)
const T & operator[] (size_t i) const
Vectorized & operator<< (T element)
Vectorized & operator+= (Vectorized *v)
Vectorized & unshift (T element)
vector< T > & elements ()
const vector< T > & elements () const
vector< T > & elements (vector< T > &e)
Protected Member Functions
void reset_hash ()
virtual void adjust_after_pushing (T element)
Protected Attributes
size_t hash_
Private Attributes
vector< T > elements_
Detailed Description
template<typename T>
class Sass::Vectorized< T >
Definition at line 154 of file ast.hpp.
Constructor & Destructor Documentation
Vectorized (size_t s = 0) [inline]
Definition at line 161 of file ast.hpp.
~Vectorized () [inline, pure virtual]
Definition at line 191 of file ast.hpp.
Member Function Documentation
virtual void adjust_after_pushing (T element) [inline, protected, virtual]
Reimplemented in Block, List, Arguments, Parameters, Compound_Selector, and Selector_List.
Definition at line 159 of file ast.hpp.
Referenced by Vectorized< Argument * >::operator<<().
vector<T>& elements (vector< T > & e) [inline]
Definition at line 188 of file ast.hpp.
const vector<T>& elements () const [inline]
Definition at line 187 of file ast.hpp.
vector<T>& elements () [inline]
Definition at line 186 of file ast.hpp.
Referenced by Sass::bind(), debug_ast(), Sass::nodeToComplexSelector(), Expand::operator()(), and Sass::parentSuperselector().
bool empty () const [inline]
Definition at line 165 of file ast.hpp.
Referenced by Sass::Functions::BUILT_IN(), Inspect::operator()(), Parser::parse_factor(), and Parser::parse_feature_queries().
T last () [inline]
Definition at line 166 of file ast.hpp.
Referenced by Cssize::operator()().
size_t length () const [inline]
Definition at line 164 of file ast.hpp.
Referenced by Expand::append_block(), Sass::bind(), Sass::Functions::BUILT_IN(), Remove_Placeholders::clean_selector_list(), Sass::eq(), At_Root_Expression::exclude(), Sass::extendCompoundSelector(), Sass::Functions::get_arg_m(), Ruleset::is_invisible(), Selector_List::is_superselector_of(), Complex_Selector::is_superselector_of(), Compound_Selector::is_superselector_of(), Sass::Util::isPrintable(), Compound_Selector::minus(), To_C::operator()(), Remove_Placeholders::operator()(), Output::operator()(), Listize::operator()(), Inspect::operator()(), Extend::operator()(), Expand::operator()(), Eval::operator()(), Cssize::operator()(), Contextualize::operator()(), Vectorized< Argument * >::operator+=(), String_Schema::operator==(), List::operator==(), Compound_Selector::operator==(), Parser::parse_each_directive(), Parser::parse_feature_query_in_parens(), Sass::shouldExtendBlock(), Pseudo_Selector::unify_with(), Selector_Qualifier::unify_with(), Type_Selector::unify_with(), and Simple_Selector::unify_with().
Vectorized& operator+= (Vectorized< T > * v) [inline]
Definition at line 176 of file ast.hpp.
Vectorized& operator<< (T element) [inline]
Definition at line 169 of file ast.hpp.
const T& operator[] (size_t i) const [inline]
Definition at line 168 of file ast.hpp.
T& operator[] (size_t i) [inline]
Definition at line 167 of file ast.hpp.
void reset_hash () [inline, protected]
Definition at line 158 of file ast.hpp.
Referenced by Vectorized< Argument * >::operator<<().
Vectorized& unshift (T element) [inline]
Definition at line 181 of file ast.hpp.
Referenced by Cssize::operator()().
Field Documentation
vector<T> elements_ [private]
Definition at line 155 of file ast.hpp.
Referenced by Vectorized< Argument * >::elements(), Vectorized< Argument * >::empty(), Vectorized< Argument * >::last(), Vectorized< Argument * >::length(), Vectorized< Argument * >::operator<<(), Vectorized< Argument * >::operator[](), Vectorized< Argument * >::unshift(), and Vectorized< Argument * >::Vectorized().
size_t hash_ [protected]
Reimplemented in String_Schema.
Definition at line 157 of file ast.hpp.
Referenced by Vectorized< Argument * >::reset_hash().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp