Emeraldion Lodge (codename Zelda): Login Class Reference
Login Class Reference
Helper class for authentication tasks.
Static Public Member Functions
static is_logged_in ()
Returns TRUE if the current user is authenticated.
Data Fields
const magic_phrase = "Nei boschi a Rumiai"
Secret phrase used in hash generation.
Static Public Attributes
static $logged_in
Set to TRUE if the current user is authenticated.
Detailed Description
Helper class for authentication tasks.
Definition at line 10 of file login.php.
Member Function Documentation
static is_logged_in () static
Returns TRUE if the current user is authenticated.
is_logged_in
This method queries the database to detect if the current user is authenticated and then caches the result to speed up subsequent calls.
Definition at line 30 of file login.php.
References $conn, $logged_in, Db\close_connection(), and Db\get_connection().
Referenced by EmeController\check_auth().
Field Documentation
$logged_in static
Set to TRUE if the current user is authenticated.
logged_in
Definition at line 22 of file login.php.
Referenced by is_logged_in().
const magic_phrase = "Nei boschi a Rumiai"
Secret phrase used in hash generation.
magic_phrase
Definition at line 16 of file login.php.
Referenced by LoginController\login().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/login.php