Emeraldion Lodge (codename Zelda): Sass::Prelexer Namespace Reference
Sass::Prelexer Namespace Reference
Typedefs
typedef const char *(* prelexer)(const char *)
Functions
const char * kwd_at (const char *src)
const char * kwd_dot (const char *src)
const char * kwd_comma (const char *src)
const char * kwd_colon (const char *src)
const char * kwd_star (const char *src)
const char * kwd_plus (const char *src)
const char * kwd_minus (const char *src)
const char * kwd_slash (const char *src)
bool is_alpha (const char &chr)
bool is_space (const char &chr)
bool is_digit (const char &chr)
bool is_xdigit (const char &chr)
bool is_punct (const char &chr)
bool is_alnum (const char &chr)
bool is_unicode (const char &chr)
bool is_character (const char &chr)
const char * space (const char *src)
const char * alpha (const char *src)
const char * unicode (const char *src)
const char * digit (const char *src)
const char * xdigit (const char *src)
const char * alnum (const char *src)
const char * punct (const char *src)
const char * character (const char *src)
const char * spaces (const char *src)
const char * digits (const char *src)
const char * no_spaces (const char *src)
const char * optional_spaces (const char *src)
const char * any_char (const char *src)
const char * word_boundary (const char *src)
const char * re_linebreak (const char *src)
const char * end_of_line (const char *src)
template<char chr>
const char * exactly (const char *src)
template<const char * char_class>
const char * class_char (const char *src)
template<const char * char_class>
const char * class_chars (const char *src)
template<const char chr>
const char * any_char_but (const char *src)
template<prelexer mx>
const char * negate (const char *src)
template<prelexer mx>
const char * lookahead (const char *src)
template<prelexer... mxs>
const char * alternatives (const char *src)
template<prelexer... mxs>
const char * sequence (const char *src)
template<prelexer mx>
const char * optional (const char *src)
template<prelexer mx>
const char * zero_plus (const char *src)
template<prelexer mx>
const char * one_plus (const char *src)
template<prelexer mx, prelexer delim>
const char * non_greedy (const char *src)
template<const char * str>
const char * word (const char *src)
template<char chr>
const char * loosely (const char *src)
const char * line_comment (const char *src)
const char * block_comment (const char *src)
const char * optional_css_whitespace (const char *src)
const char * css_whitespace (const char *src)
const char * optional_css_comments (const char *src)
const char * css_comments (const char *src)
const char * escape_seq (const char *src)
const char * identifier_alpha (const char *src)
const char * identifier_alnum (const char *src)
const char * identifier (const char *src)
const char * identifier_alnums (const char *src)
const char * number_prefix (const char *src)
const char * identifier_schema (const char *src)
const char * interpolant (const char *src)
const char * single_quoted_string (const char *src)
const char * double_quoted_string (const char *src)
const char * quoted_string (const char *src)
const char * value_schema (const char *src)
const char * at_keyword (const char *src)
const char * kwd_sel_deep (const char *src)
const char * kwd_import (const char *src)
const char * kwd_at_root (const char *src)
const char * kwd_with_directive (const char *src)
const char * kwd_without_directive (const char *src)
const char * kwd_media (const char *src)
const char * kwd_supports (const char *src)
const char * kwd_mixin (const char *src)
const char * kwd_function (const char *src)
const char * kwd_return_directive (const char *src)
const char * kwd_include (const char *src)
const char * kwd_content (const char *src)
const char * kwd_extend (const char *src)
const char * kwd_if_directive (const char *src)
const char * kwd_else_directive (const char *src)
const char * elseif_directive (const char *src)
const char * kwd_for_directive (const char *src)
const char * kwd_from (const char *src)
const char * kwd_to (const char *src)
const char * kwd_through (const char *src)
const char * kwd_each_directive (const char *src)
const char * kwd_in (const char *src)
const char * kwd_while_directive (const char *src)
const char * name (const char *src)
const char * kwd_warn (const char *src)
const char * kwd_err (const char *src)
const char * kwd_dbg (const char *src)
const char * kwd_null (const char *src)
const char * namespace_prefix (const char *src)
const char * type_selector (const char *src)
const char * hyphens_and_identifier (const char *src)
const char * hyphens_and_name (const char *src)
const char * universal (const char *src)
const char * id_name (const char *src)
const char * class_name (const char *src)
const char * attribute_name (const char *src)
const char * placeholder (const char *src)
const char * sign (const char *src)
const char * unsigned_number (const char *src)
const char * number (const char *src)
const char * coefficient (const char *src)
const char * binomial (const char *src)
const char * percentage (const char *src)
const char * ampersand (const char *src)
const char * dimension (const char *src)
const char * hex (const char *src)
const char * hexa (const char *src)
const char * hex0 (const char *src)
const char * uri_prefix (const char *src)
const char * uri_value (const char *src)
const char * important (const char *src)
const char * default_flag (const char *src)
const char * global_flag (const char *src)
const char * pseudo_prefix (const char *src)
const char * functional_schema (const char *src)
const char * functional (const char *src)
const char * pseudo_not (const char *src)
const char * even (const char *src)
const char * odd (const char *src)
const char * exact_match (const char *src)
const char * class_match (const char *src)
const char * dash_match (const char *src)
const char * prefix_match (const char *src)
const char * suffix_match (const char *src)
const char * substring_match (const char *src)
const char * variable (const char *src)
const char * kwd_true (const char *src)
const char * kwd_false (const char *src)
const char * kwd_and (const char *src)
const char * kwd_or (const char *src)
const char * kwd_not (const char *src)
const char * kwd_eq (const char *src)
const char * kwd_neq (const char *src)
const char * kwd_gt (const char *src)
const char * kwd_gte (const char *src)
const char * kwd_lt (const char *src)
const char * kwd_lte (const char *src)
const char * ie_progid (const char *src)
const char * ie_expression (const char *src)
const char * ie_property (const char *src)
const char * ie_keyword_arg_property (const char *src)
const char * ie_keyword_arg_value (const char *src)
const char * ie_keyword_arg (const char *src)
const char * static_string (const char *src)
const char * static_component (const char *src)
const char * static_value (const char *src)
const char * parenthese_scope (const char *src)
template<char beg, char end, bool esc>
const char * delimited_by (const char *src)
template<prelexer start, prelexer stop>
const char * skip_over_scopes (const char *src, const char *end)
template<prelexer start, prelexer stop>
const char * skip_over_scopes (const char *src)
template<prelexer start, prelexer stop>
const char * recursive_scopes (const char *src)
template<prelexer mx, size_t lo, size_t hi>
const char * between (const char *src)
const char * line_comment_prefix (const char *src)
const char * block_comment_prefix (const char *src)
const char * comment (const char *src)
const char * custom_property_name (const char *src)
const char * vendor_prefix (const char *src)
const char * url (const char *src)
template<char c>
const char * find_first (const char *src)
template<prelexer mx>
const char * find_first_in_interval (const char *beg, const char *end)
template<prelexer mx>
unsigned int count_interval (const char *beg, const char *end)
Typedef Documentation
typedef const char*(* prelexer)(const char *)
Definition at line 72 of file lexer.hpp.
Function Documentation
const char * alnum (const char * src)
Definition at line 95 of file lexer.cpp.
References is_alnum().
Referenced by identifier_alnum(), name(), and uri_value().
const char * alpha (const char * src)
Definition at line 91 of file lexer.cpp.
References is_alpha().
Referenced by Sass::Functions::BUILT_IN(), identifier_alpha(), and Sass::register_built_in_functions().
const char* Sass::Prelexer::alternatives (const char * src) [inline]
Definition at line 146 of file lexer.hpp.
Referenced by double_quoted_string(), identifier_alnum(), identifier_alpha(), identifier_schema(), ie_keyword_arg_property(), ie_keyword_arg_value(), name(), number_prefix(), Parser::parse_comma_list(), Parser::parse_factor(), Parser::parse_relation(), Parser::parse_selector_combination(), Parser::parse_selector_group(), Parser::parse_space_list(), quoted_string(), single_quoted_string(), static_component(), static_value(), and uri_value().
const char * ampersand (const char * src)
Definition at line 405 of file prelexer.cpp.
const char * any_char (const char * src)
Definition at line 108 of file lexer.cpp.
Referenced by escape_seq(), and line_comment().
const char* Sass::Prelexer::any_char_but (const char * src) [inline]
Definition at line 121 of file lexer.hpp.
Referenced by double_quoted_string().
const char * at_keyword (const char * src)
Definition at line 215 of file prelexer.cpp.
References identifier().
const char * attribute_name (const char * src)
Definition at line 367 of file prelexer.cpp.
References identifier().
const char* Sass::Prelexer::between (const char * src) [inline]
Definition at line 151 of file prelexer.hpp.
const char * binomial (const char * src)
Definition at line 393 of file prelexer.cpp.
References digits(), and sign().
const char * block_comment (const char * src)
Definition at line 33 of file prelexer.cpp.
References delimited_by(), sequence(), Sass::Constants::slash_star, and Sass::Constants::star_slash.
const char* Sass::Prelexer::block_comment_prefix (const char * src)
const char * character (const char * src)
Definition at line 97 of file lexer.cpp.
References is_character().
Referenced by Sass::findCommentOpener(), and Sass::removeMultilineComment().
const char* Sass::Prelexer::class_char (const char * src) [inline]
Definition at line 103 of file lexer.hpp.
const char* Sass::Prelexer::class_chars (const char * src) [inline]
Definition at line 112 of file lexer.hpp.
References p().
const char * class_match (const char * src)
Definition at line 526 of file prelexer.cpp.
const char * class_name (const char * src)
Definition at line 363 of file prelexer.cpp.
References exactly(), identifier(), and sequence().
const char * coefficient (const char * src)
Definition at line 389 of file prelexer.cpp.
References digits(), and sign().
const char* Sass::Prelexer::comment (const char * src)
Referenced by BackendController::diario_comment_discard(), DiarioCommentEmail::DiarioCommentEmail(), DiarioCommentFollowupEmail::DiarioCommentFollowupEmail(), Sass::findCommentOpener(), SoftwareCommentFollowupEmail::make_text(), SoftwareCommentEmail::make_text(), DiarioCommentFollowupEmail::make_text(), DiarioCommentEmail::make_text(), Sass::removeMultilineComment(), BackendController::software_comment_discard(), SoftwareCommentEmail::SoftwareCommentEmail(), and SoftwareCommentFollowupEmail::SoftwareCommentFollowupEmail().
unsigned int Sass::Prelexer::count_interval (const char * beg, const char * end) [inline]
Definition at line 353 of file prelexer.hpp.
References p().
const char * css_comments (const char * src)
Definition at line 65 of file prelexer.cpp.
Referenced by Parser::sneak().
const char * css_whitespace (const char * src)
Definition at line 58 of file prelexer.cpp.
Referenced by Parser::parse_factor(), and Parser::sneak().
const char* Sass::Prelexer::custom_property_name (const char * src)
const char * dash_match (const char * src)
Definition at line 527 of file prelexer.cpp.
const char * default_flag (const char * src)
Definition at line 491 of file prelexer.cpp.
References optional_css_whitespace().
Referenced by Parser::parse_space_list().
const char * delimited_by (const char * src) [inline]
Definition at line 44 of file prelexer.hpp.
Referenced by block_comment().
const char * digit (const char * src)
Definition at line 93 of file lexer.cpp.
References is_digit().
Referenced by Base64VLQ::encode().
const char * digits (const char * src)
Definition at line 101 of file lexer.cpp.
Referenced by binomial(), coefficient(), and unsigned_number().
const char * dimension (const char * src)
Definition at line 413 of file prelexer.cpp.
Referenced by Parser::parse_value().
const char * double_quoted_string (const char * src)
Definition at line 169 of file prelexer.cpp.
References alternatives(), any_char_but(), escape_seq(), exactly(), interpolant(), sequence(), and zero_plus().
Referenced by quoted_string().
const char * elseif_directive (const char * src)
Definition at line 279 of file prelexer.cpp.
References optional_css_whitespace().
const char * end_of_line (const char * src)
Definition at line 126 of file lexer.cpp.
Referenced by line_comment().
const char * escape_seq (const char * src)
Definition at line 70 of file prelexer.cpp.
References any_char(), and sequence().
Referenced by double_quoted_string(), identifier_alnum(), identifier_alpha(), and single_quoted_string().
const char * even (const char * src)
Definition at line 518 of file prelexer.cpp.
const char * exact_match (const char * src)
Definition at line 525 of file prelexer.cpp.
const char * exactly (const char * src) [inline]
Definition at line 81 of file lexer.hpp.
Referenced by class_name(), double_quoted_string(), hyphens_and_identifier(), hyphens_and_name(), identifier(), identifier_alnum(), identifier_alpha(), identifier_schema(), ie_progid(), kwd_dot(), kwd_minus(), kwd_slash(), line_comment(), Parser::lookahead_for_selector(), name(), number_prefix(), Parser::parse_arguments(), Parser::parse_at_root_block(), Parser::parse_at_root_expression(), Parser::parse_at_rule(), Parser::parse_comma_list(), Parser::parse_declaration(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_factor(), Parser::parse_feature_block(), Parser::parse_feature_queries(), Parser::parse_feature_query(), Parser::parse_feature_query_in_parens(), Parser::parse_for_directive(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_map(), Parser::parse_media_block(), Parser::parse_media_expression(), Parser::parse_media_queries(), Parser::parse_mixin_call(), Parser::parse_parameters(), Parser::parse_ruleset(), Parser::parse_selector_group(), Parser::parse_space_list(), Parser::parse_value_schema(), static_value(), unsigned_number(), and uri_value().
const char * find_first (const char * src) [inline]
Definition at line 332 of file prelexer.hpp.
const char* Sass::Prelexer::find_first_in_interval (const char * beg, const char * end) [inline]
Definition at line 342 of file prelexer.hpp.
Referenced by Parser::parse_selector_schema().
const char * functional (const char * src)
Definition at line 510 of file prelexer.cpp.
const char * functional_schema (const char * src)
Definition at line 507 of file prelexer.cpp.
const char * global_flag (const char * src)
Definition at line 497 of file prelexer.cpp.
References optional_css_whitespace().
Referenced by Parser::parse_space_list().
const char * hex (const char * src)
Definition at line 416 of file prelexer.cpp.
References p().
Referenced by Sass::Functions::BUILT_IN(), Markdown_Parser::encodeEmailAddress(), imp::hex_encode(), longToHex(), static_component(), and write_hex16().
const char * hex0 (const char * src)
Definition at line 426 of file prelexer.cpp.
References p().
const char * hexa (const char * src)
Definition at line 421 of file prelexer.cpp.
References p().
Referenced by ie_keyword_arg_value().
const char * hyphens_and_identifier (const char * src)
Definition at line 349 of file prelexer.cpp.
References exactly(), identifier(), sequence(), and zero_plus().
const char * hyphens_and_name (const char * src)
Definition at line 352 of file prelexer.cpp.
References exactly(), name(), sequence(), and zero_plus().
const char * id_name (const char * src)
Definition at line 359 of file prelexer.cpp.
References name().
const char * identifier (const char * src)
Definition at line 103 of file prelexer.cpp.
References exactly(), sequence(), and zero_plus().
Referenced by at_keyword(), attribute_name(), class_name(), hyphens_and_identifier(), identifier_schema(), ie_keyword_arg_property(), ie_keyword_arg_value(), Sass::make_native_function(), Parser::parse_declaration(), placeholder(), static_component(), type_selector(), and variable().
const char * identifier_alnum (const char * src)
Definition at line 91 of file prelexer.cpp.
References alnum(), alternatives(), escape_seq(), exactly(), and unicode().
const char * identifier_alnums (const char * src)
Definition at line 113 of file prelexer.cpp.
const char * identifier_alpha (const char * src)
Definition at line 79 of file prelexer.cpp.
References alpha(), alternatives(), escape_seq(), exactly(), and unicode().
const char * identifier_schema (const char * src)
Definition at line 131 of file prelexer.cpp.
References alternatives(), exactly(), identifier(), interpolant(), number(), one_plus(), sequence(), and zero_plus().
Referenced by ie_keyword_arg_property(), ie_keyword_arg_value(), Parser::parse_declaration(), Parser::parse_factor(), and Parser::parse_identifier_schema().
const char * ie_expression (const char * src)
Definition at line 623 of file prelexer.cpp.
const char * ie_keyword_arg (const char * src)
Definition at line 660 of file prelexer.cpp.
References ie_keyword_arg_property(), ie_keyword_arg_value(), optional_css_whitespace(), and sequence().
const char * ie_keyword_arg_property (const char * src)
Definition at line 635 of file prelexer.cpp.
References alternatives(), identifier(), identifier_schema(), and variable().
Referenced by ie_keyword_arg().
const char * ie_keyword_arg_value (const char * src)
Definition at line 642 of file prelexer.cpp.
References alternatives(), hexa(), identifier(), identifier_schema(), number(), quoted_string(), sequence(), skip_over_scopes(), and variable().
Referenced by ie_keyword_arg().
const char * ie_progid (const char * src)
Definition at line 587 of file prelexer.cpp.
References exactly(), optional(), optional_css_whitespace(), sequence(), and zero_plus().
const char * ie_property (const char * src)
Definition at line 626 of file prelexer.cpp.
const char * important (const char * src)
Definition at line 479 of file prelexer.cpp.
References optional_css_whitespace().
Referenced by Output::operator()().
const char * interpolant (const char * src)
Definition at line 140 of file prelexer.cpp.
Referenced by double_quoted_string(), identifier_schema(), Parser::parse_selector_schema(), single_quoted_string(), and value_schema().
bool is_alnum (const char & chr)
Definition at line 66 of file lexer.cpp.
References is_alpha(), and is_digit().
Referenced by alnum(), and is_character().
bool is_alpha (const char & chr)
Definition at line 34 of file lexer.cpp.
Referenced by alpha(), and is_alnum().
bool is_character (const char & chr)
Definition at line 79 of file lexer.cpp.
References is_alnum(), and is_unicode().
Referenced by character(), and word_boundary().
bool is_digit (const char & chr)
Definition at line 46 of file lexer.cpp.
Referenced by digit(), and is_alnum().
bool is_punct (const char & chr)
Definition at line 60 of file lexer.cpp.
Referenced by punct().
bool is_space (const char & chr)
Definition at line 40 of file lexer.cpp.
Referenced by space().
bool is_unicode (const char & chr)
Definition at line 72 of file lexer.cpp.
Referenced by is_character(), and unicode().
bool is_xdigit (const char & chr)
Definition at line 52 of file lexer.cpp.
Referenced by xdigit().
const char * kwd_and (const char * src)
Definition at line 558 of file prelexer.cpp.
const char * kwd_at (const char * src)
Definition at line 19 of file lexer.cpp.
const char * kwd_at_root (const char * src)
Definition at line 227 of file prelexer.cpp.
const char * kwd_colon (const char * src)
Definition at line 22 of file lexer.cpp.
const char * kwd_comma (const char * src)
Definition at line 21 of file lexer.cpp.
const char * kwd_content (const char * src)
Definition at line 263 of file prelexer.cpp.
const char * kwd_dbg (const char * src)
Definition at line 328 of file prelexer.cpp.
const char * kwd_dot (const char * src)
Definition at line 20 of file lexer.cpp.
References exactly().
const char * kwd_each_directive (const char * src)
Definition at line 301 of file prelexer.cpp.
const char * kwd_else_directive (const char * src)
Definition at line 276 of file prelexer.cpp.
const char * kwd_eq (const char * src)
Definition at line 567 of file prelexer.cpp.
Referenced by Parser::parse_relation().
const char * kwd_err (const char * src)
Definition at line 324 of file prelexer.cpp.
const char * kwd_extend (const char * src)
Definition at line 267 of file prelexer.cpp.
const char * kwd_false (const char * src)
Definition at line 555 of file prelexer.cpp.
const char * kwd_for_directive (const char * src)
Definition at line 285 of file prelexer.cpp.
const char * kwd_from (const char * src)
Definition at line 289 of file prelexer.cpp.
const char * kwd_function (const char * src)
Definition at line 251 of file prelexer.cpp.
const char * kwd_gt (const char * src)
Definition at line 573 of file prelexer.cpp.
Referenced by Parser::parse_relation().
const char * kwd_gte (const char * src)
Definition at line 576 of file prelexer.cpp.
Referenced by Parser::parse_relation().
const char * kwd_if_directive (const char * src)
Definition at line 272 of file prelexer.cpp.
const char * kwd_import (const char * src)
Definition at line 223 of file prelexer.cpp.
const char * kwd_in (const char * src)
Definition at line 305 of file prelexer.cpp.
const char * kwd_include (const char * src)
Definition at line 259 of file prelexer.cpp.
const char * kwd_lt (const char * src)
Definition at line 579 of file prelexer.cpp.
Referenced by Parser::parse_relation().
const char * kwd_lte (const char * src)
Definition at line 582 of file prelexer.cpp.
Referenced by Parser::parse_relation().
const char * kwd_media (const char * src)
Definition at line 239 of file prelexer.cpp.
const char * kwd_minus (const char * src)
Definition at line 25 of file lexer.cpp.
References exactly().
const char * kwd_mixin (const char * src)
Definition at line 247 of file prelexer.cpp.
const char * kwd_neq (const char * src)
Definition at line 570 of file prelexer.cpp.
Referenced by Parser::parse_relation().
const char * kwd_not (const char * src)
Definition at line 564 of file prelexer.cpp.
const char * kwd_null (const char * src)
Definition at line 337 of file prelexer.cpp.
const char * kwd_or (const char * src)
Definition at line 561 of file prelexer.cpp.
const char * kwd_plus (const char * src)
Definition at line 24 of file lexer.cpp.
const char * kwd_return_directive (const char * src)
Definition at line 255 of file prelexer.cpp.
const char * kwd_sel_deep (const char * src)
Definition at line 219 of file prelexer.cpp.
const char * kwd_slash (const char * src)
Definition at line 26 of file lexer.cpp.
References exactly().
const char * kwd_star (const char * src)
Definition at line 23 of file lexer.cpp.
const char * kwd_supports (const char * src)
Definition at line 243 of file prelexer.cpp.
const char * kwd_through (const char * src)
Definition at line 297 of file prelexer.cpp.
const char * kwd_to (const char * src)
Definition at line 293 of file prelexer.cpp.
const char * kwd_true (const char * src)
Definition at line 552 of file prelexer.cpp.
const char * kwd_warn (const char * src)
Definition at line 320 of file prelexer.cpp.
const char * kwd_while_directive (const char * src)
Definition at line 309 of file prelexer.cpp.
const char * kwd_with_directive (const char * src)
Definition at line 231 of file prelexer.cpp.
const char * kwd_without_directive (const char * src)
Definition at line 235 of file prelexer.cpp.
const char * line_comment (const char * src)
Definition at line 19 of file prelexer.cpp.
References any_char(), end_of_line(), exactly(), non_greedy(), sequence(), and Sass::Constants::slash_slash.
const char* Sass::Prelexer::line_comment_prefix (const char * src)
const char* Sass::Prelexer::lookahead (const char * src) [inline]
Definition at line 138 of file lexer.hpp.
Referenced by Parser::parse_argument(), and Parser::parse_assignment().
const char * loosely (const char * src) [inline]
Definition at line 222 of file lexer.hpp.
References optional_spaces(), and sequence().
Referenced by Parser::parse_argument().
const char* Sass::Prelexer::name (const char * src)
Definition at line 313 of file prelexer.cpp.
References alnum(), alternatives(), exactly(), and one_plus().
Referenced by Software::appcast_permalink(), Sass::bind(), Sass::Functions::BUILT_IN(), BaseController::cached_page_filename(), Software::changelog_permalink(), EmeController::check_auth(), Software::comments_permalink(), ContactEmail::ContactEmail(), debug_ast(), DiarioCommentEmail::DiarioCommentEmail(), DiarioCommentFollowupEmail::DiarioCommentFollowupEmail(), Software::donate_permalink(), Email::Email(), BaseController::expire_cached_page(), Variable::hash(), Function_Call::hash(), Argument::hash(), hyphens_and_name(), Software::icon(), id_name(), BaseController::initialize(), Eval::interpolation(), LicenseEmail::LicenseEmail(), Sass::make_c_function(), Sass::make_native_function(), BaseController::make_relative_url(), SoftwareCommentEmail::make_text(), Email::make_text(), DiarioCommentEmail::make_text(), ContactEmail::make_text(), Inspect::operator()(), Eval::operator()(), Variable::operator==(), Function_Call::operator==(), Argument::operator==(), Parser::parse_argument(), Parser::parse_arguments(), Parser::parse_assignment(), Parser::parse_calc_function(), Parser::parse_definition(), Parser::parse_function_call(), Parser::parse_function_call_schema(), parse_long_options(), Parser::parse_mixin_call(), Parser::parse_parameter(), Parser::parse_parameters(), SoftwareController::redirect_to_software_page(), Software::registration_permalink(), Software::relative_url(), BaseController::render(), BaseController::render_component(), BaseController::render_layout(), Sass::File::resolve_file(), select(), Context::setup_color_map(), SoftwareCommentEmail::SoftwareCommentEmail(), SoftwareCommentFollowupEmail::SoftwareCommentFollowupEmail(), Selector_Qualifier::specificity(), Type_Selector::specificity(), Pseudo_Selector::unify_with(), Selector_Qualifier::unify_with(), Type_Selector::unify_with(), and Software::url_to_detail().
const char * namespace_prefix (const char * src)
Definition at line 342 of file prelexer.cpp.
const char* Sass::Prelexer::negate (const char * src) [inline]
Definition at line 129 of file lexer.hpp.
Referenced by Parser::parse_factor(), and uri_value().
const char * no_spaces (const char * src)
Definition at line 104 of file lexer.cpp.
Referenced by Parser::sneak().
const char* Sass::Prelexer::non_greedy (const char * src) [inline]
Definition at line 197 of file lexer.hpp.
References p().
Referenced by line_comment().
const char * number (const char * src)
Definition at line 386 of file prelexer.cpp.
References unsigned_number().
Referenced by identifier_schema(), ie_keyword_arg_value(), Eval::operator()(), Parser::parse_factor(), Parser::parse_static_expression(), and static_component().
const char * number_prefix (const char * src)
Definition at line 119 of file prelexer.cpp.
References alternatives(), exactly(), optional_css_whitespace(), and sequence().
const char * odd (const char * src)
Definition at line 521 of file prelexer.cpp.
const char* Sass::Prelexer::one_plus (const char * src) [inline]
Definition at line 186 of file lexer.hpp.
References p().
Referenced by identifier_schema(), name(), Parser::parse(), Parser::parse_declaration(), and Parser::parse_factor().
const char * optional (const char * src) [inline]
Definition at line 169 of file lexer.hpp.
References p().
Referenced by ie_progid(), Parser::parse_declaration(), and Parser::parse_value().
const char * optional_css_comments (const char * src)
Definition at line 62 of file prelexer.cpp.
Referenced by Parser::parse_argument(), and Parser::sneak().
const char * optional_css_whitespace (const char * src)
Definition at line 55 of file prelexer.cpp.
Referenced by default_flag(), elseif_directive(), global_flag(), ie_keyword_arg(), ie_progid(), important(), number_prefix(), Parser::parse_factor(), Parser::sneak(), and static_value().
const char * optional_spaces (const char * src)
Definition at line 105 of file lexer.cpp.
Referenced by loosely(), Parser::parse_selector_schema(), Parser::sneak(), and static_value().
const char * parenthese_scope (const char * src)
Definition at line 773 of file prelexer.cpp.
References sequence(), and skip_over_scopes().
const char * percentage (const char * src)
Definition at line 402 of file prelexer.cpp.
Referenced by Sass::register_built_in_functions(), and static_component().
const char * placeholder (const char * src)
Definition at line 372 of file prelexer.cpp.
References identifier().
const char * prefix_match (const char * src)
Definition at line 528 of file prelexer.cpp.
const char * pseudo_not (const char * src)
Definition at line 514 of file prelexer.cpp.
const char * pseudo_prefix (const char * src)
Definition at line 503 of file prelexer.cpp.
const char * punct (const char * src)
Definition at line 96 of file lexer.cpp.
References is_punct().
const char * quoted_string (const char * src)
Definition at line 193 of file prelexer.cpp.
References alternatives(), double_quoted_string(), and single_quoted_string().
Referenced by ie_keyword_arg_value(), and static_string().
const char * re_linebreak (const char * src)
Definition at line 114 of file lexer.cpp.
const char* Sass::Prelexer::recursive_scopes (const char * src) [inline]
Definition at line 126 of file prelexer.hpp.
const char* Sass::Prelexer::sequence (const char * src) [inline]
Definition at line 158 of file lexer.hpp.
Referenced by block_comment(), class_name(), double_quoted_string(), escape_seq(), hyphens_and_identifier(), hyphens_and_name(), identifier(), identifier_schema(), ie_keyword_arg(), ie_keyword_arg_value(), ie_progid(), line_comment(), loosely(), number_prefix(), parenthese_scope(), Parser::parse_argument(), Parser::parse_declaration(), Parser::parse_expression(), Parser::parse_factor(), Parser::parse_identifier_schema(), Parser::parse_ie_property(), Parser::parse_interpolated_chunk(), Parser::parse_selector_schema(), Parser::parse_static_expression(), Parser::parse_value(), single_quoted_string(), static_value(), uri_value(), and word().
const char * sign (const char * src)
Definition at line 377 of file prelexer.cpp.
Referenced by binomial(), and coefficient().
const char * single_quoted_string (const char * src)
Definition at line 145 of file prelexer.cpp.
References alternatives(), escape_seq(), interpolant(), sequence(), and zero_plus().
Referenced by quoted_string().
const char* Sass::Prelexer::skip_over_scopes (const char * src) [inline]
Definition at line 120 of file prelexer.hpp.
Referenced by Parser::parse_import().
const char* Sass::Prelexer::skip_over_scopes (const char * src, const char * end) [inline]
Definition at line 61 of file prelexer.hpp.
References Sass::Functions::level.
Referenced by ie_keyword_arg_value(), and parenthese_scope().
const char * space (const char * src)
Definition at line 90 of file lexer.cpp.
References is_space().
const char * spaces (const char * src)
Definition at line 100 of file lexer.cpp.
Referenced by Emitter::flush_schedules(), Parser::sneak(), and static_value().
const char * static_component (const char * src)
Definition at line 742 of file prelexer.cpp.
References alternatives(), hex(), identifier(), number(), percentage(), and static_string().
Referenced by static_value().
const char * static_string (const char * src)
Definition at line 734 of file prelexer.cpp.
References Token::begin, Token::end, p(), quoted_string(), and s().
Referenced by static_component().
const char * static_value (const char * src)
Definition at line 752 of file prelexer.cpp.
References alternatives(), exactly(), optional_css_whitespace(), optional_spaces(), sequence(), spaces(), static_component(), and zero_plus().
const char * substring_match (const char * src)
Definition at line 530 of file prelexer.cpp.
const char * suffix_match (const char * src)
Definition at line 529 of file prelexer.cpp.
const char * type_selector (const char * src)
Definition at line 346 of file prelexer.cpp.
References identifier().
const char * unicode (const char * src)
Definition at line 92 of file lexer.cpp.
References is_unicode().
Referenced by emit_string(), identifier_alnum(), identifier_alpha(), and parse_string().
const char * universal (const char * src)
Definition at line 355 of file prelexer.cpp.
const char * unsigned_number (const char * src)
Definition at line 380 of file prelexer.cpp.
References digits(), and exactly().
Referenced by number().
const char * uri_prefix (const char * src)
Definition at line 438 of file prelexer.cpp.
const char * uri_value (const char * src)
Definition at line 441 of file prelexer.cpp.
References alnum(), alternatives(), exactly(), negate(), sequence(), and zero_plus().
Referenced by Parser::parse_argument().
const char* Sass::Prelexer::url (const char * src)
Referenced by Context::format_source_mapping_url(), OpenGraph::OpenGraph(), GoogleGroupsEntry::permalink(), and Trackback::Trackback().
const char * value_schema (const char * src)
Definition at line 201 of file prelexer.cpp.
References interpolant().
const char * variable (const char * src)
Definition at line 547 of file prelexer.cpp.
References identifier().
Referenced by ie_keyword_arg_property(), ie_keyword_arg_value(), Expand::operator()(), Eval::operator()(), and Parser::parse_argument().
const char* Sass::Prelexer::vendor_prefix (const char * src)
const char* Sass::Prelexer::word (const char * src) [inline]
Definition at line 214 of file lexer.hpp.
References sequence(), and word_boundary().
const char * word_boundary (const char * src)
Definition at line 111 of file lexer.cpp.
References is_character().
Referenced by word().
const char * xdigit (const char * src)
Definition at line 94 of file lexer.cpp.
References is_xdigit().
const char* Sass::Prelexer::zero_plus (const char * src) [inline]
Definition at line 177 of file lexer.hpp.
References p().
Referenced by double_quoted_string(), hyphens_and_identifier(), hyphens_and_name(), identifier(), identifier_schema(), ie_progid(), single_quoted_string(), static_value(), and uri_value().