Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_functions.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_functions.h File Reference
#include <stddef.h>
#include <stdbool.h>
#include "sass.h"
Typedefs
typedef struct Sass_Import * Sass_Import_Entry
typedef struct Sass_Import ** Sass_Import_List
typedef struct Sass_Importer * Sass_Importer_Entry
typedef struct Sass_Importer ** Sass_Importer_List
typedef Sass_Import_List(* Sass_Importer_Fn)(const char *url, Sass_Importer_Entry cb, struct Sass_Compiler *compiler)
typedef struct Sass_Function * Sass_Function_Entry
typedef struct Sass_Function ** Sass_Function_List
typedef union Sass_Value *(* Sass_Function_Fn)(const union Sass_Value *, Sass_Function_Entry cb, struct Sass_Options *options)
Functions
ADDAPI Sass_Importer_List ADDCALL sass_make_importer_list (size_t length)
ADDAPI Sass_Importer_Entry ADDCALL sass_importer_get_list_entry (Sass_Importer_List list, size_t idx)
ADDAPI void ADDCALL sass_importer_set_list_entry (Sass_Importer_List list, size_t idx, Sass_Importer_Entry entry)
ADDAPI Sass_Importer_Entry ADDCALL sass_make_importer (Sass_Importer_Fn importer, double priority, void *cookie)
ADDAPI Sass_Importer_Fn ADDCALL sass_importer_get_function (Sass_Importer_Entry cb)
ADDAPI double ADDCALL sass_importer_get_priority (Sass_Importer_Entry cb)
ADDAPI void *ADDCALL sass_importer_get_cookie (Sass_Importer_Entry cb)
ADDAPI void ADDCALL sass_delete_importer (Sass_Importer_Entry cb)
ADDAPI Sass_Import_List ADDCALL sass_make_import_list (size_t length)
ADDAPI Sass_Import_Entry ADDCALL sass_make_import_entry (const char *path, char *source, char *srcmap)
ADDAPI Sass_Import_Entry ADDCALL sass_make_import (const char *path, const char *base, char *source, char *srcmap)
ADDAPI Sass_Import_Entry ADDCALL sass_import_set_error (Sass_Import_Entry import, const char *message, size_t line, size_t col)
ADDAPI void ADDCALL sass_import_set_list_entry (Sass_Import_List list, size_t idx, Sass_Import_Entry entry)
ADDAPI Sass_Import_Entry ADDCALL sass_import_get_list_entry (Sass_Import_List list, size_t idx)
ADDAPI const char *ADDCALL sass_import_get_path (Sass_Import_Entry)
ADDAPI const char *ADDCALL sass_import_get_base (Sass_Import_Entry)
ADDAPI const char *ADDCALL sass_import_get_source (Sass_Import_Entry)
ADDAPI const char *ADDCALL sass_import_get_srcmap (Sass_Import_Entry)
ADDAPI char *ADDCALL sass_import_take_source (Sass_Import_Entry)
ADDAPI char *ADDCALL sass_import_take_srcmap (Sass_Import_Entry)
ADDAPI size_t ADDCALL sass_import_get_error_line (Sass_Import_Entry)
ADDAPI size_t ADDCALL sass_import_get_error_column (Sass_Import_Entry)
ADDAPI const char *ADDCALL sass_import_get_error_message (Sass_Import_Entry)
ADDAPI void ADDCALL sass_delete_import_list (Sass_Import_List)
ADDAPI void ADDCALL sass_delete_import (Sass_Import_Entry)
ADDAPI Sass_Function_List ADDCALL sass_make_function_list (size_t length)
ADDAPI Sass_Function_Entry ADDCALL sass_make_function (const char *signature, Sass_Function_Fn cb, void *cookie)
ADDAPI Sass_Function_Entry ADDCALL sass_function_get_list_entry (Sass_Function_List list, size_t pos)
ADDAPI void ADDCALL sass_function_set_list_entry (Sass_Function_List list, size_t pos, Sass_Function_Entry cb)
ADDAPI const char *ADDCALL sass_function_get_signature (Sass_Function_Entry cb)
ADDAPI Sass_Function_Fn ADDCALL sass_function_get_function (Sass_Function_Entry cb)
ADDAPI void *ADDCALL sass_function_get_cookie (Sass_Function_Entry cb)
Typedef Documentation
typedef struct Sass_Function* Sass_Function_Entry
Definition at line 31 of file sass_functions.h.
typedef union Sass_Value*(* Sass_Function_Fn)(const union Sass_Value *, Sass_Function_Entry cb, struct Sass_Options *options)
Definition at line 35 of file sass_functions.h.
typedef struct Sass_Function** Sass_Function_List
Definition at line 32 of file sass_functions.h.
typedef struct Sass_Import* Sass_Import_Entry
Definition at line 21 of file sass_functions.h.
typedef struct Sass_Import** Sass_Import_List
Definition at line 22 of file sass_functions.h.
typedef struct Sass_Importer* Sass_Importer_Entry
Definition at line 24 of file sass_functions.h.
typedef Sass_Import_List(* Sass_Importer_Fn)(const char *url, Sass_Importer_Entry cb, struct Sass_Compiler *compiler)
Definition at line 28 of file sass_functions.h.
typedef struct Sass_Importer** Sass_Importer_List
Definition at line 25 of file sass_functions.h.
Function Documentation
ADDAPI void ADDCALL sass_delete_import (Sass_Import_Entry)
Definition at line 150 of file sass_functions.cpp.
Referenced by Context::parse_file(), sass_delete_import_list(), and Context::~Context().
ADDAPI void ADDCALL sass_delete_import_list (Sass_Import_List)
Definition at line 138 of file sass_functions.cpp.
References sass_delete_import().
Referenced by Parser::do_import().
ADDAPI void ADDCALL sass_delete_importer (Sass_Importer_Entry cb)
Definition at line 80 of file sass_functions.cpp.
ADDAPI void* ADDCALL sass_function_get_cookie (Sass_Function_Entry cb)
Definition at line 44 of file sass_functions.cpp.
References Sass_Function::cookie.
Referenced by custom_function(), and sass_custom_function().
ADDAPI Sass_Function_Fn ADDCALL sass_function_get_function (Sass_Function_Entry cb)
Definition at line 43 of file sass_functions.cpp.
References Sass_Function::function.
Referenced by Eval::operator()().
ADDAPI Sass_Function_Entry ADDCALL sass_function_get_list_entry (Sass_Function_List list, size_t pos)
Definition at line 39 of file sass_functions.cpp.
ADDAPI const char* ADDCALL sass_function_get_signature (Sass_Function_Entry cb)
Definition at line 42 of file sass_functions.cpp.
References Sass_Function::signature.
Referenced by Sass::make_c_function().
ADDAPI void ADDCALL sass_function_set_list_entry (Sass_Function_List list, size_t pos, Sass_Function_Entry cb)
Definition at line 40 of file sass_functions.cpp.
Referenced by ExtractOptions(), and libsass_load_functions().
ADDAPI const char* ADDCALL sass_import_get_base (Sass_Import_Entry)
Definition at line 162 of file sass_functions.cpp.
References Sass_Import::base.
ADDAPI size_t ADDCALL sass_import_get_error_column (Sass_Import_Entry)
Definition at line 168 of file sass_functions.cpp.
References Sass_Import::column.
Referenced by Parser::do_import().
ADDAPI size_t ADDCALL sass_import_get_error_line (Sass_Import_Entry)
Definition at line 167 of file sass_functions.cpp.
References Sass_Import::line.
Referenced by Parser::do_import().
ADDAPI const char* ADDCALL sass_import_get_error_message (Sass_Import_Entry)
Definition at line 169 of file sass_functions.cpp.
References Sass_Import::error.
Referenced by Parser::do_import().
ADDAPI Sass_Import_Entry ADDCALL sass_import_get_list_entry (Sass_Import_List list, size_t idx)
Definition at line 135 of file sass_functions.cpp.
ADDAPI const char* ADDCALL sass_import_get_path (Sass_Import_Entry)
Definition at line 161 of file sass_functions.cpp.
References Sass_Import::path.
Referenced by Parser::do_import(), and sass_importer().
ADDAPI const char* ADDCALL sass_import_get_source (Sass_Import_Entry)
Definition at line 163 of file sass_functions.cpp.
References Sass_Import::source.
ADDAPI const char* ADDCALL sass_import_get_srcmap (Sass_Import_Entry)
Definition at line 164 of file sass_functions.cpp.
References Sass_Import::srcmap.
ADDAPI Sass_Import_Entry ADDCALL sass_import_set_error (Sass_Import_Entry import, const char * message, size_t line, size_t col)
Definition at line 123 of file sass_functions.cpp.
Referenced by CustomImporterBridge::check_returned_string(), and CustomImporterBridge::post_process_return_value().
ADDAPI void ADDCALL sass_import_set_list_entry (Sass_Import_List list, size_t idx, Sass_Import_Entry entry)
Definition at line 134 of file sass_functions.cpp.
ADDAPI char* ADDCALL sass_import_take_source (Sass_Import_Entry)
Definition at line 173 of file sass_functions.cpp.
References Sass_Import::source.
Referenced by Parser::do_import().
ADDAPI char* ADDCALL sass_import_take_srcmap (Sass_Import_Entry)
Definition at line 174 of file sass_functions.cpp.
References Sass_Import::srcmap.
ADDAPI void* ADDCALL sass_importer_get_cookie (Sass_Importer_Entry cb)
Definition at line 77 of file sass_functions.cpp.
References Sass_Importer::cookie.
Referenced by custom_importer(), and sass_importer().
ADDAPI Sass_Importer_Fn ADDCALL sass_importer_get_function (Sass_Importer_Entry cb)
Definition at line 75 of file sass_functions.cpp.
References Sass_Importer::importer.
Referenced by Parser::do_import().
ADDAPI Sass_Importer_Entry ADDCALL sass_importer_get_list_entry (Sass_Importer_List list, size_t idx)
Definition at line 91 of file sass_functions.cpp.
ADDAPI double ADDCALL sass_importer_get_priority (Sass_Importer_Entry cb)
Definition at line 76 of file sass_functions.cpp.
References Sass_Importer::priority.
Referenced by Sass::sort_importers().
ADDAPI void ADDCALL sass_importer_set_list_entry (Sass_Importer_List list, size_t idx, Sass_Importer_Entry entry)
Definition at line 92 of file sass_functions.cpp.
Referenced by libsass_load_importers().
ADDAPI Sass_Function_Entry ADDCALL sass_make_function (const char * signature, Sass_Function_Fn cb, void * cookie)
Definition at line 28 of file sass_functions.cpp.
References Sass_Function::cookie, Sass_Function::function, and Sass_Function::signature.
Referenced by ExtractOptions(), and libsass_load_functions().
ADDAPI Sass_Function_List ADDCALL sass_make_function_list (size_t length)
Definition at line 23 of file sass_functions.cpp.
Referenced by ExtractOptions(), and libsass_load_functions().
ADDAPI Sass_Import_Entry ADDCALL sass_make_import (const char * path, const char * base, char * source, char * srcmap)
Definition at line 102 of file sass_functions.cpp.
References Sass_Import::base, Sass_Import::column, Sass_Import::error, Sass_Import::line, Sass_Import::path, Sass::sass_strdup(), Sass_Import::source, and Sass_Import::srcmap.
Referenced by Context::parse_file(), and sass_make_import_entry().
ADDAPI Sass_Import_Entry ADDCALL sass_make_import_entry (const char * path, char * source, char * srcmap)
Definition at line 117 of file sass_functions.cpp.
References sass_make_import().
Referenced by CustomImporterBridge::check_returned_string(), custom_importer(), CustomImporterBridge::get_importer_entry(), and CustomImporterBridge::post_process_return_value().
ADDAPI Sass_Import_List ADDCALL sass_make_import_list (size_t length)
Definition at line 95 of file sass_functions.cpp.
Referenced by custom_importer(), and CustomImporterBridge::post_process_return_value().
ADDAPI Sass_Importer_Entry ADDCALL sass_make_importer (Sass_Importer_Fn importer, double priority, void * cookie)
Definition at line 65 of file sass_functions.cpp.
References Sass_Importer::cookie, Sass_Importer::importer, and Sass_Importer::priority.
Referenced by ExtractOptions(), and libsass_load_importers().
ADDAPI Sass_Importer_List ADDCALL sass_make_importer_list (size_t length)
Definition at line 86 of file sass_functions.cpp.
Referenced by ExtractOptions(), and libsass_load_importers().