Emeraldion Lodge (codename Zelda): iterator< octet_iterator > Class Template Reference
iterator< octet_iterator > Class Template Reference
#include <checked.h>
Public Member Functions
iterator ()
iterator (const octet_iterator &octet_it, const octet_iterator &range_start, const octet_iterator &range_end)
octet_iterator base () const
uint32_t operator* () const
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
Private Attributes
octet_iterator it
octet_iterator range_start
octet_iterator range_end
Detailed Description
template<typename octet_iterator>
class utf8::iterator< octet_iterator >
Definition at line 268 of file checked.h.
Constructor & Destructor Documentation
iterator () [inline]
Definition at line 273 of file checked.h.
iterator (const octet_iterator< octet_iterator > & octet_it, const octet_iterator< octet_iterator > & range_start, const octet_iterator< octet_iterator > & range_end) [inline, explicit]
Definition at line 274 of file checked.h.
Member Function Documentation
octet_iterator base () const [inline]
Definition at line 283 of file checked.h.
References iterator< octet_iterator >::it.
bool operator!= (const iterator< octet_iterator > & rhs) const [inline]
Definition at line 295 of file checked.h.
References iterator< octet_iterator >::operator==().
uint32_t operator* () const [inline]
Definition at line 284 of file checked.h.
References iterator< octet_iterator >::it, utf8::next(), and iterator< octet_iterator >::range_end.
iterator operator++ (int) [inline]
Definition at line 304 of file checked.h.
References iterator< octet_iterator >::it, utf8::next(), and iterator< octet_iterator >::range_end.
iterator& operator++ () [inline]
Definition at line 299 of file checked.h.
References iterator< octet_iterator >::it, utf8::next(), and iterator< octet_iterator >::range_end.
iterator operator-- (int) [inline]
Definition at line 315 of file checked.h.
References iterator< octet_iterator >::it, utf8::prior(), and iterator< octet_iterator >::range_start.
iterator& operator-- () [inline]
Definition at line 310 of file checked.h.
References iterator< octet_iterator >::it, utf8::prior(), and iterator< octet_iterator >::range_start.
bool operator== (const iterator< octet_iterator > & rhs) const [inline]
Definition at line 289 of file checked.h.
References iterator< octet_iterator >::it, iterator< octet_iterator >::range_end, and iterator< octet_iterator >::range_start.
Referenced by iterator< octet_iterator >::operator!=().
Field Documentation
octet_iterator it [private]
Definition at line 269 of file checked.h.
Referenced by iterator< octet_iterator >::base(), iterator< octet_iterator >::operator*(), iterator< octet_iterator >::operator++(), iterator< octet_iterator >::operator--(), and iterator< octet_iterator >::operator==().
octet_iterator range_end [private]
Definition at line 271 of file checked.h.
Referenced by iterator< octet_iterator >::operator*(), iterator< octet_iterator >::operator++(), and iterator< octet_iterator >::operator==().
octet_iterator range_start [private]
Definition at line 270 of file checked.h.
Referenced by iterator< octet_iterator >::operator--(), and iterator< octet_iterator >::operator==().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/utf8/checked.h