Emeraldion Lodge (codename Zelda): AntispamUnitTest Class Reference
AntispamUnitTest Class Reference
Test case for Antispam helper object.
Public Member Functions
test_init_math_test ()
Test method for init_math_test.
test_check_math ()
Test method for check_math.
test_get_spam_signature ()
Test method for get_spam_signature.
test_class ()
Test for class.
Public Member Functions inherited from UnitTest
run ()
Runs all the test cases.
Additional Inherited Members
Protected Member Functions inherited from UnitTest
set_up ()
Sets up fixtures required by test cases.
tear_down ()
Tears down fixtures used by test cases.
report ()
Returns a detailed report of the test case previously run.
Detailed Description
Test case for Antispam helper object.
Definition at line 10 of file test_antispam.php.
Member Function Documentation
test_check_math ()
Test method for check_math.
Definition at line 27 of file test_antispam.php.
References Antispam\$first_operand, Antispam\$second_operand, ERAssertFalse(), ERAssertTrue(), and Antispam\init_math_test().
test_class ()
Test for class.
Definition at line 54 of file test_antispam.php.
References ERAssertOfClass().
test_get_spam_signature ()
Test method for get_spam_signature.
Definition at line 43 of file test_antispam.php.
References ERAssertEqual(), FIXTURE_ANTISPAM_SPAM_TEXT, and FIXTURE_ANTISPAM_SPAM_TEXT_SIGNATURE.
test_init_math_test ()
Test method for init_math_test.
Definition at line 16 of file test_antispam.php.
References ERAssertInRange(), and Antispam\init_math_test().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/test/unit/test_antispam.php