Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_values.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_values.h File Reference
#include <stddef.h>
#include <stdbool.h>
#include "sass.h"
Enumerations
enum Sass_Tag {
SASS_BOOLEAN, SASS_NUMBER, SASS_COLOR, SASS_STRING,
SASS_LIST, SASS_MAP, SASS_NULL, SASS_ERROR,
SASS_WARNING
}
enum Sass_Separator { SASS_COMMA, SASS_SPACE }
Functions
ADDAPI enum Sass_Tag ADDCALL sass_value_get_tag (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_null (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_number (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_string (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_boolean (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_color (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_list (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_map (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_error (const union Sass_Value *v)
ADDAPI bool ADDCALL sass_value_is_warning (const union Sass_Value *v)
ADDAPI double ADDCALL sass_number_get_value (const union Sass_Value *v)
ADDAPI void ADDCALL sass_number_set_value (union Sass_Value *v, double value)
ADDAPI const char *ADDCALL sass_number_get_unit (const union Sass_Value *v)
ADDAPI void ADDCALL sass_number_set_unit (union Sass_Value *v, char *unit)
ADDAPI const char *ADDCALL sass_string_get_value (const union Sass_Value *v)
ADDAPI void ADDCALL sass_string_set_value (union Sass_Value *v, char *value)
ADDAPI bool ADDCALL sass_string_is_quoted (const union Sass_Value *v)
ADDAPI void ADDCALL sass_string_set_quoted (union Sass_Value *v, bool quoted)
ADDAPI bool ADDCALL sass_boolean_get_value (const union Sass_Value *v)
ADDAPI void ADDCALL sass_boolean_set_value (union Sass_Value *v, bool value)
ADDAPI double ADDCALL sass_color_get_r (const union Sass_Value *v)
ADDAPI void ADDCALL sass_color_set_r (union Sass_Value *v, double r)
ADDAPI double ADDCALL sass_color_get_g (const union Sass_Value *v)
ADDAPI void ADDCALL sass_color_set_g (union Sass_Value *v, double g)
ADDAPI double ADDCALL sass_color_get_b (const union Sass_Value *v)
ADDAPI void ADDCALL sass_color_set_b (union Sass_Value *v, double b)
ADDAPI double ADDCALL sass_color_get_a (const union Sass_Value *v)
ADDAPI void ADDCALL sass_color_set_a (union Sass_Value *v, double a)
ADDAPI size_t ADDCALL sass_list_get_length (const union Sass_Value *v)
ADDAPI enum Sass_Separator ADDCALL sass_list_get_separator (const union Sass_Value *v)
ADDAPI void ADDCALL sass_list_set_separator (union Sass_Value *v, enum Sass_Separator value)
ADDAPI union Sass_Value *ADDCALL sass_list_get_value (const union Sass_Value *v, size_t i)
ADDAPI void ADDCALL sass_list_set_value (union Sass_Value *v, size_t i, union Sass_Value *value)
ADDAPI size_t ADDCALL sass_map_get_length (const union Sass_Value *v)
ADDAPI union Sass_Value *ADDCALL sass_map_get_key (const union Sass_Value *v, size_t i)
ADDAPI void ADDCALL sass_map_set_key (union Sass_Value *v, size_t i, union Sass_Value *)
ADDAPI union Sass_Value *ADDCALL sass_map_get_value (const union Sass_Value *v, size_t i)
ADDAPI void ADDCALL sass_map_set_value (union Sass_Value *v, size_t i, union Sass_Value *)
ADDAPI char *ADDCALL sass_error_get_message (const union Sass_Value *v)
ADDAPI void ADDCALL sass_error_set_message (union Sass_Value *v, char *msg)
ADDAPI char *ADDCALL sass_warning_get_message (const union Sass_Value *v)
ADDAPI void ADDCALL sass_warning_set_message (union Sass_Value *v, char *msg)
ADDAPI union Sass_Value *ADDCALL sass_make_null (void)
ADDAPI union Sass_Value *ADDCALL sass_make_boolean (bool val)
ADDAPI union Sass_Value *ADDCALL sass_make_string (const char *val)
ADDAPI union Sass_Value *ADDCALL sass_make_qstring (const char *val)
ADDAPI union Sass_Value *ADDCALL sass_make_number (double val, const char *unit)
ADDAPI union Sass_Value *ADDCALL sass_make_color (double r, double g, double b, double a)
ADDAPI union Sass_Value *ADDCALL sass_make_list (size_t len, enum Sass_Separator sep)
ADDAPI union Sass_Value *ADDCALL sass_make_map (size_t len)
ADDAPI union Sass_Value *ADDCALL sass_make_error (const char *msg)
ADDAPI union Sass_Value *ADDCALL sass_make_warning (const char *msg)
ADDAPI void ADDCALL sass_delete_value (union Sass_Value *val)
ADDAPI union Sass_Value *ADDCALL sass_clone_value (const union Sass_Value *val)
Enumeration Type Documentation
enum Sass_Separator
Enumerator:
SASS_COMMA
SASS_SPACE
Definition at line 30 of file sass_values.h.
enum Sass_Tag
Enumerator:
SASS_BOOLEAN
SASS_NUMBER
SASS_COLOR
SASS_STRING
SASS_LIST
SASS_MAP
SASS_NULL
SASS_ERROR
SASS_WARNING
Definition at line 17 of file sass_values.h.
Function Documentation
ADDAPI bool ADDCALL sass_boolean_get_value (const union Sass_Value * v)
Definition at line 118 of file sass_values.cpp.
References Sass_Value::boolean, and Sass_Boolean::value.
Referenced by Factory::create(), and Sass::cval_to_astnode().
ADDAPI void ADDCALL sass_boolean_set_value (union Sass_Value * v, bool value)
Definition at line 119 of file sass_values.cpp.
References Sass_Value::boolean, and Sass_Boolean::value.
ADDAPI union Sass_Value* ADDCALL sass_clone_value (const union Sass_Value * val) [write]
Definition at line 306 of file sass_values.cpp.
References Sass_Color::a, Sass_Color::b, Sass_Value::boolean, Sass_Value::color, Sass_Value::error, Sass_Color::g, Sass_MapPair::key, Sass_Map::length, Sass_List::length, Sass_Value::list, Sass_Value::map, Sass_Warning::message, Sass_Error::message, Sass_Value::number, Sass_Map::pairs, Sass_Color::r, SASS_BOOLEAN, sass_clone_value(), SASS_COLOR, SASS_ERROR, SASS_LIST, sass_make_boolean(), sass_make_color(), sass_make_error(), sass_make_list(), sass_make_map(), sass_make_null(), sass_make_number(), sass_make_string(), sass_make_warning(), SASS_MAP, SASS_NULL, SASS_NUMBER, SASS_STRING, SASS_WARNING, Sass_List::separator, Sass_Value::string, Sass_Unknown::tag, Sass_Number::unit, Sass_Value::unknown, Sass_MapPair::value, Sass_String::value, Sass_Number::value, Sass_Boolean::value, Sass_List::values, and Sass_Value::warning.
Referenced by SassValueWrapper< T >::get_sass_value(), sass_clone_value(), and SassValueWrapper< T >::SassValueWrapper().
ADDAPI double ADDCALL sass_color_get_a (const union Sass_Value * v)
Definition at line 128 of file sass_values.cpp.
References Sass_Color::a, and Sass_Value::color.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI double ADDCALL sass_color_get_b (const union Sass_Value * v)
Definition at line 126 of file sass_values.cpp.
References Sass_Color::b, and Sass_Value::color.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI double ADDCALL sass_color_get_g (const union Sass_Value * v)
Definition at line 124 of file sass_values.cpp.
References Sass_Value::color, and Sass_Color::g.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI double ADDCALL sass_color_get_r (const union Sass_Value * v)
Definition at line 122 of file sass_values.cpp.
References Sass_Value::color, and Sass_Color::r.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_color_set_a (union Sass_Value * v, double a)
Definition at line 129 of file sass_values.cpp.
References Sass_Color::a, and Sass_Value::color.
Referenced by SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_color_set_b (union Sass_Value * v, double b)
Definition at line 127 of file sass_values.cpp.
References Sass_Color::b, and Sass_Value::color.
Referenced by SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_color_set_g (union Sass_Value * v, double g)
Definition at line 125 of file sass_values.cpp.
References Sass_Value::color, and Sass_Color::g.
Referenced by SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_color_set_r (union Sass_Value * v, double r)
Definition at line 123 of file sass_values.cpp.
References Sass_Value::color, and Sass_Color::r.
Referenced by SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_delete_value (union Sass_Value * val)
Definition at line 263 of file sass_values.cpp.
References Sass_Value::error, Sass_MapPair::key, Sass_Map::length, Sass_List::length, Sass_Value::list, Sass_Value::map, Sass_Error::message, Sass_Value::number, Sass_Map::pairs, SASS_BOOLEAN, SASS_COLOR, sass_delete_value(), SASS_ERROR, SASS_LIST, SASS_MAP, SASS_NULL, SASS_NUMBER, SASS_STRING, SASS_WARNING, Sass_Value::string, Sass_Unknown::tag, Sass_Number::unit, Sass_Value::unknown, Sass_MapPair::value, Sass_String::value, and Sass_List::values.
Referenced by SassTypes::NAN_METHOD(), Eval::operator()(), sass_delete_value(), and SassValueWrapper< T >::~SassValueWrapper().
ADDAPI char* ADDCALL sass_error_get_message (const union Sass_Value * v)
Definition at line 148 of file sass_values.cpp.
References Sass_Value::error, and Sass_Error::message.
Referenced by Sass::cval_to_astnode(), SassTypes::NAN_METHOD(), and Eval::operator()().
ADDAPI void ADDCALL sass_error_set_message (union Sass_Value * v, char * msg)
Definition at line 149 of file sass_values.cpp.
References Sass_Value::error, and Sass_Error::message.
ADDAPI size_t ADDCALL sass_list_get_length (const union Sass_Value * v)
Definition at line 132 of file sass_values.cpp.
References Sass_List::length, and Sass_Value::list.
Referenced by Sass::cval_to_astnode(), SassTypes::NAN_METHOD(), and sass_custom_function().
ADDAPI enum Sass_Separator ADDCALL sass_list_get_separator (const union Sass_Value * v)
Definition at line 133 of file sass_values.cpp.
References Sass_Value::list, and Sass_List::separator.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI union Sass_Value* ADDCALL sass_list_get_value (const union Sass_Value * v, size_t i) [write]
Definition at line 136 of file sass_values.cpp.
References Sass_Value::list, and Sass_List::values.
Referenced by Sass::cval_to_astnode(), SassTypes::NAN_METHOD(), and sass_custom_function().
ADDAPI void ADDCALL sass_list_set_separator (union Sass_Value * v, enum Sass_Separator value)
Definition at line 134 of file sass_values.cpp.
References Sass_Value::list, and Sass_List::separator.
Referenced by SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_list_set_value (union Sass_Value * v, size_t i, union Sass_Value * value)
Definition at line 137 of file sass_values.cpp.
References Sass_Value::list, and Sass_List::values.
Referenced by SassTypes::NAN_METHOD(), To_C::operator()(), and Eval::operator()().
ADDAPI union Sass_Value* ADDCALL sass_make_boolean (bool val) [write]
Definition at line 157 of file sass_values.cpp.
References Sass_Value::boolean, SASS_BOOLEAN, Sass_Boolean::tag, and Sass_Boolean::value.
Referenced by Boolean::get_sass_value(), To_C::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_color (double r, double g, double b, double a) [write]
Definition at line 177 of file sass_values.cpp.
References Sass_Color::a, Sass_Color::b, Sass_Value::color, Sass_Color::g, Sass_Color::r, SASS_COLOR, and Sass_Color::tag.
Referenced by Color::construct(), To_C::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_error (const char * msg) [write]
Definition at line 242 of file sass_values.cpp.
References Sass_Value::error, Sass_Error::message, SASS_ERROR, and Sass::sass_strdup().
Referenced by Error::construct(), Factory::create(), SassValueWrapper< T >::fail(), CustomFunctionBridge::post_process_return_value(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_list (size_t len, enum Sass_Separator sep) [write]
Definition at line 211 of file sass_values.cpp.
References Sass_List::length, Sass_Value::list, SASS_LIST, Sass_List::separator, Sass_List::tag, and Sass_List::values.
Referenced by List::construct(), To_C::operator()(), Eval::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_map (size_t len) [write]
Definition at line 223 of file sass_values.cpp.
References Sass_Map::length, Sass_Value::map, Sass_Map::pairs, SASS_MAP, and Sass_Map::tag.
Referenced by Map::construct(), To_C::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_null (void) [write]
Definition at line 234 of file sass_values.cpp.
References Sass_Value::null, SASS_NULL, and Sass_Null::tag.
Referenced by To_C::fallback_impl(), Null::get_sass_value(), To_C::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_number (double val, const char * unit) [write]
Definition at line 166 of file sass_values.cpp.
References Sass_Value::number, SASS_NUMBER, Sass::sass_strdup(), Sass_Number::tag, Sass_Number::unit, and Sass_Number::value.
Referenced by Number::construct(), custom_function(), To_C::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_qstring (const char * val) [write]
Definition at line 200 of file sass_values.cpp.
References Sass_String::quoted, Sass::sass_strdup(), SASS_STRING, Sass_Value::string, Sass_String::tag, and Sass_String::value.
ADDAPI union Sass_Value* ADDCALL sass_make_string (const char * val) [write]
Definition at line 189 of file sass_values.cpp.
References Sass_String::quoted, Sass::sass_strdup(), SASS_STRING, Sass_Value::string, Sass_String::tag, and Sass_String::value.
Referenced by String::construct(), To_C::operator()(), and sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_make_warning (const char * msg) [write]
Definition at line 252 of file sass_values.cpp.
References Sass_Warning::message, Sass::sass_strdup(), SASS_WARNING, Sass_Warning::tag, and Sass_Value::warning.
Referenced by sass_clone_value().
ADDAPI union Sass_Value* ADDCALL sass_map_get_key (const union Sass_Value * v, size_t i) [write]
Definition at line 142 of file sass_values.cpp.
References Sass_MapPair::key, Sass_Value::map, and Sass_Map::pairs.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI size_t ADDCALL sass_map_get_length (const union Sass_Value * v)
Definition at line 140 of file sass_values.cpp.
References Sass_Map::length, and Sass_Value::map.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI union Sass_Value* ADDCALL sass_map_get_value (const union Sass_Value * v, size_t i) [write]
Definition at line 143 of file sass_values.cpp.
References Sass_Value::map, Sass_Map::pairs, and Sass_MapPair::value.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_map_set_key (union Sass_Value * v, size_t i, union Sass_Value *)
Definition at line 144 of file sass_values.cpp.
References Sass_MapPair::key, Sass_Value::map, and Sass_Map::pairs.
Referenced by SassTypes::NAN_METHOD(), and To_C::operator()().
ADDAPI void ADDCALL sass_map_set_value (union Sass_Value * v, size_t i, union Sass_Value *)
Definition at line 145 of file sass_values.cpp.
References Sass_Value::map, Sass_Map::pairs, and Sass_MapPair::value.
Referenced by SassTypes::NAN_METHOD(), and To_C::operator()().
ADDAPI const char* ADDCALL sass_number_get_unit (const union Sass_Value * v)
Definition at line 108 of file sass_values.cpp.
References Sass_Value::number, and Sass_Number::unit.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI double ADDCALL sass_number_get_value (const union Sass_Value * v)
Definition at line 106 of file sass_values.cpp.
References Sass_Value::number, and Sass_Number::value.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_number_set_unit (union Sass_Value * v, char * unit)
Definition at line 109 of file sass_values.cpp.
References Sass_Value::number, and Sass_Number::unit.
Referenced by SassTypes::NAN_METHOD().
ADDAPI void ADDCALL sass_number_set_value (union Sass_Value * v, double value)
Definition at line 107 of file sass_values.cpp.
References Sass_Value::number, and Sass_Number::value.
Referenced by SassTypes::NAN_METHOD().
ADDAPI const char* ADDCALL sass_string_get_value (const union Sass_Value * v)
Definition at line 112 of file sass_values.cpp.
References Sass_Value::string, and Sass_String::value.
Referenced by Sass::cval_to_astnode(), and SassTypes::NAN_METHOD().
ADDAPI bool ADDCALL sass_string_is_quoted (const union Sass_Value * v)
Definition at line 114 of file sass_values.cpp.
References Sass_String::quoted, and Sass_Value::string.
ADDAPI void ADDCALL sass_string_set_quoted (union Sass_Value * v, bool quoted)
Definition at line 115 of file sass_values.cpp.
References Sass_String::quoted, and Sass_Value::string.
ADDAPI void ADDCALL sass_string_set_value (union Sass_Value * v, char * value)
Definition at line 113 of file sass_values.cpp.
References Sass_Value::string, and Sass_String::value.
Referenced by SassTypes::NAN_METHOD().
ADDAPI enum Sass_Tag ADDCALL sass_value_get_tag (const union Sass_Value * v)
Definition at line 92 of file sass_values.cpp.
References Sass_Unknown::tag, and Sass_Value::unknown.
Referenced by Factory::create(), Sass::cval_to_astnode(), and Eval::operator()().
ADDAPI bool ADDCALL sass_value_is_boolean (const union Sass_Value * v)
Definition at line 98 of file sass_values.cpp.
References SASS_BOOLEAN, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_color (const union Sass_Value * v)
Definition at line 99 of file sass_values.cpp.
References SASS_COLOR, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_error (const union Sass_Value * v)
Definition at line 102 of file sass_values.cpp.
References SASS_ERROR, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_list (const union Sass_Value * v)
Definition at line 100 of file sass_values.cpp.
References SASS_LIST, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_map (const union Sass_Value * v)
Definition at line 101 of file sass_values.cpp.
References SASS_MAP, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_null (const union Sass_Value * v)
Definition at line 95 of file sass_values.cpp.
References SASS_NULL, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_number (const union Sass_Value * v)
Definition at line 96 of file sass_values.cpp.
References SASS_NUMBER, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_string (const union Sass_Value * v)
Definition at line 97 of file sass_values.cpp.
References SASS_STRING, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI bool ADDCALL sass_value_is_warning (const union Sass_Value * v)
Definition at line 103 of file sass_values.cpp.
References SASS_WARNING, Sass_Unknown::tag, and Sass_Value::unknown.
ADDAPI char* ADDCALL sass_warning_get_message (const union Sass_Value * v)
Definition at line 152 of file sass_values.cpp.
References Sass_Warning::message, and Sass_Value::warning.
Referenced by Sass::cval_to_astnode(), and Eval::operator()().
ADDAPI void ADDCALL sass_warning_set_message (union Sass_Value * v, char * msg)
Definition at line 153 of file sass_values.cpp.
References Sass_Warning::message, and Sass_Value::warning.