Emeraldion Lodge (codename Zelda): List Class Reference
List Class Reference
#include <list.h>
Inherits SassValueWrapper< List >.
Public Member Functions
List (Sass_Value *)
Static Public Member Functions
static char const * get_constructor_name ()
static Sass_Value * construct (const std::vector< v8::Local< v8::Value >>, Sass_Value **)
static void initPrototype (v8::Local< v8::FunctionTemplate >)
static NAN_METHOD (GetValue)
static NAN_METHOD (SetValue)
static NAN_METHOD (GetSeparator)
static NAN_METHOD (SetSeparator)
static NAN_METHOD (GetLength)
Detailed Description
Definition at line 9 of file list.h.
Constructor & Destructor Documentation
List (Sass_Value * v)
Definition at line 6 of file list.cpp.
Member Function Documentation
Sass_Value * construct (const std::vector< v8::Local< v8::Value >> raw_val, Sass_Value ** out) [static]
Definition at line 8 of file list.cpp.
References SassValueWrapper< List >::fail(), SASS_COMMA, sass_make_list(), and SASS_SPACE.
static char const* get_constructor_name () [inline, static]
Reimplemented from SassValueWrapper< List >.
Definition at line 12 of file list.h.
void initPrototype (v8::Local< v8::FunctionTemplate > proto) [static]
Definition at line 31 of file list.cpp.
References Nan::SetPrototypeMethod().
static NAN_METHOD (GetLength) [static]
static NAN_METHOD (SetSeparator) [static]
static NAN_METHOD (GetSeparator) [static]
static NAN_METHOD (SetValue) [static]
static NAN_METHOD (GetValue) [static]
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/list.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/list.cpp