Emeraldion Lodge (codename Zelda): Software Class Reference
Software Class Reference
Model class for software products.
Public Member Functions
relative_url ()
small_icon ()
Returns a small sized icon for the software product.
big_icon ()
Returns a big sized icon for the software product.
icon ($size= 'mini')
Returns an icon of the desired size for the software product.
releasenotes_permalink ()
Returns a permanent link for the releasenotes page of the software product.
appcast_permalink ()
Returns a permanent link for the appcast feed of the software product.
changelog_permalink ()
Returns a permanent link for the changelog page of the software product.
donate_permalink ()
Returns a permanent link for the donations page of the software product.
registration_permalink ()
Returns a permanent link for the registration page of the software product.
comments_permalink ()
Returns a permanent link for the comments page of the software product.
url_to_detail ($detail= 'main')
Returns an URL for the desired detail page of the software product.
colorful_license ()
Returns a colored license label for the the software product.
Public Member Functions inherited from ActiveRecord
ActiveRecord ($_values=NULL)
Constructs and initializes an ActiveRecord object.
belongs_to ($table_name)
Loads the parent of the receiver in a one-to-many relationship.
has_many ($table_name, $params=array())
Loads the children of the receiver in a one-to-many relationship.
has_and_belongs_to_many ($table_name, $params=array())
Loads the object network the receiver belongs to in a many-to-many relationship.
has_one ($table_name)
Loads the child the receiver in a one-to-one relationship.
find_by_query ($query)
Returns an array of model objects by executing a custom SELECT query.
find_all ($params=array())
Returns an array of model objects that satisfy the requirements expressed in the params argument.
find_by_id ($id)
Populates an object with the values of the DB row whose primary key value is id.
save ()
Requests the receiver to save its data in the bound table.
delete ($optimize=TRUE)
Deletes an object's database counterpart.
permalink ($relative=TRUE)
Provides a unique permalink URL for the receiver object.
__set ($key, $value)
Magic method to set the value of a property.
__get ($key)
Magic method to get the value of a property.
__isset ($key)
Magic method to determine if a property exists.
Static Public Attributes
static $licenses = array('freeware', 'donationware', 'shareware', 'commercial', 'demo', 'adware', 'free software', 'public beta')
Array of license types for software products.
Static Public Attributes inherited from ActiveRecord
static $columns = array()
Array of columns for the model object.
static $class_initialized = array()
Array containing initialization information for subclasses.
static $belongs_to_classes = array()
Array containing information on parent tables for subclasses.
static $has_many_classes = array()
Array containing information on child tables for subclasses.
static $object_pool = array()
Pool of objects already fetched from database.
Additional Inherited Members
Static Public Member Functions inherited from ActiveRecord
static find ($id, $classname= 'ActiveRecord')
Returns an object whose primary key value is id.
Protected Member Functions inherited from ActiveRecord
init ($values)
Performs specialized initialization tasks.
relative_url ()
Provides a relative URL that will be used by the permalink public method.
Protected Attributes inherited from ActiveRecord
$table_name
Name of the table bound to this model class.
$primary_key = 'id'
Name of the primary key column for the bound table.
$foreign_key_name
Used to create the name of foreign key column in tables that are in a relationship with the bound table.
Detailed Description
Model class for software products.
Software objects represent software products that are released to the public on the Emeraldion Lodge. Since software development is our main business, this model class is particularly loaded with functionality.
Definition at line 13 of file software.php.
Member Function Documentation
appcast_permalink ()
Returns a permanent link for the appcast feed of the software product.
Definition at line 77 of file software.php.
References APPLICATION_ROOT.
big_icon ()
Returns a big sized icon for the software product.
Definition at line 41 of file software.php.
References icon().
changelog_permalink ()
Returns a permanent link for the changelog page of the software product.
Definition at line 89 of file software.php.
References APPLICATION_ROOT.
colorful_license ()
Returns a colored license label for the the software product.
Definition at line 159 of file software.php.
References span().
comments_permalink ()
Returns a permanent link for the comments page of the software product.
Definition at line 128 of file software.php.
References APPLICATION_ROOT.
donate_permalink ()
Returns a permanent link for the donations page of the software product.
Definition at line 102 of file software.php.
References APPLICATION_ROOT.
icon ($size = 'mini')
Returns an icon of the desired size for the software product.
Parameters
size A size for the returned icon.
Definition at line 51 of file software.php.
References APPLICATION_ROOT.
Referenced by big_icon(), and small_icon().
registration_permalink ()
Returns a permanent link for the registration page of the software product.
Definition at line 115 of file software.php.
References APPLICATION_ROOT.
relative_url ()
Definition at line 21 of file software.php.
releasenotes_permalink ()
Returns a permanent link for the releasenotes page of the software product.
Definition at line 65 of file software.php.
References APPLICATION_ROOT.
small_icon ()
Returns a small sized icon for the software product.
Definition at line 32 of file software.php.
References icon().
url_to_detail ($detail = 'main')
Returns an URL for the desired detail page of the software product.
Parameters
detail The desired detail (e.g. comments).
Definition at line 142 of file software.php.
References APPLICATION_ROOT.
Field Documentation
$licenses = array('freeware', 'donationware', 'shareware', 'commercial', 'demo', 'adware', 'free software', 'public beta') static
Array of license types for software products.
licenses
Definition at line 19 of file software.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/models/software.php