Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_context.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_context.cpp File Reference
#include <unistd.h>
#include <cstring>
#include <stdexcept>
#include "file.hpp"
#include "json.hpp"
#include "util.hpp"
#include "context.hpp"
#include "sass_values.h"
#include "sass_context.h"
#include "ast_fwd_decl.hpp"
#include "error_handling.hpp"
Data Structures
struct string_list
struct Sass_Options
struct Sass_Context
struct Sass_File_Context
struct Sass_Data_Context
struct Sass_Compiler
Defines
#define LFEED "\n"
#define IMPLEMENT_SASS_OPTION_ACCESSOR(type, option)
#define IMPLEMENT_SASS_OPTION_STRING_ACCESSOR(type, option)
#define IMPLEMENT_SASS_CONTEXT_GETTER(type, option) type ADDCALL sass_context_get_##option (struct Sass_Context* ctx) { return ctx->option; }
#define IMPLEMENT_SASS_CONTEXT_TAKER(type, option)
Enumerations
enum Sass_Input_Style { SASS_CONTEXT_NULL, SASS_CONTEXT_FILE, SASS_CONTEXT_DATA, SASS_CONTEXT_FOLDER }
Functions
static void copy_options (struct Sass_Options *to, struct Sass_Options *from)
static const char * safe_str (const char *str)
static void copy_strings (const std::vector< std::string > &strings, char ***array)
static void free_string_array (char **arr)
static int handle_errors (Sass_Context *c_ctx)
static Sass_Compiler * sass_prepare_context (Sass_Context *c_ctx, Context::Data cpp_opt) throw ()
static Block * sass_parse_block (Sass_Compiler *compiler) throw ()
static int sass_compile_context (Sass_Context *c_ctx, Context::Data cpp_opt)
void init_options (struct Sass_Options *options)
Sass_Options *ADDCALL sass_make_options (void)
Sass_File_Context *ADDCALL sass_make_file_context (const char *input_path)
Sass_Data_Context *ADDCALL sass_make_data_context (char *source_string)
struct Sass_Compiler *ADDCALL sass_make_file_compiler (struct Sass_File_Context *c_ctx)
struct Sass_Compiler *ADDCALL sass_make_data_compiler (struct Sass_Data_Context *c_ctx)
int ADDCALL sass_compile_data_context (Sass_Data_Context *data_ctx)
int ADDCALL sass_compile_file_context (Sass_File_Context *file_ctx)
int ADDCALL sass_compiler_parse (struct Sass_Compiler *compiler)
int ADDCALL sass_compiler_execute (struct Sass_Compiler *compiler)
static void sass_clear_options (struct Sass_Options *options)
static void sass_clear_context (struct Sass_Context *ctx)
void ADDCALL sass_delete_compiler (struct Sass_Compiler *compiler)
void ADDCALL sass_delete_file_context (struct Sass_File_Context *ctx)
void ADDCALL sass_delete_data_context (struct Sass_Data_Context *ctx)
struct Sass_Context *ADDCALL sass_file_context_get_context (struct Sass_File_Context *ctx)
struct Sass_Context *ADDCALL sass_data_context_get_context (struct Sass_Data_Context *ctx)
struct Sass_Options *ADDCALL sass_context_get_options (struct Sass_Context *ctx)
struct Sass_Options *ADDCALL sass_file_context_get_options (struct Sass_File_Context *ctx)
struct Sass_Options *ADDCALL sass_data_context_get_options (struct Sass_Data_Context *ctx)
void ADDCALL sass_file_context_set_options (struct Sass_File_Context *ctx, struct Sass_Options *opt)
void ADDCALL sass_data_context_set_options (struct Sass_Data_Context *ctx, struct Sass_Options *opt)
enum Sass_Compiler_State ADDCALL sass_compiler_get_state (struct Sass_Compiler *compiler)
struct Sass_Context *ADDCALL sass_compiler_get_context (struct Sass_Compiler *compiler)
size_t ADDCALL sass_compiler_get_import_stack_size (struct Sass_Compiler *compiler)
Sass_Import_Entry ADDCALL sass_compiler_get_last_import (struct Sass_Compiler *compiler)
Sass_Import_Entry ADDCALL sass_compiler_get_import_entry (struct Sass_Compiler *compiler, size_t idx)
size_t ADDCALL sass_context_get_included_files_size (struct Sass_Context *ctx)
IMPLEMENT_SASS_OPTION_ACCESSOR (int, precision)
IMPLEMENT_SASS_OPTION_ACCESSOR (enum Sass_Output_Style, output_style)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool, source_comments)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool, source_map_embed)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool, source_map_contents)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool, omit_source_map_url)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool, is_indented_syntax_src)
IMPLEMENT_SASS_OPTION_ACCESSOR (Sass_Function_List, c_functions)
IMPLEMENT_SASS_OPTION_ACCESSOR (Sass_Importer_List, c_importers)
IMPLEMENT_SASS_OPTION_ACCESSOR (Sass_Importer_List, c_headers)
IMPLEMENT_SASS_OPTION_ACCESSOR (const char *, indent)
IMPLEMENT_SASS_OPTION_ACCESSOR (const char *, linefeed)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char *, input_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char *, output_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char *, plugin_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char *, include_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char *, source_map_file)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char *, source_map_root)
IMPLEMENT_SASS_CONTEXT_GETTER (int, error_status)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, error_json)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, error_message)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, error_text)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, error_file)
IMPLEMENT_SASS_CONTEXT_GETTER (size_t, error_line)
IMPLEMENT_SASS_CONTEXT_GETTER (size_t, error_column)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, error_src)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, output_string)
IMPLEMENT_SASS_CONTEXT_GETTER (const char *, source_map_string)
IMPLEMENT_SASS_CONTEXT_GETTER (char **, included_files)
IMPLEMENT_SASS_CONTEXT_TAKER (char *, error_json)
IMPLEMENT_SASS_CONTEXT_TAKER (char *, error_message)
IMPLEMENT_SASS_CONTEXT_TAKER (char *, error_text)
IMPLEMENT_SASS_CONTEXT_TAKER (char *, error_file)
IMPLEMENT_SASS_CONTEXT_TAKER (char *, output_string)
IMPLEMENT_SASS_CONTEXT_TAKER (char *, source_map_string)
IMPLEMENT_SASS_CONTEXT_TAKER (char **, included_files)
void ADDCALL sass_option_push_include_path (struct Sass_Options *options, const char *path)
void ADDCALL sass_option_push_plugin_path (struct Sass_Options *options, const char *path)
Define Documentation
#define IMPLEMENT_SASS_CONTEXT_GETTER (type, option) type ADDCALL sass_context_get_##option (struct Sass_Context* ctx) { return ctx->option; }
Definition at line 180 of file sass_context.cpp.
#define IMPLEMENT_SASS_CONTEXT_TAKER (type, option)
Value:
type sass_context_take_##option (struct Sass_Context* ctx) \
    { type foo = ctx->option; ctx->option = 0; return foo; }
Definition at line 182 of file sass_context.cpp.
#define IMPLEMENT_SASS_OPTION_ACCESSOR (type, option)
Value:
type ADDCALL sass_option_get_##option (struct Sass_Options* options) { return options->option; } \
    void ADDCALL sass_option_set_##option (struct Sass_Options* options, type option) { options->option = option; }
Definition at line 172 of file sass_context.cpp.
#define IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (type, option)
Value:
type ADDCALL sass_option_get_##option (struct Sass_Options* options) { return options->option; } \
    void ADDCALL sass_option_set_##option (struct Sass_Options* options, type option) \
    { free(options->option); options->option = option ? sass_strdup(option) : 0; }
Definition at line 175 of file sass_context.cpp.
#define LFEED "\n"
Definition at line 6 of file sass_context.cpp.
Referenced by init_options(), sass_compile(), and sass_compile_file().
Enumeration Type Documentation
enum Sass_Input_Style
Enumerator:
SASS_CONTEXT_NULL
SASS_CONTEXT_FILE
SASS_CONTEXT_DATA
SASS_CONTEXT_FOLDER
Definition at line 25 of file sass_context.cpp.
Function Documentation
static void copy_options (struct Sass_Options * to, struct Sass_Options * from) [static]
Definition at line 170 of file sass_context.cpp.
Referenced by sass_data_context_set_options(), and sass_file_context_set_options().
static void copy_strings (const std::vector< std::string > & strings, char *** array) [static]
Definition at line 191 of file sass_context.cpp.
Referenced by sass_compile(), sass_compile_file(), and sass_parse_block().
static void free_string_array (char ** arr) [static]
Definition at line 207 of file sass_context.cpp.
Referenced by sass_clear_context(), sass_free_context(), sass_free_file_context(), and sass_free_folder_context().
static int handle_errors (Sass_Context * c_ctx) [static]
Definition at line 220 of file sass_context.cpp.
References Offset::column, Sass_Context::error_column, Sass_Context::error_file, Sass_Context::error_json, Sass_Context::error_line, Sass_Context::error_message, Sass_Context::error_src, Sass_Context::error_status, Sass_Context::error_text, Sass::File::get_cwd(), json_append_member(), json_delete(), json_mknumber(), json_mkobject(), json_mkstring(), json_stringify(), Offset::line, Sass_Error::message, npos, Sass_Context::output_string, ParserState::path, Sass_Error::pstate, Sass::File::resolve_relative_path(), Sass::sass_strdup(), Sass_Context::source_map_string, and ParserState::src.
Referenced by sass_compile_context(), sass_compile_data_context(), sass_compile_file_context(), sass_compiler_execute(), sass_make_data_context(), sass_make_file_context(), sass_parse_block(), and sass_prepare_context().
IMPLEMENT_SASS_CONTEXT_GETTER (char ** , included_files)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , source_map_string)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , output_string)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , error_src)
IMPLEMENT_SASS_CONTEXT_GETTER (size_t , error_column)
IMPLEMENT_SASS_CONTEXT_GETTER (size_t , error_line)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , error_file)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , error_text)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , error_message)
IMPLEMENT_SASS_CONTEXT_GETTER (const char * , error_json)
IMPLEMENT_SASS_CONTEXT_GETTER (int , error_status)
IMPLEMENT_SASS_CONTEXT_TAKER (char ** , included_files)
IMPLEMENT_SASS_CONTEXT_TAKER (char * , source_map_string)
IMPLEMENT_SASS_CONTEXT_TAKER (char * , output_string)
IMPLEMENT_SASS_CONTEXT_TAKER (char * , error_file)
IMPLEMENT_SASS_CONTEXT_TAKER (char * , error_text)
IMPLEMENT_SASS_CONTEXT_TAKER (char * , error_message)
IMPLEMENT_SASS_CONTEXT_TAKER (char * , error_json)
IMPLEMENT_SASS_OPTION_ACCESSOR (const char * , linefeed)
IMPLEMENT_SASS_OPTION_ACCESSOR (const char * , indent)
IMPLEMENT_SASS_OPTION_ACCESSOR (Sass_Importer_List , c_headers)
IMPLEMENT_SASS_OPTION_ACCESSOR (Sass_Importer_List , c_importers)
IMPLEMENT_SASS_OPTION_ACCESSOR (Sass_Function_List , c_functions)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool , is_indented_syntax_src)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool , omit_source_map_url)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool , source_map_contents)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool , source_map_embed)
IMPLEMENT_SASS_OPTION_ACCESSOR (bool , source_comments)
IMPLEMENT_SASS_OPTION_ACCESSOR (enum Sass_Output_Style, output_style)
IMPLEMENT_SASS_OPTION_ACCESSOR (int , precision)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char * , source_map_root)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char * , source_map_file)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char * , include_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char * , plugin_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char * , output_path)
IMPLEMENT_SASS_OPTION_STRING_ACCESSOR (const char * , input_path)
void init_options (struct Sass_Options * options) [inline]
Definition at line 547 of file sass_context.cpp.
References Sass_Options::indent, LFEED, Sass_Options::linefeed, and Sass_Options::precision.
Referenced by sass_make_data_context(), sass_make_file_context(), and sass_make_options().
static const char* safe_str (const char * str) [static]
Definition at line 187 of file sass_context.cpp.
Referenced by sass_compile(), sass_compile_file(), sass_parse_block(), and sass_prepare_context().
static void sass_clear_context (struct Sass_Context * ctx) [static]
Definition at line 747 of file sass_context.cpp.
References Sass_Context::error_file, Sass_Context::error_json, Sass_Context::error_message, Sass_Context::error_text, free_string_array(), Sass_Options::include_path, Sass_Context::included_files, Sass_Options::input_path, Sass_Options::output_path, Sass_Context::output_string, sass_clear_options(), Sass_Options::source_map_file, Sass_Options::source_map_root, and Sass_Context::source_map_string.
Referenced by sass_delete_data_context(), and sass_delete_file_context().
static void sass_clear_options (struct Sass_Options * options) [static]
Definition at line 681 of file sass_context.cpp.
References Sass_Options::c_functions, Sass_Options::c_headers, Sass_Options::c_importers, Sass_Options::include_paths, string_list::next, utf8::unchecked::next(), Sass_Options::plugin_paths, and string_list::string.
Referenced by sass_clear_context().
static int sass_compile_context (Sass_Context * c_ctx, Context::Data cpp_opt) [static]
Definition at line 528 of file sass_context.cpp.
References Sass_Context::error_status, handle_errors(), sass_compiler_execute(), sass_compiler_parse(), sass_delete_compiler(), and sass_prepare_context().
Referenced by sass_compile_data_context(), and sass_compile_file_context().
int ADDCALL sass_compile_data_context (Sass_Data_Context * data_ctx)
Definition at line 610 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Sass_Context::error_status, handle_errors(), sass_compile_context(), and Sass_Data_Context::source_string.
Referenced by compile_data().
int ADDCALL sass_compile_file_context (Sass_File_Context * file_ctx)
Definition at line 626 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Sass_Context::error_status, handle_errors(), Sass_Options::input_path, and sass_compile_context().
Referenced by compile_file().
int ADDCALL sass_compiler_execute (struct Sass_Compiler * compiler)
Definition at line 657 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Context::compile_block(), Sass_Compiler::cpp_ctx, Sass_Context::error_status, Context::generate_source_map(), handle_errors(), Sass_Context::output_string, Sass_Compiler::root, SASS_COMPILER_EXECUTED, SASS_COMPILER_PARSED, Sass_Context::source_map_string, and Sass_Compiler::state.
Referenced by sass_compile_context().
struct Sass_Context* ADDCALL sass_compiler_get_context (struct Sass_Compiler * compiler) [read]
Definition at line 806 of file sass_context.cpp.
References Sass_Compiler::c_ctx.
Sass_Import_Entry ADDCALL sass_compiler_get_import_entry (struct Sass_Compiler * compiler, size_t idx)
Definition at line 810 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx, and Context::import_stack.
size_t ADDCALL sass_compiler_get_import_stack_size (struct Sass_Compiler * compiler)
Definition at line 808 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx, and Context::import_stack.
Sass_Import_Entry ADDCALL sass_compiler_get_last_import (struct Sass_Compiler * compiler)
Definition at line 809 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx, and Context::import_stack.
Referenced by sass_importer().
enum Sass_Compiler_State ADDCALL sass_compiler_get_state (struct Sass_Compiler * compiler)
Definition at line 805 of file sass_context.cpp.
References Sass_Compiler::state.
int ADDCALL sass_compiler_parse (struct Sass_Compiler * compiler)
Definition at line 642 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Sass_Compiler::cpp_ctx, Sass_Context::error_status, Sass_Compiler::root, SASS_COMPILER_CREATED, SASS_COMPILER_PARSED, sass_parse_block(), and Sass_Compiler::state.
Referenced by sass_compile_context().
size_t ADDCALL sass_context_get_included_files_size (struct Sass_Context * ctx)
Definition at line 813 of file sass_context.cpp.
References Sass_Context::included_files, and l().
struct Sass_Options* ADDCALL sass_context_get_options (struct Sass_Context * ctx) [read]
Definition at line 798 of file sass_context.cpp.
Referenced by ExtractOptions().
struct Sass_Context* ADDCALL sass_data_context_get_context (struct Sass_Data_Context * ctx) [read]
Definition at line 795 of file sass_context.cpp.
Referenced by ExtractOptions(), MakeCallback(), and NAN_METHOD().
struct Sass_Options* ADDCALL sass_data_context_get_options (struct Sass_Data_Context * ctx) [read]
Definition at line 800 of file sass_context.cpp.
void ADDCALL sass_data_context_set_options (struct Sass_Data_Context * ctx, struct Sass_Options * opt)
Definition at line 802 of file sass_context.cpp.
References copy_options().
void ADDCALL sass_delete_compiler (struct Sass_Compiler * compiler)
Definition at line 780 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx.
Referenced by sass_compile_context().
void ADDCALL sass_delete_data_context (struct Sass_Data_Context * ctx)
Definition at line 791 of file sass_context.cpp.
References sass_clear_context().
Referenced by sass_free_context_wrapper().
void ADDCALL sass_delete_file_context (struct Sass_File_Context * ctx)
Definition at line 790 of file sass_context.cpp.
References sass_clear_context().
Referenced by sass_free_context_wrapper().
struct Sass_Context* ADDCALL sass_file_context_get_context (struct Sass_File_Context * ctx) [read]
Definition at line 794 of file sass_context.cpp.
Referenced by ExtractOptions(), MakeCallback(), and NAN_METHOD().
struct Sass_Options* ADDCALL sass_file_context_get_options (struct Sass_File_Context * ctx) [read]
Definition at line 799 of file sass_context.cpp.
void ADDCALL sass_file_context_set_options (struct Sass_File_Context * ctx, struct Sass_Options * opt)
Definition at line 801 of file sass_context.cpp.
References copy_options().
struct Sass_Compiler* ADDCALL sass_make_data_compiler (struct Sass_Data_Context * c_ctx) [read]
Definition at line 602 of file sass_context.cpp.
References sass_prepare_context(), and Sass_Data_Context::source_string.
Sass_Data_Context* ADDCALL sass_make_data_context (char * source_string) [read]
Definition at line 578 of file sass_context.cpp.
References ctx, handle_errors(), init_options(), SASS_CONTEXT_DATA, Sass_Data_Context::source_string, and Sass_Context::type.
Referenced by NAN_METHOD().
struct Sass_Compiler* ADDCALL sass_make_file_compiler (struct Sass_File_Context * c_ctx) [read]
Definition at line 594 of file sass_context.cpp.
References Sass_Options::input_path, and sass_prepare_context().
Sass_File_Context* ADDCALL sass_make_file_context (const char * input_path) [read]
Definition at line 562 of file sass_context.cpp.
References ctx, handle_errors(), init_options(), SASS_CONTEXT_FILE, sass_option_set_input_path(), and Sass_Context::type.
Referenced by NAN_METHOD().
Sass_Options* ADDCALL sass_make_options (void) [read]
Definition at line 554 of file sass_context.cpp.
References init_options().
void ADDCALL sass_option_push_include_path (struct Sass_Options * options, const char * path)
Definition at line 859 of file sass_context.cpp.
References Sass_Options::include_paths, string_list::next, Sass::sass_strdup(), and string_list::string.
void ADDCALL sass_option_push_plugin_path (struct Sass_Options * options, const char * path)
Definition at line 877 of file sass_context.cpp.
References string_list::next, Sass_Options::plugin_paths, Sass::sass_strdup(), and string_list::string.
static Block* sass_parse_block (Sass_Compiler * compiler) throw () [static]
Definition at line 476 of file sass_context.cpp.
References Sass_Compiler::c_ctx, copy_strings(), Sass_Compiler::cpp_ctx, Context::get_included_files(), handle_errors(), Context::head_imports, Sass_Context::included_files, Sass_Options::input_path, Sass_Options::output_path, Context::parse_file(), Context::parse_string(), Sass_Compiler::root, safe_str(), SASS_COMPILER_PARSED, SASS_CONTEXT_DATA, SASS_CONTEXT_FILE, and Sass_Context::type.
Referenced by sass_compiler_parse().
static Sass_Compiler* sass_prepare_context (Sass_Context * c_ctx, Context::Data cpp_opt) throw () [static]
Definition at line 345 of file sass_context.cpp.
References Context::add_c_function(), Context::add_c_header(), Context::add_c_importer(), Context::c_compiler, Sass_Compiler::c_ctx, Sass_Compiler::cpp_ctx, handle_errors(), string_list::next, npos, safe_str(), SASS_COMPILER_CREATED, Sass_Compiler::state, and string_list::string.
Referenced by sass_compile_context(), sass_make_data_compiler(), and sass_make_file_compiler().