Emeraldion Lodge (codename Zelda): BackendController Class Reference
BackendController Class Reference
Controller class for Backend maintenance and website administration functions.
Public Member Functions
index ()
diario_moderation_queue ()
Action method that shows the queue of comments awaiting moderation.
diario_comment_moderate ()
Action method that moderates a comment.
diario_comment_discard ()
Action method that discards a comment or a group of comments.
diario_post_compose ()
Action method to compose a new article.
diario_post_add ()
Action method to save a newly composed article.
diario_post_edit ()
Action method to edit an existing article.
diario_post_list ()
Action method to show the list of articles.
diario_pingback_list ()
Action method to show the list of Pingbacks issued for Blog posts.
diario_pingback_moderate ()
Action method that moderates Pingbacks issued for Blog posts.
software_moderation_queue ()
Action method to manage the queue of software comments.
software_comment_moderate ()
Action method to moderate a software comment.
software_comment_list ()
Action method to show the list of software comments.
software_comment_discard ()
Action method to delete a software comments.
software_comment_mark_as_spam ()
Action method to mark a software comment as spam.
software_list ()
Action method to show the list of software products.
software_edit ()
Action method to edit a software product.
software_create ()
Action method to create a new software product.
software_delete ()
Action method to delete a software product.
software_release_list ()
Action method to show a list of software releases.
software_release_edit ()
Action method to edit a software release.
software_release_create ()
Action method to create a software release.
software_release_add ()
Action method to save a software release.
software_artifact_list ()
Action method to show a list of software artifacts.
software_artifact_edit ()
Action method to edit a software artifact.
software_artifact_create ()
Action method to create a software artifact.
software_artifact_add ()
Action method to save a software artifact.
software_quote_list ()
Action method that shows the list of quotes for a software product.
software_quote_create ()
Action method that creates a software quote entry.
software_quote_edit ()
Action method that modifies a software quote entry.
software_quote_add ()
Action method that saves a software quote entry.
software_quote_delete ()
Action method that deletes a software quote entry.
software_downloads ()
Action method that shows statistics on software downloads grouped by software product.
software_downloads_by_release ()
Action method that shows statistics on software downloads grouped by release for a particular software product.
software_downloads_by_artifact ()
Action method that shows statistics on software artifact downloads for a particular release.
software_pingback_list ()
Action method that shows the list of Pingbacks issued for Software items.
software_pingback_moderate ()
Action method that moderates Pingbacks issued for software products.
server_error_list ()
Action method that shows the list of server errors.
server_error_read ()
Action method that shows individual server error items.
server_error_next ()
Action method that shows the next server error.
server_error_previous ()
Action method that shows the previous server error.
server_error_delete ()
Action method that deletes server error items.
Public Member Functions inherited from EmeController
index ()
Public Member Functions inherited from BaseController
BaseController ()
Default constructor for controller objects.
link_to ($text, $params=array())
Links to another action.
link_to_remote ($text, $params=array())
Links to another action, with AJAX support.
button_to ($text, $params=array())
Creates a button that links to another action.
url_to ($params)
Creates a URL to an action.
url_to_myself ($relative=TRUE)
Creates a URL to the current action.
make_relative_url ($params)
Creates a URL to an action.
render ($params)
Requests the rendering of the response.
render_as_string ($params)
Requests the rendering of the response as a string.
render_page ()
Renders the page as a response for the current request.
render_component ($params)
Renders a view from a controller other than self.
set_title ($title)
Sets the title for the current page.
flash ($message, $type= 'error')
Shows a message to the user, with an optional type qualifier.
index ()
This is the default action method.
Protected Member Functions
init ()
Protected Member Functions inherited from EmeController
init ()
set_credentials ($realname= '', $email= '', $url= '')
Stores a set of credentials into a cookie using Base64 encoding.
get_credentials ()
Returns a set of credentials previously stored into a cookie with Base64 encoding.
check_auth ()
Filter method that checks authorization before accessing actions.
log_visit ()
Filter method that saves a Visit object for current request.
block_ip ()
Filter method that interrupts response generation if the client IP is blacklisted.
add_acronyms ()
Filter method that adds common acronyms.
morse_encode ()
Filter method that converts response contents to Morse code.
shrink_html ()
Filter method that removes all unnecessary spaces from HTML output.
sanskrit_ambra ()
Filter method that converts response contents to Ambra Angiolini's "sanskrit".
spot_people ()
Filter method to identify visits from known people.
load_part_contents ($filename)
Loads localized part contents from file.
include_localized ($filename)
Includes a localized version of the requested filename if possible.
Protected Member Functions inherited from BaseController
initialize ()
Initializes the controller object.
init ()
Custom initialization for the controller object.
before_filter ($filter, $params=NULL)
Registers a function as a filter to be executed before the action is invoked.
after_filter ($filter, $params=NULL)
Registers a function as a filter to be executed after the action is invoked.
caches_page ($page)
Requests that a page be cached.
conditionally_caches_page ($page, $condition=TRUE)
Requests that a page be cached when a condition is verified.
caches_action ($page)
Requests that an action be cached.
cached_page_exists ()
Checks if a cached version of the current action exists.
cached_page_filename ()
Returns a name for the cached page of current action.
expire_cached_page ($params)
Requests that the page(s) defined by params be removed from the caches.
redirect_to ($params)
Redirects the response to another action, or URL.
refresh ($amount=10)
Refreshes current page after a given amount of time.
redirect_to_referrer ($or_else=NULL)
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
unknown_action ()
render_layout ($params)
Renders the layout for the current view.
load_part_contents ($filename)
Loads the contents of the desired view file.
strip_external_php_tags ($php_code)
Strips beginning and ending delimiters from the given PHP code.
compress ()
Compresses the response with gzip encoding.
Private Member Functions
expire_cached_software_pages ()
Deletes all cached software pages.
_batch_moderate ($table_name)
Performs batch moderation operations on one or more items.
Additional Inherited Members
Data Fields inherited from EmeController
const LOG_VISITS = TRUE
Flag that determines if the controller must log the visits.
Data Fields inherited from BaseController
$name
The name of the controller.
$action
The name of the action.
$title
A title for the page.
Protected Attributes inherited from EmeController
$credentials
User credentials.
$keywords = array()
Keywords for the "Keywords" meta header.
$description
Description for the "Description" meta header.
Protected Attributes inherited from BaseController
$type = 'html'
An extension for action pages.
$mimetype = 'text/html'
A MIME type for the response.
Detailed Description
Controller class for Backend maintenance and website administration functions.
Definition at line 27 of file backend_controller.php.
Member Function Documentation
_batch_moderate ($table_name) private
Performs batch moderation operations on one or more items.
Parameters
table_name The name of the table we want to operate on.
Definition at line 913 of file backend_controller.php.
References $conn, Db\close_connection(), and Db\get_connection().
Referenced by diario_comment_moderate(), diario_pingback_moderate(), software_comment_moderate(), and software_pingback_moderate().
diario_comment_discard ()
Action method that discards a comment or a group of comments.
Definition at line 113 of file backend_controller.php.
References BaseController\redirect_to().
diario_comment_moderate ()
Action method that moderates a comment.
Definition at line 66 of file backend_controller.php.
References $conn, _batch_moderate(), Db\close_connection(), Db\get_connection(), Email\is_valid(), and BaseController\redirect_to().
diario_moderation_queue ()
Action method that shows the queue of comments awaiting moderation.
Diario administration actions Diario comments actions
Definition at line 56 of file backend_controller.php.
diario_pingback_list ()
Action method to show the list of Pingbacks issued for Blog posts.
Definition at line 255 of file backend_controller.php.
diario_pingback_moderate ()
Action method that moderates Pingbacks issued for Blog posts.
Definition at line 265 of file backend_controller.php.
References _batch_moderate(), and BaseController\redirect_to().
diario_post_add ()
Action method to save a newly composed article.
Definition at line 165 of file backend_controller.php.
References $conn, $tag_factory, Db\close_connection(), BaseController\expire_cached_page(), Db\get_connection(), and BaseController\redirect_to().
diario_post_compose ()
Action method to compose a new article.
Diario articles actions
Definition at line 155 of file backend_controller.php.
References BaseController\render().
diario_post_edit ()
Action method to edit an existing article.
Definition at line 227 of file backend_controller.php.
References BaseController\redirect_to().
diario_post_list ()
Action method to show the list of articles.
Definition at line 243 of file backend_controller.php.
expire_cached_software_pages () private
Deletes all cached software pages.
Definition at line 898 of file backend_controller.php.
References BaseController\expire_cached_page().
Referenced by software_artifact_add(), software_delete(), and software_release_add().
index ()
Definition at line 39 of file backend_controller.php.
References BaseController\redirect_to().
init () protected
Definition at line 29 of file backend_controller.php.
References BaseController\after_filter(), and BaseController\before_filter().
server_error_delete ()
Action method that deletes server error items.
Definition at line 859 of file backend_controller.php.
References $conn, Db\close_connection(), Db\get_connection(), and BaseController\redirect_to().
server_error_list ()
Action method that shows the list of server errors.
Definition at line 789 of file backend_controller.php.
server_error_next ()
Action method that shows the next server error.
Definition at line 817 of file backend_controller.php.
References BaseController\redirect_to(), and BaseController\render().
server_error_previous ()
Action method that shows the previous server error.
Definition at line 838 of file backend_controller.php.
References BaseController\redirect_to(), and BaseController\render().
server_error_read ()
Action method that shows individual server error items.
Definition at line 799 of file backend_controller.php.
References BaseController\flash(), l(), and BaseController\redirect_to().
software_artifact_add ()
Action method to save a software artifact.
Definition at line 602 of file backend_controller.php.
References expire_cached_software_pages(), and BaseController\redirect_to().
software_artifact_create ()
Action method to create a software artifact.
Definition at line 583 of file backend_controller.php.
References BaseController\redirect_to(), and BaseController\render().
software_artifact_edit ()
Action method to edit a software artifact.
Definition at line 566 of file backend_controller.php.
References BaseController\redirect_to().
software_artifact_list ()
Action method to show a list of software artifacts.
Definition at line 539 of file backend_controller.php.
References $conn, Db\close_connection(), Db\get_connection(), and BaseController\redirect_to().
software_comment_discard ()
Action method to delete a software comments.
Definition at line 353 of file backend_controller.php.
References BaseController\redirect_to().
software_comment_list ()
Action method to show the list of software comments.
Definition at line 335 of file backend_controller.php.
References $conn, Db\close_connection(), Db\get_connection(), and BaseController\redirect_to().
software_comment_mark_as_spam ()
Action method to mark a software comment as spam.
Definition at line 380 of file backend_controller.php.
References Antispam\check_spam_signature(), BaseController\render(), and Antispam\store_spam_signature().
software_comment_moderate ()
Action method to moderate a software comment.
Definition at line 289 of file backend_controller.php.
References $conn, _batch_moderate(), Db\close_connection(), Db\get_connection(), Email\is_valid(), and BaseController\redirect_to().
software_create ()
Action method to create a new software product.
Definition at line 426 of file backend_controller.php.
References BaseController\render().
software_delete ()
Action method to delete a software product.
Warning
This method has potentially destructive consquences. Do not use it without a really good reason.
Definition at line 441 of file backend_controller.php.
References expire_cached_software_pages(), and BaseController\redirect_to().
software_downloads ()
Action method that shows statistics on software downloads grouped by software product.
Definition at line 707 of file backend_controller.php.
software_downloads_by_artifact ()
Action method that shows statistics on software artifact downloads for a particular release.
Definition at line 739 of file backend_controller.php.
References BaseController\flash(), l(), and BaseController\redirect_to().
software_downloads_by_release ()
Action method that shows statistics on software downloads grouped by release for a particular software product.
Definition at line 718 of file backend_controller.php.
References BaseController\flash(), l(), and BaseController\redirect_to().
software_edit ()
Action method to edit a software product.
Definition at line 412 of file backend_controller.php.
References BaseController\redirect_to().
software_list ()
Action method to show the list of software products.
Definition at line 402 of file backend_controller.php.
software_moderation_queue ()
Action method to manage the queue of software comments.
Software administration actions
Definition at line 279 of file backend_controller.php.
software_pingback_list ()
Action method that shows the list of Pingbacks issued for Software items.
Definition at line 759 of file backend_controller.php.
software_pingback_moderate ()
Action method that moderates Pingbacks issued for software products.
Definition at line 779 of file backend_controller.php.
References _batch_moderate(), and BaseController\redirect_to().
software_quote_add ()
Action method that saves a software quote entry.
Definition at line 676 of file backend_controller.php.
References BaseController\redirect_to().
software_quote_create ()
Action method that creates a software quote entry.
Definition at line 647 of file backend_controller.php.
References BaseController\redirect_to(), and BaseController\render().
software_quote_delete ()
Action method that deletes a software quote entry.
Definition at line 692 of file backend_controller.php.
References BaseController\redirect_to().
software_quote_edit ()
Action method that modifies a software quote entry.
Definition at line 662 of file backend_controller.php.
References BaseController\redirect_to().
software_quote_list ()
Action method that shows the list of quotes for a software product.
Definition at line 629 of file backend_controller.php.
References $conn, Db\close_connection(), Db\get_connection(), and BaseController\redirect_to().
software_release_add ()
Action method to save a software release.
Definition at line 516 of file backend_controller.php.
References expire_cached_software_pages(), and BaseController\redirect_to().
software_release_create ()
Action method to create a software release.
Definition at line 500 of file backend_controller.php.
References BaseController\redirect_to(), and BaseController\render().
software_release_edit ()
Action method to edit a software release.
Definition at line 485 of file backend_controller.php.
References BaseController\redirect_to().
software_release_list ()
Action method to show a list of software releases.
Definition at line 467 of file backend_controller.php.
References $conn, Db\close_connection(), Db\get_connection(), and BaseController\redirect_to().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/controllers/backend_controller.php