Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/include/tag_support.inc.php File Reference
tag_support.inc.php File Reference
Functions
select ($name, $values, $default_value, $params=array())
block_tag ($tagname, $content, $params=NULL)
inline_tag ($tagname, $content, $params=NULL)
leaf_tag ($tagname, $params=NULL)
a ($content, $params)
p ($content, $params)
span ($content, $params)
div ($content, $params)
em ($content, $params)
h1 ($content, $params)
h2 ($content, $params)
h3 ($content, $params)
h4 ($content, $params)
h5 ($content, $params)
h6 ($content, $params)
button ($name, $value, $params=array(), $enabled=TRUE)
checkbox ($name, $checked, $params=array(), $enabled=TRUE)
Function Documentation
a ($content, $params)
Containers
Definition at line 91 of file tag_support.inc.php.
References inline_tag().
Referenced by SingularLicense\activation_link(), MiniBatteryLoggerLicense\activation_link(), BaseController\link_to(), BaseController\link_to_remote(), Wikipedia\lookup(), LicenseEmail\make_text(), SoftwareCommentFollowupEmail\make_text(), DiarioCommentFollowupEmail\make_text(), Book\permalink(), and DiarioPost\summary().
block_tag ($tagname, $content, $params = NULL)
Abstract tag factory
Definition at line 33 of file tag_support.inc.php.
Referenced by div(), h1(), h2(), h3(), h4(), h5(), h6(), and p().
button ($name, $value, $params = array(), $enabled = TRUE)
Form elements
Definition at line 160 of file tag_support.inc.php.
References leaf_tag().
Referenced by BaseController\button_to().
checkbox ($name, $checked, $params = array(), $enabled = TRUE)
Definition at line 172 of file tag_support.inc.php.
References leaf_tag().
div ($content, $params)
Definition at line 116 of file tag_support.inc.php.
References block_tag().
em ($content, $params)
Definition at line 121 of file tag_support.inc.php.
References inline_tag().
h1 ($content, $params)
Definition at line 126 of file tag_support.inc.php.
References block_tag().
h2 ($content, $params)
Definition at line 131 of file tag_support.inc.php.
References block_tag().
h3 ($content, $params)
Definition at line 136 of file tag_support.inc.php.
References block_tag().
h4 ($content, $params)
Definition at line 141 of file tag_support.inc.php.
References block_tag().
h5 ($content, $params)
Definition at line 146 of file tag_support.inc.php.
References block_tag().
h6 ($content, $params)
Definition at line 151 of file tag_support.inc.php.
References block_tag().
inline_tag ($tagname, $content, $params = NULL)
Definition at line 53 of file tag_support.inc.php.
Referenced by a(), em(), and span().
leaf_tag ($tagname, $params = NULL)
Definition at line 70 of file tag_support.inc.php.
Referenced by button(), and checkbox().
p ($content, $params)
Definition at line 106 of file tag_support.inc.php.
References block_tag().
select ($name, $values, $default_value, $params = array())
Definition at line 3 of file tag_support.inc.php.
span ($content, $params)
Definition at line 111 of file tag_support.inc.php.
References inline_tag().
Referenced by Gate\__toString(), Software\colorful_license(), and SoftwareArtifact\filename().