Emeraldion Lodge (codename Zelda): Factory< v8::Uint32 > Struct Template Reference
Factory< v8::Uint32 > Struct Template Reference
#include <nan.h>
Inherits FactoryBase< v8::Uint32 >.
Static Public Member Functions
static return_t New (int32_t value)
static return_t New (uint32_t value)
Detailed Description
template<>
struct Nan::imp::Factory< v8::Uint32 >
Definition at line 1301 of file nan.h.
Member Function Documentation
Factory< v8::Uint32 >::return_t New (uint32_t value) [inline, static]
Definition at line 1519 of file nan.h.
Factory< v8::Uint32 >::return_t New (int32_t value) [inline, static]
Definition at line 1514 of file nan.h.
References EscapableHandleScope::Escape(), Nan::Get(), and Nan::New().
The documentation for this struct was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan.h