Emeraldion Lodge (codename Zelda): List Class Reference
List Class Reference
#include <ast.hpp>
Inherits Sass::Expression, and Vectorized< Expression * >.
Public Types
enum Separator { SPACE, COMMA }
Public Member Functions
List (ParserState pstate, size_t size=0, Separator sep=SPACE, bool argl=false)
string type ()
bool is_invisible ()
Expression * value_at_index (size_t i)
virtual size_t size () const
virtual bool operator== (Expression &rhs) const
virtual bool operator== (Expression *rhs) const
virtual size_t hash ()
virtual void set_delayed (bool delayed)
ATTACH_OPERATIONS ()
Static Public Member Functions
static string type_name ()
Private Member Functions
void adjust_after_pushing (Expression *e)
ADD_PROPERTY (Separator, separator)
ADD_PROPERTY (bool, is_arglist)
Detailed Description
Definition at line 741 of file ast.hpp.
Member Enumeration Documentation
enum Separator
Enumerator:
SPACE
COMMA
Definition at line 744 of file ast.hpp.
Constructor & Destructor Documentation
List (ParserState pstate, size_t size = 0, Separator sep = SPACE, bool argl = false) [inline]
Definition at line 749 of file ast.hpp.
References Expression::LIST.
Member Function Documentation
ADD_PROPERTY (bool , is_arglist) [private]
ADD_PROPERTY (Separator , separator) [private]
void adjust_after_pushing (Expression * e) [inline, private, virtual]
Reimplemented from Vectorized< Expression * >.
Definition at line 742 of file ast.hpp.
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
virtual size_t hash () [inline, virtual]
Reimplemented from Expression.
Definition at line 764 of file ast.hpp.
References List::COMMA, Vectorized< Expression * >::elements(), Vectorized< Expression * >::hash_, and Vectorized< Expression * >::length().
bool is_invisible () [inline, virtual]
Reimplemented from Expression.
Definition at line 757 of file ast.hpp.
References Vectorized< Expression * >::length().
bool operator== (Expression * rhs) const [virtual]
Definition at line 904 of file ast.cpp.
References Vectorized< Expression * >::elements(), Vectorized< T >::length(), and Vectorized< Expression * >::length().
bool operator== (Expression & rhs) const [virtual]
Reimplemented from Expression.
Definition at line 920 of file ast.cpp.
virtual void set_delayed (bool delayed) [inline, virtual]
Reimplemented from Expression.
Definition at line 776 of file ast.hpp.
References Vectorized< Expression * >::elements(), and Vectorized< Expression * >::length().
size_t size () const [virtual]
Definition at line 925 of file ast.cpp.
References gyp::msvs_emulation::arg, and Vectorized< Expression * >::length().
Referenced by Sass::Functions::BUILT_IN(), and Inspect::operator()().
string type () [inline, virtual]
Reimplemented from Expression.
Definition at line 755 of file ast.hpp.
static string type_name () [inline, static]
Reimplemented from Expression.
Definition at line 756 of file ast.hpp.
Expression * value_at_index (size_t i) [inline]
Definition at line 1667 of file ast.hpp.
Referenced by Sass::Functions::BUILT_IN().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp