Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/views/_navbar.php File Reference
_navbar.php File Reference
Variables
$navbar_sections
if(Login::is_logged_in()) $i = 0
$navbar_length = count($navbar_sections)
Variable Documentation
if (Login::is_logged_in()) $i = 0
Definition at line 31 of file _navbar.php.
Referenced by Trackback\auto_discovery(), Markdown_Parser\hashPart(), KmlController\last_n_visits(), DiarioController\live_search(), MysqlAdapter\prepare(), MURatingsParser\ratingsList(), MURatingsParser\ratingsValues(), ActiveRecord\save(), and DiarioController\search().
$navbar_length = count($navbar_sections)
Definition at line 32 of file _navbar.php.
$navbar_sections
Initial value:
= array(
                array('title' => localized('Home'),
                        "url" => $this->url_to(array('controller' => 'home'))),
                array('title' => localized('Blog'),
                        "url" => $this->url_to(array('controller' => 'diario'))),
                array('title' => localized('Projects'),
                        "url" => $this->url_to(array('controller' => 'projects'))),
                array('title' => localized('About'),
                        "url" => $this->url_to(array('controller' => 'about'))),
                )
Definition at line 2 of file _navbar.php.