Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/create_string.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/create_string.h File Reference
#include <nan.h>
Functions
char * create_string (Nan::MaybeLocal< v8::Value >)
Function Documentation
char* create_string (Nan::MaybeLocal< v8::Value >)
Definition at line 6 of file create_string.cpp.
References MaybeLocal< T >::ToLocal().
Referenced by String::construct(), Number::construct(), Error::construct(), ExtractOptions(), CustomImporterBridge::get_importer_entry(), SassTypes::NAN_METHOD(), NAN_METHOD(), and CustomImporterBridge::post_process_return_value().