Emeraldion Lodge (codename Zelda): UnitTest Class Reference
UnitTest Class Reference
Base class for Unit Testing.
Public Member Functions
run ()
Runs all the test cases.
Protected Member Functions
set_up ()
Sets up fixtures required by test cases.
tear_down ()
Tears down fixtures used by test cases.
report ()
Returns a detailed report of the test case previously run.
Detailed Description
Base class for Unit Testing.
Unit testing allows you to run custom tests focused on validating the functionality of model objects. It is recommended that you create a test case for every method of the object.
Definition at line 9 of file unit_test.php.
Member Function Documentation
report () protected
Returns a detailed report of the test case previously run.
Definition at line 37 of file unit_test.php.
References $assertions_errors, $assertions_failed, and $assertions_total.
Referenced by run().
run ()
Runs all the test cases.
This method automatically invokes all methods that start with test*. Before and after each test case, the set_up and tear_down methods are invoked, respectively.
Definition at line 62 of file unit_test.php.
References $assertions_failed, $assertions_total, report(), set_up(), and tear_down().
set_up () protected
Sets up fixtures required by test cases.
This method is called before every test case in order to setup custom fixtures. Subclassers may override it to perform all operations required before running test cases.
Definition at line 18 of file unit_test.php.
Referenced by run().
tear_down () protected
Tears down fixtures used by test cases.
This method is called after every test case in order to remove custom fixtures. Subclassers may override it to perform all operations required after running test cases.
Definition at line 29 of file unit_test.php.
Referenced by run().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/test/unit_test.php