Emeraldion Lodge (codename Zelda): EmeController Class Reference
EmeController Class Reference
Main controller class for the Emeraldion Lodge.
Public Member Functions
index ()
Public Member Functions inherited from BaseController
BaseController ()
Default constructor for controller objects.
link_to ($text, $params=array())
Links to another action.
link_to_remote ($text, $params=array())
Links to another action, with AJAX support.
button_to ($text, $params=array())
Creates a button that links to another action.
url_to ($params)
Creates a URL to an action.
url_to_myself ($relative=TRUE)
Creates a URL to the current action.
make_relative_url ($params)
Creates a URL to an action.
render ($params)
Requests the rendering of the response.
render_as_string ($params)
Requests the rendering of the response as a string.
render_page ()
Renders the page as a response for the current request.
render_component ($params)
Renders a view from a controller other than self.
set_title ($title)
Sets the title for the current page.
flash ($message, $type= 'error')
Shows a message to the user, with an optional type qualifier.
index ()
This is the default action method.
Data Fields
const LOG_VISITS = TRUE
Flag that determines if the controller must log the visits.
Data Fields inherited from BaseController
$name
The name of the controller.
$action
The name of the action.
$title
A title for the page.
Protected Member Functions
init ()
set_credentials ($realname= '', $email= '', $url= '')
Stores a set of credentials into a cookie using Base64 encoding.
get_credentials ()
Returns a set of credentials previously stored into a cookie with Base64 encoding.
check_auth ()
Filter method that checks authorization before accessing actions.
log_visit ()
Filter method that saves a Visit object for current request.
block_ip ()
Filter method that interrupts response generation if the client IP is blacklisted.
add_acronyms ()
Filter method that adds common acronyms.
morse_encode ()
Filter method that converts response contents to Morse code.
shrink_html ()
Filter method that removes all unnecessary spaces from HTML output.
sanskrit_ambra ()
Filter method that converts response contents to Ambra Angiolini's "sanskrit".
spot_people ()
Filter method to identify visits from known people.
load_part_contents ($filename)
Loads localized part contents from file.
include_localized ($filename)
Includes a localized version of the requested filename if possible.
Protected Member Functions inherited from BaseController
initialize ()
Initializes the controller object.
init ()
Custom initialization for the controller object.
before_filter ($filter, $params=NULL)
Registers a function as a filter to be executed before the action is invoked.
after_filter ($filter, $params=NULL)
Registers a function as a filter to be executed after the action is invoked.
caches_page ($page)
Requests that a page be cached.
conditionally_caches_page ($page, $condition=TRUE)
Requests that a page be cached when a condition is verified.
caches_action ($page)
Requests that an action be cached.
cached_page_exists ()
Checks if a cached version of the current action exists.
cached_page_filename ()
Returns a name for the cached page of current action.
expire_cached_page ($params)
Requests that the page(s) defined by params be removed from the caches.
redirect_to ($params)
Redirects the response to another action, or URL.
refresh ($amount=10)
Refreshes current page after a given amount of time.
redirect_to_referrer ($or_else=NULL)
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
unknown_action ()
render_layout ($params)
Renders the layout for the current view.
load_part_contents ($filename)
Loads the contents of the desired view file.
strip_external_php_tags ($php_code)
Strips beginning and ending delimiters from the given PHP code.
compress ()
Compresses the response with gzip encoding.
Protected Attributes
$credentials
User credentials.
$keywords = array()
Keywords for the "Keywords" meta header.
$description
Description for the "Description" meta header.
Protected Attributes inherited from BaseController
$type = 'html'
An extension for action pages.
$mimetype = 'text/html'
A MIME type for the response.
Detailed Description
Main controller class for the Emeraldion Lodge.
EmeController implements all default filters and shared functionality that is specifically designed for the Emeraldion Lodge.
Definition at line 20 of file eme_controller.php.
Member Function Documentation
add_acronyms () protected
Filter method that adds common acronyms.
Definition at line 141 of file eme_controller.php.
References h().
block_ip () protected
Filter method that interrupts response generation if the client IP is blacklisted.
Definition at line 124 of file eme_controller.php.
References BlockedIp\is_blocked(), and l().
check_auth () protected
Filter method that checks authorization before accessing actions.
Definition at line 97 of file eme_controller.php.
References BaseController\flash(), Login\is_logged_in(), and BaseController\redirect_to().
get_credentials () protected
Returns a set of credentials previously stored into a cookie with Base64 encoding.
Definition at line 82 of file eme_controller.php.
References $credentials, Base64\decode(), and Cookie\get().
Referenced by init().
include_localized ($filename) protected
Includes a localized version of the requested filename if possible.
Checks if a localized version of the requested filename exists, otherwise calls include.
Parameters
filename The name of the file to be included.
Definition at line 305 of file eme_controller.php.
References HTTP\error().
index ()
Definition at line 60 of file eme_controller.php.
init () protected
Definition at line 43 of file eme_controller.php.
References get_credentials(), l(), title, and BaseController\url_to_myself().
load_part_contents ($filename) protected
Loads localized part contents from file.
Checks if a localized part file exists for the requested filename, otherwise calls the superclass implementation.
Parameters
filename The name of the part file.
Returns
The contents of the part file.
Definition at line 278 of file eme_controller.php.
References HTTP\error(), and BaseController\strip_external_php_tags().
log_visit () protected
Filter method that saves a Visit object for current request.
Definition at line 111 of file eme_controller.php.
morse_encode () protected
Filter method that converts response contents to Morse code.
Definition at line 169 of file eme_controller.php.
sanskrit_ambra () protected
Filter method that converts response contents to Ambra Angiolini's "sanskrit".
This filter replaces all vowels with 'a', thus doing like Ambra Angiolini when singing during the Italian TV show "Non la Rai".
Definition at line 224 of file eme_controller.php.
set_credentials ($realname = '', $email = '', $website = '') protected
Stores a set of credentials into a cookie using Base64 encoding.
Parameters
realname The user's real name.
email The user's email address.
url The user's website URL.
Definition at line 71 of file eme_controller.php.
References $credentials, Base64\encode(), Time\next_year(), and Cookie\set().
Referenced by SoftwareController\post_comment(), DiarioController\post_comment(), and ContactController\send().
shrink_html () protected
Filter method that removes all unnecessary spaces from HTML output.
Definition at line 199 of file eme_controller.php.
spot_people () protected
Filter method to identify visits from known people.
Definition at line 244 of file eme_controller.php.
References Cookie\set(), and Time\tomorrow().
Field Documentation
$credentials protected
User credentials.
credentials
Definition at line 31 of file eme_controller.php.
Referenced by get_credentials(), and set_credentials().
$description protected
Description for the "Description" meta header.
Definition at line 41 of file eme_controller.php.
$keywords = array() protected
Keywords for the "Keywords" meta header.
Definition at line 36 of file eme_controller.php.
const LOG_VISITS = TRUE
Flag that determines if the controller must log the visits.
Definition at line 25 of file eme_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/controllers/eme_controller.php