Emeraldion Lodge (codename Zelda): SourceMap Class Reference
SourceMap Class Reference
#include <source_map.hpp>
Public Member Functions
SourceMap ()
SourceMap (const string &file)
void setFile (const string &str)
void append (const Offset &offset)
void prepend (const Offset &offset)
void append (const OutputBuffer &out)
void prepend (const OutputBuffer &out)
void add_open_mapping (AST_Node *node)
void add_close_mapping (AST_Node *node)
string generate_source_map (Context &ctx)
ParserState remap (const ParserState &pstate)
Data Fields
vector< size_t > source_index
string file
Private Member Functions
string serialize_mappings ()
Private Attributes
vector< Mapping > mappings
Position current_position
Base64VLQ base64vlq
Detailed Description
Definition at line 20 of file source_map.hpp.
Constructor & Destructor Documentation
SourceMap ()
Definition at line 15 of file source_map.cpp.
SourceMap (const string & file)
Definition at line 16 of file source_map.cpp.
Member Function Documentation
void add_close_mapping (AST_Node * node)
Definition at line 167 of file source_map.cpp.
References SourceMap::current_position, and SourceMap::mappings.
Referenced by Emitter::add_close_mapping().
void add_open_mapping (AST_Node * node)
Definition at line 162 of file source_map.cpp.
References SourceMap::current_position, and SourceMap::mappings.
Referenced by Emitter::add_open_mapping().
void append (const OutputBuffer & out)
Definition at line 134 of file source_map.cpp.
References SourceMap::append(), and OutputBuffer::buffer.
void append (const Offset & offset)
Definition at line 157 of file source_map.cpp.
References SourceMap::current_position.
Referenced by SourceMap::append(), and Emitter::append_string().
string generate_source_map (Context & ctx)
Definition at line 18 of file source_map.cpp.
References SourceMap::file, Context::include_links, json_append_element(), json_append_member(), json_delete(), json_mkarray(), json_mknumber(), json_mkobject(), json_mkstring(), json_stringify(), SourceMap::mappings, SourceMap::serialize_mappings(), SourceMap::source_index, Context::source_map_contents, Context::source_map_root, and Context::sources.
Referenced by Emitter::generate_source_map().
void prepend (const OutputBuffer & out)
Definition at line 115 of file source_map.cpp.
References OutputBuffer::buffer, Offset::column, SourceMap::current_position, Mapping::generated_position, Offset::line, SourceMap::mappings, SourceMap::prepend(), OutputBuffer::smap, and VECTOR_UNSHIFT.
void prepend (const Offset & offset)
Definition at line 139 of file source_map.cpp.
References Offset::column, SourceMap::current_position, Offset::line, and SourceMap::mappings.
Referenced by SourceMap::prepend(), Emitter::prepend_output(), and Emitter::prepend_string().
ParserState remap (const ParserState & pstate)
Definition at line 172 of file source_map.cpp.
References Offset::column, Position::file, Offset::line, SourceMap::mappings, ParserState::offset, ParserState::path, and ParserState::src.
Referenced by Emitter::remap().
string serialize_mappings () [private]
Definition at line 72 of file source_map.cpp.
References SourceMap::base64vlq, Base64VLQ::encode(), and SourceMap::mappings.
Referenced by SourceMap::generate_source_map().
void setFile (const string & str) [inline]
Definition at line 27 of file source_map.hpp.
References SourceMap::file.
Field Documentation
Base64VLQ base64vlq [private]
Definition at line 49 of file source_map.hpp.
Referenced by SourceMap::serialize_mappings().
Position current_position [private]
Definition at line 45 of file source_map.hpp.
Referenced by SourceMap::add_close_mapping(), SourceMap::add_open_mapping(), SourceMap::append(), and SourceMap::prepend().
string file
Definition at line 47 of file source_map.hpp.
Referenced by SourceMap::generate_source_map(), Emitter::set_filename(), and SourceMap::setFile().
vector<Mapping> mappings [private]
Definition at line 44 of file source_map.hpp.
Referenced by SourceMap::add_close_mapping(), SourceMap::add_open_mapping(), SourceMap::generate_source_map(), SourceMap::prepend(), SourceMap::remap(), and SourceMap::serialize_mappings().
vector<size_t> source_index
Definition at line 23 of file source_map.hpp.
Referenced by Emitter::add_source_index(), and SourceMap::generate_source_map().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/source_map.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/source_map.cpp