Emeraldion Lodge (codename Zelda): Cssize Class Reference
Cssize Class Reference
#include <cssize.hpp>
Inherits Operation_CRTP< Statement *, Cssize >.
Public Member Functions
Cssize (Context &, Env *, Backtrace *)
virtual ~Cssize ()
Statement * operator() (Block *)
Statement * operator() (Ruleset *)
Statement * operator() (Media_Block *)
Statement * operator() (Feature_Block *)
Statement * operator() (At_Root_Block *)
Statement * operator() (At_Rule *)
Statement * operator() (Keyframe_Rule *)
Statement * parent ()
Private Member Functions
Statement * fallback_impl (AST_Node *n)
Private Attributes
Context & ctx
Env * env
vector< Block * > block_stack
vector< Statement * > p_stack
Backtrace * backtrace
Detailed Description
Definition at line 18 of file cssize.hpp.
Constructor & Destructor Documentation
Cssize (Context & ctx, Env * env, Backtrace * bt)
Definition at line 11 of file cssize.cpp.
virtual ~Cssize () [inline, virtual]
Definition at line 30 of file cssize.hpp.
Member Function Documentation
Statement * fallback_impl (AST_Node * n) [private]
Definition at line 459 of file cssize.cpp.
Statement * operator() (Keyframe_Rule * r) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 84 of file cssize.cpp.
References Block::block(), Statement::block(), Cssize::ctx, Vectorized< T >::length(), and Context::mem.
Statement * operator() (At_Rule * r) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 38 of file cssize.cpp.
References Block::block(), Statement::block(), Statement::BUBBLE, Cssize::ctx, Statement::DIRECTIVE, At_Rule::is_keyframes(), Vectorized< T >::length(), Context::mem, Cssize::p_stack, Cssize::parent(), Statement::RULESET, and s().
Statement * operator() (At_Root_Block * m) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 179 of file cssize.cpp.
References Block::block(), Statement::block(), Cssize::ctx, At_Root_Block::exclude_node(), Vectorized< T >::last(), Vectorized< T >::length(), Context::mem, Cssize::p_stack, Cssize::parent(), and s().
Statement * operator() (Feature_Block * m) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 159 of file cssize.cpp.
References Block::block(), Statement::block(), Cssize::ctx, Vectorized< T >::length(), Context::mem, Cssize::p_stack, Cssize::parent(), and Statement::RULESET.
Statement * operator() (Media_Block * m) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 139 of file cssize.cpp.
References Block::block(), Statement::block(), Cssize::ctx, Statement::MEDIA, Context::mem, Cssize::p_stack, Cssize::parent(), Statement::RULESET, and Sass::statement_type.
Statement * operator() (Ruleset * r) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 95 of file cssize.cpp.
References Block::block(), Statement::block(), Cssize::ctx, Vectorized< T >::last(), Vectorized< T >::length(), Context::mem, Cssize::p_stack, Cssize::parent(), Statement::RULESET, s(), and Vectorized< T >::unshift().
Statement * operator() (Block * b) [virtual]
Reimplemented from Operation_CRTP< Statement *, Cssize >.
Definition at line 24 of file cssize.cpp.
References Cssize::block_stack, Cssize::ctx, Cssize::env, Vectorized< T >::length(), Environment< T >::link(), and Context::mem.
Statement * parent ()
Definition at line 19 of file cssize.cpp.
References Cssize::block_stack, and Cssize::p_stack.
Referenced by Cssize::operator()().
Field Documentation
Backtrace* backtrace [private]
Definition at line 24 of file cssize.hpp.
vector<Block*> block_stack [private]
Definition at line 22 of file cssize.hpp.
Referenced by Cssize::operator()(), and Cssize::parent().
Context& ctx [private]
Definition at line 20 of file cssize.hpp.
Referenced by Cssize::operator()().
Env* env [private]
Definition at line 21 of file cssize.hpp.
Referenced by Cssize::operator()().
vector<Statement*> p_stack [private]
Definition at line 23 of file cssize.hpp.
Referenced by Cssize::operator()(), and Cssize::parent().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/cssize.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/cssize.cpp