Emeraldion Lodge (codename Zelda): SoftwareController Class Reference
SoftwareController Class Reference
Controller for Software sections.
Public Member Functions
index ()
ratings ()
Action method that shows a list of ratings for software products.
macosx ()
Convenience action method.
widgets_versioncheck ()
Action method that shows the latest version available for a widget.
last_releases ()
Action method that shows a list of the last software product releases.
main ()
Action method that shows the principal page for a software product.
instructions ()
Action method that shows the instructions page for a software product.
development ()
Action method that shows the development information page for a software product.
donate ()
Action method that shows the donation page for a software product.
register ()
Action method that shows the registration page for a software product.
license ()
Action method that shows the licensing information page for a software product.
changelog ()
Action method that shows the changelog page for a software product.
comments ()
Action method that shows the comments page for a software product.
post_comment ()
Action method that receives a comment for a software product.
show ()
Action method that shows the individual page for a software product.
releasenotes ()
Action method that shows the changes in the last release of the requested software.
user_quotes ()
Action method that shows a collection of user testimonials for software products.
download ()
Action method that performs the download of a software artifact.
download_stats ()
Action method that shows the download statistics for a software release.
redirect_to_software_page ($params)
Redirects the request to a detailed page for a software product.
Public Member Functions inherited from EmeController
index ()
Public Member Functions inherited from BaseController
BaseController ()
Default constructor for controller objects.
link_to ($text, $params=array())
Links to another action.
link_to_remote ($text, $params=array())
Links to another action, with AJAX support.
button_to ($text, $params=array())
Creates a button that links to another action.
url_to ($params)
Creates a URL to an action.
url_to_myself ($relative=TRUE)
Creates a URL to the current action.
make_relative_url ($params)
Creates a URL to an action.
render ($params)
Requests the rendering of the response.
render_as_string ($params)
Requests the rendering of the response as a string.
render_page ()
Renders the page as a response for the current request.
render_component ($params)
Renders a view from a controller other than self.
set_title ($title)
Sets the title for the current page.
flash ($message, $type= 'error')
Shows a message to the user, with an optional type qualifier.
index ()
This is the default action method.
Data Fields
const SOFTWARE_SAVE_DOWNLOADS = FALSE
Flag that determines if downloads should be logged.
Data Fields inherited from EmeController
const LOG_VISITS = TRUE
Flag that determines if the controller must log the visits.
Data Fields inherited from BaseController
$name
The name of the controller.
$action
The name of the action.
$title
A title for the page.
Protected Member Functions
init ()
Protected Member Functions inherited from EmeController
init ()
set_credentials ($realname= '', $email= '', $url= '')
Stores a set of credentials into a cookie using Base64 encoding.
get_credentials ()
Returns a set of credentials previously stored into a cookie with Base64 encoding.
check_auth ()
Filter method that checks authorization before accessing actions.
log_visit ()
Filter method that saves a Visit object for current request.
block_ip ()
Filter method that interrupts response generation if the client IP is blacklisted.
add_acronyms ()
Filter method that adds common acronyms.
morse_encode ()
Filter method that converts response contents to Morse code.
shrink_html ()
Filter method that removes all unnecessary spaces from HTML output.
sanskrit_ambra ()
Filter method that converts response contents to Ambra Angiolini's "sanskrit".
spot_people ()
Filter method to identify visits from known people.
load_part_contents ($filename)
Loads localized part contents from file.
include_localized ($filename)
Includes a localized version of the requested filename if possible.
Protected Member Functions inherited from BaseController
initialize ()
Initializes the controller object.
init ()
Custom initialization for the controller object.
before_filter ($filter, $params=NULL)
Registers a function as a filter to be executed before the action is invoked.
after_filter ($filter, $params=NULL)
Registers a function as a filter to be executed after the action is invoked.
caches_page ($page)
Requests that a page be cached.
conditionally_caches_page ($page, $condition=TRUE)
Requests that a page be cached when a condition is verified.
caches_action ($page)
Requests that an action be cached.
cached_page_exists ()
Checks if a cached version of the current action exists.
cached_page_filename ()
Returns a name for the cached page of current action.
expire_cached_page ($params)
Requests that the page(s) defined by params be removed from the caches.
redirect_to ($params)
Redirects the response to another action, or URL.
refresh ($amount=10)
Refreshes current page after a given amount of time.
redirect_to_referrer ($or_else=NULL)
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
unknown_action ()
render_layout ($params)
Renders the layout for the current view.
load_part_contents ($filename)
Loads the contents of the desired view file.
strip_external_php_tags ($php_code)
Strips beginning and ending delimiters from the given PHP code.
compress ()
Compresses the response with gzip encoding.
Protected Attributes
$mimetype = 'text/html; charset=iso-8859-1'
The MIME type of the response.
Protected Attributes inherited from EmeController
$credentials
User credentials.
$keywords = array()
Keywords for the "Keywords" meta header.
$description
Description for the "Description" meta header.
Protected Attributes inherited from BaseController
$type = 'html'
An extension for action pages.
$mimetype = 'text/html'
A MIME type for the response.
Private Member Functions
_init_software ()
Private method that initializes repetitive members of software product page actions.
Detailed Description
Controller for Software sections.
The SoftwareController is a controller class for actions that present the software products published on the Emeraldion Lodge, provides commenting support, detailed informations for individual software products, and tracks the number of downloads.
Definition at line 28 of file software_controller.php.
Member Function Documentation
_init_software () private
Private method that initializes repetitive members of software product page actions.
Definition at line 503 of file software_controller.php.
References $conn, HTTP\error(), and Db\get_connection().
Referenced by changelog(), comments(), development(), instructions(), license(), main(), register(), and show().
changelog ()
Action method that shows the changelog page for a software product.
Definition at line 242 of file software_controller.php.
References _init_software(), and BaseController\render().
comments ()
Action method that shows the comments page for a software product.
Definition at line 253 of file software_controller.php.
References _init_software(), and BaseController\render().
development ()
Action method that shows the development information page for a software product.
This page is only available for open source projects that are hosted on a project hosting website.
Definition at line 193 of file software_controller.php.
References _init_software(), and BaseController\render().
donate ()
Action method that shows the donation page for a software product.
This page is only available for freeware or open source software products.
Definition at line 205 of file software_controller.php.
References BaseController\redirect_to().
download ()
Action method that performs the download of a software artifact.
For software artifacts that are locally hosted, a DownloadManager is instantiated and the download is automatically started. For externally hosted artifacts, the client is redirected to the appropriate URL.
Definition at line 404 of file software_controller.php.
download_stats ()
Action method that shows the download statistics for a software release.
Note
This action is intented to be called from AJAX and does not show a full page layout.
Definition at line 450 of file software_controller.php.
index ()
Definition at line 53 of file software_controller.php.
Referenced by ratings(), and releasenotes().
init () protected
Definition at line 41 of file software_controller.php.
References BaseController\after_filter(), BaseController\before_filter(), and BaseController\caches_page().
instructions ()
Action method that shows the instructions page for a software product.
Definition at line 181 of file software_controller.php.
References _init_software(), and BaseController\render().
last_releases ()
Action method that shows a list of the last software product releases.
Definition at line 154 of file software_controller.php.
References BaseController\render().
license ()
Action method that shows the licensing information page for a software product.
Definition at line 231 of file software_controller.php.
References _init_software(), and BaseController\render().
macosx ()
Convenience action method.
This method redirects legacy URLs to Mac OS X software to the main software index page.
Definition at line 78 of file software_controller.php.
References BaseController\redirect_to().
main ()
Action method that shows the principal page for a software product.
Definition at line 170 of file software_controller.php.
References _init_software(), and BaseController\render().
post_comment ()
Action method that receives a comment for a software product.
Definition at line 264 of file software_controller.php.
References $conn, Antispam\check_math(), Db\close_connection(), BaseController\expire_cached_page(), BaseController\flash(), Db\get_connection(), Email\is_valid(), l(), Antispam\random_comment(), BaseController\redirect_to(), redirect_to_software_page(), and EmeController\set_credentials().
ratings ()
Action method that shows a list of ratings for software products.
This method shows a list of ratings offered by external software sites like MacUpdate, IUseThis etc.
Definition at line 68 of file software_controller.php.
References index().
redirect_to_software_page ($params)
Redirects the request to a detailed page for a software product.
Parameters
params An array of parameters that determine the software and the page for the redirection.
Definition at line 482 of file software_controller.php.
References BaseController\redirect_to().
Referenced by post_comment().
register ()
Action method that shows the registration page for a software product.
This page is only available for shareware or commercial software products.
Definition at line 215 of file software_controller.php.
References _init_software(), and BaseController\render().
releasenotes ()
Action method that shows the changes in the last release of the requested software.
Note
This action is designed to be called by Sparkle application updater.
Definition at line 341 of file software_controller.php.
References $releases, and index().
show ()
Action method that shows the individual page for a software product.
Definition at line 321 of file software_controller.php.
References _init_software(), and BaseController\render().
user_quotes ()
Action method that shows a collection of user testimonials for software products.
Note
This action is intented to be called from AJAX and does not show a full page layout.
Definition at line 370 of file software_controller.php.
widgets_versioncheck ()
Action method that shows the latest version available for a widget.
Definition at line 87 of file software_controller.php.
References $conn, $releases, Db\close_connection(), HTTP\error(), Db\get_connection(), l(), and BaseController\render().
Field Documentation
$mimetype = 'text/html; charset=iso-8859-1' protected
The MIME type of the response.
mimetype
Definition at line 39 of file software_controller.php.
const SOFTWARE_SAVE_DOWNLOADS = FALSE
Flag that determines if downloads should be logged.
Definition at line 33 of file software_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/controllers/software_controller.php