Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_implementation_12_inl.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_implementation_12_inl.h File Reference
Namespaces
namespace imp
Functions
template<typename T , typename M >
v8::Local< T > New (v8::Persistent< T, M > const &p)
template<typename T , typename M >
v8::Local< T > New (Persistent< T, M > const &p)
Function Documentation
v8::Local<T> New (Persistent< T, M > const & p) [inline]
Definition at line 395 of file nan_implementation_12_inl.h.
v8::Local<T> New (v8::Persistent< T, M > const & p) [inline]
Definition at line 390 of file nan_implementation_12_inl.h.
Referenced by Nan::CallAsConstructor(), imp::Encode(), SassValueWrapper< T >::get_constructor(), Null::get_constructor(), Boolean::get_constructor(), SassValueWrapper< T >::get_constructor_template(), SassValueWrapper< T >::get_js_object(), Null::get_js_object(), Boolean::get_js_object(), CallbackBridge< T, L >::get_wrapper_constructor(), ObjectWrap::handle(), New(), Factory< v8::StringObject >::New(), Factory< v8::RegExp >::New(), Factory< v8::ObjectTemplate >::New(), Factory< v8::Object >::New(), Factory< v8::NumberObject >::New(), Factory< v8::Number >::New(), Factory< v8::FunctionTemplate >::New(), Factory< v8::Function >::New(), Factory< v8::External >::New(), Factory< v8::Date >::New(), Factory< v8::Context >::New(), Factory< v8::BooleanObject >::New(), Factory< v8::Boolean >::New(), Factory< v8::Array >::New(), ReturnValue< v8::Array >::Set(), ReturnValue< v8::Array >::SetEmptyString(), ReturnValue< v8::Array >::SetNull(), and ReturnValue< v8::Array >::SetUndefined().