Emeraldion Lodge (codename Zelda): gyp::msvs_emulation Namespace Reference
gyp::msvs_emulation Namespace Reference
Data Structures
class MsvsSettings
class PrecompiledHeader
Functions
def EncodeRspFileList
def _GenericRetrieve
def _AddPrefix
def _DoRemapping
def _AppendOrReturn
def _FindDirectXInstallation
def GetGlobalVSMacroEnv
def ExtractSharedMSVSSystemIncludes
def _LanguageMatchesForPch
def GetVSVersion
def _GetVsvarsSetupArgs
def ExpandMacros
def _ExtractImportantEnvironment
def _FormatAsEnvironmentBlock
def _ExtractCLPath
def GenerateEnvironmentFiles
def VerifyMissingSources
def CalculateCommonVariables
Variables
tuple windows_quoter_regex
tuple arg = arg.replace('%', '%%')
vs_version = None
Function Documentation
def gyp::msvs_emulation::_AddPrefix (element, prefix) [private]
Add |prefix| to |element| or each subelement if element is iterable.
Definition at line 79 of file msvs_emulation.py.
def gyp::msvs_emulation::_AppendOrReturn (append, element) [private]
If |append| is None, simply return |element|. If |append| is not None,
then add |element| to it, adding each item in |element| if it's a list or
tuple.
Definition at line 103 of file msvs_emulation.py.
def gyp::msvs_emulation::_DoRemapping (element, map) [private]
If |element| then remap it through |map|. If |element| is iterable then
each item will be remapped. Any elements not found will be removed.
Definition at line 90 of file msvs_emulation.py.
def gyp::msvs_emulation::_ExtractCLPath (output_of_where) [private]
Gets the path to cl.exe based on the output of calling the environment
setup batch file, followed by the equivalent of `where`.
Definition at line 983 of file msvs_emulation.py.
def gyp::msvs_emulation::_ExtractImportantEnvironment (output_of_set) [private]
Extracts environment variables required for the toolchain to run from
a textual dump output by the cmd.exe 'set' command.
Definition at line 939 of file msvs_emulation.py.
def gyp::msvs_emulation::_FindDirectXInstallation () [private]
Try to find an installation location for the DirectX SDK. Check for the
standard environment variable, and if that doesn't exist, try to find
via the registry. May return None if not found in either location.
Definition at line 116 of file msvs_emulation.py.
def gyp::msvs_emulation::_FormatAsEnvironmentBlock (envvar_dict) [private]
Format as an 'environment block' directly suitable for CreateProcess.
Briefly this is a list of key=value\0, terminated by an additional \0. See
CreateProcess documentation for more details.
Definition at line 972 of file msvs_emulation.py.
def gyp::msvs_emulation::_GenericRetrieve (root, default, path) [private]
Given a list of dictionary keys |path| and a tree of dicts |root|, find
value at path, or return |default| if any of the path doesn't exist.
Definition at line 69 of file msvs_emulation.py.
def gyp::msvs_emulation::_GetVsvarsSetupArgs (generator_flags, arch) [private]
Definition at line 926 of file msvs_emulation.py.
def gyp::msvs_emulation::_LanguageMatchesForPch (source_ext, pch_source_ext) [private]
Definition at line 858 of file msvs_emulation.py.
def gyp::msvs_emulation::CalculateCommonVariables (default_variables, params)
Definition at line 1062 of file msvs_emulation.py.
def gyp::msvs_emulation::EncodeRspFileList (args)
Process a list of arguments using QuoteCmdExeArgument.
Definition at line 53 of file msvs_emulation.py.
def gyp::msvs_emulation::ExpandMacros (string, expansions)
Expand $(Variable) per expansions dict. See MsvsSettings.GetVSMacroEnv
for the canonical way to retrieve a suitable dict.
Definition at line 930 of file msvs_emulation.py.
def gyp::msvs_emulation::ExtractSharedMSVSSystemIncludes (configs, generator_flags)
Finds msvs_system_include_dirs that are common to all targets, removes
them from all targets, and returns an OrderedSet containing them.
Definition at line 158 of file msvs_emulation.py.
def gyp::msvs_emulation::GenerateEnvironmentFiles (toplevel_build_dir, generator_flags, system_includes, open_out)
It's not sufficient to have the absolute path to the compiler, linker,
etc. on Windows, as those tools rely on .dlls being in the PATH. We also
need to support both x86 and x64 compilers within the same build (to support
msvs_target_platform hackery). Different architectures require a different
compiler binary, and different supporting environment variables (INCLUDE,
LIB, LIBPATH). So, we extract the environment here, wrap all invocations
of compiler tools (cl, link, lib, rc, midl, etc.) via win_tool.py which
sets up the environment, and then we do not prefix the compiler with
an absolute path, instead preferring something like "cl.exe" in the rule
which will then run whichever the environment setup has put in the path.
When the following procedure to generate environment files does not
meet your requirement (e.g. for custom toolchains), you can pass
"-G ninja_use_custom_environment_files" to the gyp to suppress file
generation and use custom environment files prepared by yourself.
Definition at line 991 of file msvs_emulation.py.
def gyp::msvs_emulation::GetGlobalVSMacroEnv (vs_version)
Get a dict of variables mapping internal VS macro names to their gyp
equivalents. Returns all variables that are independent of the target.
Definition at line 138 of file msvs_emulation.py.
def gyp::msvs_emulation::GetVSVersion (generator_flags)
Definition at line 918 of file msvs_emulation.py.
def gyp::msvs_emulation::VerifyMissingSources (sources, build_dir, generator_flags, gyp_to_ninja)
Emulate behavior of msvs_error_on_missing_sources present in the msvs
generator: Check that all regular source files, i.e. not created at run time,
exist on disk. Missing files cause needless recompilation when building via
VS, and we want this check to match for people/bots that build using ninja,
so they're not surprised when the VS build fails.
Definition at line 1044 of file msvs_emulation.py.
Variable Documentation
tuple arg = arg.replace('%', '%%')
Definition at line 43 of file msvs_emulation.py.
Referenced by Sass::Functions::BUILT_IN(), Eval::operator()(), Parser::parse_argument(), Parser::parse_calc_function(), and List::size().
vs_version = None
Definition at line 917 of file msvs_emulation.py.
tuple windows_quoter_regex
Initial value:
re.compile(r'(\\*)"')def QuoteForRspFile(arg):  """Quote a command line argument so that it appears as one argument when
  processed via cmd.exe and parsed by CommandLineToArgvW (as is typical for
  Windows programs)."""  # See http://goo.gl/cuFbX and http://goo.gl/dhPnp including the comment  # threads. This is actually the quoting rules for CommandLineToArgvW, not  # for the shell, because the shell doesn't do anything in Windows. This  # works more or less because most programs (including the compiler, etc.)  # use that function to handle command line arguments.  # For a literal quote, CommandLineToArgvW requires 2n+1 backslashes  # preceding it, and results in n backslashes + the quote. So we substitute  # in 2* what we match, +1 more, plus the quote.  arg = windows_quoter_regex.sub(lambda mo: 2 * mo.group(1) + '\\"', arg)
Definition at line 20 of file msvs_emulation.py.