Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/test/test.php File Reference
test.php File Reference
Functions
assertion_increase ($success)
ERAssertOfClass ($expr, $class, $description)
ERAssertTrue ($expr, $description)
ERAssertFalse ($expr, $description)
ERAssertEqual ($expr, $val, $description)
ERAssertEqualStrict ($expr, $val, $description)
ERAssertInRange ($expr, $min, $max, $description)
my_assert_handler ($file, $line, $code)
Variables
$assertions_total = 0
$assertions_failed = 0
$assertions_errors = 0
Function Documentation
assertion_increase ($success)
Definition at line 13 of file test.php.
References $assertions_failed, and $assertions_total.
Referenced by ERAssertEqual(), ERAssertEqualStrict(), ERAssertFalse(), ERAssertInRange(), ERAssertOfClass(), and ERAssertTrue().
ERAssertEqual ($expr, $val, $description)
Definition at line 61 of file test.php.
References assertion_increase().
Referenced by TimeUnitTest\test_ago(), FilesystemUnitTest\test_filesize(), FilesystemUnitTest\test_filesize_readable(), AntispamUnitTest\test_get_spam_signature(), GravatarUnitTest\test_gravatar_url(), WikipediaUnitTest\test_lookup_url(), FilesystemUnitTest\test_md5_sum(), TimeUnitTest\test_tomorrow(), and TimeUnitTest\test_yesterday().
ERAssertEqualStrict ($expr, $val, $description)
Definition at line 73 of file test.php.
References assertion_increase().
ERAssertFalse ($expr, $description)
Definition at line 50 of file test.php.
References assertion_increase().
Referenced by AntispamUnitTest\test_check_math(), and EmailUnitTest\test_is_valid().
ERAssertInRange ($expr, $min, $max, $description)
Definition at line 84 of file test.php.
References assertion_increase().
Referenced by AntispamUnitTest\test_init_math_test().
ERAssertOfClass ($expr, $class, $description)
Definition at line 28 of file test.php.
References assertion_increase().
Referenced by IusethisEntryUnitTest\test_class(), EmailUnitTest\test_class(), GravatarUnitTest\test_class(), WikipediaUnitTest\test_class(), AntispamUnitTest\test_class(), TimeUnitTest\test_class(), and FilesystemUnitTest\test_class().
ERAssertTrue ($expr, $description)
Definition at line 39 of file test.php.
References assertion_increase().
Referenced by TimeUnitTest\test_ago(), AntispamUnitTest\test_check_math(), FilesystemUnitTest\test_file_exists(), EmailUnitTest\test_is_valid(), TimeUnitTest\test_tomorrow(), and TimeUnitTest\test_yesterday().
my_assert_handler ($file, $line, $code)
Definition at line 96 of file test.php.
Variable Documentation
$assertions_errors = 0
Definition at line 11 of file test.php.
Referenced by UnitTest\report().
$assertions_failed = 0
Definition at line 10 of file test.php.
Referenced by assertion_increase(), UnitTest\report(), and UnitTest\run().
$assertions_total = 0
Definition at line 9 of file test.php.
Referenced by assertion_increase(), UnitTest\report(), and UnitTest\run().