Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass.cpp File Reference
#include <cstdlib>
#include <cstring>
#include <vector>
#include <sstream>
#include "sass.h"
#include "file.hpp"
#include "util.hpp"
Functions
char *ADDCALL sass_string_quote (const char *str, const char quote_mark)
char *ADDCALL sass_string_unquote (const char *str)
char *ADDCALL sass_resolve_file (const char *file, const char *paths[])
const char *ADDCALL libsass_version (void)
Function Documentation
const char* ADDCALL libsass_version (void)
Definition at line 38 of file sass.cpp.
References LIBSASS_VERSION.
Referenced by Sass::compatibility(), libsass_get_version(), NAN_METHOD(), and NAN_MODULE_INIT().
char* ADDCALL sass_resolve_file (const char * file, const char * paths[])
Definition at line 31 of file sass.cpp.
References Sass::File::find_file(), and Sass::sass_strdup().
char* ADDCALL sass_string_quote (const char * str, const char quote_mark)
Definition at line 16 of file sass.cpp.
References Sass::quote(), and Sass::sass_strdup().
char* ADDCALL sass_string_unquote (const char * str)
Definition at line 23 of file sass.cpp.
References Sass::sass_strdup(), and Sass::unquote().