Emeraldion Lodge (codename Zelda): String_Schema Class Reference
String_Schema Class Reference
#include <ast.hpp>
Inherits Sass::String, and Vectorized< Expression * >.
Public Member Functions
String_Schema (ParserState pstate, size_t size=0, bool has_interpolants=false)
string type ()
virtual bool operator== (Expression &rhs) const
virtual size_t hash ()
ATTACH_OPERATIONS ()
Static Public Member Functions
static string type_name ()
Private Member Functions
ADD_PROPERTY (bool, has_interpolants)
Private Attributes
size_t hash_
Detailed Description
Definition at line 1318 of file ast.hpp.
Constructor & Destructor Documentation
String_Schema (ParserState pstate, size_t size = 0, bool has_interpolants = false) [inline]
Definition at line 1322 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (bool , has_interpolants) [private]
ATTACH_OPERATIONS ()
Reimplemented from String.
virtual size_t hash () [inline, virtual]
Reimplemented from Expression.
Definition at line 1345 of file ast.hpp.
References Vectorized< Expression * >::elements(), and String_Schema::hash_.
virtual bool operator== (Expression & rhs) const [inline, virtual]
Reimplemented from Expression.
Definition at line 1328 of file ast.hpp.
References Vectorized< T >::length(), and Vectorized< Expression * >::length().
string type () [inline, virtual]
Reimplemented from Expression.
Definition at line 1325 of file ast.hpp.
static string type_name () [inline, static]
Reimplemented from String.
Definition at line 1326 of file ast.hpp.
Field Documentation
size_t hash_ [private]
Reimplemented from Vectorized< Expression * >.
Definition at line 1320 of file ast.hpp.
Referenced by String_Schema::hash().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp