Emeraldion Lodge (codename Zelda): Import Class Reference
Import Class Reference
#include <ast.hpp>
Inherits Sass::Statement.
Public Member Functions
Import (ParserState pstate)
vector< string > & files ()
vector< Expression * > & urls ()
ATTACH_OPERATIONS ()
Private Attributes
vector< string > files_
vector< Expression * > urls_
Detailed Description
Definition at line 481 of file ast.hpp.
Constructor & Destructor Documentation
Import (ParserState pstate) [inline]
Definition at line 485 of file ast.hpp.
Member Function Documentation
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
vector<string>& files () [inline]
Definition at line 489 of file ast.hpp.
References Import::files_.
Referenced by Parser::add_single_file(), Parser::do_import(), and Parser::parse().
vector<Expression*>& urls () [inline]
Definition at line 490 of file ast.hpp.
References Import::urls_.
Referenced by Parser::add_single_file(), Parser::import_single_file(), Expand::operator()(), and Parser::parse().
Field Documentation
vector<string> files_ [private]
Definition at line 482 of file ast.hpp.
Referenced by Import::files().
vector<Expression*> urls_ [private]
Definition at line 483 of file ast.hpp.
Referenced by Import::urls().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp