Emeraldion Lodge (codename Zelda): Selector_Qualifier Class Reference
Selector_Qualifier Class Reference
#include <ast.hpp>
Inherits Sass::Simple_Selector.
Public Member Functions
Selector_Qualifier (ParserState pstate, string n)
virtual unsigned long specificity ()
virtual Compound_Selector * unify_with (Compound_Selector *, Context &)
ATTACH_OPERATIONS ()
Private Member Functions
ADD_PROPERTY (string, name)
Detailed Description
Definition at line 1803 of file ast.hpp.
Constructor & Destructor Documentation
Selector_Qualifier (ParserState pstate, string n) [inline]
Definition at line 1806 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (string , name) [private]
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
virtual unsigned long specificity () [inline, virtual]
Reimplemented from Selector.
Definition at line 1809 of file ast.hpp.
References Sass::Prelexer::name(), Sass::Constants::Specificity_Class, Sass::Constants::Specificity_ID, and Sass::Constants::Specificity_Type.
Compound_Selector * unify_with (Compound_Selector * rhs, Context & ctx) [virtual]
Reimplemented from Simple_Selector.
Definition at line 175 of file ast.cpp.
References Vectorized< T >::length(), and Sass::Prelexer::name().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp