Emeraldion Lodge (codename Zelda): MiniBatteryLoggerLicense Class Reference
MiniBatteryLoggerLicense Class Reference
Helper class to handle MiniBatteryLogger software licenses.
Public Member Functions
MiniBatteryLoggerLicense ($name= '', $email= '', $key= '')
Constructor for MiniBatteryLoggerLicense objects.
activation_link ($text=NULL)
Creates a hyperlink that activates a copy of MiniBatteryLogger.
activation_url ()
Creates an activation URL that can activate a copy of MiniBatteryLogger.
__toString ()
Returns a string representation of the receiver.
Public Member Functions inherited from License
is_valid ()
Tells if this license is valid.
Static Public Member Functions
static parse_url ($the_url)
Creates a MiniBatteryLoggerLicense object from an activation URL.
static generate_key ($username, $registration_date=NULL, $expiration_date=NULL, $license_type=MiniBatteryLoggerLicense::SINGLE_USER_LICENSE)
MiniBatteryLogger license generator.
static valid_key ($key, $username= '', &$cleartext=NULL)
MiniBatteryLogger license validator.
static license_for ($username, $email, $registration_date=NULL, $expiration_date=NULL, $license_type=MiniBatteryLoggerLicense::SINGLE_USER_LICENSE)
Factory method that creates a license object given registration details.
static license_type_name ($license_type)
Returns a colloquial name for the input license type.
Static Public Member Functions inherited from License
static generate_key ($username, $registration_date=NULL, $expiration_date=NULL, $license_type=NULL)
Generates a key for a license.
static valid_key ($key, $username= '', &$cleartext=NULL)
Validates a key.
Data Fields
const SINGLE_USER_LICENSE = 0
Constant for single user license type.
const FAMILYPACK_LICENSE = 1
Constant for familypack license type.
const SITE_LICENSE = 2
Constant for site license type.
const EVALUATION_LICENSE = 3
Constant for evaluation license type.
const GIFT_LICENSE = 4
Constant for gift license type.
const DEFAULT_LICENSE_DURATION = 31536000
Constant for the default license duration (365 days).
Data Fields inherited from License
$username
The user who owns this license.
$email
The email address of the license owner.
$key
The key of the license.
$license_type
The type of the license.
$registration_date
The validity date of the license.
$expiration_date
The expiration date of the license.
Protected Member Functions
init ()
Initializes a MiniBatteryLoggerLicense object.
Detailed Description
Helper class to handle MiniBatteryLogger software licenses.
Definition at line 12 of file mini_battery_logger_license.php.
Member Function Documentation
__toString ()
Returns a string representation of the receiver.
Definition at line 265 of file mini_battery_logger_license.php.
References License\$expiration_date, License\$registration_date, and username.
activation_link ($text = NULL)
Creates a hyperlink that activates a copy of MiniBatteryLogger.
Definition at line 188 of file mini_battery_logger_license.php.
References a(), activation_url(), and l().
activation_url ()
Creates an activation URL that can activate a copy of MiniBatteryLogger.
Definition at line 201 of file mini_battery_logger_license.php.
References username.
Referenced by activation_link().
generate_key ($username, $registration_date = NULL, $expiration_date = NULL, $license_type = MiniBatteryLoggerLicense::SINGLE_USER_LICENSE) static
MiniBatteryLogger license generator.
Definition at line 96 of file mini_battery_logger_license.php.
References License\$expiration_date, License\$key, License\$registration_date, License\$username, DEFAULT_LICENSE_DURATION, and Base64\encode_linelength().
init () protected
Initializes a MiniBatteryLoggerLicense object.
Definition at line 61 of file mini_battery_logger_license.php.
References username.
Referenced by MiniBatteryLoggerLicense().
license_for ($username, $email, $registration_date = NULL, $expiration_date = NULL, $license_type = MiniBatteryLoggerLicense::SINGLE_USER_LICENSE) static
Factory method that creates a license object given registration details.
Parameters
username The user this license belongs to.
email The email of the user.
registration_date The registration date. License will be valid from this date onwards.
expiration_date The expiration date. License will no longer be valid after this date.
license_type The type of the license.
Definition at line 218 of file mini_battery_logger_license.php.
References License\$email, License\$expiration_date, License\$key, $license, License\$license_type, License\$registration_date, and License\$username.
license_type_name ($license_type) static
Returns a colloquial name for the input license type.
Parameters
license_type The type of the license.
Definition at line 239 of file mini_battery_logger_license.php.
References License\$license_type.
MiniBatteryLoggerLicense ($name = '', $email = '', $key = '')
Constructor for MiniBatteryLoggerLicense objects.
Definition at line 48 of file mini_battery_logger_license.php.
References License\$email, License\$key, init(), and username.
parse_url ($the_url) static
Creates a MiniBatteryLoggerLicense object from an activation URL.
Definition at line 78 of file mini_battery_logger_license.php.
References $license.
function valid_key ($key, $username = '', & $cleartext = NULL) static
MiniBatteryLogger license validator.
Definition at line 146 of file mini_battery_logger_license.php.
References License\$key, License\$username, and Base64\decode().
Field Documentation
const DEFAULT_LICENSE_DURATION = 31536000
Constant for the default license duration (365 days).
Definition at line 42 of file mini_battery_logger_license.php.
Referenced by generate_key().
const EVALUATION_LICENSE = 3
Constant for evaluation license type.
Definition at line 32 of file mini_battery_logger_license.php.
const FAMILYPACK_LICENSE = 1
Constant for familypack license type.
Definition at line 22 of file mini_battery_logger_license.php.
const GIFT_LICENSE = 4
Constant for gift license type.
Definition at line 37 of file mini_battery_logger_license.php.
const SINGLE_USER_LICENSE = 0
Constant for single user license type.
Definition at line 17 of file mini_battery_logger_license.php.
const SITE_LICENSE = 2
Constant for site license type.
Definition at line 27 of file mini_battery_logger_license.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/mini_battery_logger_license.php