Emeraldion Lodge (codename Zelda): Contextualize_Eval Class Reference
Contextualize_Eval Class Reference
#include <contextualize_eval.hpp>
Inherits Sass::Contextualize.
Public Member Functions
Contextualize_Eval (Context &, Eval *, Env *, Backtrace *)
virtual ~Contextualize_Eval ()
Contextualize_Eval * with (Selector *, Env *, Backtrace *, Selector *placeholder=0, Selector *extender=0)
Selector * operator() (Selector_Schema *)
Selector * operator() (Selector_List *)
Selector * operator() (Complex_Selector *)
Selector * operator() (Compound_Selector *)
Selector * operator() (Wrapped_Selector *)
Selector * operator() (Pseudo_Selector *)
Selector * operator() (Attribute_Selector *)
Selector * operator() (Selector_Qualifier *)
Selector * operator() (Type_Selector *)
Selector * operator() (Selector_Placeholder *)
Selector * operator() (Selector_Reference *)
template<typename U >
Selector * fallback (U x)
Private Member Functions
Selector * fallback_impl (AST_Node *n)
Private Attributes
Eval * eval
Detailed Description
Definition at line 15 of file contextualize_eval.hpp.
Constructor & Destructor Documentation
Contextualize_Eval (Context & ctx, Eval * eval, Env * env, Backtrace * bt)
Definition at line 10 of file contextualize_eval.cpp.
~Contextualize_Eval () [virtual]
Definition at line 14 of file contextualize_eval.cpp.
Member Function Documentation
Selector* fallback (U x) [inline]
Reimplemented from Contextualize.
Definition at line 40 of file contextualize_eval.hpp.
References Contextualize_Eval::fallback_impl().
Selector * fallback_impl (AST_Node * n) [private]
Reimplemented from Contextualize.
Definition at line 16 of file contextualize_eval.cpp.
Referenced by Contextualize_Eval::fallback().
Selector * operator() (Selector_Reference * s) [virtual]
Reimplemented from Contextualize.
Definition at line 89 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Selector_Placeholder * p) [virtual]
Reimplemented from Contextualize.
Definition at line 84 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Type_Selector * s) [virtual]
Reimplemented from Contextualize.
Definition at line 80 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Selector_Qualifier * s) [virtual]
Reimplemented from Contextualize.
Definition at line 76 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Attribute_Selector * s) [virtual]
Reimplemented from Operation_CRTP< Selector *, Contextualize >.
Definition at line 62 of file contextualize_eval.cpp.
References Contextualize::backtrace, Contextualize::ctx, Contextualize::env, Contextualize_Eval::eval, Context::mem, Contextualize::parent, toString(), and Eval::with().
Selector * operator() (Pseudo_Selector * s) [virtual]
Reimplemented from Contextualize.
Definition at line 57 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Wrapped_Selector * s) [virtual]
Reimplemented from Contextualize.
Definition at line 52 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Compound_Selector * s) [virtual]
Reimplemented from Contextualize.
Definition at line 47 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Complex_Selector * s) [virtual]
Reimplemented from Contextualize.
Definition at line 42 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Selector_List * s) [virtual]
Reimplemented from Contextualize.
Definition at line 37 of file contextualize_eval.cpp.
References Contextualize_Eval::operator()().
Selector * operator() (Selector_Schema * s) [virtual]
Reimplemented from Operation_CRTP< Selector *, Contextualize >.
Definition at line 28 of file contextualize_eval.cpp.
References Contextualize::ctx, Contextualize_Eval::eval, Parser::from_c_str(), and Sass::to_string.
Referenced by Contextualize_Eval::operator()().
Contextualize_Eval * with (Selector * s, Env * e, Backtrace * bt, Selector * placeholder = 0, Selector * extender = 0)
Reimplemented from Contextualize.
Definition at line 21 of file contextualize_eval.cpp.
References Contextualize_Eval::eval, and Eval::with().
Referenced by Expand::operator()().
Field Documentation
Eval* eval [private]
Definition at line 17 of file contextualize_eval.hpp.
Referenced by Contextualize_Eval::operator()(), and Contextualize_Eval::with().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/contextualize_eval.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/contextualize_eval.cpp