Emeraldion Lodge (codename Zelda): Base64VLQ Class Reference
Base64VLQ Class Reference
#include <base64vlq.hpp>
Public Member Functions
string encode (const int number) const
Private Member Functions
char base64_encode (const int number) const
int to_vlq_signed (const int number) const
Static Private Attributes
static const char * CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static const int VLQ_BASE_SHIFT = 5
static const int VLQ_BASE = 1 << VLQ_BASE_SHIFT
static const int VLQ_BASE_MASK = VLQ_BASE - 1
static const int VLQ_CONTINUATION_BIT = VLQ_BASE
Detailed Description
Definition at line 9 of file base64vlq.hpp.
Member Function Documentation
char base64_encode (const int number) const [private]
Definition at line 23 of file base64vlq.cpp.
References Base64VLQ::CHARACTERS.
Referenced by Base64VLQ::encode().
string encode (const int number) const
Definition at line 5 of file base64vlq.cpp.
References Base64VLQ::base64_encode(), Sass::Prelexer::digit(), Base64VLQ::to_vlq_signed(), Base64VLQ::VLQ_BASE_MASK, Base64VLQ::VLQ_BASE_SHIFT, and Base64VLQ::VLQ_CONTINUATION_BIT.
Referenced by SourceMap::serialize_mappings().
int to_vlq_signed (const int number) const [private]
Definition at line 31 of file base64vlq.cpp.
Referenced by Base64VLQ::encode().
Field Documentation
const char * CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" [static, private]
Definition at line 21 of file base64vlq.hpp.
Referenced by Base64VLQ::base64_encode().
const int VLQ_BASE = 1 << VLQ_BASE_SHIFT [static, private]
Definition at line 24 of file base64vlq.hpp.
const int VLQ_BASE_MASK = VLQ_BASE - 1 [static, private]
Definition at line 25 of file base64vlq.hpp.
Referenced by Base64VLQ::encode().
const int VLQ_BASE_SHIFT = 5 [static, private]
Definition at line 23 of file base64vlq.hpp.
Referenced by Base64VLQ::encode().
const int VLQ_CONTINUATION_BIT = VLQ_BASE [static, private]
Definition at line 26 of file base64vlq.hpp.
Referenced by Base64VLQ::encode().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/base64vlq.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/base64vlq.cpp