Emeraldion Lodge (codename Zelda): Parser Class Reference
Parser Class Reference
#include <parser.hpp>
Inherits Sass::ParserState.
Public Types
enum Syntactic_Context { nothing, mixin_def, function_def }
Public Member Functions
bool do_import (const string &import_path, Import *imp, vector< Sass_Importer_Entry > importers, bool only_one=true)
Parser (Context &ctx, const ParserState &pstate)
bool peek_newline (const char *start=0)
template<prelexer mx>
const char * sneak (const char *start=0)
template<prelexer mx>
const char * peek (const char *start=0)
template<prelexer mx>
const char * lex (bool lazy=true)
template<prelexer mx>
const char * lex_css ()
template<prelexer mx>
const char * peek_css (const char *start=0)
void error (string msg, Position pos)
void css_error (const string &msg, const string &prefix=" after ", const string &middle=", was: ")
void read_bom ()
Block * parse ()
Import * parse_import ()
Definition * parse_definition ()
Parameters * parse_parameters ()
Parameter * parse_parameter ()
Mixin_Call * parse_mixin_call ()
Arguments * parse_arguments (bool has_url=false)
Argument * parse_argument (bool has_url=false)
Assignment * parse_assignment ()
Ruleset * parse_ruleset (Selector_Lookahead lookahead)
Selector_Schema * parse_selector_schema (const char *end_of_selector)
Selector_List * parse_selector_group ()
Complex_Selector * parse_selector_combination ()
Compound_Selector * parse_simple_selector_sequence ()
Simple_Selector * parse_simple_selector ()
Wrapped_Selector * parse_negated_selector ()
Simple_Selector * parse_pseudo_selector ()
Attribute_Selector * parse_attribute_selector ()
Block * parse_block ()
bool parse_number_prefix ()
Declaration * parse_declaration ()
Expression * parse_map_value ()
Expression * parse_map ()
Expression * parse_list ()
Expression * parse_comma_list ()
Expression * parse_space_list ()
Expression * parse_disjunction ()
Expression * parse_conjunction ()
Expression * parse_relation ()
Expression * parse_expression ()
Expression * parse_term ()
Expression * parse_factor ()
Expression * parse_value ()
Function_Call * parse_calc_function ()
Function_Call * parse_function_call ()
Function_Call_Schema * parse_function_call_schema ()
String * parse_interpolated_chunk (Token, bool constant=false)
String * parse_string ()
String_Constant * parse_static_expression ()
String_Constant * parse_static_value ()
String * parse_ie_property ()
String * parse_ie_keyword_arg ()
String_Schema * parse_value_schema (const char *stop)
Expression * parse_operators (Expression *factor)
String * parse_identifier_schema ()
If * parse_if_directive (bool else_if=false)
For * parse_for_directive ()
Each * parse_each_directive ()
While * parse_while_directive ()
Media_Block * parse_media_block ()
List * parse_media_queries ()
Media_Query * parse_media_query ()
Media_Query_Expression * parse_media_expression ()
Feature_Block * parse_feature_block ()
Feature_Query * parse_feature_queries ()
Feature_Query_Condition * parse_feature_query ()
Feature_Query_Condition * parse_feature_query_in_parens ()
Feature_Query_Condition * parse_supports_negation ()
Feature_Query_Condition * parse_supports_conjunction ()
Feature_Query_Condition * parse_supports_disjunction ()
Feature_Query_Condition * parse_supports_declaration ()
At_Root_Block * parse_at_root_block ()
At_Root_Expression * parse_at_root_expression ()
At_Rule * parse_at_rule ()
Warning * parse_warning ()
Error * parse_error ()
Debug * parse_debug ()
void parse_block_comments (Block *block)
Selector_Lookahead lookahead_for_value (const char *start=0)
Selector_Lookahead lookahead_for_selector (const char *start=0)
Selector_Lookahead lookahead_for_extension_target (const char *start=0)
Expression * fold_operands (Expression *base, vector< Expression * > &operands, Binary_Expression::Type op)
Expression * fold_operands (Expression *base, vector< Expression * > &operands, vector< Binary_Expression::Type > &ops)
void throw_syntax_error (string message, size_t ln=0)
void throw_read_error (string message, size_t ln=0)
Static Public Member Functions
static Parser from_c_str (const char *src, Context &ctx, ParserState pstate=ParserState("[CSTRING]"))
static Parser from_c_str (const char *beg, const char *end, Context &ctx, ParserState pstate=ParserState("[CSTRING]"))
static Parser from_token (Token t, Context &ctx, ParserState pstate=ParserState("[TOKEN]"))
static Selector_List * parse_selector (const char *src, Context &ctx, ParserState pstate=ParserState("[SELECTOR]"))
Data Fields
Context & ctx
vector< Block * > block_stack
vector< Syntactic_Context > stack
Media_Block * last_media_block
const char * source
const char * position
const char * end
Position before_token
Position after_token
ParserState pstate
int indentation
Token lexed
bool in_at_root
Private Member Functions
void add_single_file (Import *imp, string import_path)
void import_single_file (Import *imp, string import_path)
Detailed Description
Definition at line 25 of file parser.hpp.
Member Enumeration Documentation
enum Syntactic_Context
Enumerator:
nothing
mixin_def
function_def
Definition at line 32 of file parser.hpp.
Constructor & Destructor Documentation
Parser (Context & ctx, const ParserState & pstate) [inline]
Definition at line 51 of file parser.hpp.
References Parser::in_at_root, Parser::nothing, and Parser::stack.
Member Function Documentation
void add_single_file (Import * imp, string import_path) [private]
Definition at line 195 of file parser.cpp.
References Context::add_file(), Parser::ctx, Sass::File::dir_name(), Parser::error(), Import::files(), Context::mem, ParserState::path, ParserState::pstate(), Sass::unquote(), and Import::urls().
Referenced by Parser::import_single_file().
void css_error (const string & msg, const string & prefix = " after ", const string & middle = ", was: ")
Definition at line 2366 of file parser.cpp.
Referenced by Parser::parse_at_root_expression(), Parser::parse_declaration(), Parser::parse_identifier_schema(), Parser::parse_ie_property(), Parser::parse_interpolated_chunk(), Parser::parse_selector_schema(), and Parser::parse_value_schema().
bool do_import (const string & import_path, Import * imp, vector< Sass_Importer_Entry > importers, bool only_one = true)
Definition at line 235 of file parser.cpp.
References Context::add_source(), Context::c_compiler, Offset::column, Parser::ctx, Parser::error(), Position::file, Import::files(), Parser::import_single_file(), Offset::line, npos, ParserState::ParserState(), Position::Position(), ParserState::pstate(), sass_delete_import_list(), sass_import_get_error_column(), sass_import_get_error_line(), sass_import_get_error_message(), sass_import_get_path(), sass_import_take_source(), sass_importer_get_function(), Parser::source, and Sass::unquote().
Referenced by Parser::parse(), and Parser::parse_import().
void error (string msg, Position pos)
Definition at line 2360 of file parser.cpp.
Referenced by Parser::add_single_file(), Parser::do_import(), Parser::parse(), Parser::parse_arguments(), Parser::parse_assignment(), Parser::parse_at_root_expression(), Parser::parse_declaration(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_factor(), Parser::parse_feature_block(), Parser::parse_feature_queries(), Parser::parse_feature_query_in_parens(), Parser::parse_for_directive(), Parser::parse_identifier_schema(), Parser::parse_ie_property(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_interpolated_chunk(), Parser::parse_map(), Parser::parse_media_block(), Parser::parse_media_expression(), Parser::parse_mixin_call(), Parser::parse_parameters(), Parser::parse_ruleset(), Parser::parse_value(), and Parser::parse_value_schema().
Expression * fold_operands (Expression * base, vector< Expression * > & operands, vector< Binary_Expression::Type > & ops)
Definition at line 2344 of file parser.cpp.
Expression * fold_operands (Expression * base, vector< Expression * > & operands, Binary_Expression::Type op)
Definition at line 2328 of file parser.cpp.
Referenced by Parser::parse_conjunction(), Parser::parse_disjunction(), Parser::parse_expression(), and Parser::parse_operators().
Parser from_c_str (const char * beg, const char * end, Context & ctx, ParserState pstate = ParserState("[CSTRING]")) [static]
Definition at line 31 of file parser.cpp.
References Parser::block_stack, Parser::end, Context::mem, p(), Parser::position, and Parser::source.
Parser from_c_str (const char * src, Context & ctx, ParserState pstate = ParserState("[CSTRING]")) [static]
Definition at line 19 of file parser.cpp.
References Parser::block_stack, Parser::end, Context::mem, p(), Parser::position, and Parser::source.
Referenced by Sass::createComplexSelector(), Sass::extendObjectWithSelectorAndBlock(), Sass::make_c_function(), Sass::make_native_function(), Expand::operator()(), Contextualize_Eval::operator()(), Context::parse_file(), Parser::parse_selector(), and Parser::parse_selector_schema().
Parser from_token (Token t, Context & ctx, ParserState pstate = ParserState("[TOKEN]")) [static]
Definition at line 56 of file parser.cpp.
References Token::begin, Parser::block_stack, Token::end, Parser::end, Context::mem, p(), Parser::position, and Parser::source.
Referenced by Parser::parse_identifier_schema(), Parser::parse_ie_property(), Parser::parse_interpolated_chunk(), and Parser::parse_value_schema().
void import_single_file (Import * imp, string import_path) [private]
Definition at line 221 of file parser.cpp.
References Parser::add_single_file(), Parser::ctx, Context::mem, ParserState::pstate(), Sass::unquote(), and Import::urls().
Referenced by Parser::do_import(), and Parser::parse_import().
const char* lex (bool lazy = true) [inline]
Definition at line 127 of file parser.hpp.
References Position::add(), Parser::after_token, Parser::before_token, Parser::lexed, ParserState::ParserState(), ParserState::path, Parser::position, ParserState::pstate(), and Parser::source.
Referenced by Sass::make_c_function(), Sass::make_native_function(), Parser::parse(), Parser::parse_argument(), Parser::parse_assignment(), Parser::parse_at_root_expression(), Parser::parse_declaration(), Parser::parse_each_directive(), Parser::parse_expression(), Parser::parse_factor(), Parser::parse_feature_query_in_parens(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_map(), Parser::parse_media_expression(), Parser::parse_media_queries(), Parser::parse_media_query(), Parser::parse_number_prefix(), Parser::parse_parameter(), Parser::parse_value(), and Parser::parse_value_schema().
const char* lex_css () [inline]
Definition at line 168 of file parser.hpp.
References Parser::lexed, and ParserState::pos().
Referenced by Parser::parse_argument(), Parser::parse_arguments(), Parser::parse_comma_list(), Parser::parse_declaration(), Parser::parse_factor(), Parser::parse_import(), Parser::parse_map(), Parser::parse_operators(), and Parser::parse_parameters().
Selector_Lookahead lookahead_for_extension_target (const char * start = 0)
Definition at line 2149 of file parser.cpp.
Referenced by Parser::parse_at_rule().
Selector_Lookahead lookahead_for_selector (const char * start = 0)
Definition at line 2085 of file parser.cpp.
References Sass::Prelexer::exactly(), p(), Parser::peek(), and Parser::position.
Referenced by Parser::parse(), and Parser::parse_at_root_block().
Selector_Lookahead lookahead_for_value (const char * start = 0)
Definition at line 2211 of file parser.cpp.
Referenced by Parser::parse_assignment(), and Parser::parse_declaration().
Block * parse ()
Definition at line 68 of file parser.cpp.
References Parser::after_token, Parser::block_stack, Context::c_headers, Parser::ctx, Parser::do_import(), Parser::end, Parser::error(), Import::files(), Context::head_imports, Parser::lex(), Parser::lookahead_for_selector(), Context::mem, Sass::Prelexer::one_plus(), Parser::parse_assignment(), Parser::parse_at_root_block(), Parser::parse_at_rule(), Parser::parse_block_comments(), Parser::parse_debug(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_error(), Parser::parse_feature_block(), Parser::parse_for_directive(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_media_block(), Parser::parse_mixin_call(), Parser::parse_ruleset(), Parser::parse_warning(), Parser::parse_while_directive(), Parser::peek(), Parser::position, ParserState::pstate(), Context::queue, Parser::read_bom(), and Import::urls().
Referenced by Context::parse_file().
Argument * parse_argument (bool has_url = false)
Definition at line 414 of file parser.cpp.
References gyp::msvs_emulation::arg, Parser::ctx, Parser::lex(), Parser::lex_css(), Parser::lexed, Sass::Prelexer::lookahead(), Sass::Prelexer::loosely(), Expression::MAP, Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), Sass::Prelexer::optional_css_comments(), p(), Parser::parse_interpolated_chunk(), Parser::parse_space_list(), Parser::peek_css(), ParserState::pstate(), Sass::Prelexer::sequence(), Sass::Prelexer::uri_value(), and Sass::Prelexer::variable().
Referenced by Parser::parse_arguments().
Arguments * parse_arguments (bool has_url = false)
Definition at line 398 of file parser.cpp.
References Parser::after_token, Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lex_css(), Parser::lexed, Context::mem, Sass::Prelexer::name(), Parser::parse_argument(), Parser::peek_css(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse_function_call(), Parser::parse_function_call_schema(), and Parser::parse_mixin_call().
Assignment * parse_assignment ()
Definition at line 446 of file parser.cpp.
References Parser::ctx, Parser::error(), Selector_Lookahead::found, Selector_Lookahead::has_interpolants, Parser::lex(), Parser::lexed, Sass::Prelexer::lookahead(), Parser::lookahead_for_value(), Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), Parser::parse_list(), Parser::parse_value_schema(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse().
At_Root_Block * parse_at_root_block ()
Definition at line 1991 of file parser.cpp.
References Parser::ctx, Sass::Prelexer::exactly(), Parser::in_at_root, Parser::lookahead_for_selector(), Context::mem, Parser::parse_at_root_expression(), Parser::parse_block(), Parser::parse_ruleset(), Parser::peek(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse().
At_Root_Expression * parse_at_root_expression ()
Definition at line 2017 of file parser.cpp.
References Parser::css_error(), Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lex(), Expression::LIST, Context::mem, Parser::parse_declaration(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse_at_root_block().
At_Rule * parse_at_rule ()
Definition at line 2041 of file parser.cpp.
References Parser::ctx, Sass::Prelexer::exactly(), Selector_Lookahead::found, Selector_Lookahead::has_interpolants, Parser::lexed, Parser::lookahead_for_extension_target(), Context::mem, Parser::parse_block(), Parser::parse_list(), Parser::parse_selector_group(), Parser::parse_selector_schema(), Parser::peek(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse().
Attribute_Selector * parse_attribute_selector ()
Definition at line 799 of file parser.cpp.
Block * parse_block ()
Definition at line 837 of file parser.cpp.
Referenced by Parser::parse_at_root_block(), Parser::parse_at_rule(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_feature_block(), Parser::parse_for_directive(), Parser::parse_if_directive(), Parser::parse_media_block(), Parser::parse_mixin_call(), Parser::parse_ruleset(), and Parser::parse_while_directive().
void parse_block_comments (Block * block)
Definition at line 828 of file parser.cpp.
Referenced by Parser::parse().
Function_Call * parse_calc_function ()
Definition at line 1709 of file parser.cpp.
References gyp::msvs_emulation::arg, Parser::ctx, Parser::lexed, Context::mem, Sass::Prelexer::name(), Parser::parse_interpolated_chunk(), Parser::parse_list(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse_factor().
Expression * parse_comma_list ()
Definition at line 1120 of file parser.cpp.
References Sass::Prelexer::alternatives(), List::COMMA, Parser::ctx, Sass::Prelexer::exactly(), Parser::lex_css(), Context::mem, Parser::parse_space_list(), Parser::peek_css(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse_list().
Expression * parse_conjunction ()
Definition at line 1211 of file parser.cpp.
References Binary_Expression::AND, Parser::fold_operands(), and Parser::parse_relation().
Referenced by Parser::parse_disjunction().
Debug * parse_debug ()
Definition at line 2079 of file parser.cpp.
References Parser::ctx, Context::mem, Parser::parse_list(), and ParserState::pstate().
Referenced by Parser::parse().
Declaration * parse_declaration ()
Definition at line 999 of file parser.cpp.
References Parser::css_error(), Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Selector_Lookahead::found, Selector_Lookahead::has_interpolants, Sass::Prelexer::identifier(), Sass::Prelexer::identifier_schema(), Parser::lex(), Parser::lex_css(), Parser::lexed, Parser::lookahead_for_value(), Context::mem, Sass::Prelexer::one_plus(), Sass::Prelexer::optional(), Parser::parse_identifier_schema(), Parser::parse_list(), Parser::parse_static_value(), Parser::parse_value_schema(), Parser::peek(), Parser::peek_css(), Parser::position, ParserState::pstate(), and Sass::Prelexer::sequence().
Referenced by Parser::parse_at_root_expression(), and Parser::parse_supports_declaration().
Definition * parse_definition ()
Definition at line 325 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Definition::FUNCTION, Parser::function_def, Parser::lexed, Context::mem, Definition::MIXIN, Parser::mixin_def, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), Parser::parse_block(), Parser::parse_parameters(), Parser::peek(), ParserState::pstate(), and Parser::stack.
Referenced by Parser::parse().
Expression * parse_disjunction ()
Definition at line 1198 of file parser.cpp.
References Parser::fold_operands(), Binary_Expression::OR, and Parser::parse_conjunction().
Referenced by Parser::parse_space_list().
Each * parse_each_directive ()
Definition at line 1791 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), l(), Vectorized< T >::length(), Parser::lex(), Parser::lexed, Expression::LIST, Context::mem, Sass::Util::normalize_underscores(), Parser::parse_block(), Parser::parse_list(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse().
Error * parse_error ()
Definition at line 2073 of file parser.cpp.
References Parser::ctx, Context::mem, Parser::parse_list(), and ParserState::pstate().
Referenced by Parser::parse().
Expression * parse_expression ()
Definition at line 1252 of file parser.cpp.
References Binary_Expression::ADD, Parser::fold_operands(), Parser::lex(), Parser::lexed, Parser::parse_term(), Parser::peek(), Parser::position, Sass::Prelexer::sequence(), Binary_Expression::SUB, and Token::to_string().
Referenced by Parser::parse_for_directive(), Parser::parse_media_expression(), and Parser::parse_relation().
Expression * parse_factor ()
Definition at line 1303 of file parser.cpp.
References Sass::Prelexer::alternatives(), Sass::Prelexer::css_whitespace(), Parser::ctx, Binary_Expression::DIV, Vectorized< T >::empty(), Parser::error(), Sass::Prelexer::exactly(), Sass::Prelexer::identifier_schema(), l(), Parser::lex(), Parser::lex_css(), Expression::LIST, Context::mem, Unary_Expression::MINUS, Sass::Prelexer::negate(), Unary_Expression::NOT, Sass::Prelexer::number(), Sass::Prelexer::one_plus(), Sass::Prelexer::optional_css_whitespace(), Parser::parse_calc_function(), Parser::parse_function_call(), Parser::parse_function_call_schema(), Parser::parse_identifier_schema(), Parser::parse_ie_keyword_arg(), Parser::parse_ie_property(), Parser::parse_map(), Parser::parse_number_prefix(), Parser::parse_value(), Parser::peek(), Unary_Expression::PLUS, ParserState::pstate(), Sass::Prelexer::sequence(), and Expression::type().
Referenced by Parser::parse_operators(), Parser::parse_term(), and Parser::parse_value_schema().
Feature_Block * parse_feature_block ()
Definition at line 1901 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Context::mem, Parser::parse_block(), Parser::parse_feature_queries(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse().
Feature_Query * parse_feature_queries ()
Definition at line 1916 of file parser.cpp.
References Parser::ctx, Vectorized< T >::empty(), Parser::error(), Sass::Prelexer::exactly(), Context::mem, Parser::parse_feature_query(), Parser::peek(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse_feature_block().
Feature_Query_Condition * parse_feature_query ()
Definition at line 1930 of file parser.cpp.
References Sass::Prelexer::exactly(), Parser::parse_feature_query_in_parens(), Parser::parse_supports_conjunction(), Parser::parse_supports_declaration(), Parser::parse_supports_disjunction(), Parser::parse_supports_negation(), Parser::peek(), and Parser::position.
Referenced by Parser::parse_feature_queries(), Parser::parse_feature_query_in_parens(), Parser::parse_supports_conjunction(), Parser::parse_supports_disjunction(), and Parser::parse_supports_negation().
Feature_Query_Condition * parse_feature_query_in_parens ()
Definition at line 1939 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Vectorized< T >::length(), Parser::lex(), Context::mem, Parser::parse_feature_query(), Parser::peek(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse_feature_query().
For * parse_for_directive ()
Definition at line 1771 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lexed, Context::mem, Sass::Util::normalize_underscores(), Parser::parse_block(), Parser::parse_expression(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse().
Function_Call * parse_function_call ()
Definition at line 1727 of file parser.cpp.
References Parser::ctx, Parser::lexed, Context::mem, Sass::Prelexer::name(), Parser::parse_arguments(), and ParserState::pstate().
Referenced by Parser::parse_factor().
Function_Call_Schema * parse_function_call_schema ()
Definition at line 1737 of file parser.cpp.
References Parser::ctx, Context::mem, Sass::Prelexer::name(), Parser::parse_arguments(), Parser::parse_identifier_schema(), and ParserState::pstate().
Referenced by Parser::parse_factor().
String * parse_identifier_schema ()
Definition at line 1662 of file parser.cpp.
References Parser::css_error(), Parser::ctx, Parser::end, Parser::error(), Parser::from_token(), Sass::Prelexer::identifier_schema(), Parser::lexed, Context::mem, p(), Parser::parse_list(), Parser::peek(), Parser::position, ParserState::pstate(), Sass::Prelexer::sequence(), and Sass::to_string.
Referenced by Parser::parse_declaration(), Parser::parse_factor(), Parser::parse_function_call_schema(), Parser::parse_media_expression(), and Parser::parse_media_query().
String * parse_ie_keyword_arg ()
Definition at line 1549 of file parser.cpp.
References Parser::ctx, Parser::lexed, Context::mem, Sass::Util::normalize_decimals(), Sass::Util::normalize_underscores(), Textual::NUMBER, Parser::parse_list(), and ParserState::pstate().
Referenced by Parser::parse_factor().
String * parse_ie_property ()
Definition at line 1496 of file parser.cpp.
References Parser::css_error(), Parser::ctx, Parser::error(), Parser::from_token(), Parser::lexed, Context::mem, Sass::normalize_wspace(), p(), Parser::parse_list(), Parser::peek(), Parser::position, ParserState::pstate(), and Sass::Prelexer::sequence().
Referenced by Parser::parse_factor().
If * parse_if_directive (bool else_if = false)
Definition at line 1746 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lex(), Context::mem, Parser::parse_block(), Parser::parse_list(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse().
Import * parse_import ()
Definition at line 281 of file parser.cpp.
References Context::c_importers, Parser::ctx, Parser::do_import(), Parser::error(), Sass::Prelexer::exactly(), Parser::import_single_file(), Parser::lex(), Parser::lex_css(), Parser::lexed, Context::mem, Parser::parse_interpolated_chunk(), Parser::parse_list(), Parser::parse_string(), Parser::peek(), Parser::position, ParserState::pstate(), and Sass::Prelexer::skip_over_scopes().
Referenced by Parser::parse().
String * parse_interpolated_chunk (Token chunk, bool constant = false)
Definition at line 1421 of file parser.cpp.
References Token::begin, Parser::css_error(), Parser::ctx, Token::end, Parser::error(), Parser::from_token(), Context::mem, p(), Parser::parse_list(), Parser::peek(), Parser::position, ParserState::pstate(), Sass::Prelexer::sequence(), and Token::to_string().
Referenced by Parser::parse_argument(), Parser::parse_calc_function(), Parser::parse_import(), Parser::parse_media_query(), and Parser::parse_string().
Expression * parse_list ()
Definition at line 1115 of file parser.cpp.
References Parser::parse_comma_list().
Referenced by Parser::parse_assignment(), Parser::parse_at_rule(), Parser::parse_calc_function(), Parser::parse_debug(), Parser::parse_declaration(), Parser::parse_each_directive(), Parser::parse_error(), Parser::parse_identifier_schema(), Parser::parse_ie_keyword_arg(), Parser::parse_ie_property(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_interpolated_chunk(), Parser::parse_map(), Parser::parse_media_expression(), Parser::parse_selector_schema(), Parser::parse_value_schema(), Parser::parse_warning(), and Parser::parse_while_directive().
Expression * parse_map ()
Definition at line 1056 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lex(), Parser::lex_css(), Context::mem, Context::names_to_colors, ParserState::offset, Parser::parse_list(), Parser::parse_space_list(), Parser::peek(), Parser::peek_css(), Parser::position, and ParserState::pstate().
Referenced by Parser::parse_factor().
Expression* parse_map_value ()
Media_Block * parse_media_block ()
Definition at line 1826 of file parser.cpp.
References Statement::block(), Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::last_media_block, Context::mem, Parser::parse_block(), Parser::parse_media_queries(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse().
Media_Query_Expression * parse_media_expression ()
Definition at line 1877 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lex(), Context::mem, Parser::parse_expression(), Parser::parse_identifier_schema(), Parser::parse_list(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse_media_query().
List * parse_media_queries ()
Definition at line 1845 of file parser.cpp.
References List::COMMA, Parser::ctx, Sass::Prelexer::exactly(), Parser::lex(), Context::mem, Parser::parse_media_query(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse_media_block().
Media_Query * parse_media_query ()
Definition at line 1854 of file parser.cpp.
References Parser::ctx, Parser::lex(), Parser::lexed, Context::mem, Parser::parse_identifier_schema(), Parser::parse_interpolated_chunk(), Parser::parse_media_expression(), and ParserState::pstate().
Referenced by Parser::parse_media_queries().
Mixin_Call * parse_mixin_call ()
Definition at line 383 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lexed, Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), Parser::parse_arguments(), Parser::parse_block(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse().
Wrapped_Selector * parse_negated_selector ()
Definition at line 732 of file parser.cpp.
bool parse_number_prefix ()
Definition at line 1041 of file parser.cpp.
References Parser::lex().
Referenced by Parser::parse_factor().
Expression * parse_operators (Expression * factor)
Definition at line 1285 of file parser.cpp.
References Token::begin, Binary_Expression::DIV, Parser::fold_operands(), Parser::lex_css(), Parser::lexed, Binary_Expression::MOD, Binary_Expression::MUL, and Parser::parse_factor().
Referenced by Parser::parse_term(), and Parser::parse_value_schema().
Parameter * parse_parameter ()
Definition at line 362 of file parser.cpp.
References Parser::ctx, Parser::lex(), Parser::lexed, Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), p(), Parser::parse_space_list(), ParserState::pos(), and ParserState::pstate().
Referenced by Parser::parse_parameters().
Parameters * parse_parameters ()
Definition at line 346 of file parser.cpp.
References Parser::after_token, Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Parser::lex_css(), Parser::lexed, Context::mem, Sass::Prelexer::name(), Parser::parse_parameter(), Parser::peek_css(), Parser::position, and ParserState::pstate().
Referenced by Sass::make_c_function(), Sass::make_native_function(), and Parser::parse_definition().
Simple_Selector * parse_pseudo_selector ()
Definition at line 744 of file parser.cpp.
Expression * parse_relation ()
Definition at line 1224 of file parser.cpp.
References Sass::Prelexer::alternatives(), Parser::ctx, Binary_Expression::EQ, Binary_Expression::GT, Binary_Expression::GTE, Sass::Prelexer::kwd_eq(), Sass::Prelexer::kwd_gt(), Sass::Prelexer::kwd_gte(), Sass::Prelexer::kwd_lt(), Sass::Prelexer::kwd_lte(), Sass::Prelexer::kwd_neq(), Binary_Expression::LT, Binary_Expression::LTE, Context::mem, Binary_Expression::NEQ, Parser::parse_expression(), Parser::peek(), and Parser::position.
Referenced by Parser::parse_conjunction().
Ruleset * parse_ruleset (Selector_Lookahead lookahead)
Definition at line 493 of file parser.cpp.
References Parser::ctx, Parser::error(), Sass::Prelexer::exactly(), Selector_Lookahead::found, Selector_Lookahead::has_interpolants, Parser::in_at_root, Context::mem, Parser::parse_block(), Parser::parse_selector_group(), Parser::parse_selector_schema(), Parser::peek(), and ParserState::pstate().
Referenced by Parser::parse(), and Parser::parse_at_root_block().
Selector_List * parse_selector (const char * src, Context & ctx, ParserState pstate = ParserState("[SELECTOR]")) [static]
Definition at line 43 of file parser.cpp.
References Parser::from_c_str(), p(), and Parser::parse_selector_group().
Referenced by Sass::Functions::BUILT_IN().
Complex_Selector * parse_selector_combination ()
Definition at line 604 of file parser.cpp.
References Sass::Prelexer::alternatives(), and Parser::peek_css().
Referenced by Parser::parse_selector_group().
Selector_List * parse_selector_group ()
Definition at line 548 of file parser.cpp.
References Sass::Prelexer::alternatives(), Complex_Selector::ANCESTOR_OF, Parser::block_stack, Parser::ctx, Sass::Prelexer::exactly(), Parser::in_at_root, Parser::last_media_block, Context::mem, Parser::parse_selector_combination(), Parser::peek(), Parser::peek_css(), Parser::peek_newline(), ParserState::pstate(), and Sass::to_string.
Referenced by Parser::parse_at_rule(), Parser::parse_ruleset(), Parser::parse_selector(), and Parser::parse_value().
Selector_Schema * parse_selector_schema (const char * end_of_selector)
Definition at line 514 of file parser.cpp.
References Parser::block_stack, Parser::css_error(), Parser::ctx, Sass::Prelexer::find_first_in_interval(), Parser::from_c_str(), Sass::Prelexer::interpolant(), Parser::last_media_block, Context::mem, Sass::Prelexer::optional_spaces(), p(), Parser::parse_list(), Parser::peek(), Parser::position, ParserState::pstate(), and Sass::Prelexer::sequence().
Referenced by Parser::parse_at_rule(), and Parser::parse_ruleset().
Simple_Selector * parse_simple_selector ()
Definition at line 698 of file parser.cpp.
Compound_Selector * parse_simple_selector_sequence ()
Definition at line 651 of file parser.cpp.
Expression * parse_space_list ()
Definition at line 1158 of file parser.cpp.
References Sass::Prelexer::alternatives(), Parser::ctx, Sass::Prelexer::default_flag(), Parser::end, Sass::Prelexer::exactly(), Sass::Prelexer::global_flag(), Context::mem, Parser::parse_disjunction(), Parser::peek_css(), Parser::position, ParserState::pstate(), and List::SPACE.
Referenced by Parser::parse_argument(), Parser::parse_comma_list(), Parser::parse_map(), and Parser::parse_parameter().
String_Constant * parse_static_expression ()
Definition at line 1469 of file parser.cpp.
References Sass::Prelexer::number(), Parser::parse_static_value(), Parser::peek(), and Sass::Prelexer::sequence().
Referenced by Parser::parse_value_schema().
String_Constant * parse_static_value ()
Definition at line 1477 of file parser.cpp.
References Parser::ctx, Parser::lexed, Context::mem, Parser::position, and ParserState::pstate().
Referenced by Parser::parse_declaration(), and Parser::parse_static_expression().
String * parse_string ()
Definition at line 1489 of file parser.cpp.
References Parser::lexed, Parser::parse_interpolated_chunk(), and ParserState::token.
Referenced by Parser::parse_import(), and Parser::parse_value().
Feature_Query_Condition * parse_supports_conjunction ()
Definition at line 1961 of file parser.cpp.
References Feature_Query_Condition::AND, and Parser::parse_feature_query().
Referenced by Parser::parse_feature_query().
Feature_Query_Condition * parse_supports_declaration ()
Definition at line 1981 of file parser.cpp.
References Parser::ctx, Context::mem, and Parser::parse_declaration().
Referenced by Parser::parse_feature_query().
Feature_Query_Condition * parse_supports_disjunction ()
Definition at line 1971 of file parser.cpp.
References Feature_Query_Condition::OR, and Parser::parse_feature_query().
Referenced by Parser::parse_feature_query().
Feature_Query_Condition * parse_supports_negation ()
Definition at line 1951 of file parser.cpp.
References Feature_Query_Condition::NOT, and Parser::parse_feature_query().
Referenced by Parser::parse_feature_query().
Expression * parse_term ()
Definition at line 1272 of file parser.cpp.
References Parser::parse_factor(), Parser::parse_operators(), Parser::peek(), Parser::peek_css(), Parser::position, and Expression::STRING.
Referenced by Parser::parse_expression().
Expression * parse_value ()
Definition at line 1359 of file parser.cpp.
References Parser::ctx, Textual::DIMENSION, Sass::Prelexer::dimension(), Parser::error(), Textual::HEX, Parser::lex(), Parser::lexed, Context::mem, Context::names_to_colors, Sass::Util::normalize_underscores(), Nan::Null(), Textual::NUMBER, Sass::Prelexer::optional(), Parser::parse_selector_group(), Parser::parse_string(), Parser::parse_value_schema(), Textual::PERCENTAGE, ParserState::pstate(), Sass::Prelexer::sequence(), Token::to_string(), and Sass::unquote().
Referenced by Parser::parse_factor().
String_Schema * parse_value_schema (const char * stop)
Definition at line 1566 of file parser.cpp.
References Token::begin, Parser::css_error(), Parser::ctx, Textual::DIMENSION, Token::end, Parser::error(), Sass::Prelexer::exactly(), Parser::from_token(), Textual::HEX, Parser::lex(), Parser::lexed, Context::mem, Sass::Util::normalize_underscores(), Textual::NUMBER, p(), Parser::parse_factor(), Parser::parse_list(), Parser::parse_operators(), Parser::parse_static_expression(), Parser::peek(), Textual::PERCENTAGE, Parser::position, ParserState::pstate(), and Sass::unquote().
Referenced by Parser::parse_assignment(), Parser::parse_declaration(), and Parser::parse_value().
Warning * parse_warning ()
Definition at line 2067 of file parser.cpp.
References Parser::ctx, Context::mem, Parser::parse_list(), and ParserState::pstate().
Referenced by Parser::parse().
While * parse_while_directive ()
Definition at line 1816 of file parser.cpp.
References Parser::ctx, Context::mem, Parser::parse_block(), Parser::parse_list(), and ParserState::pstate().
Referenced by Parser::parse().
const char* peek (const char * start = 0) [inline]
Definition at line 108 of file parser.hpp.
Referenced by Parser::lookahead_for_selector(), Parser::parse(), Parser::parse_at_root_block(), Parser::parse_at_root_expression(), Parser::parse_at_rule(), Parser::parse_declaration(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_expression(), Parser::parse_factor(), Parser::parse_feature_block(), Parser::parse_feature_queries(), Parser::parse_feature_query(), Parser::parse_feature_query_in_parens(), Parser::parse_for_directive(), Parser::parse_identifier_schema(), Parser::parse_ie_property(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_interpolated_chunk(), Parser::parse_map(), Parser::parse_media_block(), Parser::parse_media_expression(), Parser::parse_media_queries(), Parser::parse_mixin_call(), Parser::parse_relation(), Parser::parse_ruleset(), Parser::parse_selector_group(), Parser::parse_selector_schema(), Parser::parse_static_expression(), Parser::parse_term(), and Parser::parse_value_schema().
const char* peek_css (const char * start = 0) [inline]
Definition at line 185 of file parser.hpp.
Referenced by Parser::parse_argument(), Parser::parse_arguments(), Parser::parse_comma_list(), Parser::parse_declaration(), Parser::parse_map(), Parser::parse_parameters(), Parser::parse_selector_combination(), Parser::parse_selector_group(), Parser::parse_space_list(), and Parser::parse_term().
bool peek_newline (const char * start = 0)
Definition at line 51 of file parser.cpp.
References Sass::peek_linefeed(), and Parser::position.
Referenced by Parser::parse_selector_group().
void read_bom ()
Definition at line 2260 of file parser.cpp.
Referenced by Parser::parse().
const char* sneak (const char * start = 0) [inline]
Definition at line 80 of file parser.hpp.
References Sass::Prelexer::css_comments(), Sass::Prelexer::css_whitespace(), Sass::Prelexer::no_spaces(), Sass::Prelexer::optional_css_comments(), Sass::Prelexer::optional_css_whitespace(), Sass::Prelexer::optional_spaces(), ParserState::pos(), Parser::position, and Sass::Prelexer::spaces().
void throw_read_error (string message, size_t ln = 0)
void throw_syntax_error (string message, size_t ln = 0)
Field Documentation
Position after_token
Definition at line 43 of file parser.hpp.
Referenced by Parser::lex(), Parser::parse(), Parser::parse_arguments(), and Parser::parse_parameters().
Position before_token
Definition at line 42 of file parser.hpp.
Referenced by Parser::lex().
vector<Block*> block_stack
Definition at line 36 of file parser.hpp.
Referenced by Parser::from_c_str(), Parser::from_token(), Parser::parse(), Parser::parse_selector_group(), and Parser::parse_selector_schema().
Context& ctx
Definition at line 35 of file parser.hpp.
Referenced by Parser::add_single_file(), Parser::do_import(), Parser::import_single_file(), Parser::parse(), Parser::parse_argument(), Parser::parse_arguments(), Parser::parse_assignment(), Parser::parse_at_root_block(), Parser::parse_at_root_expression(), Parser::parse_at_rule(), Parser::parse_calc_function(), Parser::parse_comma_list(), Parser::parse_debug(), Parser::parse_declaration(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_error(), Parser::parse_factor(), Parser::parse_feature_block(), Parser::parse_feature_queries(), Parser::parse_feature_query_in_parens(), Parser::parse_for_directive(), Parser::parse_function_call(), Parser::parse_function_call_schema(), Parser::parse_identifier_schema(), Parser::parse_ie_keyword_arg(), Parser::parse_ie_property(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_interpolated_chunk(), Parser::parse_map(), Parser::parse_media_block(), Parser::parse_media_expression(), Parser::parse_media_queries(), Parser::parse_media_query(), Parser::parse_mixin_call(), Parser::parse_parameter(), Parser::parse_parameters(), Parser::parse_relation(), Parser::parse_ruleset(), Parser::parse_selector_group(), Parser::parse_selector_schema(), Parser::parse_space_list(), Parser::parse_static_value(), Parser::parse_supports_declaration(), Parser::parse_value(), Parser::parse_value_schema(), Parser::parse_warning(), and Parser::parse_while_directive().
const char* end
Definition at line 41 of file parser.hpp.
Referenced by Parser::from_c_str(), Parser::from_token(), Parser::parse(), Parser::parse_identifier_schema(), and Parser::parse_space_list().
bool in_at_root
Definition at line 49 of file parser.hpp.
Referenced by Parser::parse_at_root_block(), Parser::parse_ruleset(), Parser::parse_selector_group(), and Parser::Parser().
int indentation
Definition at line 45 of file parser.hpp.
Media_Block* last_media_block
Definition at line 38 of file parser.hpp.
Referenced by Parser::parse_media_block(), Parser::parse_selector_group(), and Parser::parse_selector_schema().
Token lexed
Definition at line 48 of file parser.hpp.
Referenced by Parser::lex(), Parser::lex_css(), Sass::make_c_function(), Sass::make_native_function(), Parser::parse_argument(), Parser::parse_arguments(), Parser::parse_assignment(), Parser::parse_at_rule(), Parser::parse_calc_function(), Parser::parse_declaration(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_expression(), Parser::parse_for_directive(), Parser::parse_function_call(), Parser::parse_identifier_schema(), Parser::parse_ie_keyword_arg(), Parser::parse_ie_property(), Parser::parse_import(), Parser::parse_media_query(), Parser::parse_mixin_call(), Parser::parse_operators(), Parser::parse_parameter(), Parser::parse_parameters(), Parser::parse_static_value(), Parser::parse_string(), Parser::parse_value(), and Parser::parse_value_schema().
const char* position
Definition at line 40 of file parser.hpp.
Referenced by Parser::from_c_str(), Parser::from_token(), Parser::lex(), Parser::lookahead_for_selector(), Parser::parse(), Parser::parse_arguments(), Parser::parse_assignment(), Parser::parse_at_root_block(), Parser::parse_at_rule(), Parser::parse_calc_function(), Parser::parse_comma_list(), Parser::parse_declaration(), Parser::parse_expression(), Parser::parse_feature_queries(), Parser::parse_feature_query(), Parser::parse_feature_query_in_parens(), Parser::parse_identifier_schema(), Parser::parse_ie_property(), Parser::parse_import(), Parser::parse_interpolated_chunk(), Parser::parse_map(), Parser::parse_parameters(), Parser::parse_relation(), Parser::parse_selector_schema(), Parser::parse_space_list(), Parser::parse_static_value(), Parser::parse_term(), Parser::parse_value_schema(), Parser::peek_newline(), and Parser::sneak().
ParserState pstate
Definition at line 44 of file parser.hpp.
const char* source
Definition at line 39 of file parser.hpp.
Referenced by Parser::do_import(), Parser::from_c_str(), Parser::from_token(), and Parser::lex().
vector<Syntactic_Context> stack
Definition at line 37 of file parser.hpp.
Referenced by Parser::parse_definition(), and Parser::Parser().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/parser.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/parser.cpp