Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/json.hpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/json.hpp File Reference
#include <stdbool.h>
#include <stddef.h>
Data Structures
struct JsonNode
Defines
#define json_foreach(i, object_or_array)
Typedefs
typedef struct JsonNode JsonNode
Enumerations
enum JsonTag {
JSON_NULL, JSON_BOOL, JSON_STRING, JSON_NUMBER,
JSON_ARRAY, JSON_OBJECT
}
Functions
JsonNode * json_decode (const char *json)
char * json_encode (const JsonNode *node)
char * json_encode_string (const char *str)
char * json_stringify (const JsonNode *node, const char *space)
void json_delete (JsonNode *node)
bool json_validate (const char *json)
JsonNode * json_find_element (JsonNode *array, int index)
JsonNode * json_find_member (JsonNode *object, const char *key)
JsonNode * json_first_child (const JsonNode *node)
JsonNode * json_mknull (void)
JsonNode * json_mkbool (bool b)
JsonNode * json_mkstring (const char *s)
JsonNode * json_mknumber (double n)
JsonNode * json_mkarray (void)
JsonNode * json_mkobject (void)
void json_append_element (JsonNode *array, JsonNode *element)
void json_prepend_element (JsonNode *array, JsonNode *element)
void json_append_member (JsonNode *object, const char *key, JsonNode *value)
void json_prepend_member (JsonNode *object, const char *key, JsonNode *value)
void json_remove_from_parent (JsonNode *node)
bool json_check (const JsonNode *node, char errmsg[256])
Define Documentation
#define json_foreach (i, object_or_array)
Value:
for ((i) = json_first_child(object_or_array);   \
     (i) != NULL;                               \
     (i) = (i)->next)
Definition at line 86 of file json.hpp.
Referenced by emit_array(), emit_object(), json_find_element(), and json_find_member().
Typedef Documentation
typedef struct JsonNode JsonNode
Definition at line 39 of file json.hpp.
Enumeration Type Documentation
enum JsonTag
Enumerator:
JSON_NULL
JSON_BOOL
JSON_STRING
JSON_NUMBER
JSON_ARRAY
JSON_OBJECT
Definition at line 30 of file json.hpp.
Function Documentation
void json_append_element (JsonNode * array, JsonNode * element)
Definition at line 595 of file json.cpp.
References append_node(), JSON_ARRAY, JsonNode::parent, and JsonNode::tag.
Referenced by SourceMap::generate_source_map(), and parse_array().
void json_append_member (JsonNode * object, const char * key, JsonNode * value)
Definition at line 611 of file json.cpp.
References append_member(), JSON_OBJECT, json_strdup(), JsonNode::parent, and JsonNode::tag.
Referenced by SourceMap::generate_source_map(), and handle_errors().
bool json_check (const JsonNode * node, char errmsg[256])
Definition at line 1340 of file json.cpp.
References JsonNode::bool_, JsonNode::children, JSON_ARRAY, JSON_BOOL, json_check(), JSON_OBJECT, JSON_STRING, JsonNode::key, JsonNode::next, JsonNode::prev, problem, JsonNode::string_, JsonNode::tag, tag_is_valid(), and utf8_validate().
Referenced by json_check().
JsonNode* json_decode (const char * json)
Definition at line 388 of file json.cpp.
References json_delete(), parse_value(), s(), and skip_space().
void json_delete (JsonNode * node)
Definition at line 434 of file json.cpp.
References JsonNode::children, JSON_ARRAY, json_delete(), JSON_OBJECT, json_remove_from_parent(), JSON_STRING, JsonNode::next, utf8::unchecked::next(), JsonNode::string_, and JsonNode::tag.
Referenced by SourceMap::generate_source_map(), handle_errors(), json_decode(), json_delete(), parse_array(), and parse_object().
char* json_encode (const JsonNode * node)
Definition at line 406 of file json.cpp.
References json_stringify().
char* json_encode_string (const char * str)
Definition at line 411 of file json.cpp.
References emit_string(), sb_finish(), and sb_init().
JsonNode* json_find_element (JsonNode * array, int index)
Definition at line 475 of file json.cpp.
References JSON_ARRAY, json_foreach, and JsonNode::tag.
JsonNode* json_find_member (JsonNode * object, const char * key)
Definition at line 492 of file json.cpp.
References json_foreach, JSON_OBJECT, JsonNode::key, and JsonNode::tag.
JsonNode* json_first_child (const JsonNode * node)
Definition at line 506 of file json.cpp.
References JsonNode::children, JSON_ARRAY, JSON_OBJECT, and JsonNode::tag.
JsonNode* json_mkarray (void)
Definition at line 553 of file json.cpp.
References JSON_ARRAY, and mknode().
Referenced by SourceMap::generate_source_map(), and parse_array().
JsonNode* json_mkbool (bool b)
Definition at line 527 of file json.cpp.
References JsonNode::bool_, JSON_BOOL, and mknode().
Referenced by parse_value().
JsonNode* json_mknull (void)
Definition at line 522 of file json.cpp.
References JSON_NULL, and mknode().
Referenced by parse_value().
JsonNode* json_mknumber (double n)
Definition at line 546 of file json.cpp.
References JSON_NUMBER, mknode(), and JsonNode::number_.
Referenced by SourceMap::generate_source_map(), handle_errors(), and parse_value().
JsonNode* json_mkobject (void)
Definition at line 558 of file json.cpp.
References JSON_OBJECT, and mknode().
Referenced by SourceMap::generate_source_map(), handle_errors(), and parse_object().
JsonNode* json_mkstring (const char * s)
Definition at line 541 of file json.cpp.
References json_strdup(), and mkstring().
Referenced by SourceMap::generate_source_map(), and handle_errors().
void json_prepend_element (JsonNode * array, JsonNode * element)
Definition at line 603 of file json.cpp.
References JSON_ARRAY, JsonNode::parent, prepend_node(), and JsonNode::tag.
void json_prepend_member (JsonNode * object, const char * key, JsonNode * value)
Definition at line 619 of file json.cpp.
References JSON_OBJECT, json_strdup(), JsonNode::key, JsonNode::parent, prepend_node(), and JsonNode::tag.
void json_remove_from_parent (JsonNode * node)
Definition at line 628 of file json.cpp.
References JsonNode::children, JsonNode::key, JsonNode::next, JsonNode::parent, and JsonNode::prev.
Referenced by json_delete().
char* json_stringify (const JsonNode * node, const char * space)
Definition at line 421 of file json.cpp.
References emit_value(), emit_value_indented(), sb_finish(), and sb_init().
Referenced by SourceMap::generate_source_map(), handle_errors(), and json_encode().
bool json_validate (const char * json)
Definition at line 460 of file json.cpp.
References parse_value(), s(), and skip_space().