Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_context.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_context.h File Reference
#include <stddef.h>
#include <stdbool.h>
#include "sass.h"
Enumerations
enum Sass_Compiler_State { SASS_COMPILER_CREATED, SASS_COMPILER_PARSED, SASS_COMPILER_EXECUTED }
Functions
ADDAPI struct Sass_Options *ADDCALL sass_make_options (void)
ADDAPI struct
Sass_File_Context *ADDCALL sass_make_file_context (const char *input_path)
ADDAPI struct
Sass_Data_Context *ADDCALL sass_make_data_context (char *source_string)
ADDAPI int ADDCALL sass_compile_file_context (struct Sass_File_Context *ctx)
ADDAPI int ADDCALL sass_compile_data_context (struct Sass_Data_Context *ctx)
ADDAPI struct Sass_Compiler
*ADDCALL sass_make_file_compiler (struct Sass_File_Context *file_ctx)
ADDAPI struct Sass_Compiler
*ADDCALL sass_make_data_compiler (struct Sass_Data_Context *data_ctx)
ADDAPI int ADDCALL sass_compiler_parse (struct Sass_Compiler *compiler)
ADDAPI int ADDCALL sass_compiler_execute (struct Sass_Compiler *compiler)
ADDAPI void ADDCALL sass_delete_compiler (struct Sass_Compiler *compiler)
ADDAPI void ADDCALL sass_delete_file_context (struct Sass_File_Context *ctx)
ADDAPI void ADDCALL sass_delete_data_context (struct Sass_Data_Context *ctx)
ADDAPI struct Sass_Context *ADDCALL sass_file_context_get_context (struct Sass_File_Context *file_ctx)
ADDAPI struct Sass_Context *ADDCALL sass_data_context_get_context (struct Sass_Data_Context *data_ctx)
ADDAPI struct Sass_Options *ADDCALL sass_context_get_options (struct Sass_Context *ctx)
ADDAPI struct Sass_Options *ADDCALL sass_file_context_get_options (struct Sass_File_Context *file_ctx)
ADDAPI struct Sass_Options *ADDCALL sass_data_context_get_options (struct Sass_Data_Context *data_ctx)
ADDAPI void ADDCALL sass_file_context_set_options (struct Sass_File_Context *file_ctx, struct Sass_Options *opt)
ADDAPI void ADDCALL sass_data_context_set_options (struct Sass_Data_Context *data_ctx, struct Sass_Options *opt)
ADDAPI int ADDCALL sass_option_get_precision (struct Sass_Options *options)
ADDAPI enum Sass_Output_Style
ADDCALL sass_option_get_output_style (struct Sass_Options *options)
ADDAPI bool ADDCALL sass_option_get_source_comments (struct Sass_Options *options)
ADDAPI bool ADDCALL sass_option_get_source_map_embed (struct Sass_Options *options)
ADDAPI bool ADDCALL sass_option_get_source_map_contents (struct Sass_Options *options)
ADDAPI bool ADDCALL sass_option_get_omit_source_map_url (struct Sass_Options *options)
ADDAPI bool ADDCALL sass_option_get_is_indented_syntax_src (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_indent (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_linefeed (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_input_path (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_output_path (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_plugin_path (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_include_path (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_source_map_file (struct Sass_Options *options)
ADDAPI const char *ADDCALL sass_option_get_source_map_root (struct Sass_Options *options)
ADDAPI Sass_Importer_List ADDCALL sass_option_get_c_headers (struct Sass_Options *options)
ADDAPI Sass_Importer_List ADDCALL sass_option_get_c_importers (struct Sass_Options *options)
ADDAPI Sass_Function_List ADDCALL sass_option_get_c_functions (struct Sass_Options *options)
ADDAPI void ADDCALL sass_option_set_precision (struct Sass_Options *options, int precision)
ADDAPI void ADDCALL sass_option_set_output_style (struct Sass_Options *options, enum Sass_Output_Style output_style)
ADDAPI void ADDCALL sass_option_set_source_comments (struct Sass_Options *options, bool source_comments)
ADDAPI void ADDCALL sass_option_set_source_map_embed (struct Sass_Options *options, bool source_map_embed)
ADDAPI void ADDCALL sass_option_set_source_map_contents (struct Sass_Options *options, bool source_map_contents)
ADDAPI void ADDCALL sass_option_set_omit_source_map_url (struct Sass_Options *options, bool omit_source_map_url)
ADDAPI void ADDCALL sass_option_set_is_indented_syntax_src (struct Sass_Options *options, bool is_indented_syntax_src)
ADDAPI void ADDCALL sass_option_set_indent (struct Sass_Options *options, const char *indent)
ADDAPI void ADDCALL sass_option_set_linefeed (struct Sass_Options *options, const char *linefeed)
ADDAPI void ADDCALL sass_option_set_input_path (struct Sass_Options *options, const char *input_path)
ADDAPI void ADDCALL sass_option_set_output_path (struct Sass_Options *options, const char *output_path)
ADDAPI void ADDCALL sass_option_set_plugin_path (struct Sass_Options *options, const char *plugin_path)
ADDAPI void ADDCALL sass_option_set_include_path (struct Sass_Options *options, const char *include_path)
ADDAPI void ADDCALL sass_option_set_source_map_file (struct Sass_Options *options, const char *source_map_file)
ADDAPI void ADDCALL sass_option_set_source_map_root (struct Sass_Options *options, const char *source_map_root)
ADDAPI void ADDCALL sass_option_set_c_headers (struct Sass_Options *options, Sass_Importer_List c_headers)
ADDAPI void ADDCALL sass_option_set_c_importers (struct Sass_Options *options, Sass_Importer_List c_importers)
ADDAPI void ADDCALL sass_option_set_c_functions (struct Sass_Options *options, Sass_Function_List c_functions)
ADDAPI const char *ADDCALL sass_context_get_output_string (struct Sass_Context *ctx)
ADDAPI int ADDCALL sass_context_get_error_status (struct Sass_Context *ctx)
ADDAPI const char *ADDCALL sass_context_get_error_json (struct Sass_Context *ctx)
ADDAPI const char *ADDCALL sass_context_get_error_text (struct Sass_Context *ctx)
ADDAPI const char *ADDCALL sass_context_get_error_message (struct Sass_Context *ctx)
ADDAPI const char *ADDCALL sass_context_get_error_file (struct Sass_Context *ctx)
ADDAPI const char *ADDCALL sass_context_get_error_src (struct Sass_Context *ctx)
ADDAPI size_t ADDCALL sass_context_get_error_line (struct Sass_Context *ctx)
ADDAPI size_t ADDCALL sass_context_get_error_column (struct Sass_Context *ctx)
ADDAPI const char *ADDCALL sass_context_get_source_map_string (struct Sass_Context *ctx)
ADDAPI char **ADDCALL sass_context_get_included_files (struct Sass_Context *ctx)
ADDAPI size_t ADDCALL sass_context_get_included_files_size (struct Sass_Context *ctx)
ADDAPI char *ADDCALL sass_context_take_error_json (struct Sass_Context *ctx)
ADDAPI char *ADDCALL sass_context_take_error_text (struct Sass_Context *ctx)
ADDAPI char *ADDCALL sass_context_take_error_message (struct Sass_Context *ctx)
ADDAPI char *ADDCALL sass_context_take_error_file (struct Sass_Context *ctx)
ADDAPI char *ADDCALL sass_context_take_output_string (struct Sass_Context *ctx)
ADDAPI char *ADDCALL sass_context_take_source_map_string (struct Sass_Context *ctx)
ADDAPI char **ADDCALL sass_context_take_included_files (struct Sass_Context *ctx)
ADDAPI enum
Sass_Compiler_State ADDCALL sass_compiler_get_state (struct Sass_Compiler *compiler)
ADDAPI struct Sass_Context *ADDCALL sass_compiler_get_context (struct Sass_Compiler *compiler)
ADDAPI size_t ADDCALL sass_compiler_get_import_stack_size (struct Sass_Compiler *compiler)
ADDAPI Sass_Import_Entry ADDCALL sass_compiler_get_last_import (struct Sass_Compiler *compiler)
ADDAPI Sass_Import_Entry ADDCALL sass_compiler_get_import_entry (struct Sass_Compiler *compiler, size_t idx)
ADDAPI void ADDCALL sass_option_push_plugin_path (struct Sass_Options *options, const char *path)
ADDAPI void ADDCALL sass_option_push_include_path (struct Sass_Options *options, const char *path)
Enumeration Type Documentation
enum Sass_Compiler_State
Enumerator:
SASS_COMPILER_CREATED
SASS_COMPILER_PARSED
SASS_COMPILER_EXECUTED
Definition at line 23 of file sass_context.h.
Function Documentation
ADDAPI int ADDCALL sass_compile_data_context (struct Sass_Data_Context * ctx)
Definition at line 610 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Sass_Context::error_status, handle_errors(), sass_compile_context(), and Sass_Data_Context::source_string.
Referenced by compile_data().
ADDAPI int ADDCALL sass_compile_file_context (struct Sass_File_Context * ctx)
Definition at line 626 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Sass_Context::error_status, handle_errors(), Sass_Options::input_path, and sass_compile_context().
Referenced by compile_file().
ADDAPI int ADDCALL sass_compiler_execute (struct Sass_Compiler * compiler)
Definition at line 657 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Context::compile_block(), Sass_Compiler::cpp_ctx, Sass_Context::error_status, Context::generate_source_map(), handle_errors(), Sass_Context::output_string, Sass_Compiler::root, SASS_COMPILER_EXECUTED, SASS_COMPILER_PARSED, Sass_Context::source_map_string, and Sass_Compiler::state.
Referenced by sass_compile_context().
ADDAPI struct Sass_Context* ADDCALL sass_compiler_get_context (struct Sass_Compiler * compiler) [read]
Definition at line 806 of file sass_context.cpp.
References Sass_Compiler::c_ctx.
ADDAPI Sass_Import_Entry ADDCALL sass_compiler_get_import_entry (struct Sass_Compiler * compiler, size_t idx)
Definition at line 810 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx, and Context::import_stack.
ADDAPI size_t ADDCALL sass_compiler_get_import_stack_size (struct Sass_Compiler * compiler)
Definition at line 808 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx, and Context::import_stack.
ADDAPI Sass_Import_Entry ADDCALL sass_compiler_get_last_import (struct Sass_Compiler * compiler)
Definition at line 809 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx, and Context::import_stack.
Referenced by sass_importer().
ADDAPI enum Sass_Compiler_State ADDCALL sass_compiler_get_state (struct Sass_Compiler * compiler)
Definition at line 805 of file sass_context.cpp.
References Sass_Compiler::state.
ADDAPI int ADDCALL sass_compiler_parse (struct Sass_Compiler * compiler)
Definition at line 642 of file sass_context.cpp.
References Sass_Compiler::c_ctx, Sass_Compiler::cpp_ctx, Sass_Context::error_status, Sass_Compiler::root, SASS_COMPILER_CREATED, SASS_COMPILER_PARSED, sass_parse_block(), and Sass_Compiler::state.
Referenced by sass_compile_context().
ADDAPI size_t ADDCALL sass_context_get_error_column (struct Sass_Context * ctx)
ADDAPI const char* ADDCALL sass_context_get_error_file (struct Sass_Context * ctx)
ADDAPI const char* ADDCALL sass_context_get_error_json (struct Sass_Context * ctx)
Referenced by GetResult(), and MakeCallback().
ADDAPI size_t ADDCALL sass_context_get_error_line (struct Sass_Context * ctx)
ADDAPI const char* ADDCALL sass_context_get_error_message (struct Sass_Context * ctx)
ADDAPI const char* ADDCALL sass_context_get_error_src (struct Sass_Context * ctx)
ADDAPI int ADDCALL sass_context_get_error_status (struct Sass_Context * ctx)
Referenced by GetResult().
ADDAPI const char* ADDCALL sass_context_get_error_text (struct Sass_Context * ctx)
ADDAPI char** ADDCALL sass_context_get_included_files (struct Sass_Context * ctx)
Referenced by GetStats().
ADDAPI size_t ADDCALL sass_context_get_included_files_size (struct Sass_Context * ctx)
Definition at line 813 of file sass_context.cpp.
References Sass_Context::included_files, and l().
ADDAPI struct Sass_Options* ADDCALL sass_context_get_options (struct Sass_Context * ctx) [read]
Definition at line 798 of file sass_context.cpp.
Referenced by ExtractOptions().
ADDAPI const char* ADDCALL sass_context_get_output_string (struct Sass_Context * ctx)
Referenced by GetResult().
ADDAPI const char* ADDCALL sass_context_get_source_map_string (struct Sass_Context * ctx)
Referenced by GetResult().
ADDAPI char* ADDCALL sass_context_take_error_file (struct Sass_Context * ctx)
ADDAPI char* ADDCALL sass_context_take_error_json (struct Sass_Context * ctx)
ADDAPI char* ADDCALL sass_context_take_error_message (struct Sass_Context * ctx)
ADDAPI char* ADDCALL sass_context_take_error_text (struct Sass_Context * ctx)
ADDAPI char** ADDCALL sass_context_take_included_files (struct Sass_Context * ctx)
ADDAPI char* ADDCALL sass_context_take_output_string (struct Sass_Context * ctx)
ADDAPI char* ADDCALL sass_context_take_source_map_string (struct Sass_Context * ctx)
ADDAPI struct Sass_Context* ADDCALL sass_data_context_get_context (struct Sass_Data_Context * data_ctx) [read]
Definition at line 795 of file sass_context.cpp.
Referenced by ExtractOptions(), MakeCallback(), and NAN_METHOD().
ADDAPI struct Sass_Options* ADDCALL sass_data_context_get_options (struct Sass_Data_Context * data_ctx) [read]
Definition at line 800 of file sass_context.cpp.
ADDAPI void ADDCALL sass_data_context_set_options (struct Sass_Data_Context * data_ctx, struct Sass_Options * opt)
Definition at line 802 of file sass_context.cpp.
References copy_options().
ADDAPI void ADDCALL sass_delete_compiler (struct Sass_Compiler * compiler)
Definition at line 780 of file sass_context.cpp.
References Sass_Compiler::cpp_ctx.
Referenced by sass_compile_context().
ADDAPI void ADDCALL sass_delete_data_context (struct Sass_Data_Context * ctx)
Definition at line 791 of file sass_context.cpp.
References sass_clear_context().
Referenced by sass_free_context_wrapper().
ADDAPI void ADDCALL sass_delete_file_context (struct Sass_File_Context * ctx)
Definition at line 790 of file sass_context.cpp.
References sass_clear_context().
Referenced by sass_free_context_wrapper().
ADDAPI struct Sass_Context* ADDCALL sass_file_context_get_context (struct Sass_File_Context * file_ctx) [read]
Definition at line 794 of file sass_context.cpp.
Referenced by ExtractOptions(), MakeCallback(), and NAN_METHOD().
ADDAPI struct Sass_Options* ADDCALL sass_file_context_get_options (struct Sass_File_Context * file_ctx) [read]
Definition at line 799 of file sass_context.cpp.
ADDAPI void ADDCALL sass_file_context_set_options (struct Sass_File_Context * file_ctx, struct Sass_Options * opt)
Definition at line 801 of file sass_context.cpp.
References copy_options().
ADDAPI struct Sass_Compiler* ADDCALL sass_make_data_compiler (struct Sass_Data_Context * data_ctx) [read]
Definition at line 602 of file sass_context.cpp.
References sass_prepare_context(), and Sass_Data_Context::source_string.
ADDAPI struct Sass_Data_Context* ADDCALL sass_make_data_context (char * source_string) [read]
Definition at line 578 of file sass_context.cpp.
References ctx, handle_errors(), init_options(), SASS_CONTEXT_DATA, Sass_Data_Context::source_string, and Sass_Context::type.
Referenced by NAN_METHOD().
ADDAPI struct Sass_Compiler* ADDCALL sass_make_file_compiler (struct Sass_File_Context * file_ctx) [read]
Definition at line 594 of file sass_context.cpp.
References Sass_Options::input_path, and sass_prepare_context().
ADDAPI struct Sass_File_Context* ADDCALL sass_make_file_context (const char * input_path) [read]
Definition at line 562 of file sass_context.cpp.
References ctx, handle_errors(), init_options(), SASS_CONTEXT_FILE, sass_option_set_input_path(), and Sass_Context::type.
Referenced by NAN_METHOD().
ADDAPI struct Sass_Options* ADDCALL sass_make_options (void) [read]
Definition at line 554 of file sass_context.cpp.
References init_options().
ADDAPI Sass_Function_List ADDCALL sass_option_get_c_functions (struct Sass_Options * options)
ADDAPI Sass_Importer_List ADDCALL sass_option_get_c_headers (struct Sass_Options * options)
ADDAPI Sass_Importer_List ADDCALL sass_option_get_c_importers (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_include_path (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_indent (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_input_path (struct Sass_Options * options)
ADDAPI bool ADDCALL sass_option_get_is_indented_syntax_src (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_linefeed (struct Sass_Options * options)
ADDAPI bool ADDCALL sass_option_get_omit_source_map_url (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_output_path (struct Sass_Options * options)
ADDAPI enum Sass_Output_Style ADDCALL sass_option_get_output_style (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_plugin_path (struct Sass_Options * options)
ADDAPI int ADDCALL sass_option_get_precision (struct Sass_Options * options)
ADDAPI bool ADDCALL sass_option_get_source_comments (struct Sass_Options * options)
ADDAPI bool ADDCALL sass_option_get_source_map_contents (struct Sass_Options * options)
ADDAPI bool ADDCALL sass_option_get_source_map_embed (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_source_map_file (struct Sass_Options * options)
ADDAPI const char* ADDCALL sass_option_get_source_map_root (struct Sass_Options * options)
ADDAPI void ADDCALL sass_option_push_include_path (struct Sass_Options * options, const char * path)
Definition at line 859 of file sass_context.cpp.
References Sass_Options::include_paths, string_list::next, Sass::sass_strdup(), and string_list::string.
ADDAPI void ADDCALL sass_option_push_plugin_path (struct Sass_Options * options, const char * path)
Definition at line 877 of file sass_context.cpp.
References string_list::next, Sass_Options::plugin_paths, Sass::sass_strdup(), and string_list::string.
ADDAPI void ADDCALL sass_option_set_c_functions (struct Sass_Options * options, Sass_Function_List c_functions)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_c_headers (struct Sass_Options * options, Sass_Importer_List c_headers)
ADDAPI void ADDCALL sass_option_set_c_importers (struct Sass_Options * options, Sass_Importer_List c_importers)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_include_path (struct Sass_Options * options, const char * include_path)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_indent (struct Sass_Options * options, const char * indent)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_input_path (struct Sass_Options * options, const char * input_path)
Referenced by ExtractOptions(), and sass_make_file_context().
ADDAPI void ADDCALL sass_option_set_is_indented_syntax_src (struct Sass_Options * options, bool is_indented_syntax_src)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_linefeed (struct Sass_Options * options, const char * linefeed)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_omit_source_map_url (struct Sass_Options * options, bool omit_source_map_url)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_output_path (struct Sass_Options * options, const char * output_path)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_output_style (struct Sass_Options * options, enum Sass_Output_Style output_style)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_plugin_path (struct Sass_Options * options, const char * plugin_path)
ADDAPI void ADDCALL sass_option_set_precision (struct Sass_Options * options, int precision)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_source_comments (struct Sass_Options * options, bool source_comments)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_source_map_contents (struct Sass_Options * options, bool source_map_contents)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_source_map_embed (struct Sass_Options * options, bool source_map_embed)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_source_map_file (struct Sass_Options * options, const char * source_map_file)
Referenced by ExtractOptions().
ADDAPI void ADDCALL sass_option_set_source_map_root (struct Sass_Options * options, const char * source_map_root)
Referenced by ExtractOptions().