Emeraldion Lodge (codename Zelda): DiarioPost Class Reference
DiarioPost Class Reference
Model object for Diario articles.
Public Member Functions
relative_url ()
is_external ()
Returns true if the post is external.
approve ()
Sets the approved status.
reject ()
Unsets the approved status.
find_unapproved ()
Finds all elements whose approved status is false.
find_approved ()
Finds all elements whose approved status is true.
trackback_url ()
URL for trackback for this article.
comments_permalink ()
URL for the comments for this article.
rfc2822_date ()
Returns a RFC2822 formatted date for the date of the receiver, useful for feeds.
iso8601_date ()
Returns a ISO8601 formatted date for the date of the receiver, useful for feeds.
human_readable_date ()
Returns a human readable date for the date of the receiver.
get_stripped_text ()
Strips HTML tags from the article text.
summary ($relative=TRUE)
Returns a plain text summary for the article, with a link to the full version.
comma_separated_tags ()
Returns the list of tags for the receiver, separated by commas.
previous ()
Returns the item that precedes the receiver in the order.
next ()
Returns the item that succeeds the receiver in the order.
Public Member Functions inherited from ActiveRecord
ActiveRecord ($_values=NULL)
Constructs and initializes an ActiveRecord object.
belongs_to ($table_name)
Loads the parent of the receiver in a one-to-many relationship.
has_many ($table_name, $params=array())
Loads the children of the receiver in a one-to-many relationship.
has_and_belongs_to_many ($table_name, $params=array())
Loads the object network the receiver belongs to in a many-to-many relationship.
has_one ($table_name)
Loads the child the receiver in a one-to-one relationship.
find_by_query ($query)
Returns an array of model objects by executing a custom SELECT query.
find_all ($params=array())
Returns an array of model objects that satisfy the requirements expressed in the params argument.
find_by_id ($id)
Populates an object with the values of the DB row whose primary key value is id.
save ()
Requests the receiver to save its data in the bound table.
delete ($optimize=TRUE)
Deletes an object's database counterpart.
permalink ($relative=TRUE)
Provides a unique permalink URL for the receiver object.
__set ($key, $value)
Magic method to set the value of a property.
__get ($key)
Magic method to get the value of a property.
__isset ($key)
Magic method to determine if a property exists.
Static Public Member Functions
static sort_posts ($a, $b)
Static function used to compare releases.
Static Public Member Functions inherited from ActiveRecord
static find ($id, $classname= 'ActiveRecord')
Returns an object whose primary key value is id.
Protected Attributes
$foreign_key_name = 'post_id'
Protected Attributes inherited from ActiveRecord
$table_name
Name of the table bound to this model class.
$primary_key = 'id'
Name of the primary key column for the bound table.
$foreign_key_name
Used to create the name of foreign key column in tables that are in a relationship with the bound table.
Additional Inherited Members
Static Public Attributes inherited from ActiveRecord
static $columns = array()
Array of columns for the model object.
static $class_initialized = array()
Array containing initialization information for subclasses.
static $belongs_to_classes = array()
Array containing information on parent tables for subclasses.
static $has_many_classes = array()
Array containing information on child tables for subclasses.
static $object_pool = array()
Pool of objects already fetched from database.
Protected Member Functions inherited from ActiveRecord
init ($values)
Performs specialized initialization tasks.
relative_url ()
Provides a relative URL that will be used by the permalink public method.
Detailed Description
Model object for Diario articles.
Definition at line 15 of file diario_post.php.
Member Function Documentation
approve ()
Sets the approved status.
Implements Approvable.
Definition at line 39 of file diario_post.php.
comma_separated_tags ()
Returns the list of tags for the receiver, separated by commas.
Definition at line 153 of file diario_post.php.
References $tags, and Tag\join().
comments_permalink ()
URL for the comments for this article.
Note
This URL is absolute.
Definition at line 89 of file diario_post.php.
References ActiveRecord\permalink().
find_approved ()
Finds all elements whose approved status is true.
Implements Approvable.
Definition at line 66 of file diario_post.php.
References ActiveRecord\find_all().
find_unapproved ()
Finds all elements whose approved status is false.
Implements Approvable.
Definition at line 57 of file diario_post.php.
References ActiveRecord\find_all().
get_stripped_text ()
Strips HTML tags from the article text.
Definition at line 125 of file diario_post.php.
Referenced by summary().
human_readable_date ()
Returns a human readable date for the date of the receiver.
Implements Dateable.
Definition at line 116 of file diario_post.php.
is_external ()
Returns true if the post is external.
Definition at line 30 of file diario_post.php.
Referenced by relative_url().
iso8601_date ()
Returns a ISO8601 formatted date for the date of the receiver, useful for feeds.
Implements Dateable.
Definition at line 107 of file diario_post.php.
next ()
Returns the item that succeeds the receiver in the order.
Implements Sortable.
Definition at line 189 of file diario_post.php.
References $conn, Db\close_connection(), and Db\get_connection().
previous ()
Returns the item that precedes the receiver in the order.
Implements Sortable.
Definition at line 172 of file diario_post.php.
References $conn, Db\close_connection(), and Db\get_connection().
reject ()
Unsets the approved status.
Implements Approvable.
Definition at line 48 of file diario_post.php.
relative_url ()
Definition at line 19 of file diario_post.php.
References is_external().
rfc2822_date ()
Returns a RFC2822 formatted date for the date of the receiver, useful for feeds.
Implements Dateable.
Definition at line 98 of file diario_post.php.
sort_posts ($a, $b) static
Static function used to compare releases.
Definition at line 163 of file diario_post.php.
summary ($relative = TRUE)
Returns a plain text summary for the article, with a link to the full version.
This method returns a summary of the article text, truncated to a maximum length, with a trailing link to the full article.
Parameters
relative Set to TRUE if you want a relative URL, FALSE if you want a full URL.
Definition at line 137 of file diario_post.php.
References a(), get_stripped_text(), l(), and ActiveRecord\permalink().
trackback_url ()
URL for trackback for this article.
Note
This URL is absolute.
Definition at line 76 of file diario_post.php.
References APPLICATION_ROOT.
Field Documentation
$foreign_key_name = 'post_id' protected
Definition at line 17 of file diario_post.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/models/diario_post.php