Emeraldion Lodge (codename Zelda): SoftwareArtifact Class Reference
SoftwareArtifact Class Reference
Model class for software artifacts.
Public Member Functions
filesize_readable ()
Returns a readable size for the artifact's local file.
filesize ()
Returns the size of the artifact's local file.
filename ()
Returns the filename of the artifact.
file_exists ()
Returns TRUE if the artifact's local file exists, FALSE otherwise.
md5_sum ($raw=FALSE)
Returns the MD5 sum of the artifact's local file.
icon ()
Returns an icon suitable for the type of the artifact's local file.
type ()
Returns the extension of the artifact's local file.
relative_url ()
local_file ()
Returns the path to the artifact's local file.
Public Member Functions inherited from ActiveRecord
ActiveRecord ($_values=NULL)
Constructs and initializes an ActiveRecord object.
belongs_to ($table_name)
Loads the parent of the receiver in a one-to-many relationship.
has_many ($table_name, $params=array())
Loads the children of the receiver in a one-to-many relationship.
has_and_belongs_to_many ($table_name, $params=array())
Loads the object network the receiver belongs to in a many-to-many relationship.
has_one ($table_name)
Loads the child the receiver in a one-to-one relationship.
find_by_query ($query)
Returns an array of model objects by executing a custom SELECT query.
find_all ($params=array())
Returns an array of model objects that satisfy the requirements expressed in the params argument.
find_by_id ($id)
Populates an object with the values of the DB row whose primary key value is id.
save ()
Requests the receiver to save its data in the bound table.
delete ($optimize=TRUE)
Deletes an object's database counterpart.
permalink ($relative=TRUE)
Provides a unique permalink URL for the receiver object.
__set ($key, $value)
Magic method to set the value of a property.
__get ($key)
Magic method to get the value of a property.
__isset ($key)
Magic method to determine if a property exists.
Static Public Member Functions
static total_downloads ()
Returns the total number of downloads for all software artifacts.
Static Public Member Functions inherited from ActiveRecord
static find ($id, $classname= 'ActiveRecord')
Returns an object whose primary key value is id.
Protected Attributes
$foreign_key_name = 'artifact'
Protected Attributes inherited from ActiveRecord
$table_name
Name of the table bound to this model class.
$primary_key = 'id'
Name of the primary key column for the bound table.
$foreign_key_name
Used to create the name of foreign key column in tables that are in a relationship with the bound table.
Additional Inherited Members
Static Public Attributes inherited from ActiveRecord
static $columns = array()
Array of columns for the model object.
static $class_initialized = array()
Array containing initialization information for subclasses.
static $belongs_to_classes = array()
Array containing information on parent tables for subclasses.
static $has_many_classes = array()
Array containing information on child tables for subclasses.
static $object_pool = array()
Pool of objects already fetched from database.
Protected Member Functions inherited from ActiveRecord
init ($values)
Performs specialized initialization tasks.
relative_url ()
Provides a relative URL that will be used by the permalink public method.
Detailed Description
Model class for software artifacts.
Definition at line 10 of file software_artifact.php.
Member Function Documentation
file_exists ()
Returns TRUE if the artifact's local file exists, FALSE otherwise.
Definition at line 50 of file software_artifact.php.
References Filesystem\file_exists(), and local_file().
Referenced by filename().
filename ()
Returns the filename of the artifact.
Definition at line 36 of file software_artifact.php.
References file_exists(), l(), and span().
filesize ()
Returns the size of the artifact's local file.
Definition at line 27 of file software_artifact.php.
References Filesystem\filesize(), and local_file().
filesize_readable ()
Returns a readable size for the artifact's local file.
Definition at line 18 of file software_artifact.php.
References Filesystem\filesize_readable(), and local_file().
icon ()
Returns an icon suitable for the type of the artifact's local file.
Definition at line 69 of file software_artifact.php.
References APPLICATION_ROOT, and ends_with().
local_file ()
Returns the path to the artifact's local file.
Definition at line 96 of file software_artifact.php.
Referenced by file_exists(), filesize(), filesize_readable(), and md5_sum().
md5_sum ($raw = FALSE)
Returns the MD5 sum of the artifact's local file.
Parameters
raw Set to TRUE if you want the raw checksum.
Definition at line 60 of file software_artifact.php.
References local_file(), and Filesystem\md5_sum().
relative_url ()
Definition at line 85 of file software_artifact.php.
total_downloads () static
Returns the total number of downloads for all software artifacts.
Definition at line 106 of file software_artifact.php.
References $conn, Db\close_connection(), and Db\get_connection().
type ()
Returns the extension of the artifact's local file.
Definition at line 80 of file software_artifact.php.
Field Documentation
$foreign_key_name = 'artifact' protected
Definition at line 12 of file software_artifact.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/models/software_artifact.php