Emeraldion Lodge (codename Zelda): PersistentBase< T > Class Template Reference
PersistentBase< T > Class Template Reference
#include <nan.h>
Public Member Functions
NAN_INLINE PersistentBase ()
NAN_INLINE void Reset ()
template<typename S >
NAN_INLINE void Reset (const v8::Local< S > &other)
template<typename S >
NAN_INLINE void Reset (const PersistentBase< S > &other)
NAN_INLINE bool IsEmpty () const
NAN_INLINE void Empty ()
template<typename S >
NAN_INLINE bool operator== (const PersistentBase< S > &that)
template<typename S >
NAN_INLINE bool operator== (const v8::Local< S > &that)
template<typename S >
NAN_INLINE bool operator!= (const PersistentBase< S > &that)
template<typename S >
NAN_INLINE bool operator!= (const v8::Local< S > &that)
template<typename P >
NAN_INLINE void SetWeak (P *parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type)
NAN_INLINE void ClearWeak ()
NAN_INLINE void MarkIndependent ()
NAN_INLINE bool IsIndependent () const
NAN_INLINE bool IsNearDeath () const
NAN_INLINE bool IsWeak () const
Private Member Functions
NAN_INLINE PersistentBase (v8::Persistent< T > that)
NAN_INLINE PersistentBase (T *val)
Private Attributes
v8::Persistent< T > persistent
Friends
class ReturnValue
class Persistent
class Global
class ObjectWrap
template<typename U , typename M >
v8::Local< U > New (const Persistent< U, M > &p)
Detailed Description
template<typename T>
class Nan::PersistentBase< T >
Definition at line 1896 of file nan.h.
Constructor & Destructor Documentation
NAN_INLINE PersistentBase () [inline]
Definition at line 1903 of file nan.h.
NAN_INLINE PersistentBase (v8::Persistent< T > that) [inline, explicit, private]
Definition at line 1982 of file nan.h.
NAN_INLINE PersistentBase (T * val) [inline, explicit, private]
Definition at line 1984 of file nan.h.
Member Function Documentation
NAN_INLINE void ClearWeak () [inline]
Definition at line 1971 of file nan.h.
NAN_INLINE void Empty () [inline]
Definition at line 1943 of file nan.h.
NAN_INLINE bool IsEmpty () const [inline]
Definition at line 1941 of file nan.h.
Referenced by SassValueWrapper< T >::get_constructor(), Null::get_constructor(), Boolean::get_constructor(), SassValueWrapper< T >::get_js_object(), and CallbackBridge< T, L >::get_wrapper_constructor().
NAN_INLINE bool IsIndependent () const [inline]
Definition at line 1975 of file nan.h.
NAN_INLINE bool IsNearDeath () const [inline]
Definition at line 1977 of file nan.h.
NAN_INLINE bool IsWeak () const [inline]
Definition at line 1979 of file nan.h.
NAN_INLINE void MarkIndependent () [inline]
Definition at line 1973 of file nan.h.
NAN_INLINE bool operator!= (const v8::Local< S > & that) [inline]
Definition at line 1961 of file nan.h.
NAN_INLINE bool operator!= (const PersistentBase< S > & that) [inline]
Definition at line 1956 of file nan.h.
NAN_INLINE bool operator== (const v8::Local< S > & that) [inline]
Definition at line 1951 of file nan.h.
NAN_INLINE bool operator== (const PersistentBase< S > & that) [inline]
Definition at line 1946 of file nan.h.
NAN_INLINE void Reset (const PersistentBase< S > & other) [inline]
Definition at line 1927 of file nan.h.
NAN_INLINE void Reset (const v8::Local< S > & other) [inline]
Definition at line 1912 of file nan.h.
NAN_INLINE void Reset () [inline]
Definition at line 1906 of file nan.h.
Referenced by CallbackBridge< T, L >::CallbackBridge(), ExtractOptions(), SassValueWrapper< T >::get_constructor(), Null::get_constructor(), Boolean::get_constructor(), SassValueWrapper< T >::get_js_object(), CallbackBridge< T, L >::get_wrapper_constructor(), sass_free_context_wrapper(), CallbackBridge< T, L >::~CallbackBridge(), and SassValueWrapper< T >::~SassValueWrapper().
NAN_INLINE void SetWeak (P * parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type) [inline]
Definition at line 4589 of file nan.h.
Friends And Related Function Documentation
friend class Global [friend]
Definition at line 1986 of file nan.h.
v8::Local<U> New (const Persistent< U, M > & p) [friend]
friend class ObjectWrap [friend]
Definition at line 1987 of file nan.h.
friend class Persistent [friend]
Definition at line 1985 of file nan.h.
friend class ReturnValue [friend]
Reimplemented in Global< T >.
Definition at line 1900 of file nan.h.
Field Documentation
v8::Persistent<T> persistent [private]
Definition at line 1897 of file nan.h.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan.h