Emeraldion Lodge (codename Zelda): EscapableHandleScope Class Reference
EscapableHandleScope Class Reference
#include <nan.h>
Public Member Functions
EscapableHandleScope ()
template<typename T >
v8::Local< T > Escape (v8::Local< T > value)
Static Public Member Functions
static int NumberOfHandles ()
Private Member Functions
EscapableHandleScope (const EscapableHandleScope &)
void operator= (const EscapableHandleScope &)
void * operator new (size_t size)
void operator delete (void *, size_t)
Private Attributes
v8::HandleScope scope
Detailed Description
Definition at line 2165 of file nan.h.
Constructor & Destructor Documentation
EscapableHandleScope () [inline]
Definition at line 2182 of file nan.h.
EscapableHandleScope (const EscapableHandleScope &) [private]
Member Function Documentation
v8::Local<T> Escape (v8::Local< T > value) [inline]
Definition at line 2189 of file nan.h.
Referenced by Nan::CallAsConstructor(), Null::get_constructor(), Boolean::get_constructor(), SassValueWrapper< T >::get_constructor_template(), Factory< v8::Uint32 >::New(), IntegerFactory< T >::New(), and Nan::imp::SetterCallbackWrapper().
static int NumberOfHandles () [inline, static]
Definition at line 2184 of file nan.h.
Referenced by FunctionCallbackInfo< T >::GetIsolate().
void operator delete (void * , size_t) [private]
void* operator new (size_t size) [private]
void operator= (const EscapableHandleScope &) [private]
Field Documentation
v8::HandleScope scope [private]
Definition at line 2194 of file nan.h.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan.h