Emeraldion Lodge (codename Zelda): To_String Class Reference
To_String Class Reference
#include <to_string.hpp>
Inherits Operation_CRTP< string, To_String >.
Public Member Functions
To_String (Context *ctx=0, bool in_declaration=true)
virtual ~To_String ()
string operator() (Null *n)
string operator() (String_Constant *)
template<typename U >
string fallback (U n)
Private Member Functions
string fallback_impl (AST_Node *n)
Private Attributes
Context * ctx
bool in_declaration
Detailed Description
Definition at line 14 of file to_string.hpp.
Constructor & Destructor Documentation
To_String (Context * ctx = 0, bool in_declaration = true)
Definition at line 14 of file to_string.cpp.
~To_String () [virtual]
Definition at line 16 of file to_string.cpp.
Member Function Documentation
string fallback (U n) [inline]
Reimplemented from Operation_CRTP< string, To_String >.
Definition at line 31 of file to_string.hpp.
References To_String::fallback_impl().
string fallback_impl (AST_Node * n) [inline, private]
Definition at line 18 of file to_string.cpp.
References To_String::ctx, Emitter::get_buffer(), To_String::in_declaration, and Emitter::in_declaration.
Referenced by To_String::fallback().
string operator() (String_Constant * s) [inline, virtual]
Reimplemented from Operation_CRTP< string, To_String >.
Definition at line 27 of file to_string.cpp.
string operator() (Null * n) [inline, virtual]
Reimplemented from Operation_CRTP< string, To_String >.
Definition at line 32 of file to_string.cpp.
Field Documentation
Context* ctx [private]
Definition at line 20 of file to_string.hpp.
Referenced by To_String::fallback_impl().
bool in_declaration [private]
Definition at line 21 of file to_string.hpp.
Referenced by To_String::fallback_impl().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/to_string.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/to_string.cpp