Emeraldion Lodge (codename Zelda): Hashed Class Reference
Hashed Class Reference
#include <ast.hpp>
Inherited by Map.
Public Member Functions
Hashed (size_t s=0)
virtual ~Hashed ()
size_t length () const
bool empty () const
bool has (Expression *k) const
Expression * at (Expression *k) const
bool has_duplicate_key () const
Expression * get_duplicate_key () const
const unordered_map
< Expression *, Expression * > elements ()
Hashed & operator<< (pair< Expression *, Expression * > p)
Hashed & operator+= (Hashed *h)
const unordered_map
< Expression *, Expression * > & pairs () const
const vector< Expression * > & keys () const
Protected Member Functions
void reset_hash ()
void reset_duplicate_key ()
virtual void adjust_after_pushing (std::pair< Expression *, Expression * > p)
Protected Attributes
size_t hash_
Expression * duplicate_key_
Private Attributes
unordered_map< Expression
*, Expression * > elements_
vector< Expression * > list_
Detailed Description
Definition at line 197 of file ast.hpp.
Constructor & Destructor Documentation
Hashed (size_t s = 0) [inline]
Definition at line 208 of file ast.hpp.
References Hashed::elements_, Hashed::list_, Hashed::reset_duplicate_key(), and s().
~Hashed () [inline, virtual]
Definition at line 248 of file ast.hpp.
Member Function Documentation
virtual void adjust_after_pushing (std::pair< Expression *, Expression * > p) [inline, protected, virtual]
Reimplemented in Map.
Definition at line 206 of file ast.hpp.
Referenced by Hashed::operator<<().
Expression * at (Expression * k) const
Definition at line 937 of file ast.cpp.
References Hashed::elements_.
Referenced by Sass::bind(), Sass::Functions::BUILT_IN(), Sass::eq(), Map::hash(), To_C::operator()(), Inspect::operator()(), Expand::operator()(), Eval::operator()(), Hashed::operator+=(), and Map::operator==().
const unordered_map<Expression*, Expression*> elements () [inline]
Definition at line 217 of file ast.hpp.
References Hashed::elements_.
bool empty () const [inline]
Definition at line 212 of file ast.hpp.
References Hashed::list_.
Referenced by Sass::Functions::BUILT_IN(), and Inspect::operator()().
Expression* get_duplicate_key () const [inline]
Definition at line 216 of file ast.hpp.
References Hashed::duplicate_key_.
Referenced by Eval::operator()().
bool has (Expression * k) const [inline]
Definition at line 213 of file ast.hpp.
References Hashed::elements_.
Referenced by Sass::Functions::BUILT_IN(), and Hashed::operator<<().
bool has_duplicate_key () const [inline]
Definition at line 215 of file ast.hpp.
References Hashed::duplicate_key_.
Referenced by Eval::operator()().
const vector<Expression*>& keys () const [inline]
Definition at line 246 of file ast.hpp.
References Hashed::list_.
Referenced by Sass::bind(), Sass::Functions::BUILT_IN(), Sass::eq(), Map::hash(), To_C::operator()(), Inspect::operator()(), Expand::operator()(), Eval::operator()(), Hashed::operator+=(), and Map::operator==().
size_t length () const [inline]
Definition at line 211 of file ast.hpp.
References Hashed::list_.
Referenced by Sass::Functions::BUILT_IN(), Sass::eq(), Map::is_invisible(), To_C::operator()(), Eval::operator()(), Hashed::operator+=(), and Map::operator==().
Hashed& operator+= (Hashed * h) [inline]
Definition at line 230 of file ast.hpp.
References Hashed::at(), Hashed::elements_, Hashed::keys(), Hashed::length(), Hashed::list_, and Hashed::reset_duplicate_key().
Hashed& operator<< (pair< Expression *, Expression * > p) [inline]
Definition at line 218 of file ast.hpp.
References Hashed::adjust_after_pushing(), Hashed::duplicate_key_, Hashed::elements_, Hashed::has(), Hashed::list_, p(), and Hashed::reset_hash().
const unordered_map<Expression*, Expression*>& pairs () const [inline]
Definition at line 245 of file ast.hpp.
References Hashed::elements_.
void reset_duplicate_key () [inline, protected]
Definition at line 205 of file ast.hpp.
References Hashed::duplicate_key_.
Referenced by Hashed::Hashed(), and Hashed::operator+=().
void reset_hash () [inline, protected]
Definition at line 204 of file ast.hpp.
References Hashed::hash_.
Referenced by Hashed::operator<<().
Field Documentation
Expression* duplicate_key_ [protected]
Definition at line 203 of file ast.hpp.
Referenced by Hashed::get_duplicate_key(), Hashed::has_duplicate_key(), Hashed::operator<<(), and Hashed::reset_duplicate_key().
unordered_map<Expression*, Expression*> elements_ [private]
Definition at line 199 of file ast.hpp.
Referenced by Hashed::at(), Hashed::elements(), Hashed::has(), Hashed::Hashed(), Hashed::operator+=(), Hashed::operator<<(), and Hashed::pairs().
size_t hash_ [protected]
Definition at line 202 of file ast.hpp.
Referenced by Map::hash(), and Hashed::reset_hash().
vector<Expression*> list_ [private]
Definition at line 200 of file ast.hpp.
Referenced by Hashed::empty(), Hashed::Hashed(), Hashed::keys(), Hashed::length(), Hashed::operator+=(), and Hashed::operator<<().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp