Emeraldion Lodge (codename Zelda): Map Class Reference
Map Class Reference
#include <map.h>
Inherits SassValueWrapper< Map >.
Public Member Functions
Map (Sass_Value *)
Static Public Member Functions
static char const * get_constructor_name ()
static Sass_Value * construct (const std::vector< v8::Local< v8::Value >>, Sass_Value **)
static void initPrototype (v8::Local< v8::FunctionTemplate >)
static NAN_METHOD (GetValue)
static NAN_METHOD (SetValue)
static NAN_METHOD (GetKey)
static NAN_METHOD (SetKey)
static NAN_METHOD (GetLength)
Detailed Description
Definition at line 9 of file map.h.
Constructor & Destructor Documentation
Map (Sass_Value * v)
Definition at line 6 of file map.cpp.
Member Function Documentation
Sass_Value * construct (const std::vector< v8::Local< v8::Value >> raw_val, Sass_Value ** out) [static]
Definition at line 8 of file map.cpp.
References SassValueWrapper< Map >::fail(), and sass_make_map().
static char const* get_constructor_name () [inline, static]
Reimplemented from SassValueWrapper< Map >.
Definition at line 12 of file map.h.
void initPrototype (v8::Local< v8::FunctionTemplate > proto) [static]
Definition at line 22 of file map.cpp.
References Nan::SetPrototypeMethod().
static NAN_METHOD (GetLength) [static]
static NAN_METHOD (SetKey) [static]
static NAN_METHOD (GetKey) [static]
static NAN_METHOD (SetValue) [static]
static NAN_METHOD (GetValue) [static]
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/map.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/map.cpp