Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/cencode.c File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/cencode.c File Reference
#include "b64/cencode.h"
Functions
void base64_init_encodestate (base64_encodestate *state_in)
char base64_encode_value (char value_in)
int base64_encode_block (const char *plaintext_in, int length_in, char *code_out, base64_encodestate *state_in)
int base64_encode_blockend (char *code_out, base64_encodestate *state_in)
Function Documentation
int base64_encode_block (const char * plaintext_in, int length_in, char * code_out, base64_encodestate * state_in)
Definition at line 24 of file cencode.c.
References base64_encode_value(), base64_encodestate::result, base64_encodestate::step, step_A, step_B, step_C, and base64_encodestate::stepcount.
int base64_encode_blockend (char * code_out, base64_encodestate * state_in)
Definition at line 80 of file cencode.c.
References base64_encode_value(), base64_encodestate::result, base64_encodestate::step, step_A, step_B, and step_C.
char base64_encode_value (char value_in)
Definition at line 17 of file cencode.c.
Referenced by base64_encode_block(), and base64_encode_blockend().
void base64_init_encodestate (base64_encodestate * state_in)
Definition at line 10 of file cencode.c.
References base64_encodestate::result, base64_encodestate::step, step_A, and base64_encodestate::stepcount.