Emeraldion Lodge (codename Zelda): ObjectWrap Class Reference
ObjectWrap Class Reference
#include <nan_object_wrap.h>
Public Member Functions
ObjectWrap ()
virtual ~ObjectWrap ()
v8::Local< v8::Object > handle ()
Persistent< v8::Object > & persistent ()
Static Public Member Functions
template<class T >
static T * Unwrap (v8::Local< v8::Object > object)
Protected Member Functions
void Wrap (v8::Local< v8::Object > object)
void MakeWeak ()
virtual void Ref ()
virtual void Unref ()
Protected Attributes
int refs_
Static Private Member Functions
static void WeakCallback (v8::Persistent< v8::Value > value, void *data)
Private Attributes
Persistent< v8::Object > handle_
Detailed Description
Definition at line 12 of file nan_object_wrap.h.
Constructor & Destructor Documentation
ObjectWrap () [inline]
Definition at line 14 of file nan_object_wrap.h.
References refs_.
virtual ~ObjectWrap () [inline, virtual]
Definition at line 19 of file nan_object_wrap.h.
References PersistentBase< T >::ClearWeak(), persistent(), and Persistent< T, M >::Reset().
Member Function Documentation
v8::Local<v8::Object> handle () [inline]
Definition at line 42 of file nan_object_wrap.h.
References New(), and persistent().
void MakeWeak () [inline, protected]
Definition at line 79 of file nan_object_wrap.h.
References PersistentBase< T >::MarkIndependent(), persistent(), and WeakCallback().
Referenced by Unref(), and Wrap().
Persistent<v8::Object>& persistent () [inline]
Definition at line 47 of file nan_object_wrap.h.
References handle_.
Referenced by handle(), MakeWeak(), Ref(), Unref(), Wrap(), and ~ObjectWrap().
virtual void Ref () [inline, protected, virtual]
Definition at line 90 of file nan_object_wrap.h.
References PersistentBase< T >::ClearWeak(), persistent(), and refs_.
virtual void Unref () [inline, protected, virtual]
Definition at line 105 of file nan_object_wrap.h.
References MakeWeak(), persistent(), and refs_.
static T* Unwrap (v8::Local< v8::Object > object) [inline, static]
Definition at line 31 of file nan_object_wrap.h.
References Nan::GetInternalFieldPointer().
static void WeakCallback (v8::Persistent< v8::Value > value, void * data) [inline, static, private]
Definition at line 142 of file nan_object_wrap.h.
References handle_, PersistentBase< T >::IsNearDeath(), refs_, and Persistent< T, M >::Reset().
Referenced by MakeWeak().
void Wrap (v8::Local< v8::Object > object) [inline, protected]
Definition at line 53 of file nan_object_wrap.h.
References MakeWeak(), persistent(), Persistent< T, M >::Reset(), and Nan::SetInternalFieldPointer().
Field Documentation
Persistent<v8::Object> handle_ [private]
Definition at line 151 of file nan_object_wrap.h.
Referenced by persistent(), and WeakCallback().
int refs_ [protected]
Definition at line 113 of file nan_object_wrap.h.
Referenced by ObjectWrap(), Ref(), Unref(), and WeakCallback().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_object_wrap.h