Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/contrib/plugin.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/contrib/plugin.cpp File Reference
#include <cstring>
#include <iostream>
#include <stdint.h>
#include "sass_values.h"
Functions
const char *ADDCALL libsass_get_version ()
union Sass_Value * custom_function (const union Sass_Value *s_args, Sass_Function_Entry cb, struct Sass_Options *opts)
Sass_Function_List ADDCALL libsass_load_functions ()
Sass_Import_List custom_importer (const char *cur_path, Sass_Importer_Entry cb, struct Sass_Compiler *comp)
Sass_Importer_List ADDCALL libsass_load_importers ()
Function Documentation
union Sass_Value* custom_function (const union Sass_Value * s_args, Sass_Function_Entry cb, struct Sass_Options * opts) [write]
Definition at line 13 of file plugin.cpp.
References sass_function_get_cookie(), and sass_make_number().
Referenced by libsass_load_functions().
Sass_Import_List custom_importer (const char * cur_path, Sass_Importer_Entry cb, struct Sass_Compiler * comp)
Definition at line 34 of file plugin.cpp.
References sass_importer_get_cookie(), sass_make_import_entry(), and sass_make_import_list().
Referenced by libsass_load_importers().
const char* ADDCALL libsass_get_version ()
Definition at line 9 of file plugin.cpp.
References libsass_version().
Sass_Function_List ADDCALL libsass_load_functions ()
Definition at line 21 of file plugin.cpp.
References custom_function(), sass_function_set_list_entry(), sass_make_function(), and sass_make_function_list().
Sass_Importer_List ADDCALL libsass_load_importers ()
Definition at line 46 of file plugin.cpp.
References custom_importer(), sass_importer_set_list_entry(), sass_make_importer(), and sass_make_importer_list().