Emeraldion Lodge (codename Zelda): Complex_Selector Class Reference
Complex_Selector Class Reference
#include <ast.hpp>
Inherits Sass::Selector.
Public Types
enum Combinator { ANCESTOR_OF, PARENT_OF, PRECEDES, ADJACENT_TO }
Public Member Functions
Complex_Selector (ParserState pstate, Combinator c, Compound_Selector *h, Complex_Selector *t)
Compound_Selector * base ()
Complex_Selector * context (Context &)
Complex_Selector * innermost ()
size_t length ()
bool is_superselector_of (Compound_Selector *sub)
bool is_superselector_of (Complex_Selector *sub)
bool is_superselector_of (Selector_List *sub)
Combinator clear_innermost ()
void set_innermost (Complex_Selector *, Combinator)
virtual unsigned long specificity () const
bool operator< (const Complex_Selector &rhs) const
bool operator== (const Complex_Selector &rhs) const
bool operator!= (const Complex_Selector &rhs) const
SourcesSet sources ()
void addSources (SourcesSet &sources, Context &ctx)
void clearSources ()
Complex_Selector * clone (Context &) const
Complex_Selector * cloneFully (Context &) const
ATTACH_OPERATIONS ()
Private Member Functions
ADD_PROPERTY (Combinator, combinator)
ADD_PROPERTY (Compound_Selector *, head)
ADD_PROPERTY (Complex_Selector *, tail)
Detailed Description
Definition at line 1984 of file ast.hpp.
Member Enumeration Documentation
enum Combinator
Enumerator:
ANCESTOR_OF
PARENT_OF
PRECEDES
ADJACENT_TO
Definition at line 1986 of file ast.hpp.
Constructor & Destructor Documentation
Complex_Selector (ParserState pstate, Combinator c, Compound_Selector * h, Complex_Selector * t) [inline]
Definition at line 1992 of file ast.hpp.
Referenced by Complex_Selector::clone(), Complex_Selector::cloneFully(), and Complex_Selector::context().
Member Function Documentation
ADD_PROPERTY (Complex_Selector * , tail) [private]
ADD_PROPERTY (Compound_Selector * , head) [private]
ADD_PROPERTY (Combinator , combinator) [private]
void addSources (SourcesSet & sources, Context & ctx) [inline]
Definition at line 2044 of file ast.hpp.
References Compound_Selector::mergeSources().
Referenced by Sass::extendCompoundSelector().
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
Compound_Selector * base ()
Definition at line 431 of file ast.cpp.
Referenced by Sass::extendCompoundSelector(), and Complex_Selector::is_superselector_of().
Complex_Selector::Combinator clear_innermost ()
Definition at line 453 of file ast.cpp.
References Complex_Selector::ANCESTOR_OF, and Complex_Selector::length().
Referenced by Sass::extendCompoundSelector(), and Sass::parentSuperselector().
void clearSources () [inline]
Definition at line 2057 of file ast.hpp.
References Compound_Selector::clearSources().
Complex_Selector * clone (Context & ctx) const
Definition at line 471 of file ast.cpp.
References Complex_Selector::Complex_Selector(), and Context::mem.
Referenced by Node::clone(), Complex_Selector::cloneFully(), Node::createSelector(), Sass::mergeFinalOps(), and Sass::nodeToComplexSelector().
Complex_Selector * cloneFully (Context & ctx) const
Definition at line 478 of file ast.cpp.
References Complex_Selector::clone(), Complex_Selector::Complex_Selector(), and Context::mem.
Referenced by Sass::extendCompoundSelector().
Complex_Selector * context (Context & ctx)
Definition at line 437 of file ast.cpp.
References Complex_Selector::Complex_Selector(), Complex_Selector::context(), Context::mem, and Sass::pstate.
Referenced by Complex_Selector::context().
Complex_Selector * innermost ()
Definition at line 447 of file ast.cpp.
References Complex_Selector::innermost().
Referenced by Complex_Selector::innermost(), and Complex_Selector::is_superselector_of().
bool is_superselector_of (Selector_List * sub)
Definition at line 520 of file ast.cpp.
References Complex_Selector::is_superselector_of(), and Vectorized< T >::length().
bool is_superselector_of (Complex_Selector * sub)
Definition at line 346 of file ast.cpp.
References Complex_Selector::ANCESTOR_OF, Complex_Selector::base(), Complex_Selector::innermost(), Complex_Selector::is_superselector_of(), Complex_Selector::length(), Complex_Selector::PARENT_OF, Complex_Selector::PRECEDES, and Sass::to_string.
bool is_superselector_of (Compound_Selector * sub)
Definition at line 341 of file ast.cpp.
References Complex_Selector::base(), and Compound_Selector::is_superselector_of().
Referenced by check_complex(), Complex_Selector::is_superselector_of(), Sass::mergeFinalOps(), Sass::parentSuperselector(), and Sass::trim().
size_t length ()
Definition at line 424 of file ast.cpp.
Referenced by Complex_Selector::clear_innermost(), and Complex_Selector::is_superselector_of().
bool operator!= (const Complex_Selector & rhs) const [inline]
Definition at line 2020 of file ast.hpp.
bool operator< (const Complex_Selector & rhs) const
Definition at line 21 of file ast.cpp.
References Sass::to_string.
bool operator== (const Complex_Selector & rhs) const
Definition at line 28 of file ast.cpp.
References Complex_Selector::ANCESTOR_OF.
void set_innermost (Complex_Selector * val, Combinator c)
Definition at line 463 of file ast.cpp.
Referenced by Sass::extendCompoundSelector(), and Sass::parentSuperselector().
SourcesSet sources () [inline]
Definition at line 2021 of file ast.hpp.
References Complex_Selector::sources(), and Compound_Selector::sources().
Referenced by Sass::extendCompoundSelector(), Complex_Selector::sources(), and Sass::trim().
virtual unsigned long specificity () const [inline, virtual]
Definition at line 2011 of file ast.hpp.
Referenced by debug_ast(), and Sass::trim().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp