Emeraldion Lodge (codename Zelda): Selector_List Class Reference
Selector_List Class Reference
#include <ast.hpp>
Inherits Sass::Selector, and Vectorized< Complex_Selector * >.
Public Member Functions
Selector_List (ParserState pstate, size_t s=0)
bool is_superselector_of (Compound_Selector *sub)
bool is_superselector_of (Complex_Selector *sub)
bool is_superselector_of (Selector_List *sub)
virtual unsigned long specificity ()
ATTACH_OPERATIONS ()
Protected Member Functions
void adjust_after_pushing (Complex_Selector *c)
Private Member Functions
ADD_PROPERTY (vector< string >, wspace)
Detailed Description
Definition at line 2080 of file ast.hpp.
Constructor & Destructor Documentation
Selector_List (ParserState pstate, size_t s = 0) [inline]
Definition at line 2088 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (vector< string > , wspace) [private]
void adjust_after_pushing (Complex_Selector * c) [protected, virtual]
Reimplemented from Vectorized< Complex_Selector * >.
Definition at line 507 of file ast.cpp.
References Sass::to_string.
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
bool is_superselector_of (Selector_List * sub)
Definition at line 531 of file ast.cpp.
References Selector_List::is_superselector_of(), and Vectorized< T >::length().
bool is_superselector_of (Complex_Selector * sub)
Definition at line 553 of file ast.cpp.
References Selector_List::is_superselector_of(), and Vectorized< Complex_Selector * >::length().
bool is_superselector_of (Compound_Selector * sub)
Definition at line 542 of file ast.cpp.
References Vectorized< Complex_Selector * >::length().
Referenced by Sass::Functions::BUILT_IN(), and Selector_List::is_superselector_of().
virtual unsigned long specificity () [inline, virtual]
Reimplemented from Selector.
Definition at line 2095 of file ast.hpp.
References Vectorized< Complex_Selector * >::length().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp