Emeraldion Lodge (codename Zelda): Persistent< T, M > Class Template Reference
Persistent< T, M > Class Template Reference
#include <nan_persistent_12_inl.h>
Inherits PersistentBase< T >.
Public Member Functions
NAN_INLINE Persistent ()
template<typename S >
NAN_INLINE Persistent (v8::Local< S > that)
template<typename S , typename M2 >
NAN_INLINE Persistent (const v8::Persistent< S, M2 > &that)
NAN_INLINE void Reset ()
template<typename S >
NAN_INLINE void Reset (const v8::Local< S > &other)
template<typename S >
NAN_INLINE void Reset (const v8::PersistentBase< S > &other)
template<typename P >
NAN_INLINE void SetWeak (P *parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type)
NAN_INLINE Persistent ()
template<typename S >
NAN_INLINE Persistent (v8::Handle< S > that)
NAN_INLINE Persistent (const Persistent &that)
template<typename S , typename M2 >
NAN_INLINE Persistent (const Persistent< S, M2 > &that)
NAN_INLINE Persistent & operator= (const Persistent &that)
template<class S , class M2 >
NAN_INLINE Persistent & operator= (const Persistent< S, M2 > &that)
NAN_INLINE ~Persistent ()
Private Member Functions
NAN_INLINE T * operator* () const
template<typename S , typename M2 >
NAN_INLINE void Copy (const Persistent< S, M2 > &that)
NAN_INLINE T * operator* () const
template<typename S , typename M2 >
NAN_INLINE void Copy (const Persistent< S, M2 > &that)
Detailed Description
template<typename T, typename M>
class Persistent< T, M >
Definition at line 12 of file nan_persistent_12_inl.h.
Constructor & Destructor Documentation
NAN_INLINE Persistent () [inline]
Definition at line 15 of file nan_persistent_12_inl.h.
NAN_INLINE Persistent (v8::Local< S > that) [inline]
Definition at line 17 of file nan_persistent_12_inl.h.
NAN_INLINE Persistent (const v8::Persistent< S, M2 > & that) [inline]
Definition at line 21 of file nan_persistent_12_inl.h.
NAN_INLINE Persistent () [inline]
Definition at line 136 of file nan_persistent_pre_12_inl.h.
NAN_INLINE Persistent (v8::Handle< S > that) [inline]
Definition at line 138 of file nan_persistent_pre_12_inl.h.
NAN_INLINE Persistent (const Persistent< T, M > & that) [inline]
Definition at line 143 of file nan_persistent_pre_12_inl.h.
NAN_INLINE Persistent (const Persistent< S, M2 > & that) [inline]
Definition at line 148 of file nan_persistent_pre_12_inl.h.
NAN_INLINE ~Persistent () [inline]
Definition at line 164 of file nan_persistent_pre_12_inl.h.
Member Function Documentation
NAN_INLINE void Copy (const Persistent< S, M2 > & that) [inline, private]
Definition at line 172 of file nan_persistent_pre_12_inl.h.
NAN_INLINE void Copy (const Persistent< S, M2 > & that) [inline, private]
Definition at line 46 of file nan_persistent_12_inl.h.
Referenced by Persistent< v8::Object >::Copy(), Persistent< v8::Object >::operator=(), and Persistent< v8::Object >::Persistent().
NAN_INLINE T* operator* () const [inline, private]
Definition at line 169 of file nan_persistent_pre_12_inl.h.
NAN_INLINE T* operator* () const [inline, private]
Definition at line 43 of file nan_persistent_12_inl.h.
NAN_INLINE Persistent& operator= (const Persistent< S, M2 > & that) [inline]
Definition at line 159 of file nan_persistent_pre_12_inl.h.
NAN_INLINE Persistent& operator= (const Persistent< T, M > & that) [inline]
Definition at line 153 of file nan_persistent_pre_12_inl.h.
NAN_INLINE void Reset (const v8::PersistentBase< S > & other) [inline]
Definition at line 32 of file nan_persistent_12_inl.h.
NAN_INLINE void Reset (const v8::Local< S > & other) [inline]
Reimplemented from PersistentBase< T >.
Definition at line 27 of file nan_persistent_12_inl.h.
NAN_INLINE void Reset () [inline]
Reimplemented from PersistentBase< T >.
Definition at line 24 of file nan_persistent_12_inl.h.
Referenced by Persistent< v8::Object >::Copy(), Persistent< v8::Object >::Reset(), ObjectWrap::WeakCallback(), ObjectWrap::Wrap(), ObjectWrap::~ObjectWrap(), and Persistent< v8::Object >::~Persistent().
NAN_INLINE void SetWeak (P * parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type) [inline]
Reimplemented from PersistentBase< T >.
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_persistent_12_inl.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_persistent_pre_12_inl.h