Emeraldion Lodge (codename Zelda): Cookie Class Reference
Cookie Class Reference
Helper object for cookie support.
Static Public Member Functions
static set ($name, $value= '', $expires=0, $path= '/', $domain=NULL, $secure=FALSE)
Sets the value and other parameters of a cookie.
static get ($name)
Gets the value of a cookie.
static delete ($name)
Deletes a cookie.
Detailed Description
Helper object for cookie support.
Definition at line 9 of file cookie.php.
Member Function Documentation
delete ($name) static
Deletes a cookie.
Sets a cookie to some date in the past: this may seem ridiculous, but is the only recommended way to cause the deletion of a cookie.
Warning
This function should be called only for cookies set with set using default values, otherwise they won't be deleted properly. In all other cases, set should be used.
Parameters
name The name of the cookie.
Definition at line 51 of file cookie.php.
References Time\yesterday().
Referenced by LoginController\logout().
get ($name) static
Gets the value of a cookie.
Parameters
name The name of the cookie.
Definition at line 33 of file cookie.php.
Referenced by EmeController\get_credentials().
set ($name, $value = '', $expires = 0, $path = '/', $domain = NULL, $secure = FALSE) static
Sets the value and other parameters of a cookie.
The value of the cookie is added to the superglobal _COOKIE array in order to be readily available on the rest of the code.
Parameters
name The name of the cookie.
value The value of the cookie.
path The path for which the cookie should be valid.
domain The domain for which the cookie should be valid.
secure Whether the cookie should be secure.
Definition at line 22 of file cookie.php.
Referenced by LoginController\login(), LanguageController\set(), EmeController\set_credentials(), and EmeController\spot_people().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/cookie.php