Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/views/diario/_calendar.php File Reference
_calendar.php File Reference
Variables
$year = (isset($_REQUEST['year']) && !empty($_REQUEST['year']) ? $_REQUEST['year'] : date("Y"))
$month = (isset($_REQUEST['month']) && !empty($_REQUEST['month']) ? $_REQUEST['month'] : date("m"))
$primo_del_mese = mktime (0, 0, 0, $month, 1, $year)
$primo = date("w", $primo_del_mese)
$giorni = date("t", $primo_del_mese)
$thetime = time()
$conn = Db::get_connection()
$mindate = strtotime($conn->result(0))
Variable Documentation
$conn = Db::get_connection()
Definition at line 72 of file _calendar.php.
Referenced by BackendController\_batch_moderate(), SoftwareController\_init_software(), ActiveRecord\ActiveRecord(), MetaController\attribute_visits(), MetaController\blocked_ips_list(), Antispam\check_spam_signature(), Db\close_connection(), BlockedVisit\count_by_ip(), ActiveRecord\delete(), BackendController\diario_comment_moderate(), BackendController\diario_post_add(), ActiveRecord\find_all(), ActiveRecord\find_by_id(), ActiveRecord\find_by_query(), Db\get_connection(), ActiveRecord\has_and_belongs_to_many(), KmlController\hits_by_host(), MetaController\hits_by_host_list(), SparkleController\index(), BlockedIp\is_blocked(), Login\is_logged_in(), MaintenanceController\kill_claudio(), KmlController\last_n_visits(), DiarioController\live_search(), LoginController\login(), Host\lookup_host_and_cache(), DiarioPost\next(), MetaController\outbounds_list(), SoftwareController\post_comment(), DiarioPost\previous(), MetaController\queries_list(), DiarioController\read(), MetaController\referrers_list(), ActiveRecord\save(), DiarioController\search(), BackendController\server_error_delete(), FeedController\software(), BackendController\software_artifact_list(), BackendController\software_comment_list(), BackendController\software_comment_moderate(), BackendController\software_quote_list(), BackendController\software_release_list(), SoftwareArtifact\total_downloads(), MaintenanceController\update_macupdate_ratings(), MaintenanceController\update_versiontracker_ratings(), MetaController\visits_list(), and SoftwareController\widgets_versioncheck().
$giorni = date("t", $primo_del_mese)
Definition at line 15 of file _calendar.php.
$mindate = strtotime($conn->result(0))
Definition at line 76 of file _calendar.php.
$month = (isset($_REQUEST['month']) && !empty($_REQUEST['month']) ? $_REQUEST['month'] : date("m"))
Definition at line 11 of file _calendar.php.
$primo = date("w", $primo_del_mese)
Definition at line 14 of file _calendar.php.
$primo_del_mese = mktime (0, 0, 0, $month, 1, $year)
Definition at line 13 of file _calendar.php.
$thetime = time()
Definition at line 71 of file _calendar.php.
$year = (isset($_REQUEST['year']) && !empty($_REQUEST['year']) ? $_REQUEST['year'] : date("Y"))
Calendario del Diario
Mostra una tabella contenente i giorni del mese che hanno articoli
Definition at line 10 of file _calendar.php.