Emeraldion Lodge (codename Zelda): utf8::unchecked Namespace Reference
utf8::unchecked Namespace Reference
Data Structures
class iterator
Functions
template<typename octet_iterator >
octet_iterator append (uint32_t cp, octet_iterator result)
template<typename octet_iterator >
uint32_t next (octet_iterator &it)
template<typename octet_iterator >
uint32_t peek_next (octet_iterator it)
template<typename octet_iterator >
uint32_t prior (octet_iterator &it)
template<typename octet_iterator >
uint32_t previous (octet_iterator &it)
template<typename octet_iterator , typename distance_type >
void advance (octet_iterator &it, distance_type n)
template<typename octet_iterator >
std::iterator_traits
< octet_iterator >
::difference_type distance (octet_iterator first, octet_iterator last)
template<typename u16bit_iterator , typename octet_iterator >
octet_iterator utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result)
template<typename u16bit_iterator , typename octet_iterator >
u16bit_iterator utf8to16 (octet_iterator start, octet_iterator end, u16bit_iterator result)
template<typename octet_iterator , typename u32bit_iterator >
octet_iterator utf32to8 (u32bit_iterator start, u32bit_iterator end, octet_iterator result)
template<typename octet_iterator , typename u32bit_iterator >
u32bit_iterator utf8to32 (octet_iterator start, octet_iterator end, u32bit_iterator result)
Function Documentation
void utf8::unchecked::advance (octet_iterator & it, distance_type n) [inline]
Definition at line 113 of file unchecked.h.
References next().
Referenced by Sass::Functions::BUILT_IN(), Sass::UTF_8::code_point_size_at_offset(), Sass::UTF_8::offset_at_position(), and iterator< octet_iterator >::operator++().
octet_iterator utf8::unchecked::append (uint32_t cp, octet_iterator result) [inline]
Definition at line 38 of file unchecked.h.
Referenced by Sass::register_built_in_functions(), Sass::string_eval_escapes(), Sass::unquote(), utf16to8(), and utf32to8().
std::iterator_traits<octet_iterator>::difference_type utf8::unchecked::distance (octet_iterator first, octet_iterator last) [inline]
Definition at line 121 of file unchecked.h.
References next().
Referenced by Sass::Functions::BUILT_IN(), Sass::UTF_8::code_point_count(), Subset_Map< K, V >::get_kv(), and Sass::UTF_8::offset_at_position().
uint32_t utf8::unchecked::next (octet_iterator & it) [inline]
Definition at line 61 of file unchecked.h.
References utf8::internal::mask8(), and utf8::internal::sequence_length().
Referenced by advance(), distance(), json_delete(), iterator< octet_iterator >::operator*(), peek_next(), prior(), Sass::quote(), sass_clear_options(), utf8to16(), and utf8to32().
uint32_t utf8::unchecked::peek_next (octet_iterator it) [inline]
Definition at line 92 of file unchecked.h.
References next().
uint32_t utf8::unchecked::previous (octet_iterator & it) [inline]
Definition at line 107 of file unchecked.h.
References prior().
Referenced by sass_importer().
uint32_t utf8::unchecked::prior (octet_iterator & it) [inline]
Definition at line 98 of file unchecked.h.
References utf8::internal::is_trail(), and next().
Referenced by iterator< octet_iterator >::operator--(), and previous().
octet_iterator utf8::unchecked::utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result) [inline]
Definition at line 130 of file unchecked.h.
References append(), utf8::internal::is_lead_surrogate(), utf8::internal::mask16(), and utf8::internal::SURROGATE_OFFSET.
Referenced by Sass::UTF_8::convert_from_utf16().
octet_iterator utf8::unchecked::utf32to8 (u32bit_iterator start, u32bit_iterator end, octet_iterator result) [inline]
Definition at line 160 of file unchecked.h.
References append().
u16bit_iterator utf8::unchecked::utf8to16 (octet_iterator start, octet_iterator end, u16bit_iterator result) [inline]
Definition at line 145 of file unchecked.h.
References utf8::internal::LEAD_OFFSET, next(), and utf8::internal::TRAIL_SURROGATE_MIN.
Referenced by Sass::UTF_8::convert_to_utf16().
u32bit_iterator utf8::unchecked::utf8to32 (octet_iterator start, octet_iterator end, u32bit_iterator result) [inline]
Definition at line 169 of file unchecked.h.
References next().