Emeraldion Lodge (codename Zelda): FeedController Class Reference
FeedController Class Reference
Controller for RSS and Atom feeds generation.
Public Member Functions
software ()
Action method that generates the feed of software releases.
software_comments ()
Action method that generates the feed of software comments.
diario ()
Action method that generates the feed of Diario articles.
diario_comments ()
Action method that generates the feed of Diario comments.
feeds_list ()
Action method that generates a list of available feeds.
feed_permalink ()
Returns the permalink URL for the current feed.
Protected Member Functions
init ()
Custom initialization for the controller object.
Protected Attributes
$mimetype = 'text/xml; charset=utf-8'
A MIME type for the response.
$type = 'rss'
An extension for action pages.
Detailed Description
Controller for RSS and Atom feeds generation.
Definition at line 14 of file feed_controller.php.
Member Function Documentation
FeedController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Definition at line 19 of file feed_controller.php.
References BaseController::after_filter(), BaseController::before_filter(), and BaseController::caches_page().
FeedController::software ()
Action method that generates the feed of software releases.
Definition at line 31 of file feed_controller.php.
Referenced by software_comments().
FeedController::software_comments ()
Action method that generates the feed of software comments.
Definition at line 46 of file feed_controller.php.
References software().
FeedController::diario ()
Action method that generates the feed of Diario articles.
Definition at line 58 of file feed_controller.php.
FeedController::diario_comments ()
Action method that generates the feed of Diario comments.
Definition at line 72 of file feed_controller.php.
FeedController::feeds_list ()
Action method that generates a list of available feeds.
Definition at line 84 of file feed_controller.php.
References BaseController::render().
FeedController::feed_permalink ()
Returns the permalink URL for the current feed.
Definition at line 93 of file feed_controller.php.
References BaseController::url_to_myself().
Member Data Documentation
FeedController::$mimetype = 'text/xml; charset=utf-8' [protected]
A MIME type for the response.
mimetype
Reimplemented from BaseController.
Definition at line 16 of file feed_controller.php.
FeedController::$type = 'rss' [protected]
An extension for action pages.
type
Reimplemented from BaseController.
Definition at line 17 of file feed_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/feed_controller.php