Emeraldion Lodge (codename Zelda): MetaController Class Reference
MetaController Class Reference
Controller for the Meta section.
Public Member Functions
index ()
Default action method.
referrers ()
Action method that shows the referrer URLs of the visits.
referrers_list ()
Action method that builds the list of referrers.
visits ()
Action method that shows the last visits.
visits_list ()
Action method that builds the list of visits.
queries ()
Action method that shows the queries that brought visitors on the website.
queries_list ()
Action method that builds the list of queries.
outbounds ()
Action method that shows the outbound links that have been followed on the website.
outbounds_list ()
Action method that builds the list of outbounds.
hits_by_host ()
Action method that shows the list of visitors' hosts.
hits_by_host_list ()
Action method that builds the list of hits by host.
ip ()
Action method that returns all visits made from an IP address.
unblock_ip ()
Action method to remove an IP address from the black list.
block_ip ()
Action method to add an IP address to the black list.
blocked_ips ()
Action method to list the blacklisted IP addresses.
blocked_ips_list ()
Action method that creates a list of the blacklisted IP addresses.
id ()
Action method to get a single visit by its id.
attribute_chooser ()
Action method to get an attribute chooser.
attribute_visits ()
Action method to attribute a visit to a person.
Protected Member Functions
init ()
Initialization method for the Controller.
Detailed Description
Controller for the Meta section.
Meta refers to all those diagnostic and introspectional functions that allow visit monitoring, traffic shaping etc.
Definition at line 18 of file meta_controller.php.
Member Function Documentation
MetaController::init () [protected]
Initialization method for the Controller.
Here you can define custom filters, caching strategies etc.
Reimplemented from BaseController.
Definition at line 25 of file meta_controller.php.
References BaseController::after_filter(), and BaseController::before_filter().
MetaController::index ()
Default action method.
This method handles the default action.
Reimplemented from EmeController.
Definition at line 36 of file meta_controller.php.
MetaController::referrers ()
Action method that shows the referrer URLs of the visits.
By analyzing referrers, you can easily understand what websites contain links to your website.
Definition at line 46 of file meta_controller.php.
Referenced by referrers_list().
MetaController::referrers_list ()
Action method that builds the list of referrers.
This method is invoked with AJAX calls to update the list of referrers in a dynamic fashion.
Definition at line 56 of file meta_controller.php.
References $db, referrers(), and BaseController::render().
MetaController::visits ()
Action method that shows the last visits.
Definition at line 105 of file meta_controller.php.
Referenced by ip(), and visits_list().
MetaController::visits_list ()
Action method that builds the list of visits.
This method is invoked with AJAX calls to update the list of visits in a dynamic fashion.
Definition at line 115 of file meta_controller.php.
References $db, BaseController::render(), and visits().
MetaController::queries ()
Action method that shows the queries that brought visitors on the website.
By analyzing queries, you can easily understand what keywords lead visitors to your website.
Definition at line 150 of file meta_controller.php.
Referenced by queries_list().
MetaController::queries_list ()
Action method that builds the list of queries.
This method is invoked with AJAX calls to update the list of queries in a dynamic fashion.
Definition at line 160 of file meta_controller.php.
References $db, queries(), and BaseController::render().
MetaController::outbounds ()
Action method that shows the outbound links that have been followed on the website.
Definition at line 217 of file meta_controller.php.
Referenced by outbounds_list().
MetaController::outbounds_list ()
Action method that builds the list of outbounds.
This method is invoked with AJAX calls to update the list of queries in a dynamic fashion.
Definition at line 227 of file meta_controller.php.
References outbounds(), and BaseController::render().
MetaController::hits_by_host ()
Action method that shows the list of visitors' hosts.
By analyzing visitors' hosts, you can easily understand who visited your website.
Definition at line 278 of file meta_controller.php.
MetaController::hits_by_host_list ()
Action method that builds the list of hits by host.
This method is invoked with AJAX calls to update the list of hits by host in a dynamic fashion.
Definition at line 288 of file meta_controller.php.
References $db, Time::ago(), Host::by_ip_addr(), and BaseController::render().
MetaController::ip ()
Action method that returns all visits made from an IP address.
Definition at line 332 of file meta_controller.php.
References BaseController::render(), and visits().
MetaController::unblock_ip ()
Action method to remove an IP address from the black list.
Definition at line 346 of file meta_controller.php.
References l().
MetaController::block_ip ()
Action method to add an IP address to the black list.
Reimplemented from EmeController.
Definition at line 362 of file meta_controller.php.
References l().
MetaController::blocked_ips ()
Action method to list the blacklisted IP addresses.
Definition at line 374 of file meta_controller.php.
Referenced by blocked_ips_list().
MetaController::blocked_ips_list ()
Action method that creates a list of the blacklisted IP addresses.
This method is invoked with AJAX calls to update the list of blocked IPs in a dynamic fashion.
Definition at line 384 of file meta_controller.php.
References $db, blocked_ips(), and BaseController::render().
MetaController::id ()
Action method to get a single visit by its id.
Definition at line 399 of file meta_controller.php.
References BaseController::render().
MetaController::attribute_chooser ()
Action method to get an attribute chooser.
This method is designed to be called as an AJAX update. It provides a select box control to choose a person whom attribute something to.
Definition at line 412 of file meta_controller.php.
References BaseController::render().
MetaController::attribute_visits ()
Action method to attribute a visit to a person.
This method is designed to be called with AJAX, and does not render anything. It assigns a visit object to a person object.
Definition at line 425 of file meta_controller.php.
References $db, $visits, BaseController::render(), and s().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/meta_controller.php