Emeraldion Lodge (codename Zelda): Book Class Reference
Book Class Reference
Model object for books.
Public Member Functions
permalink ()
Creates a permalink anchor for this book.
bol_url ()
Returns the URL of the bol.it book page for the receiver.
long_description ()
Returns a detailed description of the receiver.
Detailed Description
Model object for books.
Book objects represent printed publications that I have read.
Definition at line 10 of file book.php.
Member Function Documentation
Book::permalink ()
Creates a permalink anchor for this book.
This method should be refactored to make use of the canonical relative_url / permalink pair.
Definition at line 17 of file book.php.
References a(), bol_url(), and long_description().
Book::bol_url ()
Returns the URL of the bol.it book page for the receiver.
Definition at line 33 of file book.php.
Referenced by permalink().
Book::long_description ()
Returns a detailed description of the receiver.
Definition at line 42 of file book.php.
References author, and title.
Referenced by permalink().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/models/book.php