Emeraldion Lodge (codename Zelda): TrackbackController Class Reference
TrackbackController Class Reference
Controller for Trackback actions.
Public Member Functions
init ()
Custom initialization for the controller object.
diario ()
Action for accepting pingbacks for the Diario blog.
software ()
Action for accepting pingbacks for Software products.
Protected Member Functions
require_post ()
Simple filter method that triggers a 405 error when using a method other than POST.
Detailed Description
Controller for Trackback actions.
Trackback is a blogging feature that allows a blog to be notified about other blogs quoting a post in an article. Trackback "pings" contain information on the blog name, post URL and an excerpt of the article. It became suddenly such a source of SPAM, that the term SPING (SPAM Ping) was created. Trackback pings are now commonly subject to moderation (either manual or automatic).
Definition at line 17 of file trackback_controller.php.
Member Function Documentation
TrackbackController::init ()
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Definition at line 19 of file trackback_controller.php.
References BaseController::before_filter().
TrackbackController::diario ()
Action for accepting pingbacks for the Diario blog.
Definition at line 28 of file trackback_controller.php.
References l(), and BaseController::redirect_to().
TrackbackController::software ()
Action for accepting pingbacks for Software products.
Definition at line 61 of file trackback_controller.php.
References l(), and BaseController::redirect_to().
TrackbackController::require_post () [protected]
Simple filter method that triggers a 405 error when using a method other than POST.
Definition at line 94 of file trackback_controller.php.
References HTTP::error().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/trackback_controller.php