Emeraldion Lodge (codename Zelda): BaseController Class Reference
BaseController Class Reference
Abstract base class for action controllers.
Public Member Functions
BaseController ()
Default constructor for controller objects.
link_to ($text, $params=array())
Links to another action.
link_to_remote ($text, $params=array())
Links to another action, with AJAX support.
button_to ($text, $params=array())
Creates a button that links to another action.
url_to ($params)
Creates a URL to an action.
url_to_myself ($relative=TRUE)
Creates a URL to the current action.
make_relative_url ($params)
Creates a URL to an action.
render ($params)
Requests the rendering of the response.
render_as_string ($params)
Requests the rendering of the response as a string.
render_page ()
Renders the page as a response for the current request.
render_component ($params)
Renders a view from a controller other than self.
set_title ($title)
Sets the title for the current page.
flash ($message, $type= 'error')
Shows a message to the user, with an optional type qualifier.
index ()
This is the default action method.
Public Attributes
$name
The name of the controller.
$action
The name of the action.
$title
A title for the page.
Protected Member Functions
initialize ()
Initializes the controller object.
init ()
Custom initialization for the controller object.
before_filter ($filter, $params=NULL)
Registers a function as a filter to be executed before the action is invoked.
after_filter ($filter, $params=NULL)
Registers a function as a filter to be executed after the action is invoked.
caches_page ($page)
Requests that a page be cached.
conditionally_caches_page ($page, $condition=TRUE)
Requests that a page be cached when a condition is verified.
caches_action ($page)
Requests that an action be cached.
cached_page_exists ()
Checks if a cached version of the current action exists.
cached_page_filename ()
Returns a name for the cached page of current action.
expire_cached_page ($params)
Requests that the page(s) defined by params be removed from the caches.
redirect_to ($params)
Redirects the response to another action, or URL.
redirect_to_referrer ($or_else=NULL)
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
unknown_action ()
render_layout ($params)
Renders the layout for the current view.
load_part_contents ($filename)
Loads the contents of the desired view file.
strip_external_php_tags ($php_code)
Strips beginning and ending delimiters from the given PHP code.
compress ()
Compresses the response with gzip encoding.
Protected Attributes
$type = 'html'
An extension for action pages.
$mimetype = 'text/html'
A MIME type for the response.
Private Member Functions
filter_applicable ($conditions)
Determines if a filter is applicable for the current action.
abort_and_flush ()
Interrupts the processing of the request.
Private Attributes
$headers
An array of headers for the response.
$rendered = FALSE
Flag to tell if the response has been already rendered.
$before_filters = array()
Array of filters that should be called before the response has been rendered.
$after_filters = array()
Array of filters that should be called after the response has been rendered.
$pages_cached = array()
Array of pages that should be cached.
$actions_cached = array()
Array of actions that should be cached.
Detailed Description
Abstract base class for action controllers.
Project EmeRails - Codename Ocarina
© 2008 Claudio Procida http://www.emeraldion.it
A subclass of BaseController is in charge of handling a set of actions. It creates the network of model objects that will be rendered by the views, handles and validates postback data, defines and applies before and after filters.
Definition at line 23 of file base_controller.php.
Member Function Documentation
BaseController::BaseController ()
Default constructor for controller objects.
Subclassers should not override this method. Do your specialized initialization in the init method.
Definition at line 97 of file base_controller.php.
References init(), and initialize().
BaseController::initialize () [protected]
Initializes the controller object.
Subclassers should not override this method. Do your specialized initialization in the init method.
Definition at line 111 of file base_controller.php.
References title, and unknown_action().
Referenced by BaseController().
BaseController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented in AboutController, AssetController, BackendController, BlogController, ContactController, DiarioController, DonateController, ErrorController, FeedController, HomeController, KmlController, LanguageController, LegalController, LoginController, MetaController, MorseController, ServicesController, SoftwareController, SparkleController, and TrackbackController.
Definition at line 140 of file base_controller.php.
Referenced by BaseController().
BaseController::before_filter ($ filter, $ params = NULL) [protected]
Registers a function as a filter to be executed before the action is invoked.
Action filtering
EmeRails allows the developer to call one or more functions before the action is actually invoked.
This may be useful to execute common code which is required before different action methods, to perform authentication checks, etc.
The controller keeps a list (FIFO) of filters that are invoked before the action method. Everywhere in the filters chain, you can redirect the request or simply return silently to resign control to the next filter, or the action itself. You can customize the way the filter is invoked by passing the optional parameter params.
Examples:
$this->before_filter(array('foo', 'bar'));
Executes the foo and bar filters (in this order) whatever action is requested.
$this->before_filter('foo', array('only' => 'index'));
Executes the foo filter only when the index action is requested.
$this->before_filter('foo', array('except' => array('index', 'list')));
Executes the foo filter unless the index or list actions are requested.
Parameters:
filter The name (or an array of names) of the method to be executed as filter. Currently, it must be a method of the controller.
params Parameters that define when the filter has to be invoked.
Definition at line 180 of file base_controller.php.
Referenced by TrackbackController::init(), SoftwareController::init(), ServicesController::init(), MorseController::init(), MetaController::init(), LoginController::init(), LegalController::init(), LanguageController::init(), HomeController::init(), FeedController::init(), DonateController::init(), DiarioController::init(), ContactController::init(), BackendController::init(), and AboutController::init().
BaseController::after_filter ($ filter, $ params = NULL) [protected]
Registers a function as a filter to be executed after the action is invoked.
EmeRails allows the developer to call one or more functions after the action has been invoked.
This allows the developer to perform manipulation of the response, to enable markup expansion, etc.
The controller keeps a list (FIFO) of filters that are invoked after the action method has returned. Everywhere in the filters chain, you can redirect the request or simply return silently to resign control to the next filter, or the response be flushed to the client. You can customize the way the filter is invoked by passing the optional parameter params.
Examples:
$this->after_filter(array('foo', 'bar'));
Executes the foo and bar filters (in this order) whatever action is requested.
$this->after_filter('foo', array('only' => 'index'));
Executes the foo filter only when the index action is requested.
$this->after_filter('foo', array('except' => array('index', 'list')));
Executes the foo filter unless the index or list actions are requested.
Parameters:
filter The name (or an array of names) of the method to be executed as filter. Currently, it must be a method of the controller.
params Parameters that define when the filter has to be invoked.
Definition at line 223 of file base_controller.php.
Referenced by SparkleController::init(), SoftwareController::init(), ServicesController::init(), MorseController::init(), MetaController::init(), LegalController::init(), KmlController::init(), HomeController::init(), FeedController::init(), ErrorController::init(), DiarioController::init(), ContactController::init(), BackendController::init(), AssetController::init(), and AboutController::init().
BaseController::filter_applicable ($ conditions) [private]
Determines if a filter is applicable for the current action.
This method checks the conditions argument in order to determine if the filter (whatever it is) can be applied for the current action.
Parameters:
conditions An array containing directives for the application of filters. It has the same format of the second parameter of methods before_filter and after_filter.
Definition at line 245 of file base_controller.php.
Referenced by render_page().
BaseController::caches_page ($ page) [protected]
Requests that a page be cached.
Page caching
This method registers the page page to be cached after it has been executed and rendered.
Parameters:
page The name (or an array of names) of a page that should be cached.
Definition at line 291 of file base_controller.php.
Referenced by conditionally_caches_page(), SparkleController::init(), SoftwareController::init(), and FeedController::init().
BaseController::conditionally_caches_page ($ page, $ condition = TRUE) [protected]
Requests that a page be cached when a condition is verified.
Convenience method to cache the requested page only if the condition argument evaluates as TRUE.
Parameters:
page The name (or an array of names) of a page that should be cached.
condition Flag to decide if the page should be cached.
Definition at line 312 of file base_controller.php.
References caches_page().
BaseController::caches_action ($ page) [protected]
Requests that an action be cached.
This method is currently unused.
Parameters:
page The name of a page that should be cached.
Definition at line 326 of file base_controller.php.
BaseController::cached_page_exists () [protected]
Checks if a cached version of the current action exists.
This method checks the existence of the file whose name is returned by cached_page_filename.
Definition at line 336 of file base_controller.php.
References cached_page_filename().
Referenced by render_page().
BaseController::cached_page_filename () [protected]
Returns a name for the cached page of current action.
This method creates a filename that is uniquely associated with the current controller, action, argument identifier and and language.
Definition at line 347 of file base_controller.php.
Referenced by cached_page_exists(), and render_page().
BaseController::expire_cached_page ($ params) [protected]
Requests that the page(s) defined by params be removed from the caches.
This method removes from the caches all pages that match the params argument for every supported language.
Definition at line 361 of file base_controller.php.
References $action, and Localization::$languages.
Referenced by BackendController::diario_post_add(), SoftwareController::download(), BackendController::expire_cached_software_pages(), SoftwareController::post_comment(), and DiarioController::post_comment().
BaseController::redirect_to ($ params) [protected]
Redirects the response to another action, or URL.
Response manipulation
This method can either redirect the response to an URL, or another action, whose parameters are contained in the params argument.
Parameters:
params An URL, or an array with details of the action for response redirection.
Definition at line 389 of file base_controller.php.
References url_to().
Referenced by SoftwareController::_init_software(), EmeController::check_auth(), TrackbackController::diario(), BackendController::diario_comment_discard(), BackendController::diario_comment_moderate(), BackendController::diario_pingback_moderate(), BackendController::diario_post_add(), BackendController::diario_post_edit(), SoftwareController::donate(), SoftwareController::download(), SoftwareController::download_stats(), OutboundController::index(), LegalController::index(), ErrorController::index(), DiarioController::index(), BackendController::index(), AboutController::index(), BlogController::init(), LoginController::login(), LoginController::logout(), SoftwareController::post_comment(), DiarioController::post_comment(), DiarioController::read(), redirect_to_referrer(), SoftwareController::releasenotes(), LoginController::request_password(), LoginController::request_sent(), DiarioController::search(), ContactController::send(), BackendController::server_error_delete(), BackendController::server_error_next(), BackendController::server_error_previous(), BackendController::server_error_read(), LanguageController::set(), TrackbackController::software(), BackendController::software_artifact_add(), BackendController::software_artifact_create(), BackendController::software_artifact_edit(), BackendController::software_artifact_list(), BackendController::software_comment_discard(), BackendController::software_comment_list(), BackendController::software_comment_moderate(), BackendController::software_delete(), BackendController::software_downloads_by_artifact(), BackendController::software_downloads_by_release(), BackendController::software_edit(), BackendController::software_pingback_moderate(), BackendController::software_quote_add(), BackendController::software_quote_create(), BackendController::software_quote_delete(), BackendController::software_quote_edit(), BackendController::software_quote_list(), BackendController::software_release_add(), BackendController::software_release_create(), BackendController::software_release_edit(), BackendController::software_release_list(), DiarioController::tag(), ContactController::thank_you(), and SoftwareController::user_quotes().
BaseController::redirect_to_referrer ($ or_else = NULL) [protected]
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
Parameters:
or_else An URL, or an array with details of the action for response redirection if no HTTP_REFERER is set.
Definition at line 424 of file base_controller.php.
References redirect_to().
Referenced by LanguageController::set().
BaseController::link_to ($ text, $ params = array())
Links to another action.
Hyperlinks to actions
This method creates a hyperlink to another action, as specified in the params argument. This params array has the same semantics used in the make_relative_url method. You can also provide an explicit URL for the hyperlink by passing the href key. This will override other parameters.
See also:
link_to_remote($text, $params);
Parameters:
text A text label for the hyperlink.
params Array of key value pairs defining the hyperlink.
Definition at line 452 of file base_controller.php.
References $text, a(), and make_relative_url().
BaseController::link_to_remote ($ text, $ params = array())
Links to another action, with AJAX support.
This method behaves like link_to, except that it also adds an AJAX handler to replace the contents of the element with id target. You can also provide different URLs for the static and AJAX hyperlink, by explicitly setting the keys in params: href, remote_url, or both.
See also:
link_to($text, $params);
Parameters:
text A text label for the hyperlink.
params Array of key value pairs defining the hyperlink.
Definition at line 478 of file base_controller.php.
References $text, a(), l(), and make_relative_url().
BaseController::button_to ($ text, $ params = array())
Creates a button that links to another action.
This method creates a button that links to another action, as specified in the params argument. This params array has the same semantics used in the make_relative_url method. You can also provide an explicit URL for the hyperlink by passing the href key. This will override other parameters.
Parameters:
text A text label for the button.
params Array of key value pairs defining the hyperlink.
Definition at line 505 of file base_controller.php.
References $text, button(), joined_lower(), and make_relative_url().
BaseController::unknown_action () [protected]
Definition at line 521 of file base_controller.php.
References HTTP::error().
Referenced by initialize().
BaseController::url_to ($ params)
Creates a URL to an action.
This method builds a URL to an action, as specified in the params argument. The params array has the same semantics used in the make_relative_url method.
Parameters:
params Array of key value pairs defining the URL.
Definition at line 534 of file base_controller.php.
References make_relative_url().
Referenced by redirect_to(), and url_to_myself().
BaseController::url_to_myself ($ relative = TRUE)
Creates a URL to the current action.
This method builds a URL to the current action.
Parameters:
relative Whether the URL should contain only the path, or be a qualified URI.
Definition at line 546 of file base_controller.php.
References url_to().
Referenced by FeedController::feed_permalink().
BaseController::make_relative_url ($ params)
Creates a URL to an action.
This method builds a URL to an action, as specified in the params argument. The params array has the following semantics:
controller: the name of the desired controller (optional, defaults to self). action: the name of the desired action (optional, defaults to 'index'). id: the id of the argument of the action (optional). type: the type (extension) of the resource (optional, defaults to 'html'). query_string: the query string part of the URL (optional). hash: the target HTML anchor of the URL (optional).
Parameters:
params Array of key value pairs defining the URL.
Definition at line 572 of file base_controller.php.
References $type.
Referenced by button_to(), link_to(), link_to_remote(), and url_to().
BaseController::render ($ params)
Requests the rendering of the response.
Response rendering
This method is responsible of loading the view and layout relative to the current controller and action, parsing their content, and returning the result to be appended to the response.
The params array has the following semantics:
action: the name of the action for which render a view (defaults to current action).
layout: the layout used to render the view (optional, defaults to current action). It can be set to NULL to render the view with no layout (the same result can be obtained using the nolayout request parameter).
return: return the rendered view as a string, rather than flushing it to the output buffer.
partial: triggers the partial rendering mode (optional).
object: passes an argument to be used by the partial view (optional).
Parameters:
params Parameters defining how the rendering should be realized.
Definition at line 638 of file base_controller.php.
References $action, $rendered, content_for_layout, load_part_contents(), and render_layout().
Referenced by MetaController::attribute_chooser(), MetaController::attribute_visits(), MetaController::blocked_ips_list(), DiarioController::calendar(), SoftwareController::changelog(), SoftwareController::comments(), DiarioController::comments(), DiarioController::date(), MorseController::decode(), SoftwareController::development(), BackendController::diario_post_compose(), SoftwareController::download_stats(), MorseController::encode(), FeedController::feeds_list(), MetaController::hits_by_host_list(), MetaController::id(), DiarioController::index(), index(), AssetController::index(), SoftwareController::instructions(), MetaController::ip(), MaintenanceController::kill_claudio(), KmlController::last_n_visits(), DiarioController::last_posts(), SoftwareController::last_releases(), SoftwareController::license(), DiarioController::live_search(), SoftwareController::main(), MetaController::outbounds_list(), AboutController::primula_toggle(), MetaController::queries_list(), MetaController::referrers_list(), SoftwareController::register(), SoftwareController::releasenotes(), render_as_string(), render_page(), DiarioController::search(), BackendController::server_error_next(), BackendController::server_error_previous(), SoftwareController::show(), BackendController::software_artifact_create(), BackendController::software_create(), BackendController::software_quote_create(), BackendController::software_release_create(), DiarioController::tag(), MaintenanceController::update_macupdate_ratings(), MaintenanceController::update_versiontracker_ratings(), SoftwareController::user_quotes(), MetaController::visits_list(), and SoftwareController::widgets_versioncheck().
BaseController::render_as_string ($ params)
Requests the rendering of the response as a string.
This method calls render by passing the return parameter to TRUE, and returns the rendered response as a string. The params array has the same semantics discussed in the render method.
Parameters:
params Parameters defining how the rendering should be realized.
Definition at line 730 of file base_controller.php.
References render().
BaseController::render_layout ($ params) [protected]
Renders the layout for the current view.
This method is responsible of loading the layout as defined in the params argument, parsing it and returning the result. The params array has the same semantics of the render method, although only the layout key is relevant.
Parameters:
params Parameters defining how the rendering should be realized.
Definition at line 746 of file base_controller.php.
References $rendered, and load_part_contents().
Referenced by render().
BaseController::render_page ()
Renders the page as a response for the current request.
This method is responsible for building the response for the current request.
All before filters that are registered for the current action are executed.
If the current page is cacheable, and a cached version already exists in the caches, it is returned; otherwise it is rendered and eventually stored in the cache folder.
All after filters that are registered for the current action are executed.
Finally, the response is flushed to the client.
Definition at line 786 of file base_controller.php.
References cached_page_exists(), cached_page_filename(), HTTP::error(), filter_applicable(), and render().
BaseController::render_component ($ params)
Renders a view from a controller other than self.
This method renders a view from a controller other than self, for example when embedding a view into another view.
The params array has the same semantics of the render method, with the following additions:
controller: the name of the controller responsible for the view (defaults to self).
Parameters:
params Parameters defining how the rendering should be realized.
Definition at line 874 of file base_controller.php.
References Localization::add_strings_table(), and table_name_to_class_name().
BaseController::load_part_contents ($ filename) [protected]
Loads the contents of the desired view file.
This method returns the contents of the requested view file without parsing.
Parameters:
filename The name of the view file to load.
Reimplemented in EmeController.
Definition at line 923 of file base_controller.php.
References HTTP::error(), and strip_external_php_tags().
Referenced by render(), and render_layout().
BaseController::strip_external_php_tags ($ php_code) [protected]
Strips beginning and ending delimiters from the given PHP code.
This method removes the beginning and ending PHP code delimiters to enable subsequent parsing with eval.
Parameters:
php_code The code to be stripped.
Definition at line 940 of file base_controller.php.
Referenced by EmeController::load_part_contents(), and load_part_contents().
BaseController::set_title ($ title)
Sets the title for the current page.
Miscellaneous
Parameters:
title A title for the current page.
Definition at line 970 of file base_controller.php.
References $title, and title.
Referenced by DonateController::index(), ContactController::index(), and LoginController::lost_password().
BaseController::abort_and_flush () [private]
Interrupts the processing of the request.
Definition at line 979 of file base_controller.php.
BaseController::flash ($ message, $ type = 'error')
Shows a message to the user, with an optional type qualifier.
Messages handling
The flash is a facility to store messages that should be visualized as a result of some event, or as a response to the user's previous request.
Parameters:
message A message to show to the user.
type The type of the message (e.g. 'warning').
Definition at line 997 of file base_controller.php.
References $type.
Referenced by SoftwareController::_init_software(), EmeController::check_auth(), SoftwareController::download_stats(), LoginController::login(), LoginController::logout(), SoftwareController::post_comment(), DiarioController::post_comment(), LoginController::request_password(), ContactController::send(), BackendController::server_error_read(), BackendController::software_downloads_by_artifact(), BackendController::software_downloads_by_release(), and SoftwareController::user_quotes().
BaseController::index ()
This is the default action method.
Action methods
Reimplemented in AboutController, AssetController, BackendController, ContactController, DiarioController, DonateController, EmeController, ErrorController, HomeController, KmlController, LegalController, MetaController, MorseController, OutboundController, ServicesController, SoftwareController, and SparkleController.
Definition at line 1011 of file base_controller.php.
References render().
BaseController::compress () [protected]
Compresses the response with gzip encoding.
Filters
This after-filter is capable of compressing the response with gzip encoding, in order to save bandwidth. If the client does not support gzip encoding, the response is not altered.
Definition at line 1027 of file base_controller.php.
Member Data Documentation
BaseController::$name
The name of the controller.
name
Definition at line 29 of file base_controller.php.
BaseController::$action
The name of the action.
action
Definition at line 35 of file base_controller.php.
Referenced by expire_cached_page(), and render().
BaseController::$title
A title for the page.
title
Definition at line 41 of file base_controller.php.
Referenced by set_title().
BaseController::$type = 'html' [protected]
An extension for action pages.
type
Reimplemented in FeedController.
Definition at line 47 of file base_controller.php.
Referenced by flash(), and make_relative_url().
BaseController::$mimetype = 'text/html' [protected]
A MIME type for the response.
mimetype
Reimplemented in DiarioController, FeedController, KmlController, SoftwareController, and SparkleController.
Definition at line 53 of file base_controller.php.
BaseController::$headers [private]
An array of headers for the response.
headers
Definition at line 59 of file base_controller.php.
BaseController::$rendered = FALSE [private]
Flag to tell if the response has been already rendered.
rendered
Definition at line 65 of file base_controller.php.
Referenced by render(), and render_layout().
BaseController::$before_filters = array() [private]
Array of filters that should be called before the response has been rendered.
before_filters
Definition at line 71 of file base_controller.php.
BaseController::$after_filters = array() [private]
Array of filters that should be called after the response has been rendered.
after_filters
Definition at line 77 of file base_controller.php.
BaseController::$pages_cached = array() [private]
Array of pages that should be cached.
pages_cached
Definition at line 83 of file base_controller.php.
BaseController::$actions_cached = array() [private]
Array of actions that should be cached.
actions_cached
Definition at line 89 of file base_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/base_controller.php