Emeraldion Lodge (codename Zelda): Markdown_Parser Class Reference
Markdown_Parser Class Reference
Public Member Functions
Markdown_Parser ()
transform ($text)
stripLinkDefinitions ($text)
_stripLinkDefinitions_callback ($matches)
hashHTMLBlocks ($text)
_hashHTMLBlocks_callback ($matches)
hashPart ($text, $boundary= 'X')
hashBlock ($text)
runBlockGamut ($text)
runBasicBlockGamut ($text)
doHorizontalRules ($text)
runSpanGamut ($text)
doHardBreaks ($text)
_doHardBreaks_callback ($matches)
doAnchors ($text)
_doAnchors_reference_callback ($matches)
_doAnchors_inline_callback ($matches)
doImages ($text)
_doImages_reference_callback ($matches)
_doImages_inline_callback ($matches)
doHeaders ($text)
_doHeaders_callback_setext ($matches)
_doHeaders_callback_atx ($matches)
doLists ($text)
_doLists_callback ($matches)
processListItems ($list_str, $marker_any)
_processListItems_callback ($matches)
doCodeBlocks ($text)
_doCodeBlocks_callback ($matches)
makeCodeSpan ($code)
doItalicsAndBold ($text)
_doItalicAndBold_em_callback ($matches)
_doItalicAndBold_strong_callback ($matches)
doBlockQuotes ($text)
_doBlockQuotes_callback ($matches)
_doBlockQuotes_callback2 ($matches)
formParagraphs ($text)
encodeAmpsAndAngles ($text)
doAutoLinks ($text)
_doAutoLinks_url_callback ($matches)
_doAutoLinks_email_callback ($matches)
encodeEmailAddress ($addr)
parseSpan ($str)
handleSpanToken ($token, &$str)
outdent ($text)
detab ($text)
_detab_callback ($matches)
_initDetab ()
unhash ($text)
_unhash_callback ($matches)
Public Attributes
$nested_brackets_depth = 6
$nested_brackets
$nested_url_parenthesis_depth = 4
$nested_url_parenthesis
$escape_chars = '\`*_{}[]()>#+-.!'
$empty_element_suffix = MARKDOWN_EMPTY_ELEMENT_SUFFIX
$tab_width = MARKDOWN_TAB_WIDTH
$no_markup = false
$no_entities = false
$urls = array()
$titles = array()
$html_hashes = array()
$in_anchor = false
$document_gamut
$block_gamut
$span_gamut
$list_level = 0
$utf8_strlen = 'mb_strlen'
Detailed Description
Definition at line 191 of file markdown.php.
Member Function Documentation
Markdown_Parser::Markdown_Parser ()
Definition at line 213 of file markdown.php.
References _initDetab().
Markdown_Parser::transform ($ text)
Definition at line 243 of file markdown.php.
References $text, detab(), and hashHTMLBlocks().
Markdown_Parser::stripLinkDefinitions ($ text)
Definition at line 293 of file markdown.php.
References $text.
Markdown_Parser::_stripLinkDefinitions_callback ($ matches)
Definition at line 323 of file markdown.php.
References encodeAmpsAndAngles().
Markdown_Parser::hashHTMLBlocks ($ text)
Definition at line 332 of file markdown.php.
References $text.
Referenced by runBlockGamut(), and transform().
Markdown_Parser::_hashHTMLBlocks_callback ($ matches)
Definition at line 470 of file markdown.php.
References $text, and hashBlock().
Markdown_Parser::hashPart ($ text, $ boundary = 'X')
Definition at line 477 of file markdown.php.
References $i, $text, and unhash().
Referenced by _doAnchors_inline_callback(), _doAnchors_reference_callback(), _doAutoLinks_email_callback(), _doAutoLinks_url_callback(), _doHardBreaks_callback(), _doImages_inline_callback(), _doImages_reference_callback(), _doItalicAndBold_em_callback(), _doItalicAndBold_strong_callback(), handleSpanToken(), hashBlock(), and makeCodeSpan().
Markdown_Parser::hashBlock ($ text)
Definition at line 500 of file markdown.php.
References $text, and hashPart().
Referenced by _doBlockQuotes_callback(), _doHeaders_callback_atx(), _doHeaders_callback_setext(), _doLists_callback(), _hashHTMLBlocks_callback(), and doHorizontalRules().
Markdown_Parser::runBlockGamut ($ text)
Definition at line 521 of file markdown.php.
References $text, hashHTMLBlocks(), and runBasicBlockGamut().
Referenced by _doBlockQuotes_callback(), and _processListItems_callback().
Markdown_Parser::runBasicBlockGamut ($ text)
Definition at line 535 of file markdown.php.
References $text, and formParagraphs().
Referenced by runBlockGamut().
Markdown_Parser::doHorizontalRules ($ text)
Definition at line 552 of file markdown.php.
References $text, and hashBlock().
Markdown_Parser::runSpanGamut ($ text)
Definition at line 594 of file markdown.php.
References $text.
Referenced by _doAnchors_inline_callback(), _doAnchors_reference_callback(), _doItalicAndBold_em_callback(), _doItalicAndBold_strong_callback(), _processListItems_callback(), and formParagraphs().
Markdown_Parser::doHardBreaks ($ text)
Definition at line 606 of file markdown.php.
References $text.
Markdown_Parser::_doHardBreaks_callback ($ matches)
Definition at line 611 of file markdown.php.
References hashPart().
Markdown_Parser::doAnchors ($ text)
Definition at line 616 of file markdown.php.
References $text.
Markdown_Parser::_doAnchors_reference_callback ($ matches)
Definition at line 686 of file markdown.php.
References encodeAmpsAndAngles(), hashPart(), and runSpanGamut().
Markdown_Parser::_doAnchors_inline_callback ($ matches)
Definition at line 720 of file markdown.php.
References encodeAmpsAndAngles(), hashPart(), and runSpanGamut().
Markdown_Parser::doImages ($ text)
Definition at line 742 of file markdown.php.
References $text.
Markdown_Parser::_doImages_reference_callback ($ matches)
Definition at line 797 of file markdown.php.
References hashPart().
Markdown_Parser::_doImages_inline_callback ($ matches)
Definition at line 824 of file markdown.php.
References hashPart().
Markdown_Parser::doHeaders ($ text)
Definition at line 842 of file markdown.php.
References $text.
Markdown_Parser::_doHeaders_callback_setext ($ matches)
Definition at line 872 of file markdown.php.
References hashBlock().
Markdown_Parser::_doHeaders_callback_atx ($ matches)
Definition at line 877 of file markdown.php.
References hashBlock().
Markdown_Parser::doLists ($ text)
Definition at line 884 of file markdown.php.
References $text.
Referenced by _processListItems_callback().
Markdown_Parser::_doLists_callback ($ matches)
Definition at line 941 of file markdown.php.
References hashBlock(), and processListItems().
Markdown_Parser::processListItems ($ list_str, $ marker_any)
Definition at line 961 of file markdown.php.
Referenced by _doLists_callback().
Markdown_Parser::_processListItems_callback ($ matches)
Definition at line 1005 of file markdown.php.
References doLists(), outdent(), runBlockGamut(), and runSpanGamut().
Markdown_Parser::doCodeBlocks ($ text)
Definition at line 1027 of file markdown.php.
References $text.
Markdown_Parser::_doCodeBlocks_callback ($ matches)
Definition at line 1045 of file markdown.php.
References outdent().
Markdown_Parser::makeCodeSpan ($ code)
Definition at line 1059 of file markdown.php.
References hashPart().
Referenced by handleSpanToken().
Markdown_Parser::doItalicsAndBold ($ text)
Definition at line 1068 of file markdown.php.
References $text.
Markdown_Parser::_doItalicAndBold_em_callback ($ matches)
Definition at line 1098 of file markdown.php.
References $text, hashPart(), and runSpanGamut().
Markdown_Parser::_doItalicAndBold_strong_callback ($ matches)
Definition at line 1103 of file markdown.php.
References $text, hashPart(), and runSpanGamut().
Markdown_Parser::doBlockQuotes ($ text)
Definition at line 1110 of file markdown.php.
References $text.
Markdown_Parser::_doBlockQuotes_callback ($ matches)
Definition at line 1125 of file markdown.php.
References hashBlock(), and runBlockGamut().
Markdown_Parser::_doBlockQuotes_callback2 ($ matches)
Definition at line 1139 of file markdown.php.
Markdown_Parser::formParagraphs ($ text)
Definition at line 1146 of file markdown.php.
References $text, runSpanGamut(), and unhash().
Referenced by runBasicBlockGamut().
Markdown_Parser::encodeAmpsAndAngles ($ text)
Definition at line 1216 of file markdown.php.
References $text.
Referenced by _doAnchors_inline_callback(), _doAnchors_reference_callback(), _doAutoLinks_url_callback(), and _stripLinkDefinitions_callback().
Markdown_Parser::doAutoLinks ($ text)
Definition at line 1236 of file markdown.php.
References $text.
Markdown_Parser::_doAutoLinks_url_callback ($ matches)
Definition at line 1255 of file markdown.php.
References encodeAmpsAndAngles(), and hashPart().
Markdown_Parser::_doAutoLinks_email_callback ($ matches)
Definition at line 1260 of file markdown.php.
References encodeEmailAddress(), and hashPart().
Markdown_Parser::encodeEmailAddress ($ addr)
Definition at line 1267 of file markdown.php.
References $text.
Referenced by _doAutoLinks_email_callback().
Markdown_Parser::parseSpan ($ str)
Definition at line 1308 of file markdown.php.
References handleSpanToken().
Markdown_Parser::handleSpanToken ($ token, &$ str)
Definition at line 1364 of file markdown.php.
References hashPart(), and makeCodeSpan().
Referenced by parseSpan().
Markdown_Parser::outdent ($ text)
Definition at line 1388 of file markdown.php.
References $text.
Referenced by _doCodeBlocks_callback(), and _processListItems_callback().
Markdown_Parser::detab ($ text)
Definition at line 1400 of file markdown.php.
References $text.
Referenced by transform().
Markdown_Parser::_detab_callback ($ matches)
Definition at line 1413 of file markdown.php.
Markdown_Parser::_initDetab ()
Definition at line 1430 of file markdown.php.
Referenced by Markdown_Parser().
Markdown_Parser::unhash ($ text)
Definition at line 1444 of file markdown.php.
References $text.
Referenced by formParagraphs(), and hashPart().
Markdown_Parser::_unhash_callback ($ matches)
Definition at line 1451 of file markdown.php.
Member Data Documentation
Markdown_Parser::$nested_brackets_depth = 6
Definition at line 195 of file markdown.php.
Markdown_Parser::$nested_brackets
Definition at line 196 of file markdown.php.
Markdown_Parser::$nested_url_parenthesis_depth = 4
Definition at line 198 of file markdown.php.
Markdown_Parser::$nested_url_parenthesis
Definition at line 199 of file markdown.php.
Markdown_Parser::$escape_chars = '\`*_{}[]()>#+-.!'
Definition at line 202 of file markdown.php.
Markdown_Parser::$empty_element_suffix = MARKDOWN_EMPTY_ELEMENT_SUFFIX
Definition at line 205 of file markdown.php.
Markdown_Parser::$tab_width = MARKDOWN_TAB_WIDTH
Definition at line 206 of file markdown.php.
Markdown_Parser::$no_markup = false
Definition at line 209 of file markdown.php.
Markdown_Parser::$no_entities = false
Definition at line 210 of file markdown.php.
Markdown_Parser::$urls = array()
Definition at line 235 of file markdown.php.
Markdown_Parser::$titles = array()
Definition at line 236 of file markdown.php.
Markdown_Parser::$html_hashes = array()
Definition at line 237 of file markdown.php.
Markdown_Parser::$in_anchor = false
Definition at line 240 of file markdown.php.
Markdown_Parser::$document_gamut
Initial value:
 array(
                # Strip link definitions, store in hashes.
                "stripLinkDefinitions" => 20,
                "runBasicBlockGamut"   => 30,
                )
Definition at line 285 of file markdown.php.
Markdown_Parser::$block_gamut
Initial value:
 array(
        #
        # These are all the transformations that form block-level
        # tags like paragraphs, headers, and list items.
        #
                "doHeaders"         => 10,
                "doHorizontalRules" => 20,
                "doLists"           => 40,
                "doCodeBlocks"      => 50,
                "doBlockQuotes"     => 60,
                )
Definition at line 508 of file markdown.php.
Markdown_Parser::$span_gamut
Initial value:
 array(
        #
        # These are all the transformations that occur *within* block-level
        # tags like paragraphs, headers, and list items.
        #
                # Process character escapes, code spans, and inline HTML
                # in one shot.
                "parseSpan"           => -30,
                # Process anchor and image tags. Images must come first,
                # because ![foo][f] looks like an anchor.
                "doImages"            =>  10,
                "doAnchors"           =>  20,
                # Make links out of things like `<http://example.com/>`
                # Must come after doAnchors, because you can use < and >
                # delimiters in inline links like [this](<url>).
                "doAutoLinks"         =>  30,
                "encodeAmpsAndAngles" =>  40,
                "doItalicsAndBold"    =>  50,
                "doHardBreaks"        =>  60,
                )
Definition at line 570 of file markdown.php.
Markdown_Parser::$list_level = 0
Definition at line 959 of file markdown.php.
Markdown_Parser::$utf8_strlen = 'mb_strlen'
Definition at line 1398 of file markdown.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/helpers/markdown.php