Emeraldion Lodge (codename Zelda): LanguageController Class Reference
LanguageController Class Reference
Controller for language management.
Public Member Functions
set ()
Action method to set the user's home language.
Protected Member Functions
init ()
Custom initialization for the controller object.
Detailed Description
Controller for language management.
Definition at line 10 of file language_controller.php.
Member Function Documentation
LanguageController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Definition at line 12 of file language_controller.php.
References BaseController::before_filter().
LanguageController::set ()
Action method to set the user's home language.
Definition at line 21 of file language_controller.php.
References Time::next_year(), BaseController::redirect_to(), BaseController::redirect_to_referrer(), and Cookie::set().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/language_controller.php