Emeraldion Lodge (codename Zelda): KmlController Class Reference
KmlController Class Reference
Controller for the generation of KML Google Earth plugins.
Public Member Functions
index ()
Default action method.
hits_by_host ()
Action method that shows the list of hosts that have visited the website.
last_5_visits ()
Action method that shows the last 5 hosts that have visited the website.
last_10_visits ()
Action method that shows the last 10 hosts that have visited the website.
last_50_visits ()
Action method that shows the last 50 hosts that have visited the website.
last_n_visits ($n)
Protected Member Functions
init ()
Initialization method for the Controller.
Protected Attributes
$mimetype = 'application/vnd.google-earth.kml+xml'
A MIME type for the response.
Detailed Description
Controller for the generation of KML Google Earth plugins.
Definition at line 11 of file kml_controller.php.
Member Function Documentation
KmlController::init () [protected]
Initialization method for the Controller.
Here you can define custom filters, caching strategies etc.
Reimplemented from BaseController.
Definition at line 20 of file kml_controller.php.
References BaseController::after_filter().
KmlController::index ()
Default action method.
This method handles the default action.
Reimplemented from EmeController.
Definition at line 30 of file kml_controller.php.
References Geoip::by_ip_addr().
KmlController::hits_by_host ()
Action method that shows the list of hosts that have visited the website.
Definition at line 40 of file kml_controller.php.
References $db, Time::ago(), and Geoip::by_ip_addr().
KmlController::last_5_visits ()
Action method that shows the last 5 hosts that have visited the website.
Definition at line 82 of file kml_controller.php.
References last_n_visits().
KmlController::last_10_visits ()
Action method that shows the last 10 hosts that have visited the website.
Definition at line 91 of file kml_controller.php.
References last_n_visits().
KmlController::last_50_visits ()
Action method that shows the last 50 hosts that have visited the website.
Definition at line 100 of file kml_controller.php.
References last_n_visits().
KmlController::last_n_visits ($ n)
Definition at line 109 of file kml_controller.php.
References $db, $i, Geoip::by_ip_addr(), and BaseController::render().
Referenced by last_10_visits(), last_50_visits(), and last_5_visits().
Member Data Documentation
KmlController::$mimetype = 'application/vnd.google-earth.kml+xml' [protected]
A MIME type for the response.
mimetype
Reimplemented from BaseController.
Definition at line 13 of file kml_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/kml_controller.php