Emeraldion Lodge (codename Zelda): ErrorController Class Reference
ErrorController Class Reference
Controller class for HTTP errors.
Public Member Functions
index ()
This is the default action method.
_404 ()
Handles 404 Not Found HTTP errors.
_403 ()
Handles 403 Forbidden HTTP errors.
_405 ()
Handles 405 Method Not Supported HTTP errors.
_500 ()
Handles 500 Internal Server Error HTTP errors.
Static Public Attributes
static $descriptions
Brief descriptions of HTTP error codes.
Protected Member Functions
init ()
Custom initialization for the controller object.
Private Member Functions
generate_error ($code)
Private common error handler.
Detailed Description
Controller class for HTTP errors.
ErrorController is responsible for handling HTTP errors. This is an improved version of the mainstream ErrorController class.
Definition at line 11 of file error_controller.php.
Member Function Documentation
ErrorController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Definition at line 22 of file error_controller.php.
References BaseController::after_filter().
ErrorController::index ()
This is the default action method.
Action methods
Reimplemented from EmeController.
Definition at line 27 of file error_controller.php.
References BaseController::redirect_to().
ErrorController::_404 ()
Handles 404 Not Found HTTP errors.
Definition at line 36 of file error_controller.php.
References generate_error().
ErrorController::_403 ()
Handles 403 Forbidden HTTP errors.
Definition at line 45 of file error_controller.php.
References generate_error().
ErrorController::_405 ()
Handles 405 Method Not Supported HTTP errors.
Definition at line 54 of file error_controller.php.
References generate_error().
ErrorController::_500 ()
Handles 500 Internal Server Error HTTP errors.
Definition at line 63 of file error_controller.php.
References generate_error().
ErrorController::generate_error ($ code) [private]
Private common error handler.
Parameters:
code An error code.
Definition at line 73 of file error_controller.php.
Referenced by _403(), _404(), _405(), and _500().
Member Data Documentation
ErrorController::$descriptions [static]
Initial value:
 array('404' => 'Not Found',
                        '403' => 'Forbidden',
                        '405' => 'Method Not Supported',
                        '500' => 'Internal Server Error',
                        )
Brief descriptions of HTTP error codes.
Definition at line 16 of file error_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/error_controller.php