Emeraldion Lodge (codename Zelda): Trackback Class Reference
Trackback Class Reference
Public Member Functions
Trackback ($blog_name, $author, $encoding="UTF-8")
ping ($tb, $url, $title="", $excerpt="")
receive ($success=false, $err_response="")
fetch ($success=false, $response="")
rdf_autodiscover ($RFC822_date, $title, $excerpt, $permalink, $trackback, $author="")
auto_discovery ($text)
RFC822_from_datetime ($datetime)
xml_safe ($string)
cut_short ($string, $max_length=255)
Public Attributes
$blog_name = ''
$author = ''
$encoding = ''
$get_id = ''
$post_id = ''
$url = ''
$title = ''
$excerpt = ''
Detailed Description
PHP Class to handle TrackBacks (send/ping, receive, retrieve, detect, seed, etc...)
<?php include('trackback_cls.php'); $trackback = new Trackback('BLOGish', 'Ran Aroussi', 'UTF-8'); ?>
==============================================================================
Version:
Id
trackback_cls.php,v 1.2 2004/12/11 18:54:32 Ran Exp
Copyright (c) 2004 Ran Aroussi (http://www.blogish.org)
Author:
Ran Aroussi <ran@blogish.org> http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
============================================================================== Trackback - The main class
Parameters:
string $blog_name
string $author
string $encoding
Definition at line 28 of file trackback.php.
Member Function Documentation
Trackback::Trackback ($ blog_name, $ author, $ encoding = "UTF-8")
Class Constructure
Parameters:
string $blog_name
string $author
string $encoding
Returns:
Definition at line 45 of file trackback.php.
References $author, $blog_name, $encoding, author, and title.
Trackback::ping ($ tb, $ url, $ title = "", $ excerpt = "")
Sends a trackback ping to a specified trackback URL. allowing clients to auto-discover the TrackBack Ping URL.
<?php include('trackback_cls.php'); $trackback = new Trackback('BLOGish', 'Ran Aroussi', 'UTF-8'); if ($trackback->ping('http://tracked-blog.com', 'http://your-url.com', 'Your entry title')) { echo "Trackback sent successfully..."; } else { echo "Error sending trackback...."; } ?>
Parameters:
string $tb
string $url
string $title
string $excerpt
Returns:
boolean
Definition at line 89 of file trackback.php.
References $excerpt, $title, and $url.
Trackback::receive ($ success = false, $ err_response = "")
Produces XML response for trackbackers with ok/error message.
<?php // Set page header to XML header('Content-Type: text/xml'); // MUST be the 1st line // // Instantiate the class // include('trackback_cls.php'); $trackback = new Trackback('BLOGish', 'Ran Aroussi', 'UTF-8'); // // Get trackback information // $tb_id = $trackback->post_id; // The id of the item being trackbacked $tb_url = $trackback->url; // The URL from which we got the trackback $tb_title = $trackback->title; // Subject/title send by trackback $tb_excerpt = $trackback->excerpt; // Short text send by trackback // // Do whatever to log the trackback (save in DB, flatfile, etc...) // if (TRACKBACK_LOGGED_SUCCESSFULLY) { // Logged successfully... echo $trackback->receive(true); } else { // Something went wrong... echo $trackback->receive(false, 'Explain why you return error'); } ?>
Parameters:
boolean $success
string $err_response
Returns:
boolean
Definition at line 174 of file trackback.php.
References xml_safe().
Trackback::fetch ($ success = false, $ response = "")
Feteched trackback information and produces an RSS-0.91 feed.
<?php // 1 header('Content-Type: text/xml'); // MUST be the 1st line // 2 include('trackback_cls.php'); $trackback = new Trackback('BLOGish', 'Ran Aroussi', 'UTF-8'); // 3 $tb_id = $trackback->get_id; // 4 Do whatever to get trackback information by ID (search db, etc...) if (GOT_TRACKBACK_INFO) { // Successful - pass trackback info as array()... $tb_info = array('title' => string TRACKBACK_TITLE, 'excerpt' => string TRACKBACK_excerpt, 'permalink' => string PERMALINK_URL, 'trackback' => string TRACKBACK_URL); echo $trackback->fetch(true, $tb_info); } else { // Something went wrong - tell my why... echo $trackback->fetch(false, string RESPONSE); } ?>
Parameters:
boolean $success
string $response
Returns:
string XML response to the caller
Definition at line 229 of file trackback.php.
References xml_safe().
Trackback::rdf_autodiscover ($ RFC822_date, $ title, $ excerpt, $ permalink, $ trackback, $ author = "")
Produces embedded RDF representing metadata about the entry, allowing clients to auto-discover the TrackBack Ping URL.
NOTE: DATE should be string in RFC822 Format - Use RFC822_from_datetime().
<?php include('trackback_cls.php'); $trackback = new Trackback('BLOGish', 'Ran Aroussi', 'UTF-8');
echo $trackback->rdf_autodiscover(string DATE, string TITLE, string excerpt, string PERMALINK, string TRACKBACK [, string AUTHOR]); ?>
Parameters:
string $RFC822_date
string $title
string $excerpt
string $permalink
string $trackback
string $author
Returns:
string
Definition at line 286 of file trackback.php.
References $author, $excerpt, $title, author, cut_short(), and xml_safe().
Trackback::auto_discovery ($ text)
Search text for links, and searches links for trackback URLs.
<?php
include('trackback_cls.php'); $trackback = new Trackback('BLOGish', 'Ran Aroussi', 'UTF-8');
if ($tb_array = $trackback->auto_discovery(string TEXT)) { // Found trackbacks in TEXT. Looping... foreach($tb_array as $tb_key => $tb_url) { // Attempt to ping each one... if ($trackback->ping($tb_url, string URL, [string TITLE], [string excerpt])) { // Successful ping... echo "Trackback sent to <i>$tb_url</i>...\n"; } else { // Error pinging... echo "Trackback to <i>$tb_url</i> failed....\n"; } } } else { // No trackbacks in TEXT... echo "No trackbacks were auto-discover...\n" } ?>
Parameters:
string $text
Returns:
array Trackback URLs.
Definition at line 340 of file trackback.php.
References $i, and $text.
Trackback::RFC822_from_datetime ($ datetime)
Other Useful functions used in this class Converts MySQL datetime to a standart RFC 822 date format
Parameters:
string $datetime
Returns:
string RFC 822 date
Definition at line 400 of file trackback.php.
Trackback::xml_safe ($ string)
Converts a string into an XML-safe string (replaces &, <, >, " and ')
Parameters:
string $string
Returns:
string
Definition at line 415 of file trackback.php.
Referenced by fetch(), rdf_autodiscover(), and receive().
Trackback::cut_short ($ string, $ max_length = 255)
Cuts a string short (with "...") according to $max_length...
Parameters:
string $string
integer $max_length
Returns:
string
Definition at line 427 of file trackback.php.
Referenced by rdf_autodiscover().
Member Data Documentation
Trackback::$blog_name = ''
Definition at line 29 of file trackback.php.
Referenced by Trackback().
Trackback::$author = ''
Definition at line 30 of file trackback.php.
Referenced by rdf_autodiscover(), and Trackback().
Trackback::$encoding = ''
Definition at line 31 of file trackback.php.
Referenced by Trackback().
Trackback::$get_id = ''
Definition at line 32 of file trackback.php.
Trackback::$post_id = ''
Definition at line 33 of file trackback.php.
Trackback::$url = ''
Definition at line 34 of file trackback.php.
Referenced by ping().
Trackback::$title = ''
Definition at line 35 of file trackback.php.
Referenced by ping(), and rdf_autodiscover().
Trackback::$excerpt = ''
Definition at line 36 of file trackback.php.
Referenced by ping(), and rdf_autodiscover().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/helpers/trackback.php