Emeraldion Lodge (codename Zelda): ContactController Class Reference
ContactController Class Reference
Controller for contact and mailing communication actions.
Public Member Functions
index ()
Default action method.
send ()
Sends the contact email if validation passes.
thank_you ()
Shows thankfulness to the user for the contact email.
Protected Member Functions
init ()
Initialization method for the Controller.
Detailed Description
Controller for contact and mailing communication actions.
Definition at line 12 of file contact_controller.php.
Member Function Documentation
ContactController::init () [protected]
Initialization method for the Controller.
Here you can define custom filters, caching strategies etc.
Reimplemented from BaseController.
Definition at line 19 of file contact_controller.php.
References BaseController::after_filter(), and BaseController::before_filter().
ContactController::index ()
Default action method.
Reimplemented from EmeController.
Definition at line 29 of file contact_controller.php.
References l(), and BaseController::set_title().
ContactController::send ()
Sends the contact email if validation passes.
This method creates a contact email with the post data submitted by the user and delivers it to the website owner. Cookies are set for the user details if the remember_me flag has been set. If any of the validation steps fails, it performs a redirection to the action index. A redirection to the action thank_you is performed on success.
Definition at line 44 of file contact_controller.php.
References Antispam::check_math(), BaseController::flash(), Time::next_year(), Antispam::random_comment(), BaseController::redirect_to(), and Cookie::set().
ContactController::thank_you ()
Shows thankfulness to the user for the contact email.
A delayed redirection to the Home controller is performed here.
Definition at line 74 of file contact_controller.php.
References BaseController::redirect_to().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/contact_controller.php