Emeraldion Lodge (codename Zelda): AbstractComment Class Reference
AbstractComment Class Reference
Abstract superclass for comment model objects.
Public Member Functions
relative_url ()
Provides a relative URL for the comment object.
comment_class ()
Provides a class name that depends on the status of the comment, useful for lists.
pretty_text ()
Provides very basic markup modification to display text in HTML views.
human_readable_date ()
Returns a human readable date for the creation date of the receiver.
rfc2822_date ()
Returns a RFC2822 formatted date for the creation date of the receiver, useful for feeds.
iso8601_date ()
Returns a ISO8601 formatted date for the creation date of the receiver, useful for feeds.
approve ()
Sets the approved status.
reject ()
Unsets the approved status.
find_unapproved ()
Finds all elements whose approved status is false.
find_approved ()
Finds all elements whose approved status is true.
Static Public Member Functions
static sort_comments ($a, $b)
Static function used to compare releases.
Protected Member Functions
init ($values)
Performs specialized initialization tasks.
Detailed Description
Abstract superclass for comment model objects.
AbstractComment is an abstract ancestor for every comment-like model class. Comment objects contain a small text, are linked to an author (not necessarily another model object) and can be permalinked.
Definition at line 15 of file abstract_comment.php.
Member Function Documentation
AbstractComment::init ($ values) [protected]
Performs specialized initialization tasks.
Subclassers will use this method to perform custom initialization.
Note:
The default implementation simply does nothing.
Parameters:
values An array of column-value pairs to initialize the receiver.
Reimplemented from ActiveRecord.
Reimplemented in DiarioPingback.
Definition at line 17 of file abstract_comment.php.
References ActiveRecord::$values.
AbstractComment::relative_url ()
Provides a relative URL for the comment object.
Reimplemented from ActiveRecord.
Reimplemented in DiarioComment, and DiarioPingback.
Definition at line 31 of file abstract_comment.php.
AbstractComment::comment_class ()
Provides a class name that depends on the status of the comment, useful for lists.
Reimplemented in DiarioPingback.
Definition at line 40 of file abstract_comment.php.
References $row.
AbstractComment::pretty_text ()
Provides very basic markup modification to display text in HTML views.
Subclassers will likely improve this method to parse textile, markdown etc.
Definition at line 56 of file abstract_comment.php.
References Markdown().
AbstractComment::human_readable_date ()
Returns a human readable date for the creation date of the receiver.
Implements Dateable.
Definition at line 65 of file abstract_comment.php.
AbstractComment::rfc2822_date ()
Returns a RFC2822 formatted date for the creation date of the receiver, useful for feeds.
Implements Dateable.
Definition at line 74 of file abstract_comment.php.
AbstractComment::iso8601_date ()
Returns a ISO8601 formatted date for the creation date of the receiver, useful for feeds.
Implements Dateable.
Definition at line 83 of file abstract_comment.php.
AbstractComment::sort_comments ($ a, $ b) [static]
Static function used to compare releases.
Definition at line 92 of file abstract_comment.php.
AbstractComment::approve ()
Sets the approved status.
Implements Approvable.
Definition at line 101 of file abstract_comment.php.
AbstractComment::reject ()
Unsets the approved status.
Implements Approvable.
Definition at line 110 of file abstract_comment.php.
AbstractComment::find_unapproved ()
Finds all elements whose approved status is false.
Implements Approvable.
Definition at line 119 of file abstract_comment.php.
References ActiveRecord::find_all().
AbstractComment::find_approved ()
Finds all elements whose approved status is true.
Implements Approvable.
Definition at line 128 of file abstract_comment.php.
References ActiveRecord::find_all().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/models/abstract_comment.php