Emeraldion Lodge (codename Zelda): MURatingsParser Class Reference
MURatingsParser Class Reference
Public Member Functions
MURatingsParser ($inFile=null)
parseFile ($persist=false)
startHandler ($parser, $tagName, $attrs)
endHandler ($parser, $tagName)
cdataHandler ($parser, $cdata)
release ()
hasItems ()
formatRating (&$item)
ratingForTitle ($title)
ratingsList ($withTitles=true)
ratingsValues ($withTitles=true)
writeRatingOutput ($title)
debug ()
Public Attributes
$parser
$file
$isWithinItem
$currentItem
$currentTag
$items
Detailed Description
MacUpdate Ratings parser http://www.macupdate.com/rss/examples.php#downloads_php
Definition at line 7 of file MURatingsParser.php.
Member Function Documentation
MURatingsParser::MURatingsParser ($ inFile = null)
Definition at line 16 of file MURatingsParser.php.
MURatingsParser::parseFile ($ persist = false)
Definition at line 24 of file MURatingsParser.php.
MURatingsParser::startHandler ($ parser, $ tagName, $ attrs)
Definition at line 58 of file MURatingsParser.php.
MURatingsParser::endHandler ($ parser, $ tagName)
Definition at line 66 of file MURatingsParser.php.
MURatingsParser::cdataHandler ($ parser, $ cdata)
Definition at line 75 of file MURatingsParser.php.
MURatingsParser::release ()
Definition at line 88 of file MURatingsParser.php.
MURatingsParser::hasItems ()
Definition at line 93 of file MURatingsParser.php.
Referenced by debug().
MURatingsParser::formatRating (&$ item)
Definition at line 98 of file MURatingsParser.php.
MURatingsParser::ratingForTitle ($ title)
Definition at line 102 of file MURatingsParser.php.
Referenced by writeRatingOutput().
MURatingsParser::ratingsList ($ withTitles = true)
Definition at line 107 of file MURatingsParser.php.
References $i.
MURatingsParser::ratingsValues ($ withTitles = true)
Definition at line 119 of file MURatingsParser.php.
References $i.
MURatingsParser::writeRatingOutput ($ title)
Definition at line 131 of file MURatingsParser.php.
References $stars, and ratingForTitle().
MURatingsParser::debug ()
Definition at line 149 of file MURatingsParser.php.
References hasItems().
Member Data Documentation
MURatingsParser::$parser
Definition at line 9 of file MURatingsParser.php.
MURatingsParser::$file
Definition at line 10 of file MURatingsParser.php.
MURatingsParser::$isWithinItem
Definition at line 11 of file MURatingsParser.php.
MURatingsParser::$currentItem
Definition at line 12 of file MURatingsParser.php.
MURatingsParser::$currentTag
Definition at line 13 of file MURatingsParser.php.
MURatingsParser::$items
Definition at line 14 of file MURatingsParser.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/helpers/MURatingsParser.php