Emeraldion Lodge (codename Zelda): MorseController Class Reference
MorseController Class Reference
Controller for Morse encoding / decoding actions.
Public Member Functions
index ()
This is the default action method.
encode ()
Action method to encode in Morse code the request.
decode ()
Action method to decode the request from Morse code.
Protected Member Functions
init ()
Custom initialization for the controller object.
my_morse_encode ()
Filter method to encode a plain text response body to Morse code.
my_morse_decode ()
Filter method to decode a Morse encoded response body to plain text.
Detailed Description
Controller for Morse encoding / decoding actions.
This controller is just a proof of concept to illustrate EmeRails filtering capabilities.
Definition at line 10 of file morse_controller.php.
Member Function Documentation
MorseController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Definition at line 12 of file morse_controller.php.
References BaseController::after_filter(), and BaseController::before_filter().
MorseController::index ()
This is the default action method.
Action methods
Reimplemented from EmeController.
Definition at line 21 of file morse_controller.php.
MorseController::encode ()
Action method to encode in Morse code the request.
Definition at line 29 of file morse_controller.php.
References BaseController::render().
MorseController::decode ()
Action method to decode the request from Morse code.
Definition at line 38 of file morse_controller.php.
References BaseController::render().
MorseController::my_morse_encode () [protected]
Filter method to encode a plain text response body to Morse code.
Definition at line 47 of file morse_controller.php.
References Morse::encode().
MorseController::my_morse_decode () [protected]
Filter method to decode a Morse encoded response body to plain text.
Definition at line 67 of file morse_controller.php.
References Morse::decode().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/morse_controller.php