Emeraldion Lodge (codename Zelda): Filesystem Class Reference
Filesystem Class Reference
Helper class for file system manipulation.
Static Public Member Functions
static filesize_readable ($file, $retstring=null)
Returns a human readable representation of the size of file.
static filesize ($file)
Returns the size of the file file.
static file_exists ($file)
Returns TRUE if the file exists, FALSE otherwise.
static md5_sum ($file, $raw=FALSE)
Returns the MD5 sum of the file file.
Detailed Description
Helper class for file system manipulation.
Definition at line 8 of file filesystem.php.
Member Function Documentation
Filesystem::filesize_readable ($ file, $ retstring = null) [static]
Returns a human readable representation of the size of file.
This method formats the filesize according to a hardcoded format string, but you can also provide a custom format string.
Parameters:
file The name of the file whose size we want to show.
retstring An optional alternative format string.
Definition at line 18 of file filesystem.php.
References filesize(), and l().
Referenced by SoftwareArtifact::filesize_readable().
Filesystem::filesize ($ file) [static]
Returns the size of the file file.
Parameters:
file The name of the file whose size we want to know.
Definition at line 42 of file filesystem.php.
References file_exists().
Referenced by SoftwareArtifact::filesize(), and filesize_readable().
Filesystem::file_exists ($ file) [static]
Returns TRUE if the file exists, FALSE otherwise.
Parameters:
file The name of the file whose existence we want to check.
Definition at line 56 of file filesystem.php.
Referenced by SoftwareArtifact::file_exists(), filesize(), and md5_sum().
Filesystem::md5_sum ($ file, $ raw = FALSE) [static]
Returns the MD5 sum of the file file.
Parameters:
file The name of the file.
raw Tells whether the checksum should be returned in a raw format.
Definition at line 67 of file filesystem.php.
References file_exists().
Referenced by SoftwareArtifact::md5_sum().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/helpers/filesystem.php