Emeraldion Lodge (codename Zelda): HTTP Class Reference
HTTP Class Reference
Helper class to manipulate HTTP error codes.
Static Public Member Functions
static error ($code=500, $headers=array())
Redirects the request to the error page for the desired HTTP error code.
Detailed Description
Helper class to manipulate HTTP error codes.
Definition at line 8 of file http.php.
Member Function Documentation
HTTP::error ($ code = 500, $ headers = array()) [static]
Redirects the request to the error page for the desired HTTP error code.
This method redirects the request to the ErrorController action method that handles the HTTP error code code, optionally sending a set of headers.
Parameters:
code The HTTP error code.
headers An optional set of HTTP headers to send to the client.
Definition at line 18 of file http.php.
Referenced by SoftwareController::_init_software(), SoftwareController::download(), EmeController::include_localized(), EmeController::load_part_contents(), BaseController::load_part_contents(), DiarioController::read(), SoftwareController::releasenotes(), BaseController::render_page(), TrackbackController::require_post(), DownloadManager::start_download(), BaseController::unknown_action(), and SoftwareController::widgets_versioncheck().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/helpers/http.php