Emeraldion Lodge (codename Zelda): LegalController Class Reference
LegalController Class Reference
Controller for the legal notices in the website.
Public Member Functions
index ()
This is the default action method.
disclaimer ()
Action method that shows a disclaimer for the usage of the website.
Protected Member Functions
init ()
Custom initialization for the controller object.
Detailed Description
Controller for the legal notices in the website.
Definition at line 8 of file legal_controller.php.
Member Function Documentation
LegalController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Definition at line 10 of file legal_controller.php.
References BaseController::after_filter(), and BaseController::before_filter().
LegalController::index ()
This is the default action method.
Action methods
Reimplemented from EmeController.
Definition at line 16 of file legal_controller.php.
References BaseController::redirect_to().
LegalController::disclaimer ()
Action method that shows a disclaimer for the usage of the website.
Definition at line 25 of file legal_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/legal_controller.php