Emeraldion Lodge (codename Zelda): DiarioController Class Reference
DiarioController Class Reference
Controller for the Diario blog.
Public Member Functions
index ()
This is the default action method.
last_posts ()
Action method that returns the latest blog posts.
tag ()
Action method that returns a list of articles tagged with a particular label.
calendar ()
Action method that creates a calendar to browse articles.
date ()
Action method that returns a list of articles written before a particular date.
live_search ()
Action method that returns a list of articles that satisfy a search query.
search ()
Action method that returns a list of articles that satisfy a search query.
read ()
Action method that shows an article for reading.
comments ()
Action method that returns a list of comments for a given article ID.
post_comment ()
Action method to receive a comment for an article.
Protected Member Functions
init ()
Custom initialization for the controller object.
init_math_test ()
Filter method that initializes the Antispam math test for commenting articles.
highlight_words ()
Filter method to highlight words that are search terms.
Protected Attributes
$mimetype = 'text/html; charset=iso-8859-1'
A MIME type for the response.
Detailed Description
Controller for the Diario blog.
Definition at line 17 of file diario_controller.php.
Member Function Documentation
DiarioController::init () [protected]
Custom initialization for the controller object.
Subclassers should override this method to perform specialized initialization. The default implementation does nothing.
Reimplemented from BaseController.
Reimplemented in BlogController.
Definition at line 25 of file diario_controller.php.
References BaseController::after_filter(), and BaseController::before_filter().
DiarioController::index ()
This is the default action method.
Action methods
Reimplemented from EmeController.
Definition at line 35 of file diario_controller.php.
References $db, BaseController::redirect_to(), and BaseController::render().
DiarioController::last_posts ()
Action method that returns the latest blog posts.
Definition at line 58 of file diario_controller.php.
References BaseController::render().
DiarioController::tag ()
Action method that returns a list of articles tagged with a particular label.
Definition at line 69 of file diario_controller.php.
References limit_3(), BaseController::redirect_to(), and BaseController::render().
DiarioController::calendar ()
Action method that creates a calendar to browse articles.
Definition at line 95 of file diario_controller.php.
References $db, and BaseController::render().
DiarioController::date ()
Action method that returns a list of articles written before a particular date.
Definition at line 106 of file diario_controller.php.
References $db, and BaseController::render().
Referenced by post_comment().
DiarioController::live_search ()
Action method that returns a list of articles that satisfy a search query.
Note:
This action does not return a full layout, and is intended to be used with AJAX calls.
Definition at line 145 of file diario_controller.php.
References $db, $i, and BaseController::render().
DiarioController::search ()
Action method that returns a list of articles that satisfy a search query.
Definition at line 179 of file diario_controller.php.
References $db, $i, BaseController::redirect_to(), and BaseController::render().
DiarioController::read ()
Action method that shows an article for reading.
Definition at line 217 of file diario_controller.php.
References HTTP::error(), and BaseController::redirect_to().
DiarioController::comments ()
Action method that returns a list of comments for a given article ID.
Definition at line 247 of file diario_controller.php.
References BaseController::render().
DiarioController::post_comment ()
Action method to receive a comment for an article.
Definition at line 262 of file diario_controller.php.
References Antispam::check_math(), date(), BaseController::expire_cached_page(), BaseController::flash(), Time::next_year(), Antispam::random_comment(), BaseController::redirect_to(), and Cookie::set().
DiarioController::init_math_test () [protected]
Filter method that initializes the Antispam math test for commenting articles.
Definition at line 298 of file diario_controller.php.
References Antispam::init_math_test().
DiarioController::highlight_words () [protected]
Filter method to highlight words that are search terms.
Definition at line 307 of file diario_controller.php.
Member Data Documentation
DiarioController::$mimetype = 'text/html; charset=iso-8859-1' [protected]
A MIME type for the response.
mimetype
Reimplemented from BaseController.
Definition at line 23 of file diario_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/diario_controller.php