Emeraldion Lodge (codename Zelda): MaintenanceController Class Reference
MaintenanceController Class Reference
Controller for maintenance tasks.
Public Member Functions
kill_claudio ()
Action method to remove claudio's evidence from the DB.
update_macupdate_ratings ()
Action method that updates the MacUpdate ratings for software products.
update_mu_ratings ()
Shorthand for MaintenanceController::update_macupdate_ratings().
update_versiontracker_ratings ()
Action method that updates the VersionTracker ratings for software products.
update_vt_ratings ()
Shorthand for MaintenanceController::update_versiontracker_ratings().
Detailed Description
Controller for maintenance tasks.
Definition at line 13 of file maintenance_controller.php.
Member Function Documentation
MaintenanceController::kill_claudio ()
Action method to remove claudio's evidence from the DB.
Definition at line 19 of file maintenance_controller.php.
References $db, and BaseController::render().
MaintenanceController::update_macupdate_ratings ()
Action method that updates the MacUpdate ratings for software products.
Definition at line 38 of file maintenance_controller.php.
References $db, and BaseController::render().
Referenced by update_mu_ratings().
MaintenanceController::update_mu_ratings ()
Shorthand for MaintenanceController::update_macupdate_ratings().
Definition at line 77 of file maintenance_controller.php.
References update_macupdate_ratings().
MaintenanceController::update_versiontracker_ratings ()
Action method that updates the VersionTracker ratings for software products.
Definition at line 86 of file maintenance_controller.php.
References $db, $software, and BaseController::render().
Referenced by update_vt_ratings().
MaintenanceController::update_vt_ratings ()
Shorthand for MaintenanceController::update_versiontracker_ratings().
Definition at line 115 of file maintenance_controller.php.
References update_versiontracker_ratings().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/maintenance_controller.php