Emeraldion Lodge (codename Zelda): AboutController Class Reference
AboutController Class Reference
Controller for the About section.
Public Member Functions
index ()
Default action method.
claudio ()
Action method that shows info on Claudio.
dorotea ()
Hidden action method that shows info on Dorotea.
emeraldion_lodge ()
Action method that shows info on the Emeraldion Lodge website.
emerails ()
Action method that shows info on the EmeRails framework.
primula_toggle ()
Just records the click on the primula toggler.
joke ()
Filter method that replaces "Emeraldion Lodge" with "Emilio Fede" in the response body.
Protected Member Functions
init ()
Initialization method for the Controller.
Detailed Description
Controller for the About section.
The About section collects information pages that illustrate the website, the technologies it relies upon, and something about the author.
Definition at line 10 of file about_controller.php.
Member Function Documentation
AboutController::init () [protected]
Initialization method for the Controller.
Here you can define custom filters, caching strategies etc.
Reimplemented from BaseController.
Definition at line 17 of file about_controller.php.
References BaseController::after_filter(), and BaseController::before_filter().
AboutController::index ()
Default action method.
This method simply performs a redirection to the action claudio.
Reimplemented from EmeController.
Definition at line 41 of file about_controller.php.
References BaseController::redirect_to().
AboutController::claudio ()
Action method that shows info on Claudio.
Definition at line 50 of file about_controller.php.
AboutController::dorotea ()
Hidden action method that shows info on Dorotea.
Definition at line 58 of file about_controller.php.
AboutController::emeraldion_lodge ()
Action method that shows info on the Emeraldion Lodge website.
Definition at line 66 of file about_controller.php.
AboutController::emerails ()
Action method that shows info on the EmeRails framework.
Definition at line 74 of file about_controller.php.
AboutController::primula_toggle ()
Just records the click on the primula toggler.
Definition at line 82 of file about_controller.php.
References BaseController::render().
AboutController::joke ()
Filter method that replaces "Emeraldion Lodge" with "Emilio Fede" in the response body.
Definition at line 92 of file about_controller.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/controllers/about_controller.php