Emeraldion Lodge (codename Zelda): DBConn Class Reference
DBConn Class Reference
Database connection manager.
Public Member Functions
connect ()
Connects to the database.
select_db ($database_name)
Selects the desired database.
close ()
Closes the connection to the database.
prepare ($query)
Prepares a query for execution.
exec ()
Executes a query.
insert_id ()
Returns the id generated by the last INSERT query.
escape ($value)
Escapes the given value to avoid SQL injections.
result ($pos=0, $colname=NULL)
Returns a single result of the last SELECT query.
num_rows ()
Returns the number of rows returned by a previous SELECT query.
affected_rows ()
Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
fetch_assoc ()
Returns the current row of the resultset as an associative array.
free_result ()
Releases the result of the last query.
print_query ()
Prints the last query for debug.
Public Attributes
$link
Connection link to the database.
$query
Query for the database.
$result
The result of the last query.
Static Public Attributes
static $queries_count = 0
Counter for queries executed.
Detailed Description
Database connection manager.
Definition at line 9 of file db.inc.php.
Member Function Documentation
DBConn::connect ()
Connects to the database.
Definition at line 39 of file db.inc.php.
Referenced by escape(), exec(), prepare(), and select_db().
DBConn::select_db ($ database_name)
Selects the desired database.
Parameters:
database_name The name of the database.
Definition at line 53 of file db.inc.php.
References connect().
DBConn::close ()
Closes the connection to the database.
Definition at line 63 of file db.inc.php.
DBConn::prepare ($ query)
Prepares a query for execution.
Parameters:
query The query to execute.
Definition at line 73 of file db.inc.php.
References $i, $query, connect(), and print_query().
DBConn::exec ()
Executes a query.
Definition at line 96 of file db.inc.php.
References connect(), and result().
DBConn::insert_id ()
Returns the id generated by the last INSERT query.
Definition at line 110 of file db.inc.php.
DBConn::escape ($ value)
Escapes the given value to avoid SQL injections.
Parameters:
value The value to escape.
Definition at line 120 of file db.inc.php.
References connect().
DBConn::result ($ pos = 0, $ colname = NULL)
Returns a single result of the last SELECT query.
Parameters:
row The row of the resultset.
colname The name (or the alias, if applicable) of the desired row.
Definition at line 133 of file db.inc.php.
Referenced by affected_rows(), exec(), fetch_assoc(), free_result(), and num_rows().
DBConn::num_rows ()
Returns the number of rows returned by a previous SELECT query.
Definition at line 142 of file db.inc.php.
References result().
DBConn::affected_rows ()
Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
Definition at line 151 of file db.inc.php.
References result().
DBConn::fetch_assoc ()
Returns the current row of the resultset as an associative array.
Definition at line 160 of file db.inc.php.
References result().
DBConn::free_result ()
Releases the result of the last query.
Definition at line 169 of file db.inc.php.
References result().
DBConn::print_query ()
Prints the last query for debug.
Definition at line 178 of file db.inc.php.
Referenced by prepare().
Member Data Documentation
DBConn::$queries_count = 0 [static]
Counter for queries executed.
queries_count
Definition at line 15 of file db.inc.php.
DBConn::$link
Connection link to the database.
link
Definition at line 21 of file db.inc.php.
DBConn::$query
Query for the database.
query
Definition at line 27 of file db.inc.php.
Referenced by prepare().
DBConn::$result
The result of the last query.
result
Definition at line 33 of file db.inc.php.
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/include/db.inc.php