Emeraldion Lodge (codename Zelda): /Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/include/common.inc.php File Reference
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/include/common.inc.php File Reference
Functions
http_error ($code)
pluralize ($term)
singularize ($term)
ends_with ($term, $suffix)
class_name_to_table_name ($classname)
table_name_to_class_name ($tablename)
joined_lower ($text)
joined_lower_to_camel_case ($text)
camel_case_to_joined_lower ($text)
class_name_to_foreign_key ($classname)
table_name_to_foreign_key ($tablename)
l ($str)
Shorthand method for the Localization::localize method.
localized ($str)
h ($str)
s ($str)
limit_3 ($val, $a, $b)
Variables
$irregular_nouns
Function Documentation
camel_case_to_joined_lower ($ text)
Definition at line 116 of file common.inc.php.
References $text.
Referenced by class_name_to_foreign_key(), and class_name_to_table_name().
class_name_to_foreign_key ($ classname)
Definition at line 123 of file common.inc.php.
References camel_case_to_joined_lower().
Referenced by ActiveRecord::get_foreign_key_name().
class_name_to_table_name ($ classname)
Definition at line 96 of file common.inc.php.
References camel_case_to_joined_lower(), and pluralize().
Referenced by ActiveRecord::get_table_name().
ends_with ($ term, $ suffix)
Definition at line 91 of file common.inc.php.
Referenced by SoftwareArtifact::icon(), pluralize(), and singularize().
h ($ str)
Definition at line 151 of file common.inc.php.
Referenced by EmeController::add_acronyms().
http_error ($ code)
Definition at line 17 of file common.inc.php.
joined_lower ($ text)
Definition at line 106 of file common.inc.php.
References $text.
Referenced by BaseController::button_to().
joined_lower_to_camel_case ($ text)
Definition at line 111 of file common.inc.php.
References $text.
Referenced by table_name_to_class_name().
l ($ str)
Shorthand method for the Localization::localize method.
Definition at line 141 of file common.inc.php.
References localized().
Referenced by SoftwareController::_init_software(), MetaController::block_ip(), EmeController::block_ip(), TrackbackController::diario(), SoftwareController::download_stats(), SoftwareArtifact::filename(), Filesystem::filesize_readable(), ContactController::index(), BaseController::link_to_remote(), LoginController::login(), LoginController::logout(), LoginController::lost_password(), Antispam::random_comment(), LoginController::request_password(), BackendController::server_error_read(), TrackbackController::software(), BackendController::software_downloads_by_artifact(), BackendController::software_downloads_by_release(), DiarioPost::summary(), MetaController::unblock_ip(), SoftwareController::user_quotes(), and SoftwareController::widgets_versioncheck().
limit_3 ($ val, $ a, $ b)
Definition at line 161 of file common.inc.php.
References $max.
Referenced by DiarioController::tag().
localized ($ str)
Definition at line 146 of file common.inc.php.
References Localization::localize().
Referenced by l().
pluralize ($ term)
Definition at line 25 of file common.inc.php.
References $irregular_nouns, and ends_with().
Referenced by class_name_to_table_name().
s ($ str)
Definition at line 156 of file common.inc.php.
Referenced by MetaController::attribute_visits().
singularize ($ term)
Definition at line 59 of file common.inc.php.
References $irregular_nouns, and ends_with().
Referenced by ActiveRecord::belongs_to(), ActiveRecord::has_many(), ActiveRecord::has_one(), table_name_to_class_name(), and table_name_to_foreign_key().
table_name_to_class_name ($ tablename)
Definition at line 101 of file common.inc.php.
References joined_lower_to_camel_case(), and singularize().
Referenced by ActiveRecord::belongs_to(), ActiveRecord::has_and_belongs_to_many(), ActiveRecord::has_many(), ActiveRecord::has_one(), and BaseController::render_component().
table_name_to_foreign_key ($ tablename)
Definition at line 130 of file common.inc.php.
References singularize().
Referenced by ActiveRecord::belongs_to().
Variable Documentation
$irregular_nouns
Initial value:
 array(
                'person' => 'people',
                'child' => 'children',
                'man' => 'men',
                'woman' => 'women',
                )
Project EmeRails - Codename Ocarina
© 2008 Claudio Procida http://www.emeraldion.it
Definition at line 10 of file common.inc.php.
Referenced by pluralize(), and singularize().