Emeraldion Lodge (codename Zelda): /Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/include/db.inc.php File Reference
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/include/db.inc.php File Reference
Classes
class DBConn
Database connection manager.
Variables
$db = new DBConn()
Variable Documentation
$db = new DBConn()
Definition at line 186 of file db.inc.php.
Referenced by BackendController::_batch_moderate(), SoftwareController::_init_software(), ActiveRecord::ActiveRecord(), MetaController::attribute_visits(), MetaController::blocked_ips_list(), DiarioController::calendar(), BlockedVisit::count_by_ip(), DiarioController::date(), ActiveRecord::delete(), BackendController::diario_post_add(), SoftwareController::download_stats(), ActiveRecord::find_all(), ActiveRecord::find_by_id(), ActiveRecord::find_by_query(), ActiveRecord::has_and_belongs_to_many(), KmlController::hits_by_host(), MetaController::hits_by_host_list(), SparkleController::index(), DiarioController::index(), BlockedIp::is_blocked(), Login::is_logged_in(), MaintenanceController::kill_claudio(), KmlController::last_n_visits(), DiarioController::live_search(), LoginController::login(), Host::lookup_host_and_cache(), MetaController::queries_list(), MetaController::referrers_list(), ActiveRecord::save(), DiarioController::search(), BackendController::server_error_delete(), BackendController::server_error_next(), BackendController::server_error_previous(), BackendController::software_artifact_list(), BackendController::software_comment_list(), BackendController::software_quote_edit(), BackendController::software_quote_list(), BackendController::software_release_list(), SoftwareArtifact::total_downloads(), MaintenanceController::update_macupdate_ratings(), MaintenanceController::update_versiontracker_ratings(), MetaController::visits_list(), and SoftwareController::widgets_versioncheck().