EmeRails: /Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/test/test-render.php File Reference
/Users/delphine/Sviluppo/SVN/emeraldion.it/zelda/test/test-render.php File Reference
Variables
$controller = new DiarioController()
Variable Documentation
$controller = new DiarioController()
Definition at line 7 of file test-render.php.
Referenced by BaseController::expire_cached_page(), Localization::load_strings_file(), Localization::load_strings_table(), BaseController::make_relative_url(), and BaseController::render_component().