Emeraldion Lodge (codename Zelda): Sass::File Namespace Reference
Sass::File Namespace Reference
Functions
string get_cwd ()
bool file_exists (const string &path)
bool is_absolute_path (const string &path)
size_t find_last_folder_separator (const string &path, size_t limit=string::npos)
string dir_name (const string &path)
string base_name (const string &path)
string make_canonical_path (string path)
string join_paths (string l, string r)
string make_absolute_path (const string &path, const string &cwd)
string resolve_relative_path (const string &uri, const string &base, const string &cwd)
string resolve_file (const string &filename)
string find_file (const string &file, const vector< string > paths)
string find_file (const string &file, const char *paths[])
char * read_file (const string &path)
string find_file (const string &file, const char **paths)
Function Documentation
string base_name (const string & path)
Definition at line 107 of file file.cpp.
References find_last_folder_separator(), and npos.
Referenced by resolve_file().
string dir_name (const string & path)
Definition at line 99 of file file.cpp.
References find_last_folder_separator(), and npos.
Referenced by Parser::add_single_file(), and resolve_file().
bool file_exists (const string & path)
Definition at line 52 of file file.cpp.
References Sass::UTF_8::convert_to_utf16().
Referenced by BaseController::cached_page_exists(), Filesystem::filesize_readable(), SingularLicense::generate_key(), MiniBatteryLoggerLicense::generate_key(), EmeController::include_localized(), EmeController::load_part_contents(), BaseController::load_part_contents(), Localization::load_strings_file(), Filesystem::md5_sum(), BaseController::render_layout(), BaseController::render_page(), resolve_file(), DownloadManager::start_download(), SingularLicense::valid_key(), and MiniBatteryLoggerLicense::valid_key().
string Sass::File::find_file (const string & file, const char ** paths)
Referenced by Context::add_file(), and sass_resolve_file().
string Sass::File::find_file (const string & file, const char * paths[])
Definition at line 284 of file file.cpp.
References find_file().
string find_file (const string & file, const vector< string > paths)
Definition at line 270 of file file.cpp.
References join_paths(), and resolve_file().
Referenced by find_file().
size_t Sass::File::find_last_folder_separator (const string & path, size_t limit = string::npos) [inline]
Definition at line 77 of file file.cpp.
References npos.
Referenced by base_name(), dir_name(), and join_paths().
string get_cwd ()
Definition at line 38 of file file.cpp.
Referenced by Sass::complexSelectorHasExtension(), handle_errors(), and Backtrace::to_string().
bool is_absolute_path (const string & path)
Definition at line 68 of file file.cpp.
Referenced by join_paths(), and make_absolute_path().
string join_paths (string l, string r)
Definition at line 143 of file file.cpp.
References find_last_folder_separator(), is_absolute_path(), and npos.
Referenced by Context::add_file(), find_file(), make_absolute_path(), and resolve_file().
string make_absolute_path (const string & path, const string & cwd)
Definition at line 168 of file file.cpp.
References is_absolute_path(), join_paths(), and make_canonical_path().
Referenced by resolve_relative_path().
string make_canonical_path (string path)
Definition at line 116 of file file.cpp.
References npos.
Referenced by Context::add_file(), and make_absolute_path().
char * read_file (const string & path)
Definition at line 300 of file file.cpp.
References Sass::UTF_8::convert_to_utf16(), Sass::sass2scss(), SASS2SCSS_KEEP_COMMENT, and SASS2SCSS_PRETTIFY_1.
Referenced by Context::add_file().
string resolve_file (const string & filename)
Definition at line 240 of file file.cpp.
References base_name(), dir_name(), gyp::generator::cmake::ext, file_exists(), join_paths(), and Sass::Prelexer::name().
Referenced by Context::add_file(), and find_file().
string resolve_relative_path (const string & uri, const string & base, const string & cwd)
Definition at line 175 of file file.cpp.
References make_absolute_path().
Referenced by Context::add_source(), Sass::complexSelectorHasExtension(), Context::format_source_mapping_url(), handle_errors(), Eval::operator()(), and Backtrace::to_string().