Emeraldion Lodge (codename Zelda): At_Rule Class Reference
At_Rule Class Reference
#include <ast.hpp>
Inherits Sass::Has_Block.
Public Member Functions
At_Rule (ParserState pstate, string kwd, Selector *sel=0, Block *b=0)
bool bubbles ()
bool is_media ()
bool is_keyframes ()
ATTACH_OPERATIONS ()
Private Member Functions
ADD_PROPERTY (string, keyword)
ADD_PROPERTY (Selector *, selector)
ADD_PROPERTY (Expression *, value)
Detailed Description
Definition at line 408 of file ast.hpp.
Constructor & Destructor Documentation
At_Rule (ParserState pstate, string kwd, Selector * sel = 0, Block * b = 0) [inline]
Definition at line 413 of file ast.hpp.
References Statement::DIRECTIVE, and Sass::statement_type.
Member Function Documentation
ADD_PROPERTY (Expression * , value) [private]
ADD_PROPERTY (Selector * , selector) [private]
ADD_PROPERTY (string , keyword) [private]
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
bool bubbles () [inline, virtual]
Reimplemented from Statement.
Definition at line 416 of file ast.hpp.
References At_Rule::is_keyframes(), and At_Rule::is_media().
bool is_keyframes () [inline]
Definition at line 423 of file ast.hpp.
Referenced by At_Rule::bubbles(), Expand::operator()(), and Cssize::operator()().
bool is_media () [inline]
Definition at line 417 of file ast.hpp.
Referenced by At_Rule::bubbles().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp