Emeraldion Lodge (codename Zelda): Position Class Reference
Position Class Reference
#include <position.hpp>
Inherits Sass::Offset.
Inherited by ParserState.
Public Member Functions
Position (const size_t file)
Position (const size_t file, const Offset &offset)
Position (const size_t line, const size_t column)
Position (const size_t file, const size_t line, const size_t column)
void operator+= (const Offset &off)
bool operator== (const Position &pos) const
bool operator!= (const Position &pos) const
const Position operator+ (const Offset &off) const
const Offset operator- (const Offset &off) const
Position add (const char *begin, const char *end)
Position inc (const char *begin, const char *end) const
Data Fields
size_t file
Detailed Description
Definition at line 47 of file position.hpp.
Constructor & Destructor Documentation
Position (const size_t file)
Definition at line 86 of file position.cpp.
Referenced by Parser::do_import(), Position::inc(), Position::operator+(), and Position::operator+=().
Position (const size_t file, const Offset & offset)
Definition at line 89 of file position.cpp.
Position (const size_t line, const size_t column)
Definition at line 92 of file position.cpp.
Position (const size_t file, const size_t line, const size_t column)
Definition at line 95 of file position.cpp.
Member Function Documentation
Position add (const char * begin, const char * end)
Reimplemented from Offset.
Definition at line 108 of file position.cpp.
Referenced by Parser::lex().
Position inc (const char * begin, const char * end) const
Reimplemented from Offset.
Definition at line 114 of file position.cpp.
References Offset::column, Position::file, Offset::inc(), Offset::line, and Position::Position().
bool operator!= (const Position & pos) const
Definition at line 126 of file position.cpp.
References Offset::column, Position::file, and Offset::line.
const Position operator+ (const Offset & off) const
Reimplemented from Offset.
Definition at line 136 of file position.cpp.
References Offset::column, Position::file, Offset::line, and Position::Position().
void operator+= (const Offset & off)
Reimplemented from Offset.
Definition at line 131 of file position.cpp.
References Offset::column, Position::file, Offset::line, and Position::Position().
const Offset operator- (const Offset & off) const
Reimplemented from Offset.
Definition at line 141 of file position.cpp.
References Offset::column, Offset::line, and Offset::Offset().
bool operator== (const Position & pos) const
Definition at line 121 of file position.cpp.
References Offset::column, Position::file, and Offset::line.
Field Documentation
size_t file
Definition at line 69 of file position.hpp.
Referenced by Parser::do_import(), Position::inc(), Position::operator!=(), Position::operator+(), Position::operator+=(), Position::operator==(), and SourceMap::remap().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/position.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/position.cpp