Emeraldion Lodge (codename Zelda): Subset_Map< K, V > Class Template Reference
Subset_Map< K, V > Class Template Reference
#include <subset_map.hpp>
Public Member Functions
void put (const vector< K > &s, const V &value)
vector< pair< V, vector< K > > > get_kv (const vector< K > &s)
vector< V > get_v (const vector< K > &s)
bool empty ()
void clear ()
const vector< V > values (void)
Private Attributes
vector< V > values_
map< K, vector< triple< vector
< K >, set< K >, size_t > > > hash_
Detailed Description
template<typename K, typename V>
class Sass::Subset_Map< K, V >
Definition at line 75 of file subset_map.hpp.
Member Function Documentation
void clear () [inline]
Definition at line 84 of file subset_map.hpp.
bool empty () [inline]
Definition at line 83 of file subset_map.hpp.
Referenced by Context::parse_file().
vector< pair< V, vector< K > > > get_kv (const vector< K > & s) [inline]
Definition at line 105 of file subset_map.hpp.
References utf8::unchecked::distance(), Subset_Map< K, V >::hash_, and Subset_Map< K, V >::values_.
Referenced by Subset_Map< K, V >::get_v().
vector< V > get_v (const vector< K > & s) [inline]
Definition at line 137 of file subset_map.hpp.
References Subset_Map< K, V >::get_kv().
Referenced by Sass::complexSelectorHasExtension(), and Sass::extendCompoundSelector().
void put (const vector< K > & s, const V & value) [inline]
Definition at line 89 of file subset_map.hpp.
References Subset_Map< K, V >::hash_, Sass::make_triple(), and Subset_Map< K, V >::values_.
Referenced by Expand::operator()().
const vector<V> values (void) [inline]
Definition at line 85 of file subset_map.hpp.
Field Documentation
map<K, vector<triple<vector<K>, set<K>, size_t> > > hash_ [private]
Definition at line 78 of file subset_map.hpp.
Referenced by Subset_Map< string, pair< Complex_Selector *, Compound_Selector * > >::clear(), Subset_Map< K, V >::get_kv(), and Subset_Map< K, V >::put().
vector<V> values_ [private]
Definition at line 77 of file subset_map.hpp.
Referenced by Subset_Map< string, pair< Complex_Selector *, Compound_Selector * > >::clear(), Subset_Map< string, pair< Complex_Selector *, Compound_Selector * > >::empty(), Subset_Map< K, V >::get_kv(), Subset_Map< K, V >::put(), and Subset_Map< string, pair< Complex_Selector *, Compound_Selector * > >::values().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/subset_map.hpp