Emeraldion Lodge (codename Zelda): MaybeLocal< T > Class Template Reference
MaybeLocal< T > Class Template Reference
#include <nan_maybe_pre_43_inl.h>
Public Member Functions
NAN_INLINE MaybeLocal ()
template<typename S >
NAN_INLINE MaybeLocal (v8::Local< S > that)
NAN_INLINE bool IsEmpty () const
template<typename S >
NAN_INLINE bool ToLocal (v8::Local< S > *out) const
NAN_INLINE v8::Local< T > ToLocalChecked () const
template<typename S >
NAN_INLINE v8::Local< S > FromMaybe (v8::Local< S > default_value) const
Private Attributes
v8::Local< T > val_
Detailed Description
template<typename T>
class MaybeLocal< T >
Definition at line 13 of file nan_maybe_pre_43_inl.h.
Constructor & Destructor Documentation
NAN_INLINE MaybeLocal () [inline]
Definition at line 15 of file nan_maybe_pre_43_inl.h.
NAN_INLINE MaybeLocal (v8::Local< S > that) [inline]
Definition at line 19 of file nan_maybe_pre_43_inl.h.
Member Function Documentation
NAN_INLINE v8::Local<S> FromMaybe (v8::Local< S > default_value) const [inline]
Definition at line 41 of file nan_maybe_pre_43_inl.h.
References MaybeLocal< T >::IsEmpty(), and MaybeLocal< T >::val_.
NAN_INLINE bool IsEmpty () const [inline]
Definition at line 25 of file nan_maybe_pre_43_inl.h.
References MaybeLocal< T >::val_.
Referenced by MaybeLocal< T >::FromMaybe(), MaybeLocal< T >::ToLocal(), and MaybeLocal< T >::ToLocalChecked().
NAN_INLINE bool ToLocal (v8::Local< S > * out) const [inline]
Definition at line 28 of file nan_maybe_pre_43_inl.h.
References MaybeLocal< T >::IsEmpty(), and MaybeLocal< T >::val_.
NAN_INLINE v8::Local<T> ToLocalChecked () const [inline]
Definition at line 33 of file nan_maybe_pre_43_inl.h.
References MaybeLocal< T >::IsEmpty(), and MaybeLocal< T >::val_.
Field Documentation
v8::Local<T> val_ [private]
Definition at line 46 of file nan_maybe_pre_43_inl.h.
Referenced by MaybeLocal< T >::FromMaybe(), MaybeLocal< T >::IsEmpty(), MaybeLocal< T >::ToLocal(), and MaybeLocal< T >::ToLocalChecked().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_maybe_pre_43_inl.h