Emeraldion Lodge (codename Zelda): Error Class Reference
Error Class Reference
#include <error.h>
Inherits SassValueWrapper< Error >.
Public Member Functions
Error (Sass_Value *)
Static Public Member Functions
static char const * get_constructor_name ()
static Sass_Value * construct (const std::vector< v8::Local< v8::Value >>, Sass_Value **)
static void initPrototype (v8::Local< v8::FunctionTemplate >)
Detailed Description
Definition at line 9 of file error.h.
Constructor & Destructor Documentation
Error (Sass_Value * v)
Definition at line 7 of file error.cpp.
Member Function Documentation
Sass_Value * construct (const std::vector< v8::Local< v8::Value >> raw_val, Sass_Value ** out) [static]
Definition at line 9 of file error.cpp.
References create_string(), SassValueWrapper< Error >::fail(), sass_make_error(), and SassValueWrapper< Error >::value.
static char const* get_constructor_name () [inline, static]
Reimplemented from SassValueWrapper< Error >.
Definition at line 12 of file error.h.
void initPrototype (v8::Local< v8::FunctionTemplate >) [static]
Definition at line 23 of file error.cpp.
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/error.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/error.cpp