Emeraldion Lodge (codename Zelda): Map Class Reference
Map Class Reference
#include <ast.hpp>
Inherits Sass::Expression, and Sass::Hashed.
Public Member Functions
Map (ParserState pstate, size_t size=0)
string type ()
bool is_invisible ()
virtual bool operator== (Expression &rhs) const
virtual size_t hash ()
ATTACH_OPERATIONS ()
Static Public Member Functions
static string type_name ()
Private Member Functions
void adjust_after_pushing (std::pair< Expression *, Expression * > p)
Detailed Description
Definition at line 789 of file ast.hpp.
Constructor & Destructor Documentation
Map (ParserState pstate, size_t size = 0) [inline]
Definition at line 792 of file ast.hpp.
References Expression::MAP.
Member Function Documentation
void adjust_after_pushing (std::pair< Expression *, Expression * > p) [inline, private, virtual]
Reimplemented from Hashed.
Definition at line 790 of file ast.hpp.
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
virtual size_t hash () [inline, virtual]
Reimplemented from Expression.
Definition at line 818 of file ast.hpp.
References Hashed::at(), Expression::hash(), Hashed::hash_, and Hashed::keys().
bool is_invisible () [inline, virtual]
Reimplemented from Expression.
Definition at line 799 of file ast.hpp.
References Hashed::length().
Referenced by Inspect::operator()().
virtual bool operator== (Expression & rhs) const [inline, virtual]
Reimplemented from Expression.
Definition at line 801 of file ast.hpp.
References Hashed::at(), Hashed::keys(), and Hashed::length().
string type () [inline, virtual]
Reimplemented from Expression.
Definition at line 797 of file ast.hpp.
static string type_name () [inline, static]
Reimplemented from Expression.
Definition at line 798 of file ast.hpp.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp