Emeraldion Lodge (codename Zelda): Number Class Reference
Number Class Reference
#include <ast.hpp>
Inherits Sass::Expression.
Public Member Functions
Number (ParserState pstate, double val, string u="", bool zero=true)
bool zero ()
vector< string > & numerator_units ()
vector< string > & denominator_units ()
string type ()
string unit () const
bool is_unitless ()
void convert (const string &unit="")
void normalize (const string &unit="")
string find_convertible_unit () const
virtual bool operator== (Expression &rhs) const
virtual bool operator== (Expression *rhs) const
virtual size_t hash ()
ATTACH_OPERATIONS ()
Static Public Member Functions
static string type_name ()
Private Member Functions
ADD_PROPERTY (double, value)
ADD_PROPERTY (bool, zero)
Private Attributes
vector< string > numerator_units_
vector< string > denominator_units_
size_t hash_
Detailed Description
Definition at line 1184 of file ast.hpp.
Constructor & Destructor Documentation
Number (ParserState pstate, double val, string u = "", bool zero = true)
Definition at line 658 of file ast.cpp.
References Number::denominator_units_, l(), npos, Expression::NUMBER, Number::numerator_units_, and Number::unit().
Member Function Documentation
ADD_PROPERTY (bool , zero) [private]
ADD_PROPERTY (double , value) [private]
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
void convert (const string & unit = "")
Definition at line 783 of file ast.cpp.
References Sass::conversion_factor(), Number::denominator_units_, Number::numerator_units_, Sass::string_to_unit(), and Sass::UNKNOWN.
Referenced by Number::normalize().
vector<string>& denominator_units () [inline]
Definition at line 1194 of file ast.hpp.
References Number::denominator_units_.
Referenced by Sass::op_numbers(), and Inspect::operator()().
string find_convertible_unit () const
Definition at line 869 of file ast.cpp.
References Number::denominator_units_, Number::numerator_units_, Sass::string_to_unit(), and Sass::UNKNOWN.
Referenced by Sass::Functions::BUILT_IN(), Sass::lt(), Sass::op_numbers(), and Number::operator==().
virtual size_t hash () [inline, virtual]
Reimplemented from Expression.
Definition at line 1208 of file ast.hpp.
References Number::hash_.
bool is_unitless ()
Definition at line 697 of file ast.cpp.
References Number::denominator_units_, and Number::numerator_units_.
Referenced by Sass::Functions::BUILT_IN().
void normalize (const string & unit = "")
Definition at line 700 of file ast.cpp.
References Sass::conversion_factor(), Number::convert(), Number::denominator_units_, Sass::error(), Number::numerator_units_, Sass::pstate, Sass::string_to_unit(), Sass::UNKNOWN, and incompatibleUnits::what().
Referenced by Sass::Functions::BUILT_IN(), Sass::lt(), Sass::op_numbers(), Inspect::operator()(), Eval::operator()(), and Number::operator==().
vector<string>& numerator_units () [inline]
Definition at line 1193 of file ast.hpp.
References Number::numerator_units_.
Referenced by Sass::op_numbers(), and Inspect::operator()().
bool operator== (Expression * rhs) const [virtual]
Definition at line 883 of file ast.cpp.
References Number::find_convertible_unit(), l(), Number::normalize(), and Number::unit().
bool operator== (Expression & rhs) const [virtual]
Reimplemented from Expression.
Definition at line 899 of file ast.cpp.
string type () [inline, virtual]
Reimplemented from Expression.
Definition at line 1195 of file ast.hpp.
static string type_name () [inline, static]
Reimplemented from Expression.
Definition at line 1196 of file ast.hpp.
string unit () const
Definition at line 682 of file ast.cpp.
References Number::denominator_units_, and Number::numerator_units_.
Referenced by Sass::Functions::BUILT_IN(), Sass::Functions::color_num(), Sass::lt(), Number::Number(), Sass::op_numbers(), To_C::operator()(), Inspect::operator()(), Expand::operator()(), Eval::operator()(), and Number::operator==().
bool zero () [inline]
Definition at line 1192 of file ast.hpp.
Field Documentation
vector<string> denominator_units_ [private]
Definition at line 1188 of file ast.hpp.
Referenced by Number::convert(), Number::denominator_units(), Number::find_convertible_unit(), Number::is_unitless(), Number::normalize(), Number::Number(), and Number::unit().
size_t hash_ [private]
Definition at line 1189 of file ast.hpp.
Referenced by Number::hash().
vector<string> numerator_units_ [private]
Definition at line 1187 of file ast.hpp.
Referenced by Number::convert(), Number::find_convertible_unit(), Number::is_unitless(), Number::normalize(), Number::Number(), Number::numerator_units(), and Number::unit().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp