Emeraldion Lodge (codename Zelda): Emitter Class Reference
Emitter Class Reference
#include <emitter.hpp>
Inherited by Inspect.
Public Member Functions
Emitter (Context *ctx)
virtual ~Emitter ()
const string buffer (void)
const SourceMap smap (void)
const OutputBuffer output (void)
void add_source_index (size_t idx)
void set_filename (const string &str)
void add_open_mapping (AST_Node *node)
void add_close_mapping (AST_Node *node)
string generate_source_map (Context &ctx)
ParserState remap (const ParserState &pstate)
string get_buffer (void)
Output_Style output_style (void)
void finalize (void)
void flush_schedules (void)
void prepend_string (const string &text)
void prepend_output (const OutputBuffer &out)
void append_string (const string &text)
void append_wspace (const string &text)
void append_token (const string &text, AST_Node *node)
void append_indentation ()
void append_optional_space (void)
void append_mandatory_space (void)
void append_special_linefeed (void)
void append_optional_linefeed (void)
void append_mandatory_linefeed (void)
void append_scope_opener (AST_Node *node=0)
void append_scope_closer (AST_Node *node=0)
void append_comma_separator (void)
void append_colon_separator (void)
void append_delimiter (void)
Data Fields
Context * ctx
size_t indentation
size_t scheduled_space
size_t scheduled_linefeed
bool scheduled_delimiter
bool in_comment
bool in_wrapped
bool in_media_block
bool in_declaration
bool in_space_array
bool in_comma_array
Protected Attributes
OutputBuffer wbuf
Detailed Description
Definition at line 12 of file emitter.hpp.
Constructor & Destructor Documentation
Emitter (Context * ctx)
Definition at line 10 of file emitter.cpp.
virtual ~Emitter () [inline, virtual]
Definition at line 16 of file emitter.hpp.
Member Function Documentation
void add_close_mapping (AST_Node * node)
Definition at line 49 of file emitter.cpp.
References SourceMap::add_close_mapping(), OutputBuffer::smap, and Emitter::wbuf.
Referenced by Emitter::append_scope_closer(), Emitter::append_token(), and Inspect::operator()().
void add_open_mapping (AST_Node * node)
Definition at line 47 of file emitter.cpp.
References SourceMap::add_open_mapping(), OutputBuffer::smap, and Emitter::wbuf.
Referenced by Emitter::append_scope_opener(), Emitter::append_token(), and Inspect::operator()().
void add_source_index (size_t idx)
Definition at line 38 of file emitter.cpp.
References OutputBuffer::smap, SourceMap::source_index, and Emitter::wbuf.
Referenced by Context::add_source().
void append_colon_separator (void)
Definition at line 179 of file emitter.cpp.
References Emitter::append_optional_space(), Emitter::append_string(), and Emitter::scheduled_space.
Referenced by Output::operator()(), and Inspect::operator()().
void append_comma_separator (void)
Definition at line 172 of file emitter.cpp.
References Emitter::append_optional_space(), Emitter::append_string(), and Emitter::scheduled_space.
Referenced by Inspect::operator()().
void append_delimiter (void)
Definition at line 158 of file emitter.cpp.
References Emitter::append_mandatory_linefeed(), Emitter::append_mandatory_space(), Emitter::append_optional_linefeed(), Sass::COMPACT, Sass::COMPRESSED, Emitter::indentation, Emitter::output_style(), and Emitter::scheduled_delimiter.
Referenced by Output::operator()(), and Inspect::operator()().
void append_indentation ()
Definition at line 146 of file emitter.cpp.
References Emitter::append_string(), Sass::COMPACT, Sass::COMPRESSED, Emitter::ctx, Context::indent, Emitter::indentation, Emitter::output_style(), and Emitter::scheduled_linefeed.
Referenced by Emitter::append_scope_closer(), Output::operator()(), and Inspect::operator()().
void append_mandatory_linefeed (void)
Definition at line 219 of file emitter.cpp.
References Sass::COMPRESSED, Emitter::output_style(), Emitter::scheduled_linefeed, and Emitter::scheduled_space.
Referenced by Emitter::append_delimiter(), Emitter::append_optional_linefeed(), Emitter::append_special_linefeed(), Emitter::append_wspace(), Output::get_buffer(), Output::operator()(), and Inspect::operator()().
void append_mandatory_space (void)
Definition at line 186 of file emitter.cpp.
References Emitter::scheduled_space.
Referenced by Emitter::append_delimiter(), Emitter::append_optional_linefeed(), Emitter::append_optional_space(), Output::operator()(), and Inspect::operator()().
void append_optional_linefeed (void)
Definition at line 210 of file emitter.cpp.
References Emitter::append_mandatory_linefeed(), Emitter::append_mandatory_space(), Sass::COMPACT, and Emitter::output_style().
Referenced by Emitter::append_delimiter(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Output::operator()(), and Inspect::operator()().
void append_optional_space (void)
Definition at line 191 of file emitter.cpp.
References Emitter::append_mandatory_space(), Emitter::buffer(), Sass::COMPRESSED, Emitter::output_style(), and Emitter::scheduled_delimiter.
Referenced by Emitter::append_colon_separator(), Emitter::append_comma_separator(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), and Inspect::operator()().
void append_scope_closer (AST_Node * node = 0)
Definition at line 238 of file emitter.cpp.
References Emitter::add_close_mapping(), Emitter::append_indentation(), Emitter::append_optional_linefeed(), Emitter::append_optional_space(), Emitter::append_string(), Sass::COMPRESSED, Sass::EXPANDED, Emitter::indentation, Emitter::output_style(), Emitter::scheduled_delimiter, and Emitter::scheduled_linefeed.
Referenced by Output::operator()(), and Inspect::operator()().
void append_scope_opener (AST_Node * node = 0)
Definition at line 228 of file emitter.cpp.
References Emitter::add_open_mapping(), Emitter::append_optional_linefeed(), Emitter::append_optional_space(), Emitter::append_string(), Emitter::flush_schedules(), and Emitter::indentation.
Referenced by Output::operator()(), and Inspect::operator()().
void append_special_linefeed (void)
Definition at line 201 of file emitter.cpp.
References Emitter::append_mandatory_linefeed(), Emitter::append_string(), Sass::COMPACT, Emitter::ctx, Context::indent, Emitter::indentation, Emitter::output_style(), and p().
Referenced by Output::operator()().
void append_string (const string & text)
Definition at line 104 of file emitter.cpp.
References SourceMap::append(), OutputBuffer::buffer, Sass::comment_to_string(), Sass::COMPACT, Emitter::flush_schedules(), Emitter::in_comment, Emitter::output_style(), OutputBuffer::smap, and Emitter::wbuf.
Referenced by Emitter::append_colon_separator(), Emitter::append_comma_separator(), Emitter::append_indentation(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_special_linefeed(), Emitter::append_token(), Emitter::flush_schedules(), Output::get_buffer(), Output::operator()(), and Inspect::operator()().
void append_token (const string & text, AST_Node * node)
Definition at line 136 of file emitter.cpp.
References Emitter::add_close_mapping(), Emitter::add_open_mapping(), Emitter::append_string(), and Emitter::flush_schedules().
Referenced by Output::operator()(), and Inspect::operator()().
void append_wspace (const string & text)
Definition at line 125 of file emitter.cpp.
References Emitter::append_mandatory_linefeed(), Sass::peek_linefeed(), and Emitter::scheduled_space.
const string buffer (void) [inline]
Definition at line 21 of file emitter.hpp.
References OutputBuffer::buffer, and Emitter::wbuf.
Referenced by Emitter::append_optional_space(), and Output::operator()().
void finalize (void)
Definition at line 57 of file emitter.cpp.
References Emitter::flush_schedules(), Emitter::scheduled_linefeed, and Emitter::scheduled_space.
Referenced by Context::compile_block(), and Output::get_buffer().
void flush_schedules (void)
Definition at line 66 of file emitter.cpp.
References Emitter::append_string(), Emitter::ctx, Context::linefeed, Emitter::scheduled_delimiter, Emitter::scheduled_linefeed, Emitter::scheduled_space, and Sass::Prelexer::spaces().
Referenced by Emitter::append_scope_opener(), Emitter::append_string(), Emitter::append_token(), and Emitter::finalize().
string generate_source_map (Context & ctx)
Definition at line 41 of file emitter.cpp.
References SourceMap::generate_source_map(), OutputBuffer::smap, and Emitter::wbuf.
Referenced by Context::format_source_mapping_url(), and Context::generate_source_map().
string get_buffer (void)
Reimplemented in Output.
Definition at line 26 of file emitter.cpp.
References OutputBuffer::buffer, and Emitter::wbuf.
Referenced by To_String::fallback_impl(), and Expand::operator()().
const OutputBuffer output (void) [inline]
Definition at line 23 of file emitter.hpp.
References Emitter::wbuf.
Referenced by Output::get_buffer().
Output_Style output_style (void)
Definition at line 31 of file emitter.cpp.
References Sass::COMPRESSED, Emitter::ctx, and Context::output_style.
Referenced by Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_linefeed(), Emitter::append_optional_linefeed(), Emitter::append_optional_space(), Emitter::append_scope_closer(), Emitter::append_special_linefeed(), Emitter::append_string(), Output::get_buffer(), Output::operator()(), and Inspect::operator()().
void prepend_output (const OutputBuffer & out)
Definition at line 90 of file emitter.cpp.
References OutputBuffer::buffer, SourceMap::prepend(), OutputBuffer::smap, and Emitter::wbuf.
Referenced by Output::get_buffer().
void prepend_string (const string & text)
Definition at line 97 of file emitter.cpp.
References OutputBuffer::buffer, SourceMap::prepend(), OutputBuffer::smap, and Emitter::wbuf.
Referenced by Output::get_buffer().
ParserState remap (const ParserState & pstate)
Definition at line 51 of file emitter.cpp.
References SourceMap::remap(), OutputBuffer::smap, and Emitter::wbuf.
void set_filename (const string & str)
Definition at line 44 of file emitter.cpp.
References SourceMap::file, OutputBuffer::smap, and Emitter::wbuf.
const SourceMap smap (void) [inline]
Definition at line 22 of file emitter.hpp.
References OutputBuffer::smap, and Emitter::wbuf.
Field Documentation
Context* ctx
Definition at line 33 of file emitter.hpp.
Referenced by Emitter::append_indentation(), Emitter::append_special_linefeed(), Emitter::flush_schedules(), Output::get_buffer(), Output::operator()(), Inspect::operator()(), and Emitter::output_style().
bool in_comma_array
Definition at line 50 of file emitter.hpp.
Referenced by Inspect::operator()().
bool in_comment
Definition at line 41 of file emitter.hpp.
Referenced by Emitter::append_string(), Output::operator()(), and Inspect::operator()().
bool in_declaration
Definition at line 47 of file emitter.hpp.
Referenced by To_String::fallback_impl(), and Inspect::operator()().
bool in_media_block
Definition at line 45 of file emitter.hpp.
Referenced by Output::operator()(), and Inspect::operator()().
bool in_space_array
Definition at line 49 of file emitter.hpp.
Referenced by Inspect::operator()().
bool in_wrapped
Definition at line 43 of file emitter.hpp.
Referenced by Output::operator()(), and Inspect::operator()().
size_t indentation
Definition at line 34 of file emitter.hpp.
Referenced by Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::append_special_linefeed(), Output::operator()(), and Inspect::operator()().
bool scheduled_delimiter
Definition at line 37 of file emitter.hpp.
Referenced by Emitter::append_delimiter(), Emitter::append_optional_space(), Emitter::append_scope_closer(), and Emitter::flush_schedules().
size_t scheduled_linefeed
Definition at line 36 of file emitter.hpp.
Referenced by Emitter::append_indentation(), Emitter::append_mandatory_linefeed(), Emitter::append_scope_closer(), Emitter::finalize(), and Emitter::flush_schedules().
size_t scheduled_space
Definition at line 35 of file emitter.hpp.
Referenced by Emitter::append_colon_separator(), Emitter::append_comma_separator(), Emitter::append_mandatory_linefeed(), Emitter::append_mandatory_space(), Emitter::append_wspace(), Emitter::finalize(), Emitter::flush_schedules(), and Inspect::operator()().
OutputBuffer wbuf [protected]
Definition at line 16 of file emitter.hpp.
Referenced by Emitter::add_close_mapping(), Emitter::add_open_mapping(), Emitter::add_source_index(), Emitter::append_string(), Emitter::buffer(), Emitter::generate_source_map(), Output::get_buffer(), Emitter::get_buffer(), Emitter::output(), Emitter::prepend_output(), Emitter::prepend_string(), Emitter::remap(), Emitter::set_filename(), and Emitter::smap().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/emitter.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/emitter.cpp