Emeraldion Lodge (codename Zelda): Localization Class Reference
Localization Class Reference
Adds localization support to EmeRails.
Static Public Member Functions
static localize ($term)
Localizes a string according to the current language settings.
static add_strings_table ($controller)
Adds another strings table for a desired controller.
Static Public Attributes
static $languages = array('it', 'en', 'es', 'fr', 'de', 'ja', 'da', 'ru', 'pt', 'pl', 'cs', 'nl', 'fi', 'sv', 'el', 'ro', 'nb', 'hu', 'hr', 'ko')
Array of supported languages.
Static Private Member Functions
static wrap ($term)
Wraps a string in a parent HTML element to add debug style selectors.
static load_strings_file ($lang= 'en', $controller=NULL)
Loads the string file for the desired controller and language.
static load_strings_table ()
Loads the string table for the current controller and language.
Static Private Attributes
static $strings_table
Table of translated strings.
Detailed Description
Adds localization support to EmeRails.
Definition at line 10 of file localization.php.
Member Function Documentation
add_strings_table ($controller) static
Adds another strings table for a desired controller.
Language is obtained by the request parameters.
Parameters
controller The name of the controller.
Definition at line 45 of file localization.php.
Referenced by BaseController\render_component().
load_strings_file ($lang = 'en', $controller = NULL) static private
Loads the string file for the desired controller and language.
Parameters
lang The language for the strings file.
controller The name of the controller.
Definition at line 73 of file localization.php.
load_strings_table () static private
Loads the string table for the current controller and language.
Controller and language are obtained by the request parameters.
Definition at line 97 of file localization.php.
localize ($term) static
Localizes a string according to the current language settings.
Parameters
term The string to be translated.
Definition at line 29 of file localization.php.
Referenced by localized().
wrap ($term) static private
Wraps a string in a parent HTML element to add debug style selectors.
Parameters
term The string to be wrapped.
Definition at line 60 of file localization.php.
References LOCALIZATION_DEBUG.
Field Documentation
$languages = array('it', 'en', 'es', 'fr', 'de', 'ja', 'da', 'ru', 'pt', 'pl', 'cs', 'nl', 'fi', 'sv', 'el', 'ro', 'nb', 'hu', 'hr', 'ko') static
Array of supported languages.
languages
Definition at line 16 of file localization.php.
Referenced by BaseController\expire_cached_page().
$strings_table static private
Table of translated strings.
strings_table
Definition at line 22 of file localization.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/localization.php