Emeraldion Lodge (codename Zelda): At_Root_Expression Class Reference
At_Root_Expression Class Reference
#include <ast.hpp>
Inherits Sass::Expression.
Public Member Functions
At_Root_Expression (ParserState pstate, String *f=0, Expression *v=0, bool i=false)
bool exclude (string str)
ATTACH_OPERATIONS ()
Private Member Functions
ADD_PROPERTY (String *, feature)
ADD_PROPERTY (Expression *, value)
ADD_PROPERTY (bool, is_interpolated)
Detailed Description
Definition at line 1489 of file ast.hpp.
Constructor & Destructor Documentation
At_Root_Expression (ParserState pstate, String * f = 0, Expression * v = 0, bool i = false) [inline]
Definition at line 1495 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (bool , is_interpolated) [private]
ADD_PROPERTY (Expression * , value) [private]
ADD_PROPERTY (String * , feature) [private]
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
bool exclude (string str) [inline]
Definition at line 1498 of file ast.hpp.
References l(), Vectorized< T >::length(), Sass::to_string, and Sass::unquote().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp