Emeraldion Lodge (codename Zelda): iterator< octet_iterator > Class Template Reference
iterator< octet_iterator > Class Template Reference
#include <unchecked.h>
Public Member Functions
iterator ()
iterator (const octet_iterator &octet_it)
octet_iterator base () const
uint32_t operator* () const
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
Private Attributes
octet_iterator it
Detailed Description
template<typename octet_iterator>
class utf8::unchecked::iterator< octet_iterator >
Definition at line 179 of file unchecked.h.
Constructor & Destructor Documentation
iterator () [inline]
Definition at line 182 of file unchecked.h.
iterator (const octet_iterator< octet_iterator > & octet_it) [inline, explicit]
Definition at line 183 of file unchecked.h.
Member Function Documentation
octet_iterator base () const [inline]
Definition at line 185 of file unchecked.h.
References iterator< octet_iterator >::it.
bool operator!= (const iterator< octet_iterator > & rhs) const [inline]
Definition at line 195 of file unchecked.h.
References iterator< octet_iterator >::operator==().
uint32_t operator* () const [inline]
Definition at line 186 of file unchecked.h.
References iterator< octet_iterator >::it, and utf8::unchecked::next().
iterator operator++ (int) [inline]
Definition at line 204 of file unchecked.h.
References utf8::unchecked::advance(), iterator< octet_iterator >::it, and utf8::internal::sequence_length().
iterator& operator++ () [inline]
Definition at line 199 of file unchecked.h.
References utf8::unchecked::advance(), iterator< octet_iterator >::it, and utf8::internal::sequence_length().
iterator operator-- (int) [inline]
Definition at line 215 of file unchecked.h.
References iterator< octet_iterator >::it, and utf8::unchecked::prior().
iterator& operator-- () [inline]
Definition at line 210 of file unchecked.h.
References iterator< octet_iterator >::it, and utf8::unchecked::prior().
bool operator== (const iterator< octet_iterator > & rhs) const [inline]
Definition at line 191 of file unchecked.h.
References iterator< octet_iterator >::it.
Referenced by iterator< octet_iterator >::operator!=().
Field Documentation
octet_iterator it [private]
Definition at line 180 of file unchecked.h.
Referenced by iterator< octet_iterator >::base(), iterator< octet_iterator >::operator*(), iterator< octet_iterator >::operator++(), iterator< octet_iterator >::operator--(), and iterator< octet_iterator >::operator==().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/utf8/unchecked.h