Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass.h File Reference
#include <stddef.h>
#include <stdbool.h>
#include "sass_version.h"
#include "sass_values.h"
#include "sass_functions.h"
Defines
#define DEPRECATED(func) func
#define ADDAPI
#define ADDCALL
Enumerations
enum Sass_Output_Style { SASS_STYLE_NESTED, SASS_STYLE_EXPANDED, SASS_STYLE_COMPACT, SASS_STYLE_COMPRESSED }
Functions
ADDAPI char *ADDCALL sass_string_quote (const char *str, const char quote_mark)
ADDAPI char *ADDCALL sass_string_unquote (const char *str)
ADDAPI char *ADDCALL sass_resolve_file (const char *path, const char *incs[])
ADDAPI const char *ADDCALL libsass_version (void)
Define Documentation
#define ADDAPI
Definition at line 30 of file sass.h.
#define ADDCALL
Definition at line 31 of file sass.h.
#define DEPRECATED (func) func
Definition at line 13 of file sass.h.
Enumeration Type Documentation
enum Sass_Output_Style
Enumerator:
SASS_STYLE_NESTED
SASS_STYLE_EXPANDED
SASS_STYLE_COMPACT
SASS_STYLE_COMPRESSED
Definition at line 47 of file sass.h.
Function Documentation
ADDAPI const char* ADDCALL libsass_version (void)
Definition at line 38 of file sass.cpp.
References LIBSASS_VERSION.
Referenced by Sass::compatibility(), libsass_get_version(), NAN_METHOD(), and NAN_MODULE_INIT().
ADDAPI char* ADDCALL sass_resolve_file (const char * path, const char * incs[])
Definition at line 31 of file sass.cpp.
References Sass::File::find_file(), and Sass::sass_strdup().
ADDAPI char* ADDCALL sass_string_quote (const char * str, const char quote_mark)
Definition at line 16 of file sass.cpp.
References Sass::quote(), and Sass::sass_strdup().
ADDAPI char* ADDCALL sass_string_unquote (const char * str)
Definition at line 23 of file sass.cpp.
References Sass::sass_strdup(), and Sass::unquote().