Emeraldion Lodge (codename Zelda): ParserState Class Reference
ParserState Class Reference
#include <position.hpp>
Inherits Sass::Position.
Inherited by Parser.
Public Member Functions
ParserState (string path, const char *src=0, const size_t file=string::npos)
ParserState (string path, const char *src, Position position, Offset offset=Offset(0, 0))
ParserState (string path, const char *src, Token token, Position position, Offset offset=Offset(0, 0))
Offset off ()
Position pos ()
ParserState pstate ()
Data Fields
string path
const char * src
Offset offset
Token token
Detailed Description
Definition at line 104 of file position.hpp.
Constructor & Destructor Documentation
ParserState (string path, const char * src = 0, const size_t file = string::npos)
Definition at line 99 of file position.cpp.
Referenced by Parser::do_import(), and Parser::lex().
ParserState (string path, const char * src, Position position, Offset offset = Offset(0, 0))
Definition at line 102 of file position.cpp.
ParserState (string path, const char * src, Token token, Position position, Offset offset = Offset(0, 0))
Definition at line 105 of file position.cpp.
Member Function Documentation
Offset off () [inline]
Reimplemented from Offset.
Definition at line 112 of file position.hpp.
Position pos () [inline]
Definition at line 113 of file position.hpp.
Referenced by Parser::lex_css(), Parser::parse_parameter(), and Parser::sneak().
ParserState pstate () [inline]
Definition at line 114 of file position.hpp.
Referenced by Parser::add_single_file(), Parser::do_import(), Parser::import_single_file(), Parser::lex(), Parser::parse(), Parser::parse_argument(), Parser::parse_arguments(), Parser::parse_assignment(), Parser::parse_at_root_block(), Parser::parse_at_root_expression(), Parser::parse_at_rule(), Parser::parse_calc_function(), Parser::parse_comma_list(), Parser::parse_debug(), Parser::parse_declaration(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_error(), Parser::parse_factor(), Parser::parse_feature_block(), Parser::parse_feature_queries(), Parser::parse_feature_query_in_parens(), Parser::parse_for_directive(), Parser::parse_function_call(), Parser::parse_function_call_schema(), Parser::parse_identifier_schema(), Parser::parse_ie_keyword_arg(), Parser::parse_ie_property(), Parser::parse_if_directive(), Parser::parse_import(), Parser::parse_interpolated_chunk(), Parser::parse_map(), Parser::parse_media_block(), Parser::parse_media_expression(), Parser::parse_media_queries(), Parser::parse_media_query(), Parser::parse_mixin_call(), Parser::parse_parameter(), Parser::parse_parameters(), Parser::parse_ruleset(), Parser::parse_selector_group(), Parser::parse_selector_schema(), Parser::parse_space_list(), Parser::parse_static_value(), Parser::parse_value(), Parser::parse_value_schema(), Parser::parse_warning(), and Parser::parse_while_directive().
Field Documentation
Offset offset
Definition at line 119 of file position.hpp.
Referenced by Parser::parse_map(), and SourceMap::remap().
string path
Definition at line 114 of file position.hpp.
Referenced by Parser::add_single_file(), handle_errors(), Parser::lex(), SourceMap::remap(), and Backtrace::to_string().
const char* src
Definition at line 118 of file position.hpp.
Referenced by handle_errors(), and SourceMap::remap().
Token token
Definition at line 120 of file position.hpp.
Referenced by Parser::parse_string().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/position.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/position.cpp