Emeraldion Lodge (codename Zelda): Backtrace Struct Reference
Backtrace Struct Reference
#include <backtrace.hpp>
Public Member Functions
Backtrace (Backtrace *prn, ParserState pstate, string c)
string to_string (bool warning=false)
size_t depth ()
Data Fields
Backtrace * parent
ParserState pstate
string caller
Detailed Description
Definition at line 13 of file backtrace.hpp.
Constructor & Destructor Documentation
Backtrace (Backtrace * prn, ParserState pstate, string c) [inline]
Definition at line 19 of file backtrace.hpp.
Member Function Documentation
size_t depth () [inline]
Definition at line 62 of file backtrace.hpp.
References p(), and Backtrace::parent.
Referenced by Eval::operator()().
string to_string (bool warning = false) [inline]
Definition at line 25 of file backtrace.hpp.
References Backtrace::caller, Sass::File::get_cwd(), Offset::line, Backtrace::parent, ParserState::path, Backtrace::pstate, and Sass::File::resolve_relative_path().
Referenced by Sass::error(), and Sass::warn().
Field Documentation
string caller
Definition at line 17 of file backtrace.hpp.
Referenced by Backtrace::to_string().
Backtrace* parent
Definition at line 15 of file backtrace.hpp.
Referenced by Backtrace::depth(), Eval::operator()(), and Backtrace::to_string().
ParserState pstate
Definition at line 16 of file backtrace.hpp.
Referenced by Backtrace::to_string().
The documentation for this struct was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/backtrace.hpp