Emeraldion Lodge (codename Zelda): Db Class Reference
Db Class Reference
Implements an abstraction of a Database connection manager.
Static Public Member Functions
static get_adapter ($name=DB_ADAPTER)
Returns a database adapter registered under name.
static register_adapter ($adapter, $name)
Registers a database adapter under name.
static get_default_adapter ()
Returns the default database adapter.
static get_connection ($name=DB_ADAPTER)
Returns a connection for the requested adapter.
static close_connection ($conn, $name=DB_ADAPTER)
Closes a connection for the requested adapter.
static show_pool ()
Static Private Attributes
static $adapters = array()
List of registered adapters.
static $pool = array()
Connections pool.
Detailed Description
Implements an abstraction of a Database connection manager.
Definition at line 8 of file db.inc.php.
Member Function Documentation
close_connection ($conn, $name = DB_ADAPTER) static
Closes a connection for the requested adapter.
The connection is actually never closed, it is just marked as free and kept in the pool for later reuse.
Parameters
conn The connection that should be closed
name The name of the adapter
Definition at line 93 of file db.inc.php.
References $conn.
Referenced by BackendController\_batch_moderate(), ActiveRecord\ActiveRecord(), MetaController\attribute_visits(), MetaController\blocked_ips_list(), Antispam\check_spam_signature(), BlockedVisit\count_by_ip(), ActiveRecord\delete(), BackendController\diario_comment_moderate(), BackendController\diario_post_add(), ActiveRecord\find_all(), ActiveRecord\find_by_id(), ActiveRecord\find_by_query(), ActiveRecord\has_and_belongs_to_many(), KmlController\hits_by_host(), MetaController\hits_by_host_list(), SparkleController\index(), BlockedIp\is_blocked(), Login\is_logged_in(), MaintenanceController\kill_claudio(), KmlController\last_n_visits(), DiarioController\live_search(), LoginController\login(), Host\lookup_host_and_cache(), DiarioPost\next(), MetaController\outbounds_list(), SoftwareController\post_comment(), DiarioPost\previous(), MetaController\queries_list(), DiarioController\read(), MetaController\referrers_list(), ActiveRecord\save(), DiarioController\search(), BackendController\server_error_delete(), BackendController\software_artifact_list(), BackendController\software_comment_list(), BackendController\software_comment_moderate(), BackendController\software_quote_list(), BackendController\software_release_list(), SoftwareArtifact\total_downloads(), MaintenanceController\update_macupdate_ratings(), MaintenanceController\update_versiontracker_ratings(), MetaController\visits_list(), and SoftwareController\widgets_versioncheck().
get_adapter ($name = DB_ADAPTER) static
Returns a database adapter registered under name.
Parameters
name A name associated to the adapter.
Definition at line 25 of file db.inc.php.
get_connection ($name = DB_ADAPTER) static
Returns a connection for the requested adapter.
If a free connection is found in the pool it is returned to the caller, otherwise a new connection is created and added to the pool.
Parameters
name The name of the adapter
Definition at line 57 of file db.inc.php.
References $conn.
Referenced by BackendController\_batch_moderate(), SoftwareController\_init_software(), ActiveRecord\ActiveRecord(), MetaController\attribute_visits(), MetaController\blocked_ips_list(), Antispam\check_spam_signature(), BlockedVisit\count_by_ip(), ActiveRecord\delete(), BackendController\diario_comment_moderate(), BackendController\diario_post_add(), ActiveRecord\find_all(), ActiveRecord\find_by_id(), ActiveRecord\find_by_query(), ActiveRecord\has_and_belongs_to_many(), KmlController\hits_by_host(), MetaController\hits_by_host_list(), SparkleController\index(), BlockedIp\is_blocked(), Login\is_logged_in(), MaintenanceController\kill_claudio(), KmlController\last_n_visits(), DiarioController\live_search(), LoginController\login(), Host\lookup_host_and_cache(), DiarioPost\next(), MetaController\outbounds_list(), SoftwareController\post_comment(), DiarioPost\previous(), MetaController\queries_list(), DiarioController\read(), MetaController\referrers_list(), ActiveRecord\save(), DiarioController\search(), BackendController\server_error_delete(), FeedController\software(), BackendController\software_artifact_list(), BackendController\software_comment_list(), BackendController\software_comment_moderate(), BackendController\software_quote_list(), BackendController\software_release_list(), SoftwareArtifact\total_downloads(), MaintenanceController\update_macupdate_ratings(), MaintenanceController\update_versiontracker_ratings(), MetaController\visits_list(), and SoftwareController\widgets_versioncheck().
get_default_adapter () static
Returns the default database adapter.
Definition at line 45 of file db.inc.php.
register_adapter ($adapter, $name) static
Registers a database adapter under name.
Parameters
adapter An instance of a class implementing the DbAdapter interface.
name A name associated to the adapter.
Definition at line 36 of file db.inc.php.
static show_pool () static
Definition at line 109 of file db.inc.php.
Field Documentation
$adapters = array() static private
List of registered adapters.
Definition at line 13 of file db.inc.php.
$pool = array() static private
Connections pool.
Definition at line 18 of file db.inc.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/include/db.inc.php