Emeraldion Lodge (codename Zelda): Global< T > Class Template Reference
Global< T > Class Template Reference
#include <nan_persistent_12_inl.h>
Inherits PersistentBase< T >.
Data Structures
struct RValue
Public Member Functions
NAN_INLINE Global ()
template<typename S >
NAN_INLINE Global (v8::Local< S > that)
template<typename S >
NAN_INLINE Global (const v8::PersistentBase< S > &that)
NAN_INLINE void Reset ()
template<typename S >
NAN_INLINE void Reset (const v8::Local< S > &other)
template<typename S >
NAN_INLINE void Reset (const v8::PersistentBase< S > &other)
template<typename P >
NAN_INLINE void SetWeak (P *parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type)
NAN_INLINE Global ()
template<typename S >
NAN_INLINE Global (v8::Local< S > that)
template<typename S >
NAN_INLINE Global (const PersistentBase< S > &that)
NAN_INLINE Global (RValue rvalue)
NAN_INLINE ~Global ()
template<typename S >
NAN_INLINE Global & operator= (Global< S > rhs)
NAN_INLINE operator RValue ()
Global Pass ()
Private Member Functions
Global (Global &)
void operator= (Global &)
Friends
class ReturnValue
Detailed Description
template<typename T>
class Global< T >
Definition at line 95 of file nan_persistent_12_inl.h.
Constructor & Destructor Documentation
NAN_INLINE Global () [inline]
Definition at line 97 of file nan_persistent_12_inl.h.
Referenced by Global< T >::Pass().
NAN_INLINE Global (v8::Local< S > that) [inline]
Definition at line 99 of file nan_persistent_12_inl.h.
NAN_INLINE Global (const v8::PersistentBase< S > & that) [inline]
Definition at line 103 of file nan_persistent_12_inl.h.
NAN_INLINE Global () [inline]
Definition at line 192 of file nan_persistent_pre_12_inl.h.
NAN_INLINE Global (v8::Local< S > that) [inline]
Definition at line 195 of file nan_persistent_pre_12_inl.h.
References TYPE_CHECK.
NAN_INLINE Global (const PersistentBase< S > & that) [inline]
Definition at line 201 of file nan_persistent_pre_12_inl.h.
References TYPE_CHECK.
NAN_INLINE Global (RValue rvalue) [inline]
Move constructor.
Definition at line 208 of file nan_persistent_pre_12_inl.h.
References Global::RValue::object, and Global< T >::Reset().
NAN_INLINE ~Global () [inline]
Definition at line 212 of file nan_persistent_pre_12_inl.h.
References Global< T >::Reset().
Global (Global< T > &) [private]
Member Function Documentation
NAN_INLINE operator RValue () [inline]
Cast operator for moves.
Definition at line 226 of file nan_persistent_pre_12_inl.h.
void operator= (Global< T > &) [private]
NAN_INLINE Global& operator= (Global< S > rhs) [inline]
Move via assignment.
Definition at line 217 of file nan_persistent_pre_12_inl.h.
References Global< T >::Reset(), and TYPE_CHECK.
Global Pass () [inline]
Pass allows returning uniques from functions, etc.
Definition at line 230 of file nan_persistent_pre_12_inl.h.
References Global< T >::Global().
NAN_INLINE void Reset (const v8::PersistentBase< S > & other) [inline]
Definition at line 114 of file nan_persistent_12_inl.h.
References Global< T >::Reset().
NAN_INLINE void Reset (const v8::Local< S > & other) [inline]
Reimplemented from PersistentBase< T >.
Definition at line 109 of file nan_persistent_12_inl.h.
References Global< T >::Reset().
NAN_INLINE void Reset () [inline]
Reimplemented from PersistentBase< T >.
Definition at line 106 of file nan_persistent_12_inl.h.
Referenced by Global< T >::Global(), Global< T >::operator=(), Global< T >::Reset(), and Global< T >::~Global().
NAN_INLINE void SetWeak (P * parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type) [inline]
Reimplemented from PersistentBase< T >.
Definition at line 119 of file nan_persistent_12_inl.h.
Friends And Related Function Documentation
friend class ReturnValue [friend]
Reimplemented from PersistentBase< T >.
Definition at line 235 of file nan_persistent_pre_12_inl.h.
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_persistent_12_inl.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_persistent_pre_12_inl.h