Emeraldion Lodge (codename Zelda): imp Namespace Reference
imp Namespace Reference
Data Structures
class ReturnValueImp
struct ToFactoryBase
struct ValueFactoryBase
struct FactoryBase
struct MaybeFactoryBase
struct Factory< v8::Array >
struct Factory< v8::Boolean >
struct Factory< v8::BooleanObject >
struct Factory< v8::Context >
struct Factory< v8::Date >
struct Factory< v8::External >
struct Factory< v8::Function >
struct Factory< v8::FunctionTemplate >
struct Factory< v8::Number >
struct Factory< v8::NumberObject >
struct IntegerFactory
struct Factory< v8::Integer >
struct Factory< v8::Int32 >
struct Factory< v8::Uint32 >
struct Factory< v8::Object >
struct Factory< v8::ObjectTemplate >
struct Factory< v8::RegExp >
struct Factory< v8::Script >
struct Factory< v8::Signature >
struct Factory< v8::String >
struct Factory< v8::StringObject >
Typedefs
typedef v8::Local
< v8::AccessorSignature > Sig
typedef void(* NativeFunction)(const v8::FunctionCallbackInfo< v8::Value > &)
typedef void(* NativeGetter)(v8::Local< v8::String >, const v8::PropertyCallbackInfo< v8::Value > &)
typedef void(* NativeSetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::PropertyCallbackInfo< void > &)
typedef void(* NativePropertyGetter)(v8::Local< v8::String >, const v8::PropertyCallbackInfo< v8::Value > &)
typedef void(* NativePropertySetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::PropertyCallbackInfo< v8::Value > &)
typedef void(* NativePropertyEnumerator)(const v8::PropertyCallbackInfo< v8::Array > &)
typedef void(NativePropertyDeleter)(v8::Local< v8::String >, const v8::PropertyCallbackInfo< v8::Boolean > &)
typedef void(* NativePropertyQuery)(v8::Local< v8::String >, const v8::PropertyCallbackInfo< v8::Integer > &)
typedef void(* NativeIndexGetter)(uint32_t, const v8::PropertyCallbackInfo< v8::Value > &)
typedef void(* NativeIndexSetter)(uint32_t, v8::Local< v8::Value >, const v8::PropertyCallbackInfo< v8::Value > &)
typedef void(* NativeIndexEnumerator)(const v8::PropertyCallbackInfo< v8::Array > &)
typedef void(* NativeIndexDeleter)(uint32_t, const v8::PropertyCallbackInfo< v8::Boolean > &)
typedef void(* NativeIndexQuery)(uint32_t, const v8::PropertyCallbackInfo< v8::Integer > &)
Functions
static void FunctionCallbackWrapper (const v8::FunctionCallbackInfo< v8::Value > &info)
static void GetterCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Value > &info)
static void SetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< void > &info)
static void PropertyGetterCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Value > &info)
static void PropertySetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< v8::Value > &info)
static void PropertyEnumeratorCallbackWrapper (const v8::PropertyCallbackInfo< v8::Array > &info)
static void PropertyDeleterCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Boolean > &info)
static void PropertyQueryCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Integer > &info)
static void IndexGetterCallbackWrapper (uint32_t index, const v8::PropertyCallbackInfo< v8::Value > &info)
static void IndexSetterCallbackWrapper (uint32_t index, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< v8::Value > &info)
static void IndexEnumeratorCallbackWrapper (const v8::PropertyCallbackInfo< v8::Array > &info)
static void IndexDeleterCallbackWrapper (uint32_t index, const v8::PropertyCallbackInfo< v8::Boolean > &info)
static void IndexQueryCallbackWrapper (uint32_t index, const v8::PropertyCallbackInfo< v8::Integer > &info)
static v8::Handle< v8::Value > FunctionCallbackWrapper (const v8::Arguments &args)
static v8::Handle< v8::Value > GetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo &info)
static void SetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > PropertyGetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > PropertySetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo &info)
static v8::Handle< v8::Array > PropertyEnumeratorCallbackWrapper (const v8::AccessorInfo &info)
static v8::Handle< v8::Boolean > PropertyDeleterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > IndexGetterCallbackWrapper (uint32_t index, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > IndexSetterCallbackWrapper (uint32_t index, v8::Local< v8::Value > value, const v8::AccessorInfo &info)
static v8::Handle< v8::Array > IndexEnumeratorCallbackWrapper (const v8::AccessorInfo &info)
static v8::Handle< v8::Boolean > IndexDeleterCallbackWrapper (uint32_t index, const v8::AccessorInfo &info)
static v8::Handle< v8::Integer > IndexQueryCallbackWrapper (uint32_t index, const v8::AccessorInfo &info)
template<typename T >
v8::Local< T > To (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Integer > To< v8::Integer > (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Int32 > To< v8::Int32 > (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Uint32 > To< v8::Uint32 > (v8::Local< v8::Integer > i)
static bool contains_non_ascii_slow (const char *buf, size_t len)
static bool contains_non_ascii (const char *src, size_t len)
static void force_ascii_slow (const char *src, char *dst, size_t len)
static void force_ascii (const char *src, char *dst, size_t len)
static size_t base64_encode (const char *src, size_t slen, char *dst, size_t dlen)
static size_t hex_encode (const char *src, size_t slen, char *dst, size_t dlen)
static Local< Value > Encode (const char *buf, size_t buflen, enum Encoding encoding)
Variables
static const int kDataIndex = 0
static const int kFunctionIndex = 1
static const int kFunctionFieldCount = 2
static const int kGetterIndex = 1
static const int kSetterIndex = 2
static const int kAccessorFieldCount = 3
static const int kPropertyGetterIndex = 1
static const int kPropertySetterIndex = 2
static const int kPropertyEnumeratorIndex = 3
static const int kPropertyDeleterIndex = 4
static const int kPropertyQueryIndex = 5
static const int kPropertyFieldCount = 6
static const int kIndexPropertyGetterIndex = 1
static const int kIndexPropertySetterIndex = 2
static const int kIndexPropertyEnumeratorIndex = 3
static const int kIndexPropertyDeleterIndex = 4
static const int kIndexPropertyQueryIndex = 5
static const int kIndexPropertyFieldCount = 6
Typedef Documentation
typedef v8::Handle< v8::Value >(* NativeFunction)(const v8::Arguments &)
Definition at line 177 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Value >(* NativeGetter)(v8::Local< v8::String >, const v8::AccessorInfo &)
Definition at line 229 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Boolean >(* NativeIndexDeleter)(uint32_t, const v8::AccessorInfo &)
Definition at line 493 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Array >(* NativeIndexEnumerator)(const v8::AccessorInfo &)
Definition at line 477 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Value >(* NativeIndexGetter)(uint32_t, const v8::AccessorInfo &)
Definition at line 441 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Integer >(* NativeIndexQuery)(uint32_t, const v8::AccessorInfo &)
Definition at line 509 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Value >(* NativeIndexSetter)(uint32_t, v8::Local< v8::Value >, const v8::AccessorInfo &)
Definition at line 458 of file nan_callbacks_12_inl.h.
typedef void(NativePropertyDeleter)(v8::Local< v8::String >, const v8::PropertyCallbackInfo< v8::Boolean > &)
Definition at line 407 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Array >(* NativePropertyEnumerator)(const v8::AccessorInfo &)
Definition at line 390 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Value >(* NativePropertyGetter)(v8::Local< v8::String >, const v8::AccessorInfo &)
Definition at line 354 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Integer >(* NativePropertyQuery)(v8::Local< v8::String >, const v8::AccessorInfo &)
Definition at line 424 of file nan_callbacks_12_inl.h.
typedef v8::Handle< v8::Value >(* NativePropertySetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::AccessorInfo &)
Definition at line 371 of file nan_callbacks_12_inl.h.
typedef void(* NativeSetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::AccessorInfo &)
Definition at line 245 of file nan_callbacks_12_inl.h.
typedef v8::Local<v8::AccessorSignature> Sig
Definition at line 55 of file nan_callbacks.h.
Function Documentation
static size_t imp::base64_encode (const char * src, size_t slen, char * dst, size_t dlen) [static]
Definition at line 142 of file nan_string_bytes.h.
References a(), and base64_encoded_size.
Referenced by Encode(), and Base64::encode().
static bool imp::contains_non_ascii (const char * src, size_t len) [static]
Definition at line 51 of file nan_string_bytes.h.
References contains_non_ascii_slow(), and l().
Referenced by Encode().
static bool imp::contains_non_ascii_slow (const char * buf, size_t len) [static]
Definition at line 43 of file nan_string_bytes.h.
Referenced by contains_non_ascii().
static Local<Value> imp::Encode (const char * buf, size_t buflen, enum Encoding encoding) [static]
Definition at line 224 of file nan_string_bytes.h.
References Nan::ASCII, Nan::BASE64, base64_encode(), base64_encoded_size, Nan::BINARY, Nan::BUFFER, contains_non_ascii(), Nan::CopyBuffer(), force_ascii(), Nan::HEX, hex_encode(), Nan::imp::kMaxLength, New(), Nan::UCS2, and Nan::UTF8.
static void imp::force_ascii (const char * src, char * dst, size_t len) [static]
Definition at line 97 of file nan_string_bytes.h.
References force_ascii_slow(), and l().
Referenced by Encode().
static void imp::force_ascii_slow (const char * src, char * dst, size_t len) [static]
Definition at line 90 of file nan_string_bytes.h.
Referenced by force_ascii().
static v8::Handle<v8::Value> imp::FunctionCallbackWrapper (const v8::Arguments & args) [static]
Definition at line 284 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kFunctionIndex.
static void imp::FunctionCallbackWrapper (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 167 of file nan_callbacks_12_inl.h.
References kDataIndex, and kFunctionIndex.
Referenced by Factory< v8::FunctionTemplate >::New(), and Factory< v8::Function >::New().
static v8::Handle<v8::Value> imp::GetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo & info) [static]
Definition at line 298 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kGetterIndex.
static void imp::GetterCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Value > & info) [static]
Definition at line 216 of file nan_callbacks_12_inl.h.
References kDataIndex, and kGetterIndex.
static size_t imp::hex_encode (const char * src, size_t slen, char * dst, size_t dlen) [static]
Definition at line 206 of file nan_string_bytes.h.
References Sass::Prelexer::hex().
Referenced by Encode().
static v8::Handle<v8::Boolean> imp::IndexDeleterCallbackWrapper (uint32_t index, const v8::AccessorInfo & info) [static]
Definition at line 472 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kIndexPropertyDeleterIndex.
static void imp::IndexDeleterCallbackWrapper (uint32_t index, const v8::PropertyCallbackInfo< v8::Boolean > & info) [static]
Definition at line 480 of file nan_callbacks_12_inl.h.
References kDataIndex, and kIndexPropertyDeleterIndex.
static v8::Handle<v8::Array> imp::IndexEnumeratorCallbackWrapper (const v8::AccessorInfo & info) [static]
Definition at line 455 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kIndexPropertyEnumeratorIndex.
static void imp::IndexEnumeratorCallbackWrapper (const v8::PropertyCallbackInfo< v8::Array > & info) [static]
Definition at line 464 of file nan_callbacks_12_inl.h.
References kDataIndex, and kIndexPropertyEnumeratorIndex.
static v8::Handle<v8::Value> imp::IndexGetterCallbackWrapper (uint32_t index, const v8::AccessorInfo & info) [static]
Definition at line 419 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kIndexPropertyGetterIndex.
static void imp::IndexGetterCallbackWrapper (uint32_t index, const v8::PropertyCallbackInfo< v8::Value > & info) [static]
Definition at line 428 of file nan_callbacks_12_inl.h.
References kDataIndex, and kIndexPropertyGetterIndex.
static v8::Handle<v8::Integer> imp::IndexQueryCallbackWrapper (uint32_t index, const v8::AccessorInfo & info) [static]
Definition at line 489 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kIndexPropertyQueryIndex.
static void imp::IndexQueryCallbackWrapper (uint32_t index, const v8::PropertyCallbackInfo< v8::Integer > & info) [static]
Definition at line 496 of file nan_callbacks_12_inl.h.
References kDataIndex, and kIndexPropertyQueryIndex.
static v8::Handle<v8::Value> imp::IndexSetterCallbackWrapper (uint32_t index, v8::Local< v8::Value > value, const v8::AccessorInfo & info) [static]
Definition at line 436 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kIndexPropertySetterIndex.
static void imp::IndexSetterCallbackWrapper (uint32_t index, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< v8::Value > & info) [static]
Definition at line 444 of file nan_callbacks_12_inl.h.
References kDataIndex, and kIndexPropertySetterIndex.
static v8::Handle<v8::Boolean> imp::PropertyDeleterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo & info) [static]
Definition at line 384 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kPropertyDeleterIndex.
static void imp::PropertyDeleterCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Boolean > & info) [static]
Definition at line 393 of file nan_callbacks_12_inl.h.
References kDataIndex, and kPropertyDeleterIndex.
static v8::Handle<v8::Array> imp::PropertyEnumeratorCallbackWrapper (const v8::AccessorInfo & info) [static]
Definition at line 367 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kPropertyEnumeratorIndex.
static void imp::PropertyEnumeratorCallbackWrapper (const v8::PropertyCallbackInfo< v8::Array > & info) [static]
Definition at line 377 of file nan_callbacks_12_inl.h.
References kDataIndex, and kPropertyEnumeratorIndex.
static v8::Handle<v8::Value> imp::PropertyGetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo & info) [static]
Definition at line 331 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kPropertyGetterIndex.
static void imp::PropertyGetterCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Value > & info) [static]
Definition at line 340 of file nan_callbacks_12_inl.h.
References kDataIndex, and kPropertyGetterIndex.
static void imp::PropertyQueryCallbackWrapper (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Integer > & info) [static]
Definition at line 410 of file nan_callbacks_12_inl.h.
References kDataIndex, and kPropertyQueryIndex.
static v8::Handle<v8::Value> imp::PropertySetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo & info) [static]
Definition at line 348 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kPropertySetterIndex.
static void imp::PropertySetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< v8::Value > & info) [static]
Definition at line 357 of file nan_callbacks_12_inl.h.
References kDataIndex, and kPropertySetterIndex.
static void imp::SetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo & info) [static]
Definition at line 314 of file nan_callbacks_pre_12_inl.h.
References kDataIndex, and kSetterIndex.
static void imp::SetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< void > & info) [static]
Definition at line 232 of file nan_callbacks_12_inl.h.
References kDataIndex, and kSetterIndex.
v8::Local<T> imp::To (v8::Local< v8::Integer > i) [inline]
v8::Local<v8::Int32> imp::To< v8::Int32 > (v8::Local< v8::Integer > i) [inline]
v8::Local<v8::Integer> imp::To< v8::Integer > (v8::Local< v8::Integer > i) [inline]
v8::Local<v8::Uint32> imp::To< v8::Uint32 > (v8::Local< v8::Integer > i) [inline]
Variable Documentation
const int kAccessorFieldCount = 3 [static]
Definition at line 64 of file nan_callbacks.h.
const int kDataIndex = 0 [static]
Definition at line 57 of file nan_callbacks.h.
Referenced by FunctionCallbackWrapper(), GetterCallbackWrapper(), IndexDeleterCallbackWrapper(), IndexEnumeratorCallbackWrapper(), IndexGetterCallbackWrapper(), IndexQueryCallbackWrapper(), IndexSetterCallbackWrapper(), Factory< v8::FunctionTemplate >::New(), Factory< v8::Function >::New(), PropertyDeleterCallbackWrapper(), PropertyEnumeratorCallbackWrapper(), PropertyGetterCallbackWrapper(), PropertyQueryCallbackWrapper(), PropertySetterCallbackWrapper(), and SetterCallbackWrapper().
const int kFunctionFieldCount = 2 [static]
Definition at line 60 of file nan_callbacks.h.
Referenced by Factory< v8::FunctionTemplate >::New(), and Factory< v8::Function >::New().
const int kFunctionIndex = 1 [static]
Definition at line 59 of file nan_callbacks.h.
Referenced by FunctionCallbackWrapper(), Factory< v8::FunctionTemplate >::New(), and Factory< v8::Function >::New().
const int kGetterIndex = 1 [static]
Definition at line 62 of file nan_callbacks.h.
Referenced by GetterCallbackWrapper().
const int kIndexPropertyDeleterIndex = 4 [static]
Definition at line 76 of file nan_callbacks.h.
Referenced by IndexDeleterCallbackWrapper().
const int kIndexPropertyEnumeratorIndex = 3 [static]
Definition at line 75 of file nan_callbacks.h.
Referenced by IndexEnumeratorCallbackWrapper().
const int kIndexPropertyFieldCount = 6 [static]
Definition at line 78 of file nan_callbacks.h.
const int kIndexPropertyGetterIndex = 1 [static]
Definition at line 73 of file nan_callbacks.h.
Referenced by IndexGetterCallbackWrapper().
const int kIndexPropertyQueryIndex = 5 [static]
Definition at line 77 of file nan_callbacks.h.
Referenced by IndexQueryCallbackWrapper().
const int kIndexPropertySetterIndex = 2 [static]
Definition at line 74 of file nan_callbacks.h.
Referenced by IndexSetterCallbackWrapper().
const int kPropertyDeleterIndex = 4 [static]
Definition at line 69 of file nan_callbacks.h.
Referenced by PropertyDeleterCallbackWrapper().
const int kPropertyEnumeratorIndex = 3 [static]
Definition at line 68 of file nan_callbacks.h.
Referenced by PropertyEnumeratorCallbackWrapper().
const int kPropertyFieldCount = 6 [static]
Definition at line 71 of file nan_callbacks.h.
const int kPropertyGetterIndex = 1 [static]
Definition at line 66 of file nan_callbacks.h.
Referenced by PropertyGetterCallbackWrapper().
const int kPropertyQueryIndex = 5 [static]
Definition at line 70 of file nan_callbacks.h.
Referenced by PropertyQueryCallbackWrapper().
const int kPropertySetterIndex = 2 [static]
Definition at line 67 of file nan_callbacks.h.
Referenced by PropertySetterCallbackWrapper().
const int kSetterIndex = 2 [static]
Definition at line 63 of file nan_callbacks.h.
Referenced by SetterCallbackWrapper().