Emeraldion Lodge (codename Zelda): Extend Class Reference
Extend Class Reference
#include <extend.hpp>
Inherits Operation_CRTP< void, Extend >.
Public Member Functions
Extend (Context &, ExtensionSubsetMap &)
virtual ~Extend ()
void operator() (Block *)
void operator() (Ruleset *)
void operator() (Feature_Block *)
void operator() (Media_Block *)
void operator() (At_Rule *)
template<typename U >
void fallback (U x)
Private Member Functions
void fallback_impl (AST_Node *n)
Private Attributes
Context & ctx
ExtensionSubsetMap & subset_map
Detailed Description
Definition at line 20 of file extend.hpp.
Constructor & Destructor Documentation
Extend (Context & ctx, ExtensionSubsetMap & ssm)
Definition at line 1970 of file extend.cpp.
virtual ~Extend () [inline, virtual]
Definition at line 29 of file extend.hpp.
Member Function Documentation
void fallback (U x) [inline]
Reimplemented from Operation_CRTP< void, Extend >.
Definition at line 40 of file extend.hpp.
References Extend::fallback_impl().
void fallback_impl (AST_Node * n) [inline, private]
Definition at line 25 of file extend.hpp.
Referenced by Extend::fallback().
void operator() (At_Rule * a) [virtual]
Reimplemented from Operation_CRTP< void, Extend >.
Definition at line 2006 of file extend.cpp.
References Statement::block().
void operator() (Media_Block * pMediaBlock) [virtual]
Reimplemented from Operation_CRTP< void, Extend >.
Definition at line 1997 of file extend.cpp.
References Statement::block(), Sass::extendObjectWithSelectorAndBlock(), and Extend::subset_map.
void operator() (Feature_Block * pFeatureBlock) [virtual]
Reimplemented from Operation_CRTP< void, Extend >.
Definition at line 1988 of file extend.cpp.
References Statement::block(), Sass::extendObjectWithSelectorAndBlock(), and Extend::subset_map.
void operator() (Ruleset * pRuleset) [virtual]
Reimplemented from Operation_CRTP< void, Extend >.
Definition at line 1981 of file extend.cpp.
References Statement::block(), Sass::extendObjectWithSelectorAndBlock(), and Extend::subset_map.
void operator() (Block * b) [virtual]
Reimplemented from Operation_CRTP< void, Extend >.
Definition at line 1974 of file extend.cpp.
References Vectorized< T >::length().
Field Documentation
Context& ctx [private]
Definition at line 22 of file extend.hpp.
ExtensionSubsetMap& subset_map [private]
Definition at line 23 of file extend.hpp.
Referenced by Extend::operator()().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/extend.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/extend.cpp