Emeraldion Lodge (codename Zelda): Geoip Class Reference
Geoip Class Reference
Helper object for geolocation of IP addresses.
Static Public Member Functions
static by_ip_addr ($ip_addr, $params=NULL)
Creates a Geoip object for the given IP address.
Static Public Member Functions inherited from Host
static by_ip_addr ($ip_addr, $params=NULL)
Creates a Host object for the given IP address.
Data Fields
$latitude
The value of the latitude coordinate.
$longitude
The value of the longitude coordinate.
$altitude = 0
The value of the altitude on the level of sea.
$country
The name of the country of the IP address.
$country_code
The country code of the IP address.
$city
The name of the city of the IP address.
$guessed
Tells whether the geographical location has been inferred or is a certain value.
Data Fields inherited from Host
$ip_addr
The IP address of the host.
$real_ip_addr
The real IP address of the host.
$hostname
The name of the host.
Detailed Description
Helper object for geolocation of IP addresses.
Geolocation information is obtained by querying the hostip.info web service.
Definition at line 12 of file geoip.php.
Member Function Documentation
by_ip_addr ($ip_addr, $params = NULL) static
Creates a Geoip object for the given IP address.
Parameters
ip_addr The IP address.
params Parameters to initialize the IP address.
Definition at line 63 of file geoip.php.
References Host\$ip_addr, and GEOIP_LOOKUP.
Referenced by KmlController\hits_by_host(), KmlController\index(), and KmlController\last_n_visits().
Field Documentation
$altitude = 0
The value of the altitude on the level of sea.
altitude
Definition at line 30 of file geoip.php.
$city
The name of the city of the IP address.
city
Definition at line 48 of file geoip.php.
$country
The name of the country of the IP address.
country
Definition at line 36 of file geoip.php.
$country_code
The country code of the IP address.
country_code
Definition at line 42 of file geoip.php.
$guessed
Tells whether the geographical location has been inferred or is a certain value.
guessed
Returns
TRUE if the geographical location has been guessed, FALSE otherwise.
Definition at line 55 of file geoip.php.
$latitude
The value of the latitude coordinate.
latitude
Definition at line 18 of file geoip.php.
$longitude
The value of the longitude coordinate.
longitude
Definition at line 24 of file geoip.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/geoip.php