Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/posix/getopt.c File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/posix/getopt.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <stdarg.h>
#include <stdio.h>
#include <windows.h>
Defines
#define REPLACE_GETOPT
#define optreset __mingw_optreset
#define PRINT_ERROR ((opterr) && (*options != ':'))
#define FLAG_PERMUTE 0x01
#define FLAG_ALLARGS 0x02
#define FLAG_LONGONLY 0x04
#define BADCH (int)'?'
#define BADARG ((*options == ':') ? (int)':' : (int)'?')
#define INORDER (int)1
#define __progname __argv[0]
#define EMSG ""
#define IDENTICAL_INTERPRETATION(_x, _y)
Functions
static int getopt_internal (int, char *const *, const char *, const struct option *, int *, int)
static int parse_long_options (char *const *, const char *, const struct option *, int *, int)
static int gcd (int, int)
static void permute_args (int, int, int, char *const *)
static void _vwarnx (const char *fmt, va_list ap)
static void warnx (const char *fmt,...)
int getopt (int nargc, char *const *nargv, const char *options)
int getopt_long (int nargc, char *const *nargv, const char *options, const struct option *long_options, int *idx)
int getopt_long_only (int nargc, char *const *nargv, const char *options, const struct option *long_options, int *idx)
Variables
int opterr = 1
int optind = 1
int optopt = '?'
int optreset
char * optarg
static char * place = EMSG
static int nonopt_start = -1
static int nonopt_end = -1
static const char recargchar [] = "option requires an argument -- %c"
static const char recargstring [] = "option requires an argument -- %s"
static const char ambig [] = "ambiguous option -- %.*s"
static const char noarg [] = "option doesn't take an argument -- %.*s"
static const char illoptchar [] = "unknown option -- %c"
static const char illoptstring [] = "unknown option -- %s"
Define Documentation
#define __progname __argv[0]
Definition at line 84 of file getopt.c.
Referenced by _vwarnx().
#define BADARG ((*options == ':') ? (int)':' : (int)'?')
Definition at line 80 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
#define BADCH (int)'?'
Definition at line 79 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
#define EMSG ""
Definition at line 92 of file getopt.c.
Referenced by getopt_internal().
#define FLAG_ALLARGS 0x02
Definition at line 75 of file getopt.c.
Referenced by getopt_internal().
#define FLAG_LONGONLY 0x04
Definition at line 76 of file getopt.c.
Referenced by getopt_internal(), and getopt_long_only().
#define FLAG_PERMUTE 0x01
Definition at line 74 of file getopt.c.
Referenced by getopt_internal(), getopt_long(), and getopt_long_only().
#define IDENTICAL_INTERPRETATION (_x, _y)
Value:
(long_options[(_x)].has_arg == long_options[(_y)].has_arg &&    \
         long_options[(_x)].flag == long_options[(_y)].flag &&          \
         long_options[(_x)].val == long_options[(_y)].val)
Referenced by parse_long_options().
#define INORDER (int)1
Definition at line 81 of file getopt.c.
Referenced by getopt_internal().
#define optreset __mingw_optreset
Definition at line 67 of file getopt.c.
Referenced by getopt_internal().
#define PRINT_ERROR ((opterr) && (*options != ':'))
Definition at line 72 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
#define REPLACE_GETOPT
Definition at line 60 of file getopt.c.
Function Documentation
static void _vwarnx (const char * fmt, va_list ap) [static]
Definition at line 117 of file getopt.c.
References __progname.
Referenced by warnx().
static int gcd (int a, int b) [static]
Definition at line 138 of file getopt.c.
Referenced by permute_args().
int getopt (int nargc, char *const * nargv, const char * options)
Definition at line 523 of file getopt.c.
References getopt_internal().
static int getopt_internal (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx, int flags) [static]
Definition at line 323 of file getopt.c.
References BADARG, BADCH, EMSG, FLAG_ALLARGS, FLAG_LONGONLY, FLAG_PERMUTE, illoptchar, INORDER, nonopt_end, nonopt_start, optarg, optind, optopt, optreset, parse_long_options(), permute_args(), place, PRINT_ERROR, recargchar, and warnx().
Referenced by getopt(), getopt_long(), and getopt_long_only().
int getopt_long (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx)
Definition at line 543 of file getopt.c.
References FLAG_PERMUTE, and getopt_internal().
int getopt_long_only (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx)
Definition at line 556 of file getopt.c.
References FLAG_LONGONLY, FLAG_PERMUTE, and getopt_internal().
static int parse_long_options (char *const * nargv, const char * options, const struct option * long_options, int * idx, int short_too) [static]
Definition at line 195 of file getopt.c.
References ambig, BADARG, BADCH, option::flag, IDENTICAL_INTERPRETATION, illoptstring, Sass::Prelexer::name(), option::name, no_argument, noarg, optarg, optind, optional_argument, optopt, place, PRINT_ERROR, recargstring, required_argument, option::val, and warnx().
Referenced by getopt_internal().
static void permute_args (int panonopt_start, int panonopt_end, int opt_end, char *const * nargv) [static]
Definition at line 158 of file getopt.c.
References gcd().
Referenced by getopt_internal().
static void warnx (const char * fmt, ...) [static]
Definition at line 126 of file getopt.c.
References _vwarnx().
Referenced by getopt_internal(), and parse_long_options().
Variable Documentation
const char ambig[] = "ambiguous option -- %.*s" [static]
Definition at line 111 of file getopt.c.
Referenced by parse_long_options().
const char illoptchar[] = "unknown option -- %c" [static]
Definition at line 113 of file getopt.c.
Referenced by getopt_internal().
const char illoptstring[] = "unknown option -- %s" [static]
Definition at line 114 of file getopt.c.
Referenced by parse_long_options().
const char noarg[] = "option doesn't take an argument -- %.*s" [static]
Definition at line 112 of file getopt.c.
Referenced by parse_long_options().
int nonopt_end = -1 [static]
Definition at line 106 of file getopt.c.
Referenced by getopt_internal().
int nonopt_start = -1 [static]
Definition at line 105 of file getopt.c.
Referenced by getopt_internal().
char* optarg
Definition at line 69 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
int opterr = 1
Definition at line 63 of file getopt.c.
int optind = 1
DISCLAIMER This file has no copyright assigned and is placed in the Public Domain. This file is a part of the w64 mingw-runtime package.
The w64 mingw-runtime package and its code is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY. ALL WARRANTIES, EXPRESSED OR IMPLIED ARE HEREBY DISCLAIMED. This includes but is not limited to warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Definition at line 64 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
int optopt = '?'
Definition at line 65 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
int optreset
Definition at line 68 of file getopt.c.
char* place = EMSG [static]
Definition at line 102 of file getopt.c.
Referenced by getopt_internal(), and parse_long_options().
const char recargchar[] = "option requires an argument -- %c" [static]
Definition at line 109 of file getopt.c.
Referenced by getopt_internal().
const char recargstring[] = "option requires an argument -- %s" [static]
Definition at line 110 of file getopt.c.
Referenced by parse_long_options().