Emeraldion Lodge (codename Zelda): Sass Namespace Reference
Sass Namespace Reference
Namespaces
namespace Constants
namespace File
namespace Functions
namespace Prelexer
namespace UTF_8
namespace Util
Data Structures
class AST_Node
class Expression
class Vectorized
class Hashed
class Statement
class Block
class Has_Block
class Ruleset
class Propset
class Bubble
class Media_Block
class Feature_Block
class At_Rule
class Keyframe_Rule
class Declaration
class Assignment
class Import
class Import_Stub
class Warning
class Error
class Debug
class Comment
class If
class For
class Each
class While
class Return
class Extension
class Definition
class Mixin_Call
class Content
class List
class Map
class Binary_Expression
class Unary_Expression
class Argument
class Arguments
class Function_Call
class Function_Call_Schema
class Variable
class Textual
class Number
class Color
class Boolean
class String
class String_Schema
class String_Constant
class String_Quoted
class Media_Query
class Media_Query_Expression
class Feature_Query
class Feature_Query_Condition
class At_Root_Expression
class At_Root_Block
class Null
class Thunk
class Parameter
class Parameters
class Parent_Selector
class Selector
class Selector_Schema
class Simple_Selector
class Selector_Reference
class Selector_Placeholder
class Type_Selector
class Selector_Qualifier
class Attribute_Selector
class Pseudo_Selector
class Wrapped_Selector
struct Complex_Selector_Pointer_Compare
class Compound_Selector
class Complex_Selector
class Selector_List
class AST_Factory
struct Backtrace
class Base64VLQ
struct Sass_Queued
class Context
class Contextualize
class Contextualize_Eval
class Cssize
class Emitter
class Environment
struct Sass_Error
class Eval
class Expand
class LcsCollectionComparator
class ParentSuperselectorChunker
class SubweaveEmptyChunker
class GroupByToAFunctor
class Extend
class Inspect
class Listize
struct Mapping
class Memory_Manager
class Node
class Operation
class Operation_CRTP
class Output
class Parser
class Plugins
class Offset
class Position
class Token
class ParserState
class Remove_Placeholders
class DefaultLcsComparator
class SourceMap
class OutputBuffer
struct triple
class Subset_Map
class To_C
class To_String
class incompatibleUnits
Typedefs
typedef Environment< AST_Node * > Env
typedef const char * Signature
typedef Expression *(* Native_Function)(Env &, Env &, Context &, Signature, ParserState, Backtrace *)
typedef set< Complex_Selector
*, Complex_Selector_Pointer_Compare > SourcesSet
typedef deque< Complex_Selector * > ComplexSelectorDeque
typedef double(* bop)(double, double)
typedef pair< Complex_Selector
*, Compound_Selector * > ExtensionPair
typedef vector< ExtensionPair > SubsetMapEntries
typedef Subset_Map< string,
pair< Complex_Selector
*, Compound_Selector * > > ExtensionSubsetMap
typedef deque< Node > NodeDeque
typedef shared_ptr< NodeDeque > NodeDequePtr
typedef vector< vector< int > > LCSTable
Enumerations
enum Output_Style {
NESTED, EXPANDED, COMPACT, COMPRESSED,
FORMATTED
}
enum SassUnitType {
SIZE = 0x000, ANGLE = 0x100, TIME = 0x200, FREQUENCY = 0x300,
RESOLUTION = 0x400, INCOMMENSURABLE = 0x500
}
enum SassUnit {
IN = SIZE, CM, PC, MM,
PT, PX, DEG = ANGLE, GRAD,
RAD, TURN, SEC = TIME, MSEC,
HERTZ = FREQUENCY, KHERTZ, DPI = RESOLUTION, DPCM,
DPPX, UNKNOWN = INCOMMENSURABLE
}
Functions
static Null sass_null (Sass::Null(ParserState("null")))
bool is_pseudo_class_element (const string &name)
template<typename SelectorType >
bool selectors_equal (const SelectorType &one, const SelectorType &two, bool simpleSelectorOrderDependent)
void bind (string callee, Parameters *ps, Arguments *as, Context &ctx, Env *env, Eval *eval)
bool sort_importers (const Sass_Importer_Entry &i, const Sass_Importer_Entry &j)
void register_function (Context &, Signature sig, Native_Function f, Env *env)
void register_function (Context &, Signature sig, Native_Function f, size_t arity, Env *env)
void register_overload_stub (Context &, string name, Env *env)
void register_built_in_functions (Context &, Env *env)
void register_c_functions (Context &, Env *env, Sass_Function_List)
void register_c_function (Context &, Env *env, Sass_Function_Entry)
void warn (string msg, ParserState pstate)
void warn (string msg, ParserState pstate, Backtrace *bt)
void error (string msg, ParserState pstate)
void error (string msg, ParserState pstate, Backtrace *bt)
double add (double x, double y)
double sub (double x, double y)
double mul (double x, double y)
double div (double x, double y)
bool eq (Expression *, Expression *, Context &, Eval *)
bool lt (Expression *, Expression *, Context &)
Expression * op_numbers (Context &, Binary_Expression *, Expression *, Expression *)
Expression * op_number_color (Context &, Binary_Expression::Type, Expression *, Expression *)
Expression * op_color_number (Context &, Binary_Expression::Type, Expression *, Expression *)
Expression * op_colors (Context &, Binary_Expression::Type, Expression *, Expression *)
Expression * op_strings (Context &, Binary_Expression::Type, Expression *, Expression *)
char is_quoted (string str)
bool eq (Expression *lhs, Expression *rhs, Context &ctx)
Expression * cval_to_astnode (Sass_Value *v, Context &ctx, Backtrace *backtrace, ParserState pstate)
static bool parentSuperselector (Complex_Selector *pOne, Complex_Selector *pTwo, Context &ctx)
void nodeToComplexSelectorDeque (const Node &node, ComplexSelectorDeque &out, Context &ctx)
Node complexSelectorDequeToNode (const ComplexSelectorDeque &deque, Context &ctx)
void lcs_backtrace (const LCSTable &c, ComplexSelectorDeque &x, ComplexSelectorDeque &y, int i, int j, const LcsCollectionComparator &comparator, ComplexSelectorDeque &out)
void lcs_table (const ComplexSelectorDeque &x, const ComplexSelectorDeque &y, const LcsCollectionComparator &comparator, LCSTable &out)
void lcs (ComplexSelectorDeque &x, ComplexSelectorDeque &y, const LcsCollectionComparator &comparator, Context &ctx, ComplexSelectorDeque &out)
static Node trim (Node &seqses, Context &ctx)
static bool parentSuperselector (const Node &one, const Node &two, Context &ctx)
template<typename ChunkerType >
static Node chunks (Node &seq1, Node &seq2, const ChunkerType &chunker)
static Node groupSelectors (Node &seq, Context &ctx)
static void getAndRemoveInitialOps (Node &seq, Node &ops)
static void getAndRemoveFinalOps (Node &seq, Node &ops)
static Node mergeInitialOps (Node &seq1, Node &seq2, Context &ctx)
static Node mergeFinalOps (Node &seq1, Node &seq2, Context &ctx, Node &res)
static Node subweave (Node &one, Node &two, Context &ctx)
static Node weave (Node &path, Context &ctx)
static Node extendComplexSelector (Complex_Selector *pComplexSelector, Context &ctx, ExtensionSubsetMap &subsetMap, set< Compound_Selector > seen)
static Node extendCompoundSelector (Compound_Selector *pSelector, Context &ctx, ExtensionSubsetMap &subsetMap, set< Compound_Selector > seen)
static bool complexSelectorHasExtension (Complex_Selector *pComplexSelector, Context &ctx, ExtensionSubsetMap &subsetMap)
static Selector_List * extendSelectorList (Selector_List *pSelectorList, Context &ctx, ExtensionSubsetMap &subsetMap, bool &extendedSomething)
bool shouldExtendBlock (Block *b)
template<typename ObjectType >
static void extendObjectWithSelectorAndBlock (ObjectType *pObject, Context &ctx, ExtensionSubsetMap &subsetMap)
Definition * make_native_function (Signature sig, Native_Function func, Context &ctx)
Definition * make_c_function (Sass_Function_Entry c_func, Context &ctx)
template<size_t range>
static double cap_channel (double c)
bool nodesEqual (const Node &lhs, const Node &rhs, bool simpleSelectorOrderDependent)
Node complexSelectorToNode (Complex_Selector *pToConvert, Context &ctx)
Complex_Selector * nodeToComplexSelector (const Node &toConvert, Context &ctx)
bool ends_with (std::string const &value, std::string const &ending)
size_t check_bom_chars (const char *src, const char *end, const unsigned char *bom, size_t len)
template<typename T >
vector< vector< T > > paths (vector< vector< T > > strata, size_t from_end=0)
bool compatibility (const char *their_version)
static string closer (const converter &converter)
static string opener (const converter &converter)
static bool isPseudoSelector (string &sel)
static bool hasCharData (string &sass)
static size_t findCommentOpener (string &sass)
static string removeMultilineComment (string &sass)
string rtrim (const string &sass)
string flush (string &sass, converter &converter)
string process (string &sass, converter &converter)
static std::istream & safeGetline (std::istream &is, std::string &t)
char * sass2scss (const string sass, const int options)
Node paths (const Node &arrs, Context &ctx)
Node flatten (const Node &arr, Context &ctx, int n=-1)
template<typename ComparatorType >
Node lcs_backtrace (const LCSTable &c, const Node &x, const Node &y, int i, int j, const ComparatorType &comparator)
template<typename ComparatorType >
void lcs_table (const Node &x, const Node &y, const ComparatorType &comparator, LCSTable &out)
template<typename ComparatorType >
Node lcs (Node &x, Node &y, const ComparatorType &comparator, Context &ctx)
template<typename EnumType , typename KeyType , typename KeyFunctorType >
void group_by_to_a (vector< EnumType > &enumeration, KeyFunctorType &keyFunc, vector< pair< KeyType, vector< EnumType > > > &arr)
template<typename F , typename S , typename T >
triple< F, S, T > make_triple (const F &f, const S &s, const T &t)
static Complex_Selector * createComplexSelector (string src)
void roundtripTest (const char *toTest)
int main ()
SassUnitType get_unit_type (SassUnit unit)
SassUnit string_to_unit (const string &s)
const char * unit_to_string (SassUnit unit)
double conversion_factor (const string &s1, const string &s2)
char * sass_strdup (const char *str)
double sass_atof (const char *str)
string string_eval_escapes (const string &s)
string string_escape (const string &str)
string string_unescape (const string &str)
string read_css_string (const string &str)
string evacuate_quotes (const string &str)
string evacuate_escapes (const string &str)
string string_to_output (const string &str)
string comment_to_string (const string &text)
string normalize_wspace (const string &str)
char detect_best_quotemark (const char *s, char qm)
string unquote (const string &s, char *qd)
string quote (const string &s, char q, bool keep_linefeed_whitespace)
bool is_hex_doublet (double n)
bool is_color_doublet (double r, double g, double b)
bool peek_linefeed (const char *start)
Variables
const char * color_names []
const double color_values []
vector< pair< bool, Block * >
> Cssize::slice_by_bubble(Statement
*b){vector< pair< bool, Block * >
> results;for(size_t i=0, L=b->
block()->length();i< L;++i){Statement
*value=(*b->block()) pstate [i];bool key=value->statement_type()==Statement::BUBBLE;if(!results.empty()&&results.back().first==key){Block *wrapper_block=results.back().second;*wrapper_block<< value;}else{Block *wrapper_block=new(ctx.mem) Block(value->())
*wrapper_block<< value;results.push_back(make_pair(key,
wrapper_block));}}return
results;}Statement
*Cssize::shallow_copy(Statement
*s){switch(s- statement_type)())
bop ops [Binary_Expression::NUM_OPS]
Context ctx = Context::Data()
To_String to_string
const char *const ROUNDTRIP_TESTS []
const double size_conversion_factors [6][6]
const double angle_conversion_factors [4][4]
const double time_conversion_factors [2][2]
const double frequency_conversion_factors [2][2]
const double resolution_conversion_factors [3][3]
const double PI = acos(-1)
Typedef Documentation
typedef double(* bop)(double, double)
Definition at line 28 of file eval.cpp.
typedef deque<Complex_Selector*> ComplexSelectorDeque
Definition at line 2075 of file ast.hpp.
typedef Environment< AST_Node * > Env
Definition at line 636 of file ast.hpp.
typedef pair<Complex_Selector*, Compound_Selector*> ExtensionPair
Definition at line 63 of file extend.cpp.
typedef Subset_Map<string, pair<Complex_Selector*, Compound_Selector*> > ExtensionSubsetMap
Definition at line 16 of file extend.hpp.
typedef vector<vector<int> > LCSTable
Definition at line 57 of file sass_util.hpp.
typedef Expression *(* Native_Function)(Env &, Env &, Context &, Signature, ParserState, Backtrace *)
Definition at line 639 of file ast.hpp.
typedef deque<Node> NodeDeque
Definition at line 35 of file node.hpp.
typedef shared_ptr<NodeDeque> NodeDequePtr
Definition at line 37 of file node.hpp.
typedef const char * Signature
Definition at line 638 of file ast.hpp.
typedef set<Complex_Selector*, Complex_Selector_Pointer_Compare> SourcesSet
Definition at line 1918 of file ast.hpp.
typedef vector<ExtensionPair> SubsetMapEntries
Definition at line 64 of file extend.cpp.
Enumeration Type Documentation
enum Output_Style
Enumerator:
NESTED
EXPANDED
COMPACT
COMPRESSED
FORMATTED
Definition at line 9 of file ast_fwd_decl.hpp.
enum SassUnit
Enumerator:
IN
CM
PC
MM
PT
PX
DEG
GRAD
RAD
TURN
SEC
MSEC
HERTZ
KHERTZ
DPI
DPCM
DPPX
UNKNOWN
Definition at line 22 of file units.hpp.
enum SassUnitType
Enumerator:
SIZE
ANGLE
TIME
FREQUENCY
RESOLUTION
INCOMMENSURABLE
Definition at line 13 of file units.hpp.
Function Documentation
double Sass::add (double x, double y) [inline]
Definition at line 24 of file eval.cpp.
void bind (string callee, Parameters * ps, Arguments * as, Context & ctx, Env * env, Eval * eval)
Definition at line 13 of file bind.cpp.
References a(), Hashed::at(), Eval::backtrace, List::COMMA, Eval::contextualize, Vectorized< T >::elements(), Eval::env, error(), Environment< T >::has_local(), Hashed::keys(), l(), Vectorized< T >::length(), Environment< T >::local_frame(), Context::mem, Sass::Prelexer::name(), p(), to_string, unquote(), and Eval::with().
Referenced by Expand::operator()(), and Eval::operator()().
static double Sass::cap_channel (double c) [inline, static]
Definition at line 532 of file inspect.cpp.
size_t check_bom_chars (const char * src, const char * end, const unsigned char * bom, size_t len)
Definition at line 2317 of file parser.cpp.
static Node Sass::chunks (Node & seq1, Node & seq2, const ChunkerType & chunker) [inline, static]
Definition at line 673 of file extend.cpp.
References CHUNKS, Node::collection(), Node::createCollection(), and DEBUG_PRINTLN.
Referenced by subweave().
static string Sass::closer (const converter & converter) [static]
Definition at line 48 of file sass2scss.cpp.
Referenced by process(), and sass2scss().
string comment_to_string (const string & text)
Definition at line 229 of file util.cpp.
Referenced by Emitter::append_string().
bool Sass::compatibility (const char * their_version) [inline]
Definition at line 24 of file plugins.cpp.
References libsass_version(), and npos.
Referenced by Plugins::load_plugin().
Node Sass::complexSelectorDequeToNode (const ComplexSelectorDeque & deque, Context & ctx)
Definition at line 266 of file extend.cpp.
References Node::collection(), complexSelectorToNode(), and Node::createCollection().
Referenced by subweave().
static bool Sass::complexSelectorHasExtension (Complex_Selector * pComplexSelector, Context & ctx, ExtensionSubsetMap & subsetMap) [static]
Definition at line 1664 of file extend.cpp.
References error(), gyp::generator::cmake::ext, Sass::File::get_cwd(), Subset_Map< K, V >::get_v(), pstate, Sass::File::resolve_relative_path(), Compound_Selector::to_str_vec(), and to_string.
Referenced by extendSelectorList().
Node complexSelectorToNode (Complex_Selector * pToConvert, Context & ctx)
Definition at line 174 of file node.cpp.
References Complex_Selector::ANCESTOR_OF, Node::collection(), Node::createCollection(), Node::createCombinator(), Node::createNil(), and Node::createSelector().
Referenced by complexSelectorDequeToNode(), extendCompoundSelector(), extendSelectorList(), and roundtripTest().
double conversion_factor (const string & s1, const string & s2)
Definition at line 123 of file units.cpp.
References ANGLE, angle_conversion_factors, FREQUENCY, frequency_conversion_factors, get_unit_type(), INCOMMENSURABLE, RESOLUTION, resolution_conversion_factors, SIZE, size_conversion_factors, string_to_unit(), TIME, time_conversion_factors, and UNKNOWN.
Referenced by Number::convert(), and Number::normalize().
static Complex_Selector* Sass::createComplexSelector (string src) [static]
Definition at line 34 of file test_node.cpp.
References ctx, and Parser::from_c_str().
Referenced by roundtripTest().
Expression * cval_to_astnode (Sass_Value * v, Context & ctx, Backtrace * backtrace, ParserState pstate)
Definition at line 1345 of file eval.cpp.
References List::COMMA, error(), l(), Context::mem, Nan::Null(), SASS_BOOLEAN, sass_boolean_get_value(), SASS_COLOR, sass_color_get_a(), sass_color_get_b(), sass_color_get_g(), sass_color_get_r(), SASS_COMMA, SASS_ERROR, sass_error_get_message(), SASS_LIST, sass_list_get_length(), sass_list_get_separator(), sass_list_get_value(), SASS_MAP, sass_map_get_key(), sass_map_get_length(), sass_map_get_value(), SASS_NULL, SASS_NUMBER, sass_number_get_unit(), sass_number_get_value(), SASS_STRING, sass_string_get_value(), sass_value_get_tag(), SASS_WARNING, sass_warning_get_message(), and List::SPACE.
Referenced by Eval::operator()().
char detect_best_quotemark (const char * s, char qm)
Definition at line 297 of file util.cpp.
Referenced by quote().
double Sass::div (double x, double y) [inline]
Definition at line 27 of file eval.cpp.
bool Sass::ends_with (std::string const & value, std::string const & ending) [inline]
Definition at line 16 of file output.hpp.
Referenced by Output::get_buffer(), and Plugins::load_plugins().
bool eq (Expression * lhs, Expression * rhs, Context & ctx)
Definition at line 1099 of file eval.cpp.
References Hashed::at(), Expression::BOOLEAN, Expression::COLOR, eq(), is_quoted(), Hashed::keys(), l(), Hashed::length(), Vectorized< T >::length(), Expression::LIST, Expression::MAP, Expression::NULL_VAL, Expression::NUMBER, Expression::STRING, and unquote().
bool Sass::eq (Expression * , Expression * , Context & , Eval *)
Referenced by Sass::Functions::BUILT_IN(), eq(), and Eval::operator()().
void error (string msg, ParserState pstate, Backtrace * bt)
Definition at line 28 of file error_handling.cpp.
References error(), and Backtrace::to_string().
Referenced by SoftwareController::_init_software(), DiarioController::go(), EmeController::include_localized(), EmeController::load_part_contents(), BaseController::load_part_contents(), DiarioController::read(), BaseController::render_page(), TrackbackController::require_post(), BackendController::server_error_next(), BackendController::server_error_previous(), BackendController::server_error_read(), DownloadManager::start_download(), BaseController::unknown_action(), and SoftwareController::widgets_versioncheck().
void error (string msg, ParserState pstate)
Definition at line 23 of file error_handling.cpp.
References Sass_Error::syntax.
Referenced by Parameters::adjust_after_pushing(), Arguments::adjust_after_pushing(), Argument::Argument(), bind(), complexSelectorHasExtension(), cval_to_astnode(), error(), Expand::fallback_impl(), Eval::interpolation(), lt(), Number::normalize(), op_color_number(), op_colors(), op_number_color(), op_numbers(), op_strings(), Inspect::operator()(), Expand::operator()(), Eval::operator()(), and Parameter::Parameter().
string evacuate_escapes (const string & str)
Definition at line 182 of file util.cpp.
Referenced by Eval::interpolation().
string evacuate_quotes (const string & str)
Definition at line 160 of file util.cpp.
Referenced by Eval::interpolation().
static Node Sass::extendComplexSelector (Complex_Selector * pComplexSelector, Context & ctx, ExtensionSubsetMap & subsetMap, set< Compound_Selector > seen) [static]
Referenced by extendCompoundSelector(), and extendSelectorList().
static Node Sass::extendCompoundSelector (Compound_Selector * pSelector, Context & ctx, ExtensionSubsetMap & subsetMap, set< Compound_Selector > seen) [static]
Definition at line 1485 of file extend.cpp.
References Complex_Selector::addSources(), Complex_Selector::ANCESTOR_OF, Complex_Selector::base(), Complex_Selector::clear_innermost(), Complex_Selector::cloneFully(), Node::collection(), complexSelectorToNode(), Node::contains(), Node::createCollection(), DEBUG_EXEC, DEBUG_PRINTLN, EXTEND_COMPOUND, extendComplexSelector(), Subset_Map< K, V >::get_v(), group_by_to_a(), Vectorized< T >::length(), Context::mem, Compound_Selector::minus(), Complex_Selector::set_innermost(), Compound_Selector::sources(), Complex_Selector::sources(), Compound_Selector::to_str_vec(), and Compound_Selector::unify_with().
static void Sass::extendObjectWithSelectorAndBlock (ObjectType * pObject, Context & ctx, ExtensionSubsetMap & subsetMap) [inline, static]
Definition at line 1933 of file extend.cpp.
References DEBUG_PRINTLN, EXTEND_OBJECT, extendSelectorList(), Parser::from_c_str(), shouldExtendBlock(), and to_string.
Referenced by Extend::operator()().
static Selector_List* Sass::extendSelectorList (Selector_List * pSelectorList, Context & ctx, ExtensionSubsetMap & subsetMap, bool & extendedSomething) [static]
Definition at line 1857 of file extend.cpp.
References Node::collection(), complexSelectorHasExtension(), complexSelectorToNode(), Node::contains(), extendComplexSelector(), nodeToComplexSelector(), and to_string.
Referenced by extendObjectWithSelectorAndBlock().
static size_t Sass::findCommentOpener (string & sass) [static]
Definition at line 187 of file sass2scss.cpp.
References Sass::Prelexer::character(), Sass::Prelexer::comment(), and npos.
Referenced by flush().
Node flatten (const Node & arr, Context & ctx, int n = -1)
Definition at line 111 of file sass_util.cpp.
References Node::collection(), Node::createCollection(), and Node::isCollection().
Referenced by subweave().
string Sass::flush (string & sass, converter & converter)
Definition at line 358 of file sass2scss.cpp.
References CONVERT_COMMENT, findCommentOpener(), IS_COMMENT, npos, PRETTIFY, and STRIP_COMMENT.
Referenced by process().
SassUnitType get_unit_type (SassUnit unit)
Definition at line 51 of file units.cpp.
References ANGLE, FREQUENCY, INCOMMENSURABLE, RESOLUTION, SIZE, and TIME.
Referenced by conversion_factor().
static void Sass::getAndRemoveFinalOps (Node & seq, Node & ops) [static]
Definition at line 755 of file extend.cpp.
References Node::collection().
Referenced by mergeFinalOps().
static void Sass::getAndRemoveInitialOps (Node & seq, Node & ops) [static]
Definition at line 744 of file extend.cpp.
References Node::collection().
Referenced by mergeInitialOps().
void Sass::group_by_to_a (vector< EnumType > & enumeration, KeyFunctorType & keyFunc, vector< pair< KeyType, vector< EnumType > > > & arr) [inline]
Definition at line 224 of file sass_util.hpp.
Referenced by extendCompoundSelector().
static Node Sass::groupSelectors (Node & seq, Context & ctx) [static]
Definition at line 723 of file extend.cpp.
References Node::collection(), Node::createCollection(), and Node::plus().
Referenced by subweave().
static bool Sass::hasCharData (string & sass) [static]
Definition at line 151 of file sass2scss.cpp.
Referenced by process().
bool is_color_doublet (double r, double g, double b)
Definition at line 453 of file util.cpp.
References is_hex_doublet().
Referenced by Inspect::operator()().
bool is_hex_doublet (double n)
Definition at line 445 of file util.cpp.
Referenced by is_color_doublet().
bool Sass::is_pseudo_class_element (const string & name) [inline]
Definition at line 1844 of file ast.hpp.
Referenced by Pseudo_Selector::is_pseudo_class(), and Pseudo_Selector::is_pseudo_element().
char Sass::is_quoted (string str)
Definition at line 845 of file eval.cpp.
Referenced by eq().
static bool Sass::isPseudoSelector (string & sel) [static]
Definition at line 65 of file sass2scss.cpp.
Referenced by process().
Node Sass::lcs (Node & x, Node & y, const ComparatorType & comparator, Context & ctx) [inline]
Definition at line 146 of file sass_util.hpp.
References Node::collection(), Node::createCollection(), Node::createNil(), DEBUG_PRINTLN, LCS, lcs_backtrace(), lcs_table(), and Node::plus().
void Sass::lcs (ComplexSelectorDeque & x, ComplexSelectorDeque & y, const LcsCollectionComparator & comparator, Context & ctx, ComplexSelectorDeque & out)
Definition at line 398 of file extend.cpp.
References lcs_backtrace(), and lcs_table().
Referenced by mergeFinalOps(), mergeInitialOps(), and subweave().
Node Sass::lcs_backtrace (const LCSTable & c, const Node & x, const Node & y, int i, int j, const ComparatorType & comparator) [inline]
Definition at line 67 of file sass_util.hpp.
References Node::collection(), Node::createCollection(), Node::createNil(), DEBUG_PRINTLN, LCS, and lcs_backtrace().
void Sass::lcs_backtrace (const LCSTable & c, ComplexSelectorDeque & x, ComplexSelectorDeque & y, int i, int j, const LcsCollectionComparator & comparator, ComplexSelectorDeque & out)
Definition at line 324 of file extend.cpp.
References DEBUG_PRINTLN, and LCS.
Referenced by lcs(), and lcs_backtrace().
void Sass::lcs_table (const Node & x, const Node & y, const ComparatorType & comparator, LCSTable & out) [inline]
Definition at line 103 of file sass_util.hpp.
References Node::collection(), Node::createNil(), DEBUG_PRINTLN, and LCS.
void Sass::lcs_table (const ComplexSelectorDeque & x, const ComplexSelectorDeque & y, const LcsCollectionComparator & comparator, LCSTable & out)
Definition at line 359 of file extend.cpp.
Referenced by lcs().
bool lt (Expression * , Expression * , Context &)
Definition at line 1160 of file eval.cpp.
References error(), Number::find_convertible_unit(), l(), Number::normalize(), Expression::NUMBER, and Number::unit().
Referenced by Sass::Functions::BUILT_IN(), and Eval::operator()().
int Sass::main ()
Definition at line 87 of file test_node.cpp.
References ROUNDTRIP_TESTS, roundtripTest(), and STATIC_ARRAY_SIZE.
Definition * make_c_function (Sass_Function_Entry c_func, Context & ctx)
Definition at line 53 of file functions.cpp.
References Parser::from_c_str(), Parser::lex(), Parser::lexed, Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), Parser::parse_parameters(), and sass_function_get_signature().
Referenced by register_c_function().
Definition * make_native_function (Signature sig, Native_Function func, Context & ctx)
Definition at line 38 of file functions.cpp.
References Parser::from_c_str(), Sass::Prelexer::identifier(), Parser::lex(), Parser::lexed, Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), and Parser::parse_parameters().
Referenced by register_function().
triple<F, S, T> Sass::make_triple (const F & f, const S & s, const T & t) [inline]
Definition at line 71 of file subset_map.hpp.
Referenced by Subset_Map< K, V >::put().
static Node Sass::mergeFinalOps (Node & seq1, Node & seq2, Context & ctx, Node & res) [static]
Definition at line 874 of file extend.cpp.
References Complex_Selector::ADJACENT_TO, ALL, Complex_Selector::clone(), Node::collection(), Node::combinator(), Node::createCollection(), Node::createCombinator(), Node::createNil(), Node::createSelector(), DEBUG_EXEC, DEBUG_PRINTLN, getAndRemoveFinalOps(), Complex_Selector::is_superselector_of(), lcs(), Complex_Selector::PARENT_OF, Complex_Selector::PRECEDES, and Node::selector().
Referenced by subweave().
static Node Sass::mergeInitialOps (Node & seq1, Node & seq2, Context & ctx) [static]
Definition at line 783 of file extend.cpp.
References Node::collection(), Node::createCollection(), Node::createNil(), getAndRemoveInitialOps(), and lcs().
Referenced by subweave().
double Sass::mul (double x, double y) [inline]
Definition at line 26 of file eval.cpp.
bool nodesEqual (const Node & lhs, const Node & rhs, bool simpleSelectorOrderDependent)
Definition at line 83 of file node.cpp.
References Node::collection(), Node::combinator(), Node::isCollection(), Node::isCombinator(), Node::isNil(), Node::isSelector(), Node::selector(), selectors_equal(), and Node::type().
Referenced by Node::contains(), and Node::operator==().
Complex_Selector * nodeToComplexSelector (const Node & toConvert, Context & ctx)
Definition at line 199 of file node.cpp.
References Complex_Selector::ANCESTOR_OF, Complex_Selector::clone(), Node::collection(), Node::combinator(), Vectorized< T >::elements(), Node::got_line_feed, Node::isCollection(), Node::isCombinator(), Node::isNil(), Node::isSelector(), Context::mem, and Node::selector().
Referenced by extendSelectorList(), nodeToComplexSelectorDeque(), parentSuperselector(), roundtripTest(), and trim().
void Sass::nodeToComplexSelectorDeque (const Node & node, ComplexSelectorDeque & out, Context & ctx)
Definition at line 259 of file extend.cpp.
References Node::collection(), and nodeToComplexSelector().
Referenced by subweave().
string normalize_wspace (const string & str)
Definition at line 261 of file util.cpp.
Referenced by Parser::parse_ie_property().
Expression * op_color_number (Context & ctx, Binary_Expression::Type op, Expression * lhs, Expression * rhs)
Definition at line 1269 of file eval.cpp.
References Binary_Expression::DIV, error(), l(), Context::mem, and ops.
Referenced by op_strings(), and Eval::operator()().
Expression * op_colors (Context & ctx, Binary_Expression::Type op, Expression * lhs, Expression * rhs)
Definition at line 1282 of file eval.cpp.
References Binary_Expression::DIV, error(), l(), Context::mem, Binary_Expression::MOD, and ops.
Referenced by op_strings(), and Eval::operator()().
Expression * op_number_color (Context & ctx, Binary_Expression::Type op, Expression * lhs, Expression * rhs)
Definition at line 1230 of file eval.cpp.
References Binary_Expression::ADD, Sass_Value::color, COMPRESSED, Binary_Expression::DIV, error(), l(), Context::mem, Binary_Expression::MOD, Binary_Expression::MUL, Sass::Util::normalize_sixtuplet(), ops, Context::output_style, Binary_Expression::SUB, and to_string.
Referenced by op_strings(), and Eval::operator()().
Expression * op_numbers (Context & ctx, Binary_Expression * b, Expression * lhs, Expression * rhs)
Definition at line 1177 of file eval.cpp.
References Binary_Expression::ADD, Number::denominator_units(), Binary_Expression::DIV, error(), Number::find_convertible_unit(), l(), Context::mem, Binary_Expression::MOD, Binary_Expression::MUL, Number::normalize(), Number::numerator_units(), ops, Binary_Expression::SUB, Expression::type(), and Number::unit().
Referenced by Eval::operator()().
Expression * op_strings (Context & ctx, Binary_Expression::Type op, Expression * lhs, Expression * rhs)
Definition at line 1300 of file eval.cpp.
References Expression::COLOR, Binary_Expression::DIV, error(), Context::mem, Binary_Expression::MOD, Binary_Expression::MUL, Context::names_to_colors, Expression::NULL_VAL, Expression::NUMBER, op_color_number(), op_colors(), op_number_color(), quote(), Expression::STRING, Binary_Expression::SUB, to_string, and unquote().
Referenced by Eval::operator()().
static string Sass::opener (const converter & converter) [static]
Definition at line 56 of file sass2scss.cpp.
Referenced by process().
static bool Sass::parentSuperselector (const Node & one, const Node & two, Context & ctx) [static]
Definition at line 601 of file extend.cpp.
References Complex_Selector::ANCESTOR_OF, Vectorized< T >::elements(), Complex_Selector::is_superselector_of(), nodeToComplexSelector(), and Complex_Selector::set_innermost().
static bool Sass::parentSuperselector (Complex_Selector * pOne, Complex_Selector * pTwo, Context & ctx) [static]
Definition at line 239 of file extend.cpp.
References Complex_Selector::ANCESTOR_OF, Complex_Selector::clear_innermost(), Vectorized< T >::elements(), Complex_Selector::is_superselector_of(), and Complex_Selector::set_innermost().
Referenced by ParentSuperselectorChunker::operator()(), and LcsCollectionComparator::operator()().
Node paths (const Node & arrs, Context & ctx)
Definition at line 40 of file sass_util.cpp.
References Node::collection(), Node::createCollection(), Node::plus(), and to_string.
Referenced by main().
vector<vector<T> > Sass::paths (vector< vector< T > > strata, size_t from_end = 0) [inline]
Definition at line 38 of file paths.hpp.
Referenced by subweave().
bool peek_linefeed (const char * start)
Definition at line 458 of file util.cpp.
Referenced by Emitter::append_wspace(), and Parser::peek_newline().
string Sass::process (string & sass, converter & converter)
Definition at line 432 of file sass2scss.cpp.
References closer(), CONVERT_COMMENT, flush(), hasCharData(), INDENT, IS_COMMENT, IS_CSS_COMMENT, IS_PARSING, IS_SRC_COMMENT, isPseudoSelector(), KEEP_COMMENT, npos, opener(), removeMultilineComment(), rtrim(), and STRIP_COMMENT.
Referenced by sass2scss().
string quote (const string & s, char q, bool keep_linefeed_whitespace)
Definition at line 398 of file util.cpp.
References detect_best_quotemark(), and utf8::unchecked::next().
Referenced by Sass::Functions::BUILT_IN(), Eval::interpolation(), op_strings(), Output::operator()(), Inspect::operator()(), sass_string_quote(), BackendController::software_quote_create(), BackendController::software_quote_delete(), and BackendController::software_quote_edit().
string read_css_string (const string & str)
Definition at line 136 of file util.cpp.
void register_built_in_functions (Context & ctx, Env * env)
Definition at line 452 of file context.cpp.
References Sass::Functions::abs_sig, Sass::Functions::adjust_color_sig, Sass::Functions::adjust_hue_sig, Sass::Prelexer::alpha(), Sass::Functions::alpha_sig, utf8::unchecked::append(), Sass::Functions::append_sig, Sass::Functions::blue_sig, Sass::Functions::call_sig, Sass::Functions::ceil_sig, Sass::Functions::change_color_sig, Sass::Functions::comparable_sig, Sass::Functions::complement_sig, Sass::Functions::darken_sig, Sass::Functions::desaturate_sig, Sass::Functions::fade_in_sig, Sass::Functions::fade_out_sig, Sass::Functions::feature_exists_sig, Sass::Functions::floor_sig, Sass::Functions::function_exists_sig, Sass::Functions::global_variable_exists_sig, Sass::Functions::grayscale_sig, Sass::Functions::green_sig, Sass::Functions::hsl_sig, Sass::Functions::hsla_sig, Sass::Functions::hue_sig, Sass::Functions::ie_hex_str_sig, Sass::Functions::if_sig, Sass::Functions::index_sig, Sass::Functions::inspect_sig, Sass::Functions::invert_sig, Sass::Functions::is_superselector_sig, Sass::Functions::join_sig, Sass::Functions::keywords_sig, Sass::Functions::length_sig, Sass::Functions::lighten_sig, Sass::Functions::lightness_sig, Sass::Functions::list_separator_sig, Sass::Functions::map_get_sig, Sass::Functions::map_has_key_sig, Sass::Functions::map_keys_sig, Sass::Functions::map_merge_sig, Sass::Functions::map_remove_sig, Sass::Functions::map_values_sig, Sass::Functions::max_sig, Sass::Functions::min_sig, Sass::Functions::mix_sig, Sass::Functions::mixin_exists_sig, Sass::Functions::not_sig, Sass::Functions::nth_sig, Sass::Functions::opacify_sig, Sass::Functions::opacity_sig, Sass::Prelexer::percentage(), Sass::Functions::percentage_sig, Sass::Functions::quote_sig, Sass::Functions::random_sig, Sass::Functions::red_sig, register_function(), register_overload_stub(), Sass::Functions::rgb_sig, Sass::Functions::rgba_2_sig, Sass::Functions::rgba_4_sig, Sass::Functions::round_sig, Sass::Functions::saturate_sig, Sass::Functions::saturation_sig, Sass::Functions::scale_color_sig, Sass::Functions::set_nth_sig, Sass::Functions::str_index_sig, Sass::Functions::str_insert_sig, Sass::Functions::str_length_sig, Sass::Functions::str_slice_sig, Sass::Functions::to_lower_case_sig, Sass::Functions::to_upper_case_sig, Sass::Functions::transparentize_sig, Sass::Functions::type_of_sig, Sass::Functions::unique_id_sig, Sass::Functions::unit_sig, Sass::Functions::unitless_sig, Sass::Functions::unquote_sig, Sass::Functions::variable_exists_sig, and Sass::Functions::zip_sig.
Referenced by Context::parse_file().
void register_c_function (Context & ctx, Env * env, Sass_Function_Entry descr)
Definition at line 553 of file context.cpp.
References make_c_function().
Referenced by Context::parse_file(), and register_c_functions().
void register_c_functions (Context & ctx, Env * env, Sass_Function_List descrs)
Definition at line 546 of file context.cpp.
References register_c_function().
void register_function (Context & ctx, Signature sig, Native_Function f, size_t arity, Env * env)
Definition at line 430 of file context.cpp.
References make_native_function().
void register_function (Context & ctx, Signature sig, Native_Function f, Env * env)
Definition at line 423 of file context.cpp.
References make_native_function().
Referenced by register_built_in_functions().
void register_overload_stub (Context & ctx, string name, Env * env)
Definition at line 439 of file context.cpp.
References Context::mem.
Referenced by register_built_in_functions().
static string Sass::removeMultilineComment (string & sass) [static]
Definition at line 269 of file sass2scss.cpp.
References Sass::Prelexer::character(), Sass::Prelexer::comment(), and npos.
Referenced by process().
void Sass::roundtripTest (const char * toTest)
Definition at line 41 of file test_node.cpp.
References complexSelectorToNode(), createComplexSelector(), ctx, nodeToComplexSelector(), and to_string.
Referenced by main().
string Sass::rtrim (const string & sass)
Definition at line 345 of file sass2scss.cpp.
References npos.
Referenced by process().
static std::istream& Sass::safeGetline (std::istream & is, std::string & t) [static]
Definition at line 741 of file sass2scss.cpp.
Referenced by sass2scss().
char* Sass::sass2scss (const string sass, const int options)
Definition at line 775 of file sass2scss.cpp.
References closer(), process(), and safeGetline().
Referenced by Context::parse_string(), Sass::File::read_file(), and sass2scss().
double sass_atof (const char * str)
Definition at line 25 of file util.cpp.
References sass_strdup().
Referenced by Eval::operator()().
static Null Sass::sass_null (Sass:: NullParserState("null")) [static]
char * sass_strdup (const char * str)
Definition at line 15 of file util.cpp.
References out_of_memory.
Referenced by Context::compile_block(), Context::generate_source_map(), handle_errors(), sass_atof(), sass_compile(), sass_compile_file(), sass_make_error(), sass_make_import(), sass_make_number(), sass_make_qstring(), sass_make_string(), sass_make_warning(), sass_option_push_include_path(), sass_option_push_plugin_path(), sass_resolve_file(), sass_string_quote(), and sass_string_unquote().
bool Sass::selectors_equal (const SelectorType & one, const SelectorType & two, bool simpleSelectorOrderDependent) [inline]
Definition at line 2116 of file ast.hpp.
Referenced by nodesEqual(), and LcsCollectionComparator::operator()().
bool Sass::shouldExtendBlock (Block * b)
Definition at line 1900 of file extend.cpp.
References Vectorized< T >::length().
Referenced by extendObjectWithSelectorAndBlock().
bool Sass::sort_importers (const Sass_Importer_Entry & i, const Sass_Importer_Entry & j) [inline]
Definition at line 53 of file context.cpp.
References sass_importer_get_priority().
Referenced by Context::add_c_header(), and Context::add_c_importer().
string string_escape (const string & str)
Definition at line 102 of file util.cpp.
Referenced by Eval::interpolation().
string string_eval_escapes (const string & s)
Definition at line 47 of file util.cpp.
References utf8::unchecked::append().
string string_to_output (const string & str)
Definition at line 216 of file util.cpp.
Referenced by Eval::interpolation(), and Output::operator()().
SassUnit string_to_unit (const string & s)
Definition at line 64 of file units.cpp.
References CM, DEG, DPCM, DPI, DPPX, GRAD, HERTZ, IN, KHERTZ, MM, MSEC, PC, PT, PX, RAD, SEC, TURN, and UNKNOWN.
Referenced by conversion_factor(), Number::convert(), Number::find_convertible_unit(), and Number::normalize().
string string_unescape (const string & str)
Definition at line 117 of file util.cpp.
Referenced by Eval::operator()().
double Sass::sub (double x, double y) [inline]
Definition at line 25 of file eval.cpp.
Referenced by weave().
static Node Sass::subweave (Node & one, Node & two, Context & ctx) [static]
Definition at line 1137 of file extend.cpp.
References chunks(), Node::collection(), complexSelectorDequeToNode(), Node::createCollection(), Node::createNil(), DEBUG_PRINTLN, diff(), flatten(), groupSelectors(), Node::isCollection(), Node::isNil(), lcs(), mergeFinalOps(), mergeInitialOps(), nodeToComplexSelectorDeque(), paths(), Node::plus(), and SUBWEAVE.
Referenced by weave().
static Node Sass::trim (Node & seqses, Context & ctx) [static]
Definition at line 478 of file extend.cpp.
References Node::collection(), Node::createCollection(), DEBUG_EXEC, DEBUG_PRINTLN, Complex_Selector::is_superselector_of(), nodeToComplexSelector(), Node::plus(), Complex_Selector::sources(), Complex_Selector::specificity(), and TRIM.
Referenced by Trackback::auto_discovery(), Geoip::by_ip_addr(), RSSParser::cdataHandler(), MURatingsParser::cdataHandler(), and Markdown_Parser::makeCodeSpan().
const char * unit_to_string (SassUnit unit)
Definition at line 92 of file units.cpp.
References CM, DEG, DPCM, DPI, DPPX, GRAD, HERTZ, IN, KHERTZ, MM, MSEC, PC, PT, PX, RAD, SEC, and TURN.
Referenced by incompatibleUnits::incompatibleUnits().
string unquote (const string & s, char * qd)
Definition at line 313 of file util.cpp.
References utf8::unchecked::append().
Referenced by Parser::add_single_file(), bind(), Sass::Functions::BUILT_IN(), Parser::do_import(), eq(), At_Root_Expression::exclude(), Parser::import_single_file(), Eval::interpolation(), op_strings(), Eval::operator()(), Parser::parse_value(), Parser::parse_value_schema(), sass_string_unquote(), and String_Quoted::String_Quoted().
void warn (string msg, ParserState pstate, Backtrace * bt)
Definition at line 16 of file error_handling.cpp.
References Backtrace::to_string(), and warn().
void warn (string msg, ParserState pstate)
Definition at line 11 of file error_handling.cpp.
Referenced by warn().
static Node Sass::weave (Node & path, Context & ctx) [static]
Definition at line 1400 of file extend.cpp.
References Node::collection(), Node::createCollection(), DEBUG_PRINTLN, Node::isNil(), Node::plus(), sub(), subweave(), and WEAVE.
Variable Documentation
const double angle_conversion_factors
Initial value:
  {
     { 1,         40.0/36.0, PI/180.0,  1.0/360.0 },
     { 36.0/40.0, 1,         PI/200.0,  1.0/400.0 },
     { 180.0/PI,  200.0/PI,  1,         0.5/PI    },
     { 360.0,     400.0,     2.0*PI,    1         }
  }
Definition at line 22 of file units.cpp.
Referenced by conversion_factor().
const char* color_names[]
Definition at line 11 of file color_names.hpp.
Referenced by Context::setup_color_map().
const double color_values[]
Definition at line 168 of file color_names.hpp.
Referenced by Context::setup_color_map().
Context ctx = Context::Data()
Definition at line 14 of file test_node.cpp.
Referenced by Sass::Functions::BUILT_IN(), createComplexSelector(), and roundtripTest().
const double frequency_conversion_factors
Initial value:
  {
     { 1,         1/1000.0  },
     { 1000.0,    1         }
  }
Definition at line 37 of file units.cpp.
Referenced by conversion_factor().
bop ops[Binary_Expression::NUM_OPS]
Initial value:
 {
    0, 0,
    0, 0, 0, 0, 0, 0,
    add, sub, mul, div, fmod
  }
Definition at line 29 of file eval.cpp.
Referenced by op_color_number(), op_colors(), op_number_color(), and op_numbers().
const double PI = acos(-1)
Definition at line 11 of file units.hpp.
vector<pair<bool, Block*>> Cssize::slice_by_bubble(Statement* b) { vector<pair<bool, Block*>> results; for (size_t i = 0, L = b->block()->length(); i < L; ++i) { Statement* value = (*b->block()) pstate[i]; bool key = value->statement_type() == Statement::BUBBLE; if (!results.empty() && results.back().first == key) { Block* wrapper_block = results.back().second; *wrapper_block << value; } else { Block* wrapper_block = new (ctx.mem) Block(value->())
Referenced by Sass::Functions::BUILT_IN(), complexSelectorHasExtension(), Complex_Selector::context(), Compound_Selector::minus(), Number::normalize(), AST_Node::off(), and AST_Node::pos().
const double resolution_conversion_factors
Initial value:
  {
     { 1,         2.54,      96       },
     { 1/2.54,    1,         96/2.54  },
     { 1/96.0,    2.54/96,   1        }
  }
Definition at line 43 of file units.cpp.
Referenced by conversion_factor().
const char* const ROUNDTRIP_TESTS[]
Initial value:
 {
    NULL,
        "~",
                "CMPD",
    "~ CMPD",
    "CMPD >",
    "> > CMPD",
    "CMPD ~ ~",
    "> + CMPD1.CMPD2 > ~",
    "> + CMPD1.CMPD2 CMPD3.CMPD4 > ~",
    "+ CMPD1 CMPD2 ~ CMPD3 + CMPD4 > CMPD5 > ~"
  }
Definition at line 19 of file test_node.cpp.
Referenced by main().
const double size_conversion_factors
Initial value:
  {
     { 1,         2.54,      6,         25.4,      72,        96,       },
     { 1.0/2.54,  1,         6.0/2.54,  10,        72.0/2.54, 96.0/2.54 },
     { 1.0/6.0,   2.54/6.0,  1,         25.4/6.0,  72.0/6.0,  96.0/6.0  },
     { 1.0/25.4,  1.0/10.0,  6.0/25.4,  1,         72.0/25.4, 96.0/25.4 },
     { 1.0/72.0,  2.54/72.0, 6.0/72.0,  25.4/72.0, 1,         96.0/72.0 },
     { 1.0/96.0,  2.54/96.0, 6.0/96.0,  25.4/96.0, 72.0/96.0, 1,        }
  }
Definition at line 11 of file units.cpp.
Referenced by conversion_factor().
* wrapper_block<< value; results.push_back(make_pair(key, wrapper_block)); } } return results; } Statement* Cssize::shallow_copy(Statement* s) { switch (s- statement_type)())
Definition at line 353 of file cssize.cpp.
Referenced by At_Root_Block::At_Root_Block(), At_Rule::At_Rule(), Feature_Block::Feature_Block(), Keyframe_Rule::Keyframe_Rule(), Media_Block::Media_Block(), Cssize::operator()(), and Ruleset::Ruleset().
const double time_conversion_factors
Initial value:
  {
     { 1,         1000.0    },
     { 1/1000.0,  1         }
  }
Definition at line 31 of file units.cpp.
Referenced by conversion_factor().
To_String to_string
Definition at line 16 of file test_node.cpp.
Referenced by Selector_List::adjust_after_pushing(), bind(), Sass::Functions::BUILT_IN(), complexSelectorHasExtension(), At_Root_Expression::exclude(), extendObjectWithSelectorAndBlock(), extendSelectorList(), Eval::interpolation(), Complex_Selector::is_superselector_of(), Compound_Selector::is_superselector_of(), Compound_Selector::minus(), op_number_color(), op_strings(), Output::operator()(), Listize::operator()(), Expand::operator()(), Eval::operator()(), Contextualize_Eval::operator()(), Contextualize::operator()(), Simple_Selector::operator<(), Complex_Selector::operator<(), Compound_Selector::operator<(), Compound_Selector::operator==(), Simple_Selector::operator==(), Parser::parse_identifier_schema(), Parser::parse_selector_group(), paths(), roundtripTest(), Compound_Selector::to_str_vec(), and Simple_Selector::unify_with().