Emeraldion Lodge (codename Zelda): Time Class Reference
Time Class Reference
Helper object for time calculations.
Static Public Member Functions
static tomorrow ()
Returs the number of seconds elapsed from the Unix Epoch to tomorrow.
static yesterday ()
Returs the number of seconds elapsed from the Unix Epoch to yesterday.
static next_month ()
Returs the number of seconds elapsed from the Unix Epoch to next month.
static next_year ()
Returs the number of seconds elapsed from the Unix Epoch to next year.
static ago ($time_amount=NULL)
Returs the number of seconds elapsed from the Unix Epoch to a given date.
Detailed Description
Helper object for time calculations.
Definition at line 7 of file time.php.
Member Function Documentation
ago ($time_amount = NULL) static
Returs the number of seconds elapsed from the Unix Epoch to a given date.
Parameters
time_amount A quantity of time (e.g. day).
Definition at line 62 of file time.php.
Referenced by KmlController\hits_by_host(), and MetaController\hits_by_host_list().
next_month () static
Returs the number of seconds elapsed from the Unix Epoch to next month.
Definition at line 31 of file time.php.
next_year () static
Returs the number of seconds elapsed from the Unix Epoch to next year.
Definition at line 46 of file time.php.
Referenced by LoginController\login(), LanguageController\set(), and EmeController\set_credentials().
tomorrow () static
Returs the number of seconds elapsed from the Unix Epoch to tomorrow.
Definition at line 13 of file time.php.
Referenced by LoginController\login(), and EmeController\spot_people().
yesterday () static
Returs the number of seconds elapsed from the Unix Epoch to yesterday.
Definition at line 22 of file time.php.
Referenced by Cookie\delete().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/time.php