Emeraldion Lodge (codename Zelda): SassTypes Namespace Reference
SassTypes Namespace Reference
Data Structures
class Boolean
class Color
class Error
class Factory
class List
class Map
class Null
class Number
class SassValueWrapper
class String
class Value
Functions
NAN_METHOD (Boolean::New)
NAN_METHOD (Boolean::GetValue)
NAN_METHOD (Color::GetR)
NAN_METHOD (Color::GetG)
NAN_METHOD (Color::GetB)
NAN_METHOD (Color::GetA)
NAN_METHOD (Color::SetR)
NAN_METHOD (Color::SetG)
NAN_METHOD (Color::SetB)
NAN_METHOD (Color::SetA)
NAN_MODULE_INIT (Factory::initExports)
NAN_METHOD (List::GetValue)
NAN_METHOD (List::SetValue)
NAN_METHOD (List::GetSeparator)
NAN_METHOD (List::SetSeparator)
NAN_METHOD (List::GetLength)
NAN_METHOD (Map::GetValue)
NAN_METHOD (Map::SetValue)
NAN_METHOD (Map::GetKey)
NAN_METHOD (Map::SetKey)
NAN_METHOD (Map::GetLength)
NAN_METHOD (Null::New)
NAN_METHOD (Number::GetValue)
NAN_METHOD (Number::GetUnit)
NAN_METHOD (Number::SetValue)
NAN_METHOD (Number::SetUnit)
template<class T >
NAN_METHOD (SassValueWrapper< T >::New)
NAN_METHOD (String::GetValue)
NAN_METHOD (String::SetValue)
Function Documentation
SassTypes::NAN_METHOD (String::SetValue)
Definition at line 32 of file string.cpp.
References create_string(), Nan::New(), and sass_string_set_value().
SassTypes::NAN_METHOD (String::GetValue)
Definition at line 28 of file string.cpp.
References sass_string_get_value().
SassTypes::NAN_METHOD (SassValueWrapper< T >::New) [inline]
Definition at line 91 of file sass_value_wrapper.h.
References Nan::NewInstance(), sass_delete_value(), sass_error_get_message(), Nan::SetInternalFieldPointer(), Nan::ThrowError(), and Nan::Undefined().
SassTypes::NAN_METHOD (Number::SetUnit)
Definition at line 60 of file number.cpp.
References create_string(), Nan::New(), and sass_number_set_unit().
SassTypes::NAN_METHOD (Number::SetValue)
Definition at line 47 of file number.cpp.
References Nan::New(), and sass_number_set_value().
SassTypes::NAN_METHOD (Number::GetUnit)
Definition at line 43 of file number.cpp.
References sass_number_get_unit().
SassTypes::NAN_METHOD (Number::GetValue)
Definition at line 39 of file number.cpp.
References sass_number_get_value().
SassTypes::NAN_METHOD (Null::New)
Definition at line 48 of file null.cpp.
References Nan::New().
SassTypes::NAN_METHOD (Map::GetLength)
Definition at line 114 of file map.cpp.
References sass_map_get_length().
SassTypes::NAN_METHOD (Map::SetKey)
Definition at line 93 of file map.cpp.
References Value::get_sass_value(), Nan::New(), sass_map_set_key(), and Factory::unwrap().
SassTypes::NAN_METHOD (Map::GetKey)
Definition at line 72 of file map.cpp.
References Factory::create(), Nan::New(), sass_map_get_key(), and sass_map_get_length().
SassTypes::NAN_METHOD (Map::SetValue)
Definition at line 51 of file map.cpp.
References Value::get_sass_value(), Nan::New(), sass_map_set_value(), and Factory::unwrap().
SassTypes::NAN_METHOD (Map::GetValue)
Definition at line 30 of file map.cpp.
References Factory::create(), Nan::New(), sass_map_get_length(), and sass_map_get_value().
SassTypes::NAN_METHOD (List::GetLength)
Definition at line 97 of file list.cpp.
References sass_list_get_length().
SassTypes::NAN_METHOD (List::SetSeparator)
Definition at line 85 of file list.cpp.
References Nan::New(), SASS_COMMA, sass_list_set_separator(), and SASS_SPACE.
SassTypes::NAN_METHOD (List::GetSeparator)
Definition at line 81 of file list.cpp.
References SASS_COMMA, and sass_list_get_separator().
SassTypes::NAN_METHOD (List::SetValue)
Definition at line 60 of file list.cpp.
References Value::get_sass_value(), Nan::New(), sass_list_set_value(), and Factory::unwrap().
SassTypes::NAN_METHOD (List::GetValue)
Definition at line 39 of file list.cpp.
References Factory::create(), Nan::New(), sass_list_get_length(), and sass_list_get_value().
SassTypes::NAN_METHOD (Color::SetA)
Definition at line 116 of file color.cpp.
References Nan::New(), and sass_color_set_a().
SassTypes::NAN_METHOD (Color::SetB)
Definition at line 104 of file color.cpp.
References Nan::New(), and sass_color_set_b().
SassTypes::NAN_METHOD (Color::SetG)
Definition at line 92 of file color.cpp.
References Nan::New(), and sass_color_set_g().
SassTypes::NAN_METHOD (Color::SetR)
Definition at line 80 of file color.cpp.
References Nan::New(), and sass_color_set_r().
SassTypes::NAN_METHOD (Color::GetA)
Definition at line 76 of file color.cpp.
References sass_color_get_a().
SassTypes::NAN_METHOD (Color::GetB)
Definition at line 72 of file color.cpp.
References sass_color_get_b().
SassTypes::NAN_METHOD (Color::GetG)
Definition at line 68 of file color.cpp.
References sass_color_get_g().
SassTypes::NAN_METHOD (Color::GetR)
Definition at line 64 of file color.cpp.
References sass_color_get_r().
SassTypes::NAN_METHOD (Boolean::GetValue)
Definition at line 69 of file boolean.cpp.
References Nan::New(), Factory::unwrap(), and Boolean::value.
SassTypes::NAN_METHOD (Boolean::New)
Definition at line 53 of file boolean.cpp.
References Nan::New().
SassTypes::NAN_MODULE_INIT (Factory::initExports)
Definition at line 48 of file factory.cpp.
References SassValueWrapper< Error >::get_constructor(), Null::get_constructor(), SassValueWrapper< Map >::get_constructor(), SassValueWrapper< List >::get_constructor(), Boolean::get_constructor(), SassValueWrapper< Color >::get_constructor(), SassValueWrapper< String >::get_constructor(), SassValueWrapper< Number >::get_constructor(), Nan::New(), and Set().