Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_specificity.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_specificity.cpp File Reference
#include "../ast.hpp"
#include "../context.hpp"
#include "../parser.hpp"
#include "../to_string.hpp"
#include <string>
#include <iostream>
Functions
Selector * selector (string src)
void spec (string sel)
int main ()
Variables
Context ctx = Context::Data()
To_String to_string
Function Documentation
int main ()
Definition at line 20 of file test_specificity.cpp.
References spec().
Selector* selector (string src)
Definition at line 14 of file test_specificity.cpp.
void spec (string sel)
Definition at line 17 of file test_specificity.cpp.
References selector(), and Compound_Selector::specificity().
Referenced by main().
Variable Documentation
Context ctx = Context::Data()
Definition at line 11 of file test_specificity.cpp.
To_String to_string
Definition at line 12 of file test_specificity.cpp.