Emeraldion Lodge (codename Zelda): Inspect Class Reference
Inspect Class Reference
#include <inspect.hpp>
Inherits Operation_CRTP< void, Inspect >, and Sass::Emitter.
Inherited by Output.
Public Member Functions
Inspect (Emitter emi)
virtual ~Inspect ()
virtual void operator() (Block *)
virtual void operator() (Ruleset *)
virtual void operator() (Propset *)
virtual void operator() (Bubble *)
virtual void operator() (Feature_Block *)
virtual void operator() (Media_Block *)
virtual void operator() (At_Root_Block *)
virtual void operator() (At_Rule *)
virtual void operator() (Keyframe_Rule *)
virtual void operator() (Declaration *)
virtual void operator() (Assignment *)
virtual void operator() (Import *)
virtual void operator() (Import_Stub *)
virtual void operator() (Warning *)
virtual void operator() (Error *)
virtual void operator() (Debug *)
virtual void operator() (Comment *)
virtual void operator() (If *)
virtual void operator() (For *)
virtual void operator() (Each *)
virtual void operator() (While *)
virtual void operator() (Return *)
virtual void operator() (Extension *)
virtual void operator() (Definition *)
virtual void operator() (Mixin_Call *)
virtual void operator() (Content *)
virtual void operator() (Map *)
virtual void operator() (List *)
virtual void operator() (Binary_Expression *)
virtual void operator() (Unary_Expression *)
virtual void operator() (Function_Call *)
virtual void operator() (Function_Call_Schema *)
virtual void operator() (Variable *)
virtual void operator() (Textual *)
virtual void operator() (Number *)
virtual void operator() (Color *)
virtual void operator() (Boolean *)
virtual void operator() (String_Schema *)
virtual void operator() (String_Constant *)
virtual void operator() (String_Quoted *)
virtual void operator() (Feature_Query *)
virtual void operator() (Feature_Query_Condition *)
virtual void operator() (Media_Query *)
virtual void operator() (Media_Query_Expression *)
virtual void operator() (At_Root_Expression *)
virtual void operator() (Null *)
virtual void operator() (Parent_Selector *p)
virtual void operator() (Parameter *)
virtual void operator() (Parameters *)
virtual void operator() (Argument *)
virtual void operator() (Arguments *)
virtual void operator() (Selector_Schema *)
virtual void operator() (Selector_Reference *)
virtual void operator() (Selector_Placeholder *)
virtual void operator() (Type_Selector *)
virtual void operator() (Selector_Qualifier *)
virtual void operator() (Attribute_Selector *)
virtual void operator() (Pseudo_Selector *)
virtual void operator() (Wrapped_Selector *)
virtual void operator() (Compound_Selector *)
virtual void operator() (Complex_Selector *)
virtual void operator() (Selector_List *)
Protected Member Functions
void fallback_impl (AST_Node *n)
Detailed Description
Definition at line 14 of file inspect.hpp.
Constructor & Destructor Documentation
Inspect (Emitter emi)
Definition at line 16 of file inspect.cpp.
~Inspect () [virtual]
Definition at line 19 of file inspect.cpp.
Member Function Documentation
void fallback_impl (AST_Node * n) [protected]
Reimplemented in Output.
Definition at line 943 of file inspect.cpp.
void operator() (Selector_List * g) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 927 of file inspect.cpp.
References Emitter::append_comma_separator(), Emitter::append_indentation(), Emitter::append_optional_linefeed(), Vectorized< T >::empty(), Emitter::in_wrapped, and Vectorized< T >::length().
void operator() (Complex_Selector * c) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 889 of file inspect.cpp.
References Complex_Selector::ADJACENT_TO, Complex_Selector::ANCESTOR_OF, Emitter::append_mandatory_space(), Emitter::append_optional_linefeed(), Emitter::append_optional_space(), Emitter::append_string(), Sass::COMPRESSED, Compound_Selector::is_empty_reference(), Emitter::output_style(), Complex_Selector::PARENT_OF, Complex_Selector::PRECEDES, and Emitter::scheduled_space.
void operator() (Compound_Selector * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 879 of file inspect.cpp.
References Emitter::append_optional_linefeed(), and Vectorized< T >::length().
void operator() (Wrapped_Selector * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 869 of file inspect.cpp.
References Emitter::append_string(), Emitter::append_token(), and Emitter::in_wrapped.
void operator() (Pseudo_Selector * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 860 of file inspect.cpp.
References Emitter::append_string(), and Emitter::append_token().
void operator() (Attribute_Selector * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 845 of file inspect.cpp.
References Emitter::add_close_mapping(), Emitter::add_open_mapping(), Emitter::append_string(), and Emitter::append_token().
void operator() (Selector_Qualifier * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 838 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_optional_linefeed(), and Emitter::append_token().
void operator() (Type_Selector * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 833 of file inspect.cpp.
References Emitter::append_token().
void operator() (Selector_Placeholder * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 825 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_optional_linefeed(), and Emitter::append_token().
void operator() (Selector_Reference * ref) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 819 of file inspect.cpp.
References Emitter::append_string().
void operator() (Selector_Schema * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 814 of file inspect.cpp.
void operator() (Arguments * a) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 800 of file inspect.cpp.
References Emitter::append_string(), Vectorized< T >::empty(), and Vectorized< T >::length().
void operator() (Argument * a) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 781 of file inspect.cpp.
References Emitter::append_colon_separator(), Emitter::append_string(), Emitter::append_token(), Expression::NULL_VAL, s(), and Expression::STRING.
void operator() (Parameters * p) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 768 of file inspect.cpp.
References Emitter::append_comma_separator(), Emitter::append_string(), Vectorized< T >::empty(), and Vectorized< T >::length().
void operator() (Parameter * p) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 756 of file inspect.cpp.
References Emitter::append_colon_separator(), Emitter::append_string(), and Emitter::append_token().
void operator() (Parent_Selector * p) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 744 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_string(), and Parent_Selector::selector().
void operator() (Null * n) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 739 of file inspect.cpp.
References Emitter::append_token().
void operator() (At_Root_Expression * ae) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 723 of file inspect.cpp.
References Emitter::append_colon_separator(), and Emitter::append_string().
void operator() (Media_Query_Expression * mqe) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 707 of file inspect.cpp.
References Emitter::append_string().
void operator() (Media_Query * mq) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 690 of file inspect.cpp.
References Emitter::append_string(), and Vectorized< T >::length().
void operator() (Feature_Query_Condition * fqc) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 661 of file inspect.cpp.
References Feature_Query_Condition::AND, Emitter::append_mandatory_space(), Emitter::append_string(), Emitter::append_token(), Vectorized< T >::length(), Feature_Query_Condition::NOT, and Feature_Query_Condition::OR.
void operator() (Feature_Query * fq) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 652 of file inspect.cpp.
References Vectorized< T >::length().
void operator() (String_Quoted * s) [virtual]
Reimplemented in Output.
Definition at line 643 of file inspect.cpp.
References Emitter::append_token(), and Sass::quote().
void operator() (String_Constant * s) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 635 of file inspect.cpp.
References Emitter::append_token(), and Inspect::operator()().
void operator() (String_Schema * ss) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 624 of file inspect.cpp.
References Emitter::append_string(), and Vectorized< T >::length().
void operator() (Boolean * b) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 619 of file inspect.cpp.
References Emitter::append_token().
void operator() (Color * c) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 538 of file inspect.cpp.
References a(), Emitter::append_token(), Context::colors_to_names, Sass::COMPRESSED, Emitter::ctx, Sass::is_color_doublet(), Sass::Prelexer::name(), Context::names_to_colors, and Emitter::output_style().
void operator() (Number * n) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 441 of file inspect.cpp.
References Emitter::append_token(), Emitter::ctx, Number::denominator_units(), Sass::error(), Number::normalize(), npos, Number::numerator_units(), Context::precision, and Number::unit().
void operator() (Textual * txt) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 436 of file inspect.cpp.
References Emitter::append_token().
void operator() (Variable * var) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 431 of file inspect.cpp.
References Emitter::append_token().
void operator() (Function_Call_Schema * call) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 425 of file inspect.cpp.
void operator() (Function_Call * call) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 419 of file inspect.cpp.
References Emitter::append_token().
void operator() (Unary_Expression * expr) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 412 of file inspect.cpp.
References Emitter::append_string(), Unary_Expression::PLUS, and Expression::type().
void operator() (Binary_Expression * expr) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 390 of file inspect.cpp.
References Binary_Expression::ADD, Binary_Expression::AND, Emitter::append_string(), Binary_Expression::DIV, Binary_Expression::EQ, Binary_Expression::GT, Binary_Expression::GTE, Binary_Expression::LT, Binary_Expression::LTE, Binary_Expression::MOD, Binary_Expression::MUL, Binary_Expression::NEQ, Binary_Expression::OR, Binary_Expression::SUB, and Expression::type().
void operator() (List * list) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 345 of file inspect.cpp.
References Emitter::append_optional_space(), Emitter::append_string(), List::COMMA, Sass::COMPRESSED, Vectorized< T >::empty(), Emitter::in_comma_array, Emitter::in_declaration, Emitter::in_media_block, Emitter::in_space_array, Expression::is_invisible(), Emitter::output_style(), List::size(), and List::SPACE.
void operator() (Map * map) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 327 of file inspect.cpp.
References Emitter::append_colon_separator(), Emitter::append_comma_separator(), Emitter::append_string(), Hashed::at(), Hashed::empty(), Expression::is_invisible(), Map::is_invisible(), and Hashed::keys().
void operator() (Content * content) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 320 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), and Emitter::append_token().
void operator() (Mixin_Call * call) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 304 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_optional_space(), Emitter::append_string(), Emitter::append_token(), and Statement::block().
void operator() (Definition * def) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 289 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_string(), Emitter::append_token(), Statement::block(), and Definition::MIXIN.
void operator() (Extension * extend) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 280 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), and Emitter::append_token().
void operator() (Return * ret) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 271 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), and Emitter::append_token().
void operator() (While * loop) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 262 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_token(), and Statement::block().
void operator() (Each * loop) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 247 of file inspect.cpp.
References Emitter::append_comma_separator(), Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_string(), Emitter::append_token(), and Statement::block().
void operator() (For * loop) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 234 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_string(), Emitter::append_token(), and Statement::block().
void operator() (If * cond) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 219 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_optional_linefeed(), Emitter::append_string(), and Emitter::append_token().
void operator() (Comment * comment) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 212 of file inspect.cpp.
References Emitter::in_comment.
void operator() (Debug * debug) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 203 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), and Emitter::append_token().
void operator() (Error * error) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 194 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), and Emitter::append_token().
void operator() (Warning * warning) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 185 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), and Emitter::append_token().
void operator() (Import_Stub * import) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 176 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_string(), and Emitter::append_token().
void operator() (Import * import) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 149 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_mandatory_linefeed(), Emitter::append_mandatory_space(), and Emitter::append_token().
void operator() (Assignment * assn) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 137 of file inspect.cpp.
References Emitter::append_colon_separator(), Emitter::append_delimiter(), Emitter::append_optional_space(), Emitter::append_string(), and Emitter::append_token().
void operator() (Declaration * dec) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 116 of file inspect.cpp.
References Emitter::append_colon_separator(), Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_optional_space(), Emitter::append_string(), Emitter::in_declaration, Emitter::indentation, Sass::NESTED, Expression::NULL_VAL, and Emitter::output_style().
void operator() (Keyframe_Rule * rule) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 46 of file inspect.cpp.
References Statement::block().
void operator() (At_Rule * at_rule) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 97 of file inspect.cpp.
References Emitter::append_delimiter(), Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_token(), Statement::block(), and Emitter::in_wrapped.
void operator() (At_Root_Block * at_root_block) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 88 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_token(), and Statement::block().
void operator() (Media_Block * media_block) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 68 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_token(), Statement::block(), and Emitter::in_media_block.
void operator() (Feature_Block * feature_block) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 79 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_mandatory_space(), Emitter::append_token(), and Statement::block().
void operator() (Bubble * bubble) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 59 of file inspect.cpp.
References Emitter::append_indentation(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), and Emitter::append_token().
void operator() (Propset * propset) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 52 of file inspect.cpp.
References Emitter::append_colon_separator(), and Statement::block().
void operator() (Ruleset * ruleset) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Reimplemented in Output.
Definition at line 40 of file inspect.cpp.
References Statement::block().
void operator() (Block * block) [virtual]
Reimplemented from Operation_CRTP< void, Inspect >.
Definition at line 22 of file inspect.cpp.
References Emitter::add_close_mapping(), Emitter::add_open_mapping(), Emitter::append_scope_closer(), Emitter::append_scope_opener(), Emitter::indentation, Vectorized< T >::length(), Sass::NESTED, and Emitter::output_style().
Referenced by Inspect::operator()().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/inspect.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/inspect.cpp