Emeraldion Lodge (codename Zelda): Eval Class Reference
Eval Class Reference
#include <eval.hpp>
Inherits Operation_CRTP< Expression *, Eval >.
Public Member Functions
Eval (Context &, Contextualize *, Listize *, Env *, Backtrace *)
virtual ~Eval ()
Eval * with (Env *e, Backtrace *bt)
Eval * with (Selector *c, Env *e, Backtrace *bt, Selector *placeholder=0, Selector *extender=0)
Expression * operator() (Block *)
Expression * operator() (Assignment *)
Expression * operator() (If *)
Expression * operator() (For *)
Expression * operator() (Each *)
Expression * operator() (While *)
Expression * operator() (Return *)
Expression * operator() (Warning *)
Expression * operator() (Error *)
Expression * operator() (Debug *)
Expression * operator() (List *)
Expression * operator() (Map *)
Expression * operator() (Binary_Expression *)
Expression * operator() (Unary_Expression *)
Expression * operator() (Function_Call *)
Expression * operator() (Function_Call_Schema *)
Expression * operator() (Variable *)
Expression * operator() (Textual *)
Expression * operator() (Number *)
Expression * operator() (Boolean *)
Expression * operator() (String_Schema *)
Expression * operator() (String_Constant *)
Expression * operator() (Media_Query *)
Expression * operator() (Media_Query_Expression *)
Expression * operator() (At_Root_Expression *)
Expression * operator() (Feature_Query *)
Expression * operator() (Feature_Query_Condition *)
Expression * operator() (Null *)
Expression * operator() (Argument *)
Expression * operator() (Arguments *)
Expression * operator() (Comment *)
Expression * operator() (Parent_Selector *p)
template<typename U >
Expression * fallback (U x)
Data Fields
Contextualize * contextualize
Listize * listize
Env * env
Backtrace * backtrace
Private Member Functions
Expression * fallback_impl (AST_Node *n)
string interpolation (Expression *s)
Private Attributes
Context & ctx
Detailed Description
Definition at line 22 of file eval.hpp.
Constructor & Destructor Documentation
Eval (Context & ctx, Contextualize * contextualize, Listize * listize, Env * env, Backtrace * bt)
Definition at line 35 of file eval.cpp.
~Eval () [virtual]
Definition at line 37 of file eval.cpp.
Member Function Documentation
Expression* fallback (U x) [inline]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 75 of file eval.hpp.
References Eval::fallback_impl().
Expression * fallback_impl (AST_Node * n) [inline, private]
Definition at line 1092 of file eval.cpp.
Referenced by Eval::fallback().
string interpolation (Expression * s) [private]
Definition at line 857 of file eval.cpp.
References COMMA, Sass::COMPRESSED, Eval::ctx, Eval::env, Sass::error(), Sass::evacuate_escapes(), Sass::evacuate_quotes(), Environment< T >::has(), Sass_Value::list, Context::mem, Sass::Prelexer::name(), Context::output_style, Sass::quote(), Sass_List::separator, Sass::string_escape(), Sass::string_to_output(), Sass::to_string, and Sass::unquote().
Referenced by Eval::operator()().
Expression * operator() (Parent_Selector * p) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 1079 of file eval.cpp.
References Eval::contextualize, Eval::ctx, l(), Eval::listize, Context::mem, s(), and Parent_Selector::selector().
Expression * operator() (Comment * c) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 1074 of file eval.cpp.
Expression * operator() (Arguments * a) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 1065 of file eval.cpp.
References Eval::ctx, Vectorized< T >::length(), and Context::mem.
Expression * operator() (Argument * a) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 1034 of file eval.cpp.
References List::COMMA, Eval::ctx, Expression::LIST, Expression::MAP, and Context::mem.
Expression * operator() (Null * n) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 1029 of file eval.cpp.
Expression * operator() (Feature_Query_Condition * c) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 963 of file eval.cpp.
References Eval::ctx, Vectorized< T >::length(), and Context::mem.
Expression * operator() (Feature_Query * q) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 953 of file eval.cpp.
References Eval::ctx, Vectorized< T >::length(), and Context::mem.
Expression * operator() (At_Root_Expression * e) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 980 of file eval.cpp.
References Eval::ctx, and Context::mem.
Expression * operator() (Media_Query_Expression * e) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 1009 of file eval.cpp.
References Eval::ctx, and Context::mem.
Expression * operator() (Media_Query * q) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 993 of file eval.cpp.
References Eval::ctx, Vectorized< T >::length(), Context::mem, and Sass::to_string.
Expression * operator() (String_Constant * s) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 942 of file eval.cpp.
References Eval::ctx, Context::mem, and Context::names_to_colors.
Expression * operator() (String_Schema * s) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 923 of file eval.cpp.
References Eval::ctx, Eval::interpolation(), Vectorized< T >::length(), Context::mem, and Sass::string_unescape().
Expression * operator() (Boolean * b) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 840 of file eval.cpp.
Expression * operator() (Number * n) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 830 of file eval.cpp.
References Eval::ctx, Context::mem, Number::normalize(), and Number::unit().
Expression * operator() (Textual * t) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 766 of file eval.cpp.
References Eval::ctx, Textual::DIMENSION, Textual::HEX, Context::mem, npos, Textual::NUMBER, Sass::Prelexer::number(), Textual::PERCENTAGE, Sass::sass_atof(), and Expression::type().
Expression * operator() (Variable * v) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 720 of file eval.cpp.
References Expression::BOOLEAN, Expression::COLOR, Eval::ctx, Eval::env, Sass::error(), Environment< T >::has(), Expression::LIST, Expression::MAP, Context::mem, Sass::Prelexer::name(), Nan::Null(), Expression::NULL_VAL, Expression::NUMBER, Expression::STRING, Sass::to_string, and Sass::unquote().
Expression * operator() (Function_Call_Schema * s) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 711 of file eval.cpp.
References Eval::ctx, and Context::mem.
Expression * operator() (Function_Call * c) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 544 of file eval.cpp.
References gyp::msvs_emulation::arg, Eval::backtrace, Sass::bind(), Statement::block(), Eval::ctx, Sass::cval_to_astnode(), Backtrace::depth(), Eval::env, Sass::error(), Environment< T >::has(), Vectorized< T >::length(), Environment< T >::link(), Environment< T >::local_frame(), Sass::Constants::MaxCallStack, Context::mem, Sass::Prelexer::name(), Expression::NONE, Sass::Util::normalize_underscores(), npos, Backtrace::parent, SASS_COMMA, sass_delete_value(), SASS_ERROR, sass_error_get_message(), sass_function_get_function(), sass_list_set_value(), sass_make_list(), sass_value_get_tag(), SASS_WARNING, sass_warning_get_message(), Expression::STRING, and Sass::to_string.
Expression * operator() (Unary_Expression * u) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 513 of file eval.cpp.
References Eval::ctx, Context::mem, Unary_Expression::MINUS, Unary_Expression::NOT, Expression::NULL_VAL, Expression::NUMBER, Sass::to_string, and Expression::type().
Expression * operator() (Binary_Expression * b) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 430 of file eval.cpp.
References Binary_Expression::AND, Expression::COLOR, Eval::ctx, Binary_Expression::DIV, Sass::eq(), Binary_Expression::EQ, Binary_Expression::GT, Binary_Expression::GTE, Sass::lt(), Binary_Expression::LT, Binary_Expression::LTE, Context::mem, Binary_Expression::NEQ, Expression::NUMBER, Sass::op_color_number(), Sass::op_colors(), Sass::op_number_color(), Sass::op_numbers(), Sass::op_strings(), Binary_Expression::OR, Expression::set_delayed(), Expression::STRING, and Expression::type().
Expression * operator() (Map * m) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 393 of file eval.cpp.
References Hashed::at(), Eval::ctx, Sass::error(), Hashed::get_duplicate_key(), Hashed::has_duplicate_key(), Hashed::keys(), Hashed::length(), Context::mem, and Sass::to_string.
Expression * operator() (List * l) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 379 of file eval.cpp.
References Eval::ctx, Vectorized< T >::length(), and Context::mem.
Expression * operator() (Debug * d) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 347 of file eval.cpp.
References Context::c_options, Eval::ctx, Eval::env, Context::get_cwd(), Environment< T >::has(), Sass::File::resolve_relative_path(), SASS_COMMA, sass_delete_value(), sass_function_get_function(), sass_list_set_value(), sass_make_list(), Sass::to_string, and Sass::unquote().
Expression * operator() (Error * e) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 318 of file eval.cpp.
References Context::c_options, Eval::ctx, Eval::env, Sass::error(), Environment< T >::has(), SASS_COMMA, sass_delete_value(), sass_function_get_function(), sass_list_set_value(), sass_make_list(), Sass::to_string, and Sass::unquote().
Expression * operator() (Warning * w) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 286 of file eval.cpp.
References Eval::backtrace, Context::c_options, Eval::ctx, Eval::env, Environment< T >::has(), SASS_COMMA, sass_delete_value(), sass_function_get_function(), sass_list_set_value(), sass_make_list(), Sass::to_string, and Sass::unquote().
Expression * operator() (Return * r) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 281 of file eval.cpp.
Expression * operator() (While * w) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 270 of file eval.cpp.
References Statement::block().
Expression * operator() (Each * e) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 196 of file eval.cpp.
References Hashed::at(), Statement::block(), List::COMMA, Eval::ctx, Environment< T >::del_local(), Eval::env, Environment< T >::get_local(), Environment< T >::has_local(), Hashed::keys(), Vectorized< T >::length(), Expression::LIST, Expression::MAP, Context::mem, Environment< T >::set_local(), List::SPACE, and Sass::Prelexer::variable().
Expression * operator() (For * f) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 139 of file eval.cpp.
References Eval::backtrace, Statement::block(), Environment< T >::del_local(), Eval::env, Sass::error(), Environment< T >::get_local(), Environment< T >::has_local(), Environment< T >::mem, Expression::NUMBER, Environment< T >::set_local(), Number::unit(), and Sass::Prelexer::variable().
Expression * operator() (If * i) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 125 of file eval.cpp.
Expression * operator() (Assignment * a) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 65 of file eval.cpp.
References Eval::env, Environment< T >::get_global(), Environment< T >::has_global(), Environment< T >::has_lexical(), Environment< T >::is_lexical(), Expression::NULL_VAL, Environment< T >::set_global(), Environment< T >::set_lexical(), and Environment< T >::set_local().
Expression * operator() (Block * b) [virtual]
Reimplemented from Operation_CRTP< Expression *, Eval >.
Definition at line 55 of file eval.cpp.
References Vectorized< T >::length().
Eval * with (Selector * c, Env * e, Backtrace * bt, Selector * placeholder = 0, Selector * extender = 0)
Definition at line 47 of file eval.cpp.
References Eval::backtrace, Eval::contextualize, Eval::env, and Contextualize::with().
Eval * with (Env * e, Backtrace * bt)
Definition at line 39 of file eval.cpp.
References Eval::backtrace, Eval::contextualize, Eval::env, and Contextualize::with().
Referenced by Sass::bind(), Expand::operator()(), Contextualize_Eval::operator()(), and Contextualize_Eval::with().
Field Documentation
Backtrace* backtrace
Definition at line 32 of file eval.hpp.
Referenced by Sass::bind(), Eval::operator()(), and Eval::with().
Contextualize* contextualize
Definition at line 29 of file eval.hpp.
Referenced by Sass::bind(), Eval::operator()(), and Eval::with().
Context& ctx [private]
Definition at line 24 of file eval.hpp.
Referenced by Eval::interpolation(), and Eval::operator()().
Env* env
Definition at line 31 of file eval.hpp.
Referenced by Sass::bind(), Eval::interpolation(), Eval::operator()(), and Eval::with().
Listize* listize
Definition at line 30 of file eval.hpp.
Referenced by Eval::operator()().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/eval.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/eval.cpp