Emeraldion Lodge (codename Zelda): Listize Class Reference
Listize Class Reference
#include <listize.hpp>
Inherits Operation_CRTP< Expression *, Listize >.
Public Member Functions
Listize (Context &)
virtual ~Listize ()
Expression * operator() (Selector_List *)
Expression * operator() (Complex_Selector *)
Expression * operator() (Compound_Selector *)
Expression * operator() (Selector_Reference *)
template<typename U >
Expression * fallback (U x)
Private Member Functions
Expression * fallback_impl (AST_Node *n)
Private Attributes
Context & ctx
Detailed Description
Definition at line 18 of file listize.hpp.
Constructor & Destructor Documentation
Listize (Context & ctx)
Definition at line 12 of file listize.cpp.
virtual ~Listize () [inline, virtual]
Definition at line 26 of file listize.hpp.
Member Function Documentation
Expression* fallback (U x) [inline]
Reimplemented from Operation_CRTP< Expression *, Listize >.
Definition at line 36 of file listize.hpp.
References Listize::fallback_impl().
Expression * fallback_impl (AST_Node * n) [private]
Definition at line 79 of file listize.cpp.
Referenced by Listize::fallback().
Expression * operator() (Selector_Reference * sel) [virtual]
Reimplemented from Operation_CRTP< Expression *, Listize >.
Definition at line 74 of file listize.cpp.
Expression * operator() (Compound_Selector * sel) [virtual]
Reimplemented from Operation_CRTP< Expression *, Listize >.
Definition at line 25 of file listize.cpp.
References Listize::ctx, Vectorized< T >::length(), Context::mem, and Sass::to_string.
Expression * operator() (Complex_Selector * sel) [virtual]
Reimplemented from Operation_CRTP< Expression *, Listize >.
Definition at line 36 of file listize.cpp.
References Complex_Selector::ADJACENT_TO, Complex_Selector::ANCESTOR_OF, Listize::ctx, Compound_Selector::is_empty_reference(), l(), Vectorized< T >::length(), Expression::LIST, Context::mem, Complex_Selector::PARENT_OF, and Complex_Selector::PRECEDES.
Expression * operator() (Selector_List * sel) [virtual]
Reimplemented from Operation_CRTP< Expression *, Listize >.
Definition at line 16 of file listize.cpp.
References List::COMMA, Listize::ctx, l(), Vectorized< T >::length(), and Context::mem.
Field Documentation
Context& ctx [private]
Definition at line 20 of file listize.hpp.
Referenced by Listize::operator()().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/listize.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/listize.cpp