Emeraldion Lodge (codename Zelda): Boolean Class Reference
Boolean Class Reference
#include <boolean.h>
Inherits SassTypes::Value.
Public Member Functions
Sass_Value * get_sass_value ()
v8::Local< v8::Object > get_js_object ()
Static Public Member Functions
static Boolean & get_singleton (bool)
static v8::Local< v8::Function > get_constructor ()
static NAN_METHOD (New)
static NAN_METHOD (GetValue)
Private Member Functions
Boolean (bool)
Private Attributes
bool value
Nan::Persistent< v8::Object > js_object
Static Private Attributes
static Nan::Persistent
< v8::Function > constructor
static bool constructor_locked = false
Detailed Description
Definition at line 10 of file boolean.h.
Constructor & Destructor Documentation
Boolean (bool v) [private]
Definition at line 9 of file boolean.cpp.
Member Function Documentation
v8::Local< v8::Function > get_constructor () [static]
Definition at line 16 of file boolean.cpp.
References Boolean::constructor, Boolean::constructor_locked, EscapableHandleScope::Escape(), Boolean::get_singleton(), GetFunction(), Nan::GetFunction(), PersistentBase< T >::IsEmpty(), Boolean::js_object, Nan::New(), New(), Nan::NewInstance(), PersistentBase< T >::Reset(), Set(), Nan::SetInternalFieldPointer(), and Nan::SetPrototypeTemplate().
Referenced by SassTypes::NAN_MODULE_INIT().
v8::Local< v8::Object > get_js_object () [virtual]
Implements Value.
Definition at line 49 of file boolean.cpp.
References Boolean::js_object, and New().
Sass_Value * get_sass_value () [virtual]
Implements Value.
Definition at line 45 of file boolean.cpp.
References sass_make_boolean(), and Boolean::value.
Boolean & get_singleton (bool v) [static]
Definition at line 11 of file boolean.cpp.
Referenced by Factory::create(), and Boolean::get_constructor().
static NAN_METHOD (GetValue) [static]
static NAN_METHOD (New) [static]
Field Documentation
Nan::Persistent< v8::Function > constructor [static, private]
Definition at line 27 of file boolean.h.
Referenced by Boolean::get_constructor().
bool constructor_locked = false [static, private]
Definition at line 28 of file boolean.h.
Referenced by Boolean::get_constructor().
Nan::Persistent<v8::Object> js_object [private]
Definition at line 25 of file boolean.h.
Referenced by Boolean::get_constructor(), and Boolean::get_js_object().
bool value [private]
Definition at line 24 of file boolean.h.
Referenced by Boolean::get_sass_value(), and SassTypes::NAN_METHOD().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/boolean.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/boolean.cpp