Emeraldion Lodge (codename Zelda): Nan Namespace Reference
Nan Namespace Reference
Namespaces
namespace imp
Data Structures
class ReturnValue
class FunctionCallbackInfo
class PropertyCallbackInfoBase
class PropertyCallbackInfo
class PropertyCallbackInfo< v8::Array >
class PropertyCallbackInfo< v8::Boolean >
class PropertyCallbackInfo< v8::Integer >
class MaybeLocal
class Maybe
struct WeakCallbackType
class PersistentBase
class NonCopyablePersistentTraits
struct CopyablePersistentTraits
class Persistent
class Global
class HandleScope
class EscapableHandleScope
class TryCatch
class Utf8String
class Callback
class AsyncWorker
class AsyncProgressWorker
class WeakCallbackInfo
class ObjectWrap
struct Tap
Typedefs
typedef v8::Handle< v8::Object > ADDON_REGISTER_FUNCTION_ARGS_TYPE
typedef void(* FunctionCallback)(const FunctionCallbackInfo< v8::Value > &)
typedef void(* GetterCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Value > &)
typedef void(* SetterCallback)(v8::Local< v8::String >, v8::Local< v8::Value >, const PropertyCallbackInfo< void > &)
typedef void(* PropertyGetterCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Value > &)
typedef void(* PropertySetterCallback)(v8::Local< v8::String >, v8::Local< v8::Value >, const PropertyCallbackInfo< v8::Value > &)
typedef void(* PropertyEnumeratorCallback)(const PropertyCallbackInfo< v8::Array > &)
typedef void(* PropertyDeleterCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Boolean > &)
typedef void(* PropertyQueryCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Integer > &)
typedef void(* IndexGetterCallback)(uint32_t, const PropertyCallbackInfo< v8::Value > &)
typedef void(* IndexSetterCallback)(uint32_t, v8::Local< v8::Value >, const PropertyCallbackInfo< v8::Value > &)
typedef void(* IndexEnumeratorCallback)(const PropertyCallbackInfo< v8::Array > &)
typedef void(* IndexDeleterCallback)(uint32_t, const PropertyCallbackInfo< v8::Boolean > &)
typedef void(* IndexQueryCallback)(uint32_t, const PropertyCallbackInfo< v8::Integer > &)
typedef v8::Script UnboundScript
typedef v8::Script BoundScript
typedef
v8::String::ExternalAsciiStringResource ExternalOneByteStringResource
typedef pthread_key_t nauv_key_t
typedef void(* FreeCallback)(char *data, void *hint)
typedef const
FunctionCallbackInfo
< v8::Value > & NAN_METHOD_ARGS_TYPE
typedef void NAN_METHOD_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Value > & NAN_GETTER_ARGS_TYPE
typedef void NAN_GETTER_RETURN_TYPE
typedef const
PropertyCallbackInfo< void > & NAN_SETTER_ARGS_TYPE
typedef void NAN_SETTER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Value > & NAN_PROPERTY_GETTER_ARGS_TYPE
typedef void NAN_PROPERTY_GETTER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Value > & NAN_PROPERTY_SETTER_ARGS_TYPE
typedef void NAN_PROPERTY_SETTER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Array > & NAN_PROPERTY_ENUMERATOR_ARGS_TYPE
typedef void NAN_PROPERTY_ENUMERATOR_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Boolean > & NAN_PROPERTY_DELETER_ARGS_TYPE
typedef void NAN_PROPERTY_DELETER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Integer > & NAN_PROPERTY_QUERY_ARGS_TYPE
typedef void NAN_PROPERTY_QUERY_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Value > & NAN_INDEX_GETTER_ARGS_TYPE
typedef void NAN_INDEX_GETTER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Value > & NAN_INDEX_SETTER_ARGS_TYPE
typedef void NAN_INDEX_SETTER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Array > & NAN_INDEX_ENUMERATOR_ARGS_TYPE
typedef void NAN_INDEX_ENUMERATOR_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Boolean > & NAN_INDEX_DELETER_ARGS_TYPE
typedef void NAN_INDEX_DELETER_RETURN_TYPE
typedef const
PropertyCallbackInfo
< v8::Integer > & NAN_INDEX_QUERY_ARGS_TYPE
typedef void NAN_INDEX_QUERY_RETURN_TYPE
Enumerations
enum Encoding {
ASCII, UTF8, BASE64, UCS2,
BINARY, HEX, BUFFER
}
Functions
template<typename T >
Maybe< T > Nothing ()
template<typename T >
Maybe< T > Just (const T &t)
NAN_INLINE MaybeLocal< v8::String > ToDetailString (v8::Handle< v8::Value > val)
NAN_INLINE MaybeLocal< v8::Uint32 > ToArrayIndex (v8::Handle< v8::Value > val)
NAN_INLINE Maybe< bool > Equals (v8::Handle< v8::Value > a, v8::Handle< v8::Value >(b))
NAN_INLINE MaybeLocal< v8::Object > NewInstance (v8::Handle< v8::Function > h)
NAN_INLINE MaybeLocal< v8::Object > NewInstance (v8::Local< v8::Function > h, int argc, v8::Local< v8::Value > argv[])
NAN_INLINE MaybeLocal< v8::Object > NewInstance (v8::Handle< v8::ObjectTemplate > h)
NAN_INLINE MaybeLocal
< v8::Function > GetFunction (v8::Handle< v8::FunctionTemplate > t)
NAN_INLINE Maybe< bool > Set (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key, v8::Handle< v8::Value > value)
NAN_INLINE Maybe< bool > Set (v8::Handle< v8::Object > obj, uint32_t index, v8::Handle< v8::Value > value)
NAN_INLINE Maybe< bool > ForceSet (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key, v8::Handle< v8::Value > value, v8::PropertyAttribute attribs=v8::None)
NAN_INLINE MaybeLocal< v8::Value > Get (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key)
NAN_INLINE MaybeLocal< v8::Value > Get (v8::Handle< v8::Object > obj, uint32_t index)
NAN_INLINE Maybe
< v8::PropertyAttribute > GetPropertyAttributes (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key)
NAN_INLINE Maybe< bool > Has (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE Maybe< bool > Has (v8::Handle< v8::Object > obj, uint32_t index)
NAN_INLINE Maybe< bool > Delete (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE Maybe< bool > Delete (v8::Handle< v8::Object > obj, uint32_t index)
NAN_INLINE MaybeLocal< v8::Array > GetPropertyNames (v8::Handle< v8::Object > obj)
NAN_INLINE MaybeLocal< v8::Array > GetOwnPropertyNames (v8::Handle< v8::Object > obj)
NAN_INLINE Maybe< bool > SetPrototype (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > prototype)
NAN_INLINE MaybeLocal< v8::String > ObjectProtoToString (v8::Handle< v8::Object > obj)
NAN_INLINE Maybe< bool > HasOwnProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE Maybe< bool > HasRealNamedProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE Maybe< bool > HasRealIndexedProperty (v8::Handle< v8::Object > obj, uint32_t index)
NAN_INLINE Maybe< bool > HasRealNamedCallbackProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE MaybeLocal< v8::Value > GetRealNamedPropertyInPrototypeChain (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE MaybeLocal< v8::Value > GetRealNamedProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
NAN_INLINE MaybeLocal< v8::Value > CallAsFunction (v8::Handle< v8::Object > obj, v8::Handle< v8::Object > recv, int argc, v8::Handle< v8::Value > argv[])
NAN_INLINE MaybeLocal< v8::Value > CallAsConstructor (v8::Handle< v8::Object > obj, int argc, v8::Local< v8::Value > argv[])
NAN_INLINE MaybeLocal< v8::String > GetSourceLine (v8::Handle< v8::Message > msg)
NAN_INLINE Maybe< int > GetLineNumber (v8::Handle< v8::Message > msg)
NAN_INLINE Maybe< int > GetStartColumn (v8::Handle< v8::Message > msg)
NAN_INLINE Maybe< int > GetEndColumn (v8::Handle< v8::Message > msg)
NAN_INLINE MaybeLocal< v8::Object > CloneElementAt (v8::Handle< v8::Array > array, uint32_t index)
template<typename T >
NAN_INLINE imp::ToFactory< T >
::return_t To (v8::Local< v8::Value > val)
template<typename T >
v8::Local< T > New (v8::Handle< T > h)
template<typename T >
v8::Local< T > New (v8::Persistent< T > const &p)
template<typename T , typename M >
v8::Local< T > New (Persistent< T, M > const &p)
template<typename T >
imp::Factory< T >::return_t New ()
template<typename T , typename A0 >
imp::Factory< T >::return_t New (A0 arg0)
template<typename T , typename A0 , typename A1 >
imp::Factory< T >::return_t New (A0 arg0, A1 arg1)
template<typename T , typename A0 , typename A1 , typename A2 >
imp::Factory< T >::return_t New (A0 arg0, A1 arg1, A2 arg2)
template<typename T , typename A0 , typename A1 , typename A2 , typename A3 >
imp::Factory< T >::return_t New (A0 arg0, A1 arg1, A2 arg2, A3 arg3)
template<typename T >
imp::Factory< T >::return_t New (FunctionCallback callback, v8::Local< v8::Value > data=v8::Local< v8::Value >())
template<typename T , typename A2 >
imp::Factory< T >::return_t New (FunctionCallback callback, v8::Local< v8::Value > data=v8::Local< v8::Value >(), A2 a2=A2())
imp::Factory< v8::Boolean >
::return_t New (bool value)
imp::Factory< v8::Int32 >::return_t New (int32_t value)
imp::Factory< v8::Uint32 >
::return_t New (uint32_t value)
imp::Factory< v8::Number >
::return_t New (double value)
imp::Factory< v8::String >
::return_t New (std::string const &value)
imp::Factory< v8::String >
::return_t New (const char *value, int length)
imp::Factory< v8::String >
::return_t New (const char *value)
imp::Factory< v8::String >
::return_t New (const uint16_t *value)
imp::Factory< v8::String >
::return_t New (v8::String::ExternalStringResource *value)
imp::Factory< v8::String >
::return_t New (ExternalOneByteStringResource *value)
imp::Factory< v8::RegExp >
::return_t New (v8::Local< v8::String > pattern, v8::RegExp::Flags flags)
int nauv_key_create (nauv_key_t *key)
void nauv_key_delete (nauv_key_t *key)
void * nauv_key_get (nauv_key_t *key)
void nauv_key_set (nauv_key_t *key, void *value)
NAN_INLINE void SetCounterFunction (v8::CounterLookupCallback cb)
NAN_INLINE void SetCreateHistogramFunction (v8::CreateHistogramCallback cb)
NAN_INLINE void SetAddHistogramSampleFunction (v8::AddHistogramSampleCallback cb)
NAN_INLINE bool IdleNotification (int idle_time_in_ms)
NAN_INLINE void LowMemoryNotification ()
NAN_INLINE void ContextDisposedNotification ()
NAN_INLINE v8::Local
< v8::Primitive > Undefined ()
NAN_INLINE v8::Local
< v8::Primitive > Null ()
NAN_INLINE v8::Local< v8::Boolean > True ()
NAN_INLINE v8::Local< v8::Boolean > False ()
NAN_INLINE v8::Local< v8::String > EmptyString ()
NAN_INLINE int AdjustExternalMemory (int bc)
NAN_INLINE void SetTemplate (v8::Local< v8::Template > templ, const char *name, v8::Local< v8::Data > value)
NAN_INLINE void SetTemplate (v8::Local< v8::Template > templ, v8::Local< v8::String > name, v8::Local< v8::Data > value, v8::PropertyAttribute attributes)
NAN_INLINE v8::Local< v8::Context > GetCurrentContext ()
NAN_INLINE void * GetInternalFieldPointer (v8::Local< v8::Object > object, int index)
NAN_INLINE void SetInternalFieldPointer (v8::Local< v8::Object > object, int index, void *value)
NAN_INLINE void AddGCEpilogueCallback (v8::GCEpilogueCallback callback, v8::GCType gc_type_filter=v8::kGCTypeAll)
NAN_INLINE void RemoveGCEpilogueCallback (v8::GCEpilogueCallback callback)
NAN_INLINE void AddGCPrologueCallback (v8::GCPrologueCallback callback, v8::GCType gc_type_filter=v8::kGCTypeAll)
NAN_INLINE void RemoveGCPrologueCallback (v8::GCPrologueCallback callback)
NAN_INLINE void GetHeapStatistics (v8::HeapStatistics *heap_statistics)
NAN_INLINE void ThrowError (v8::Local< v8::Value > error)
NAN_INLINE MaybeLocal< v8::Object > NewBuffer (char *data, size_t length, node::Buffer::free_callback callback, void *hint)
NAN_INLINE MaybeLocal< v8::Object > CopyBuffer (const char *data, uint32_t size)
NAN_INLINE MaybeLocal< v8::Object > NewBuffer (uint32_t size)
NAN_INLINE void FreeData (char *data, void *hint)
NAN_INLINE MaybeLocal< v8::Object > NewBuffer (char *data, uint32_t size)
NAN_INLINE MaybeLocal< v8::String > NewOneByteString (const uint8_t *value, int length=-1)
NAN_INLINE MaybeLocal
< BoundScript > CompileScript (v8::Local< v8::String > s, const v8::ScriptOrigin &origin)
NAN_INLINE MaybeLocal
< BoundScript > CompileScript (v8::Local< v8::String > s)
NAN_INLINE MaybeLocal< v8::Value > RunScript (v8::Local< v8::Script > script)
NAN_INLINE v8::Local< v8::Value > MakeCallback (v8::Local< v8::Object > target, v8::Local< v8::Function > func, int argc, v8::Local< v8::Value > *argv)
NAN_INLINE v8::Local< v8::Value > MakeCallback (v8::Local< v8::Object > target, v8::Local< v8::String > symbol, int argc, v8::Local< v8::Value > *argv)
NAN_INLINE v8::Local< v8::Value > MakeCallback (v8::Local< v8::Object > target, const char *method, int argc, v8::Local< v8::Value > *argv)
NAN_INLINE void FatalException (const TryCatch &try_catch)
NAN_INLINE v8::Local< v8::Value > NanErrnoException (int errorno, const char *syscall=NULL, const char *message=NULL, const char *path=NULL)
template<typename T >
NAN_INLINE void SetIsolateData (v8::Isolate *isolate, T *data)
template<typename T >
NAN_INLINE T * GetIsolateData (v8::Isolate *isolate)
NAN_INLINE void AsyncExecute (uv_work_t *req)
NAN_INLINE void AsyncExecuteComplete (uv_work_t *req)
NAN_INLINE void AsyncQueueWorker (AsyncWorker *worker)
NAN_INLINE v8::Local< v8::Value > Encode (const void *buf, size_t len, enum Encoding encoding=BINARY)
NAN_INLINE ssize_t DecodeBytes (v8::Local< v8::Value > val, enum Encoding encoding=BINARY)
NAN_INLINE ssize_t DecodeWrite (char *buf, size_t len, v8::Local< v8::Value > val, enum Encoding encoding=BINARY)
NAN_INLINE void SetPrototypeTemplate (v8::Local< v8::FunctionTemplate > templ, const char *name, v8::Local< v8::Data > value)
NAN_INLINE void SetPrototypeTemplate (v8::Local< v8::FunctionTemplate > templ, v8::Local< v8::String > name, v8::Local< v8::Data > value, v8::PropertyAttribute attributes)
NAN_INLINE void SetInstanceTemplate (v8::Local< v8::FunctionTemplate > templ, const char *name, v8::Local< v8::Data > value)
NAN_INLINE void SetInstanceTemplate (v8::Local< v8::FunctionTemplate > templ, v8::Local< v8::String > name, v8::Local< v8::Data > value, v8::PropertyAttribute attributes)
template<typename T >
NAN_INLINE void SetMethod (const T &recv, const char *name, FunctionCallback callback)
NAN_INLINE void SetPrototypeMethod (v8::Local< v8::FunctionTemplate > recv, const char *name, FunctionCallback callback)
void SetAccessor (v8::Local< v8::ObjectTemplate > tpl, v8::Local< v8::String > name, GetterCallback getter, SetterCallback setter=0, v8::Local< v8::Value > data=v8::Local< v8::Value >(), v8::AccessControl settings=v8::DEFAULT, v8::PropertyAttribute attribute=v8::None, imp::Sig signature=imp::Sig())
bool SetAccessor (v8::Local< v8::Object > obj, v8::Local< v8::String > name, GetterCallback getter, SetterCallback setter=0, v8::Local< v8::Value > data=v8::Local< v8::Value >(), v8::AccessControl settings=v8::DEFAULT, v8::PropertyAttribute attribute=v8::None)
void SetNamedPropertyHandler (v8::Local< v8::ObjectTemplate > tpl, PropertyGetterCallback getter, PropertySetterCallback setter=0, PropertyQueryCallback query=0, PropertyDeleterCallback deleter=0, PropertyEnumeratorCallback enumerator=0, v8::Local< v8::Value > data=v8::Local< v8::Value >())
void SetIndexedPropertyHandler (v8::Local< v8::ObjectTemplate > tpl, IndexGetterCallback getter, IndexSetterCallback setter=0, IndexQueryCallback query=0, IndexDeleterCallback deleter=0, IndexEnumeratorCallback enumerator=0, v8::Local< v8::Value > data=v8::Local< v8::Value >())
void Export (ADDON_REGISTER_FUNCTION_ARGS_TYPE target, const char *name, FunctionCallback f)
Variables
static const int kInternalFieldsInWeakCallback = 2
static const int kNoInternalFieldIndex = -1
Typedef Documentation
typedef v8::Handle<v8::Object> ADDON_REGISTER_FUNCTION_ARGS_TYPE
Definition at line 128 of file nan.h.
typedef v8::Script BoundScript
Definition at line 736 of file nan.h.
typedef v8::String::ExternalAsciiStringResource ExternalOneByteStringResource
Definition at line 744 of file nan.h.
typedef void(* FreeCallback)(char *data, void *hint)
Definition at line 3032 of file nan.h.
typedef void(* FunctionCallback)(const FunctionCallbackInfo< v8::Value > &)
Definition at line 153 of file nan.h.
typedef void(* GetterCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Value > &)
Definition at line 155 of file nan.h.
typedef void(* IndexDeleterCallback)(uint32_t, const PropertyCallbackInfo< v8::Boolean > &)
Definition at line 184 of file nan.h.
typedef void(* IndexEnumeratorCallback)(const PropertyCallbackInfo< v8::Array > &)
Definition at line 183 of file nan.h.
typedef void(* IndexGetterCallback)(uint32_t, const PropertyCallbackInfo< v8::Value > &)
Definition at line 175 of file nan.h.
typedef void(* IndexQueryCallback)(uint32_t, const PropertyCallbackInfo< v8::Integer > &)
Definition at line 187 of file nan.h.
typedef void(* IndexSetterCallback)(uint32_t, v8::Local< v8::Value >, const PropertyCallbackInfo< v8::Value > &)
Definition at line 178 of file nan.h.
typedef const PropertyCallbackInfo<v8::Value>& NAN_GETTER_ARGS_TYPE
Definition at line 3037 of file nan.h.
typedef void NAN_GETTER_RETURN_TYPE
Definition at line 3038 of file nan.h.
typedef const PropertyCallbackInfo<v8::Boolean>& NAN_INDEX_DELETER_ARGS_TYPE
Definition at line 3074 of file nan.h.
typedef void NAN_INDEX_DELETER_RETURN_TYPE
Definition at line 3075 of file nan.h.
typedef const PropertyCallbackInfo<v8::Array>& NAN_INDEX_ENUMERATOR_ARGS_TYPE
Definition at line 3070 of file nan.h.
typedef void NAN_INDEX_ENUMERATOR_RETURN_TYPE
Definition at line 3071 of file nan.h.
typedef const PropertyCallbackInfo<v8::Value>& NAN_INDEX_GETTER_ARGS_TYPE
Definition at line 3063 of file nan.h.
typedef void NAN_INDEX_GETTER_RETURN_TYPE
Definition at line 3064 of file nan.h.
typedef const PropertyCallbackInfo<v8::Integer>& NAN_INDEX_QUERY_ARGS_TYPE
Definition at line 3078 of file nan.h.
typedef void NAN_INDEX_QUERY_RETURN_TYPE
Definition at line 3079 of file nan.h.
typedef const PropertyCallbackInfo<v8::Value>& NAN_INDEX_SETTER_ARGS_TYPE
Definition at line 3066 of file nan.h.
typedef void NAN_INDEX_SETTER_RETURN_TYPE
Definition at line 3067 of file nan.h.
typedef const FunctionCallbackInfo<v8::Value>& NAN_METHOD_ARGS_TYPE
Definition at line 3034 of file nan.h.
typedef void NAN_METHOD_RETURN_TYPE
Definition at line 3035 of file nan.h.
typedef const PropertyCallbackInfo<v8::Boolean>& NAN_PROPERTY_DELETER_ARGS_TYPE
Definition at line 3056 of file nan.h.
typedef void NAN_PROPERTY_DELETER_RETURN_TYPE
Definition at line 3057 of file nan.h.
typedef const PropertyCallbackInfo<v8::Array>& NAN_PROPERTY_ENUMERATOR_ARGS_TYPE
Definition at line 3052 of file nan.h.
typedef void NAN_PROPERTY_ENUMERATOR_RETURN_TYPE
Definition at line 3053 of file nan.h.
typedef const PropertyCallbackInfo<v8::Value>& NAN_PROPERTY_GETTER_ARGS_TYPE
Definition at line 3044 of file nan.h.
typedef void NAN_PROPERTY_GETTER_RETURN_TYPE
Definition at line 3045 of file nan.h.
typedef const PropertyCallbackInfo<v8::Integer>& NAN_PROPERTY_QUERY_ARGS_TYPE
Definition at line 3060 of file nan.h.
typedef void NAN_PROPERTY_QUERY_RETURN_TYPE
Definition at line 3061 of file nan.h.
typedef const PropertyCallbackInfo<v8::Value>& NAN_PROPERTY_SETTER_ARGS_TYPE
Definition at line 3048 of file nan.h.
typedef void NAN_PROPERTY_SETTER_RETURN_TYPE
Definition at line 3049 of file nan.h.
typedef const PropertyCallbackInfo<void>& NAN_SETTER_ARGS_TYPE
Definition at line 3040 of file nan.h.
typedef void NAN_SETTER_RETURN_TYPE
Definition at line 3041 of file nan.h.
typedef pthread_key_t nauv_key_t
Definition at line 1806 of file nan.h.
typedef void(* PropertyDeleterCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Boolean > &)
Definition at line 169 of file nan.h.
typedef void(* PropertyEnumeratorCallback)(const PropertyCallbackInfo< v8::Array > &)
Definition at line 168 of file nan.h.
typedef void(* PropertyGetterCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Value > &)
Definition at line 160 of file nan.h.
typedef void(* PropertyQueryCallback)(v8::Local< v8::String >, const PropertyCallbackInfo< v8::Integer > &)
Definition at line 172 of file nan.h.
typedef void(* PropertySetterCallback)(v8::Local< v8::String >, v8::Local< v8::Value >, const PropertyCallbackInfo< v8::Value > &)
Definition at line 163 of file nan.h.
typedef void(* SetterCallback)(v8::Local< v8::String >, v8::Local< v8::Value >, const PropertyCallbackInfo< void > &)
Definition at line 156 of file nan.h.
typedef v8::Script UnboundScript
Definition at line 735 of file nan.h.
Enumeration Type Documentation
enum Encoding
Enumerator:
ASCII
UTF8
BASE64
UCS2
BINARY
HEX
BUFFER
Definition at line 3523 of file nan.h.
Function Documentation
NAN_INLINE void Nan::AddGCEpilogueCallback (v8::GCEpilogueCallback callback, v8::GCType gc_type_filter = v8::kGCTypeAll)
Definition at line 2783 of file nan.h.
Referenced by Delete().
NAN_INLINE void Nan::AddGCPrologueCallback (v8::GCPrologueCallback callback, v8::GCType gc_type_filter = v8::kGCTypeAll)
Definition at line 2792 of file nan.h.
NAN_INLINE int Nan::AdjustExternalMemory (int bc)
Definition at line 2744 of file nan.h.
NAN_INLINE void Nan::AsyncExecute (uv_work_t * req)
Definition at line 3479 of file nan.h.
NAN_INLINE void Nan::AsyncExecuteComplete (uv_work_t * req)
Definition at line 3484 of file nan.h.
NAN_INLINE void Nan::AsyncQueueWorker (AsyncWorker * worker)
Definition at line 3490 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> Nan::CallAsConstructor (v8::Handle< v8::Object > obj, int argc, v8::Local< v8::Value > argv[])
Definition at line 1040 of file nan.h.
References EscapableHandleScope::Escape(), Nan::imp::kMaxLength, New(), and New().
NAN_INLINE MaybeLocal<v8::Value> Nan::CallAsFunction (v8::Handle< v8::Object > obj, v8::Handle< v8::Object > recv, int argc, v8::Handle< v8::Value > argv[])
Definition at line 1032 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::CloneElementAt (v8::Handle< v8::Array > array, uint32_t index)
Definition at line 1064 of file nan.h.
NAN_INLINE MaybeLocal<BoundScript> Nan::CompileScript (v8::Local< v8::String > s)
Definition at line 2925 of file nan.h.
NAN_INLINE MaybeLocal<BoundScript> Nan::CompileScript (v8::Local< v8::String > s, const v8::ScriptOrigin & origin)
Definition at line 2917 of file nan.h.
NAN_INLINE void Nan::ContextDisposedNotification ()
Definition at line 2319 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::CopyBuffer (const char * data, uint32_t size)
Definition at line 2853 of file nan.h.
Referenced by imp::Encode(), and GetResult().
NAN_INLINE ssize_t Nan::DecodeBytes (v8::Local< v8::Value > val, enum Encoding encoding = BINARY)
Definition at line 3865 of file nan.h.
Referenced by New().
NAN_INLINE ssize_t Nan::DecodeWrite (char * buf, size_t len, v8::Local< v8::Value > val, enum Encoding encoding = BINARY)
Definition at line 3882 of file nan.h.
Referenced by New().
NAN_INLINE Maybe<bool> Nan::Delete (v8::Handle< v8::Object > obj, uint32_t index)
Definition at line 968 of file nan.h.
References AddGCEpilogueCallback().
NAN_INLINE Maybe<bool> Nan::Delete (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 962 of file nan.h.
NAN_INLINE v8::Local<v8::String> Nan::EmptyString ()
Definition at line 2740 of file nan.h.
NAN_INLINE v8::Local<v8::Value> Nan::Encode (const void * buf, size_t len, enum Encoding encoding = BINARY)
Definition at line 3833 of file nan.h.
NAN_INLINE Maybe<bool> Nan::Equals (v8::Handle< v8::Value > a, v8::Handle< v8::Value > b)
Definition at line 883 of file nan.h.
void Nan::Export (ADDON_REGISTER_FUNCTION_ARGS_TYPE target, const char * name, FunctionCallback f) [inline]
Definition at line 4783 of file nan.h.
NAN_INLINE v8::Local<v8::Boolean> Nan::False ()
Definition at line 2735 of file nan.h.
Referenced by Nan::imp::SetterCallbackWrapper().
NAN_INLINE void Nan::FatalException (const TryCatch & try_catch)
Definition at line 2960 of file nan.h.
Referenced by CallbackBridge< T, L >::dispatched_async_uv_callback(), MakeCallback(), NAN_METHOD(), and CallbackBridge< T, L >::operator()().
NAN_INLINE Maybe<bool> Nan::ForceSet (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key, v8::Handle< v8::Value > value, v8::PropertyAttribute attribs = v8::None)
Definition at line 924 of file nan.h.
NAN_INLINE void Nan::FreeData (char * data, void * hint)
Definition at line 2879 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> Nan::Get (v8::Handle< v8::Object > obj, uint32_t index)
Definition at line 938 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> Nan::Get (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key)
Definition at line 932 of file nan.h.
Referenced by ExtractOptions(), GetStats(), NAN_METHOD(), Factory< v8::Uint32 >::New(), IntegerFactory< T >::New(), Factory< v8::External >::New(), Factory< v8::BooleanObject >::New(), and CustomImporterBridge::post_process_return_value().
NAN_INLINE v8::Local<v8::Context> Nan::GetCurrentContext ()
Definition at line 2763 of file nan.h.
Referenced by CallAsConstructor(), CallAsFunction(), CloneElementAt(), Delete(), Equals(), ForceSet(), Get(), GetEndColumn(), GetFunction(), GetLineNumber(), GetOwnPropertyNames(), GetPropertyAttributes(), GetPropertyNames(), GetRealNamedProperty(), GetRealNamedPropertyInPrototypeChain(), PropertyCallbackInfo< T >::GetReturnValue(), GetSourceLine(), GetStartColumn(), Has(), HasOwnProperty(), HasRealIndexedProperty(), HasRealNamedCallbackProperty(), HasRealNamedProperty(), NewInstance(), ObjectProtoToString(), Set(), SetPrototype(), ToArrayIndex(), and ToDetailString().
NAN_INLINE Maybe<int> Nan::GetEndColumn (v8::Handle< v8::Message > msg)
Definition at line 1060 of file nan.h.
NAN_INLINE MaybeLocal<v8::Function> Nan::GetFunction (v8::Handle< v8::FunctionTemplate > t)
Definition at line 906 of file nan.h.
Referenced by SassValueWrapper< T >::get_constructor(), Boolean::get_constructor(), CallbackBridge< T, L >::get_wrapper_constructor(), and nauv_key_set().
NAN_INLINE void Nan::GetHeapStatistics (v8::HeapStatistics * heap_statistics)
Definition at line 2801 of file nan.h.
NAN_INLINE void* Nan::GetInternalFieldPointer (v8::Local< v8::Object > object, int index)
Definition at line 2767 of file nan.h.
Referenced by SassValueWrapper< T >::get_js_object(), NAN_METHOD(), Factory::unwrap(), and ObjectWrap::Unwrap().
NAN_INLINE T* Nan::GetIsolateData (v8::Isolate * isolate) [inline]
Definition at line 2982 of file nan.h.
NAN_INLINE Maybe<int> Nan::GetLineNumber (v8::Handle< v8::Message > msg)
Definition at line 1052 of file nan.h.
NAN_INLINE MaybeLocal<v8::Array> Nan::GetOwnPropertyNames (v8::Handle< v8::Object > obj)
Definition at line 980 of file nan.h.
Referenced by ExtractOptions().
NAN_INLINE Maybe<v8::PropertyAttribute> Nan::GetPropertyAttributes (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key)
Definition at line 944 of file nan.h.
NAN_INLINE MaybeLocal<v8::Array> Nan::GetPropertyNames (v8::Handle< v8::Object > obj)
Definition at line 975 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> Nan::GetRealNamedProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 1026 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> Nan::GetRealNamedPropertyInPrototypeChain (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 1019 of file nan.h.
NAN_INLINE MaybeLocal<v8::String> Nan::GetSourceLine (v8::Handle< v8::Message > msg)
Definition at line 1048 of file nan.h.
NAN_INLINE Maybe<int> Nan::GetStartColumn (v8::Handle< v8::Message > msg)
Definition at line 1056 of file nan.h.
NAN_INLINE Maybe<bool> Nan::Has (v8::Handle< v8::Object > obj, uint32_t index)
Definition at line 956 of file nan.h.
NAN_INLINE Maybe<bool> Nan::Has (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 950 of file nan.h.
NAN_INLINE Maybe<bool> Nan::HasOwnProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 995 of file nan.h.
NAN_INLINE Maybe<bool> Nan::HasRealIndexedProperty (v8::Handle< v8::Object > obj, uint32_t index)
Definition at line 1007 of file nan.h.
NAN_INLINE Maybe<bool> Nan::HasRealNamedCallbackProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 1013 of file nan.h.
NAN_INLINE Maybe<bool> Nan::HasRealNamedProperty (v8::Handle< v8::Object > obj, v8::Handle< v8::String > key)
Definition at line 1001 of file nan.h.
NAN_INLINE bool Nan::IdleNotification (int idle_time_in_ms)
Definition at line 2311 of file nan.h.
Maybe<T> Nan::Just (const T & t) [inline]
Definition at line 868 of file nan.h.
NAN_INLINE void Nan::LowMemoryNotification ()
Definition at line 2315 of file nan.h.
Referenced by ReturnValueImp< T >::Value().
NAN_INLINE v8::Local<v8::Value> Nan::MakeCallback (v8::Local< v8::Object > target, const char * method, int argc, v8::Local< v8::Value > * argv)
Definition at line 2952 of file nan.h.
NAN_INLINE v8::Local<v8::Value> Nan::MakeCallback (v8::Local< v8::Object > target, v8::Local< v8::String > symbol, int argc, v8::Local< v8::Value > * argv)
Definition at line 2944 of file nan.h.
NAN_INLINE v8::Local<v8::Value> Nan::MakeCallback (v8::Local< v8::Object > target, v8::Local< v8::Function > func, int argc, v8::Local< v8::Value > * argv)
Definition at line 2936 of file nan.h.
Referenced by MaybeLocal< T >::ToLocalChecked().
NAN_INLINE v8::Local<v8::Value> Nan::NanErrnoException (int errorno, const char * syscall = NULL, const char * message = NULL, const char * path = NULL)
Definition at line 2964 of file nan.h.
int Nan::nauv_key_create (nauv_key_t * key) [inline]
Definition at line 1808 of file nan.h.
References SetTemplate().
void Nan::nauv_key_delete (nauv_key_t * key) [inline]
Definition at line 1812 of file nan.h.
void* Nan::nauv_key_get (nauv_key_t * key) [inline]
Definition at line 1817 of file nan.h.
References SetTemplate().
void Nan::nauv_key_set (nauv_key_t * key, void * value) [inline]
Definition at line 1821 of file nan.h.
References GetFunction(), and New().
imp::Factory<v8::RegExp>::return_t Nan::New (v8::Local< v8::String > pattern, v8::RegExp::Flags flags) [inline]
Definition at line 1763 of file nan.h.
References DecodeWrite().
imp::Factory<v8::String>::return_t Nan::New (ExternalOneByteStringResource * value) [inline]
Definition at line 1757 of file nan.h.
imp::Factory<v8::String>::return_t Nan::New (v8::String::ExternalStringResource * value) [inline]
Definition at line 1751 of file nan.h.
imp::Factory<v8::String>::return_t Nan::New (const uint16_t * value) [inline]
Definition at line 1745 of file nan.h.
References DecodeBytes().
imp::Factory<v8::String>::return_t Nan::New (const char * value) [inline]
Definition at line 1739 of file nan.h.
imp::Factory<v8::String>::return_t Nan::New (const char * value, int length) [inline]
Definition at line 1733 of file nan.h.
imp::Factory<v8::String>::return_t Nan::New (std::string const & value) [inline]
Definition at line 1727 of file nan.h.
imp::Factory<v8::Number>::return_t Nan::New (double value) [inline]
Definition at line 1721 of file nan.h.
imp::Factory<v8::Uint32>::return_t Nan::New (uint32_t value) [inline]
Definition at line 1715 of file nan.h.
imp::Factory<v8::Int32>::return_t Nan::New (int32_t value) [inline]
Definition at line 1709 of file nan.h.
imp::Factory<v8::Boolean>::return_t Nan::New (bool value) [inline]
Definition at line 1703 of file nan.h.
imp::Factory<T>::return_t Nan::New (FunctionCallback callback, v8::Local< v8::Value > data = v8::Local<v8::Value>(), A2 a2 = A2()) [inline]
Definition at line 1680 of file nan.h.
imp::Factory<T>::return_t Nan::New (FunctionCallback callback, v8::Local< v8::Value > data = v8::Local<v8::Value>()) [inline]
Definition at line 1672 of file nan.h.
imp::Factory<T>::return_t Nan::New (A0 arg0, A1 arg1, A2 arg2, A3 arg3) [inline]
Definition at line 1660 of file nan.h.
imp::Factory<T>::return_t Nan::New (A0 arg0, A1 arg1, A2 arg2) [inline]
Definition at line 1654 of file nan.h.
imp::Factory<T>::return_t Nan::New (A0 arg0, A1 arg1) [inline]
Definition at line 1648 of file nan.h.
imp::Factory<T>::return_t Nan::New (A0 arg0) [inline]
Definition at line 1642 of file nan.h.
imp::Factory<T>::return_t Nan::New () [inline]
Definition at line 1636 of file nan.h.
v8::Local< T > New (Persistent< T, M > const & p) [inline]
Definition at line 1624 of file nan.h.
v8::Local< T > New (v8::Persistent< T > const & p) [inline]
Definition at line 1619 of file nan.h.
v8::Local< T > New (v8::Handle< T > h) [inline]
Definition at line 1614 of file nan.h.
Referenced by CallAsConstructor(), CallbackBridge< T, L >::CallbackBridge(), CallbackBridge< T, L >::dispatched_async_uv_callback(), ExtractOptions(), Null::get_constructor(), Boolean::get_constructor(), CallbackBridge< T, L >::get_wrapper_constructor(), GetResult(), GetStats(), Nan::imp::IndexEnumeratorCallbackWrapper(), Nan::imp::IndexSetterCallbackWrapper(), SassTypes::NAN_METHOD(), NAN_METHOD(), SassTypes::NAN_MODULE_INIT(), nauv_key_set(), Factory< v8::Uint32 >::New(), IntegerFactory< T >::New(), Factory< v8::External >::New(), Factory< v8::BooleanObject >::New(), CallbackBridge< T, L >::operator()(), Nan::imp::SetterCallbackWrapper(), and MaybeLocal< T >::ToLocalChecked().
NAN_INLINE MaybeLocal<v8::Object> Nan::NewBuffer (char * data, uint32_t size)
Definition at line 2884 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::NewBuffer (uint32_t size)
Definition at line 2870 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::NewBuffer (char * data, size_t length, node::Buffer::free_callback callback, void * hint)
Definition at line 2839 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::NewInstance (v8::Handle< v8::ObjectTemplate > h)
Definition at line 901 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::NewInstance (v8::Local< v8::Function > h, int argc, v8::Local< v8::Value > argv[])
Definition at line 893 of file nan.h.
NAN_INLINE MaybeLocal<v8::Object> Nan::NewInstance (v8::Handle< v8::Function > h)
Definition at line 888 of file nan.h.
References Utf8String::str_, and Utf8String::str_st_.
Referenced by CallbackBridge< T, L >::CallbackBridge(), Null::get_constructor(), Boolean::get_constructor(), and SassTypes::NAN_METHOD().
NAN_INLINE MaybeLocal<v8::String> Nan::NewOneByteString (const uint8_t * value, int length = -1)
Definition at line 2910 of file nan.h.
Maybe<T> Nan::Nothing () [inline]
Definition at line 863 of file nan.h.
NAN_INLINE v8::Local<v8::Primitive> Nan::Null ()
Definition at line 2725 of file nan.h.
Referenced by Sass::Functions::BUILT_IN(), Sass::cval_to_astnode(), Eval::operator()(), Parser::parse_value(), and ReturnValue< v8::Array >::SetNull().
NAN_INLINE MaybeLocal<v8::String> Nan::ObjectProtoToString (v8::Handle< v8::Object > obj)
Definition at line 990 of file nan.h.
NAN_INLINE void Nan::RemoveGCEpilogueCallback (v8::GCEpilogueCallback callback)
Definition at line 2788 of file nan.h.
NAN_INLINE void Nan::RemoveGCPrologueCallback (v8::GCPrologueCallback callback)
Definition at line 2797 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> Nan::RunScript (v8::Local< v8::Script > script)
Definition at line 2932 of file nan.h.
NAN_INLINE Maybe<bool> Nan::Set (v8::Handle< v8::Object > obj, uint32_t index, v8::Handle< v8::Value > value)
Definition at line 917 of file nan.h.
NAN_INLINE Maybe<bool> Nan::Set (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > key, v8::Handle< v8::Value > value)
Definition at line 910 of file nan.h.
Referenced by GetResult(), GetStats(), and Global< T >::Global().
bool Nan::SetAccessor (v8::Local< v8::Object > obj, v8::Local< v8::String > name, GetterCallback getter, SetterCallback setter = 0, v8::Local< v8::Value > data = v8::Local<v8::Value>(), v8::AccessControl settings = v8::DEFAULT, v8::PropertyAttribute attribute = v8::None) [inline]
Definition at line 4014 of file nan.h.
void Nan::SetAccessor (v8::Local< v8::ObjectTemplate > tpl, v8::Local< v8::String > name, GetterCallback getter, SetterCallback setter = 0, v8::Local< v8::Value > data = v8::Local<v8::Value>(), v8::AccessControl settings = v8::DEFAULT, v8::PropertyAttribute attribute = v8::None, imp::Sig signature = imp::Sig()) [inline]
Definition at line 3970 of file nan.h.
NAN_INLINE void Nan::SetAddHistogramSampleFunction (v8::AddHistogramSampleCallback cb)
Definition at line 2307 of file nan.h.
NAN_INLINE void Nan::SetCounterFunction (v8::CounterLookupCallback cb)
Definition at line 2297 of file nan.h.
NAN_INLINE void Nan::SetCreateHistogramFunction (v8::CreateHistogramCallback cb)
Definition at line 2302 of file nan.h.
void Nan::SetIndexedPropertyHandler (v8::Local< v8::ObjectTemplate > tpl, IndexGetterCallback getter, IndexSetterCallback setter = 0, IndexQueryCallback query = 0, IndexDeleterCallback deleter = 0, IndexEnumeratorCallback enumerator = 0, v8::Local< v8::Value > data = v8::Local<v8::Value>()) [inline]
Definition at line 4126 of file nan.h.
NAN_INLINE void Nan::SetInstanceTemplate (v8::Local< v8::FunctionTemplate > templ, v8::Local< v8::String > name, v8::Local< v8::Data > value, v8::PropertyAttribute attributes)
Definition at line 3933 of file nan.h.
NAN_INLINE void Nan::SetInstanceTemplate (v8::Local< v8::FunctionTemplate > templ, const char * name, v8::Local< v8::Data > value)
Definition at line 3925 of file nan.h.
NAN_INLINE void Nan::SetInternalFieldPointer (v8::Local< v8::Object > object, int index, void * value)
Definition at line 2773 of file nan.h.
Referenced by CallbackBridge< T, L >::CallbackBridge(), Null::get_constructor(), Boolean::get_constructor(), SassValueWrapper< T >::get_js_object(), SassTypes::NAN_METHOD(), and ObjectWrap::Wrap().
NAN_INLINE void Nan::SetIsolateData (v8::Isolate * isolate, T * data) [inline]
Definition at line 2974 of file nan.h.
NAN_INLINE void Nan::SetMethod (const T & recv, const char * name, FunctionCallback callback) [inline]
Definition at line 3943 of file nan.h.
Referenced by NAN_MODULE_INIT().
void Nan::SetNamedPropertyHandler (v8::Local< v8::ObjectTemplate > tpl, PropertyGetterCallback getter, PropertySetterCallback setter = 0, PropertyQueryCallback query = 0, PropertyDeleterCallback deleter = 0, PropertyEnumeratorCallback enumerator = 0, v8::Local< v8::Value > data = v8::Local<v8::Value>()) [inline]
Definition at line 4056 of file nan.h.
NAN_INLINE Maybe<bool> Nan::SetPrototype (v8::Handle< v8::Object > obj, v8::Handle< v8::Value > prototype)
Definition at line 984 of file nan.h.
NAN_INLINE void Nan::SetPrototypeMethod (v8::Local< v8::FunctionTemplate > recv, const char * name, FunctionCallback callback)
Definition at line 3955 of file nan.h.
Referenced by String::initPrototype(), Number::initPrototype(), Map::initPrototype(), List::initPrototype(), and Color::initPrototype().
NAN_INLINE void Nan::SetPrototypeTemplate (v8::Local< v8::FunctionTemplate > templ, v8::Local< v8::String > name, v8::Local< v8::Data > value, v8::PropertyAttribute attributes)
Definition at line 3916 of file nan.h.
Referenced by Boolean::get_constructor(), and CallbackBridge< T, L >::get_wrapper_constructor().
NAN_INLINE void Nan::SetPrototypeTemplate (v8::Local< v8::FunctionTemplate > templ, const char * name, v8::Local< v8::Data > value)
Definition at line 3908 of file nan.h.
NAN_INLINE void Nan::SetTemplate (v8::Local< v8::Template > templ, v8::Local< v8::String > name, v8::Local< v8::Data > value, v8::PropertyAttribute attributes)
Definition at line 2755 of file nan.h.
NAN_INLINE void Nan::SetTemplate (v8::Local< v8::Template > templ, const char * name, v8::Local< v8::Data > value)
Definition at line 2748 of file nan.h.
Referenced by nauv_key_create(), and nauv_key_get().
NAN_INLINE void Nan::ThrowError (v8::Local< v8::Value > error)
Definition at line 2835 of file nan.h.
Referenced by SassTypes::NAN_METHOD().
NAN_INLINE imp::ToFactory<T>::return_t Nan::To (v8::Local< v8::Value > val) [inline]
Definition at line 1125 of file nan.h.
NAN_INLINE MaybeLocal<v8::Uint32> Nan::ToArrayIndex (v8::Handle< v8::Value > val)
Definition at line 878 of file nan.h.
NAN_INLINE MaybeLocal<v8::String> Nan::ToDetailString (v8::Handle< v8::Value > val)
Definition at line 873 of file nan.h.
NAN_INLINE v8::Local<v8::Boolean> Nan::True ()
Definition at line 2730 of file nan.h.
NAN_INLINE v8::Local<v8::Primitive> Nan::Undefined ()
Definition at line 2720 of file nan.h.
Referenced by SassTypes::NAN_METHOD(), and ReturnValue< v8::Array >::SetUndefined().
Variable Documentation
const int kInternalFieldsInWeakCallback = 2 [static]
Definition at line 4209 of file nan.h.
const int kNoInternalFieldIndex = -1 [static]
Definition at line 4210 of file nan.h.