Emeraldion Lodge (codename Zelda): Sass::UTF_8 Namespace Reference
Sass::UTF_8 Namespace Reference
Functions
size_t code_point_count (const string &str, size_t start, size_t end)
size_t code_point_count (const string &str)
size_t offset_at_position (const string &str, size_t position)
size_t code_point_size_at_offset (const string &str, size_t offset)
size_t normalize_index (int index, size_t len)
string convert_from_utf16 (const wstring &utf16)
wstring convert_to_utf16 (const string &utf8)
Function Documentation
size_t code_point_count (const string & str)
Definition at line 22 of file utf8_string.cpp.
References utf8::unchecked::distance().
Referenced by Sass::Functions::BUILT_IN().
size_t code_point_count (const string & str, size_t start, size_t end)
Definition at line 18 of file utf8_string.cpp.
References utf8::unchecked::distance().
Referenced by convert_to_utf16().
size_t code_point_size_at_offset (const string & str, size_t offset)
Definition at line 34 of file utf8_string.cpp.
References utf8::unchecked::advance().
string Sass::UTF_8::convert_from_utf16 (const wstring & utf16)
Definition at line 75 of file utf8_string.cpp.
References utf8::unchecked::utf16to8().
Referenced by Plugins::load_plugins().
wstring Sass::UTF_8::convert_to_utf16 (const string & utf8)
Definition at line 86 of file utf8_string.cpp.
References code_point_count(), and utf8::unchecked::utf8to16().
Referenced by Sass::File::file_exists(), Plugins::load_plugins(), and Sass::File::read_file().
size_t normalize_index (int index, size_t len)
Definition at line 46 of file utf8_string.cpp.
size_t offset_at_position (const string & str, size_t position)
Definition at line 27 of file utf8_string.cpp.
References utf8::unchecked::advance(), and utf8::unchecked::distance().
Referenced by Sass::Functions::BUILT_IN().