Emeraldion Lodge (codename Zelda): Factory Class Reference
Factory Class Reference
#include <factory.h>
Static Public Member Functions
static NAN_MODULE_INIT (initExports)
static Value * create (Sass_Value *)
static Value * unwrap (v8::Local< v8::Value >)
Detailed Description
Definition at line 12 of file factory.h.
Member Function Documentation
SassTypes::Value * create (Sass_Value * v) [static]
Definition at line 15 of file factory.cpp.
References Null::get_singleton(), Boolean::get_singleton(), SASS_BOOLEAN, sass_boolean_get_value(), SASS_COLOR, SASS_ERROR, SASS_LIST, sass_make_error(), SASS_MAP, SASS_NULL, SASS_NUMBER, SASS_STRING, and sass_value_get_tag().
Referenced by SassTypes::NAN_METHOD().
static NAN_MODULE_INIT (initExports) [static]
Value * unwrap (v8::Local< v8::Value > obj) [static]
Definition at line 63 of file factory.cpp.
References Nan::GetInternalFieldPointer().
Referenced by SassTypes::NAN_METHOD(), and CustomFunctionBridge::post_process_return_value().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/factory.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/factory.cpp