Emeraldion Lodge (codename Zelda): Nan::imp Namespace Reference
Nan::imp Namespace Reference
Data Structures
class ReturnValueImp
struct ToFactoryBase
struct ValueFactoryBase
struct FactoryBase
struct MaybeFactoryBase
struct Factory< v8::Array >
struct Factory< v8::Boolean >
struct Factory< v8::BooleanObject >
struct Factory< v8::Context >
struct Factory< v8::Date >
struct Factory< v8::External >
struct Factory< v8::Function >
struct Factory< v8::FunctionTemplate >
struct Factory< v8::Number >
struct Factory< v8::NumberObject >
struct IntegerFactory
struct Factory< v8::Integer >
struct Factory< v8::Int32 >
struct Factory< v8::Uint32 >
struct Factory< v8::Object >
struct Factory< v8::ObjectTemplate >
struct Factory< v8::RegExp >
struct Factory< v8::Script >
struct Factory< v8::Signature >
struct Factory< v8::String >
struct Factory< v8::StringObject >
Typedefs
typedef v8::Local
< v8::AccessorSignature > Sig
typedef v8::Handle< v8::Value >(* NativeFunction)(const v8::Arguments &)
typedef v8::Handle< v8::Value >(* NativeGetter)(v8::Local< v8::String >, const v8::AccessorInfo &)
typedef void(* NativeSetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::AccessorInfo &)
typedef v8::Handle< v8::Value >(* NativePropertyGetter)(v8::Local< v8::String >, const v8::AccessorInfo &)
typedef v8::Handle< v8::Value >(* NativePropertySetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::AccessorInfo &)
typedef v8::Handle< v8::Array >(* NativePropertyEnumerator)(const v8::AccessorInfo &)
typedef v8::Handle< v8::Integer >(* NativePropertyQuery)(v8::Local< v8::String >, const v8::AccessorInfo &)
typedef v8::Handle< v8::Value >(* NativeIndexGetter)(uint32_t, const v8::AccessorInfo &)
typedef v8::Handle< v8::Value >(* NativeIndexSetter)(uint32_t, v8::Local< v8::Value >, const v8::AccessorInfo &)
typedef v8::Handle< v8::Array >(* NativeIndexEnumerator)(const v8::AccessorInfo &)
typedef v8::Handle< v8::Boolean >(* NativeIndexDeleter)(uint32_t, const v8::AccessorInfo &)
typedef v8::Handle< v8::Integer >(* NativeIndexQuery)(uint32_t, const v8::AccessorInfo &)
Functions
static v8::Handle< v8::Value > FunctionCallbackWrapper (const v8::Arguments &args)
static v8::Handle< v8::Value > GetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo &info)
static void SetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > PropertyGetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > PropertySetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo &info)
static v8::Handle< v8::Array > PropertyEnumeratorCallbackWrapper (const v8::AccessorInfo &info)
static v8::Handle< v8::Boolean > PropertyDeleterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > IndexGetterCallbackWrapper (uint32_t index, const v8::AccessorInfo &info)
static v8::Handle< v8::Value > IndexSetterCallbackWrapper (uint32_t index, v8::Local< v8::Value > value, const v8::AccessorInfo &info)
static v8::Handle< v8::Array > IndexEnumeratorCallbackWrapper (const v8::AccessorInfo &info)
static v8::Handle< v8::Boolean > IndexDeleterCallbackWrapper (uint32_t index, const v8::AccessorInfo &info)
static v8::Handle< v8::Integer > IndexQueryCallbackWrapper (uint32_t index, const v8::AccessorInfo &info)
template<typename T >
v8::Local< T > To (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Integer > To< v8::Integer > (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Int32 > To< v8::Int32 > (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Uint32 > To< v8::Uint32 > (v8::Local< v8::Integer > i)
NAN_INLINE void widenString (std::vector< uint16_t > *ws, const uint8_t *s, int l)
ExternalOneByteStringResource
const * GetExternalResource (v8::Local< v8::String > str)
bool IsExternal (v8::Local< v8::String > str)
static bool contains_non_ascii_slow (const char *buf, size_t len)
static bool contains_non_ascii (const char *src, size_t len)
static void force_ascii_slow (const char *src, char *dst, size_t len)
static void force_ascii (const char *src, char *dst, size_t len)
static size_t base64_encode (const char *src, size_t slen, char *dst, size_t dlen)
static size_t hex_encode (const char *src, size_t slen, char *dst, size_t dlen)
static Local< Value > Encode (const char *buf, size_t buflen, enum Encoding encoding)
Variables
static const int kDataIndex = 0
static const int kFunctionIndex = 1
static const int kFunctionFieldCount = 2
static const int kGetterIndex = 1
static const int kSetterIndex = 2
static const int kAccessorFieldCount = 3
static const int kPropertyGetterIndex = 1
static const int kPropertySetterIndex = 2
static const int kPropertyEnumeratorIndex = 3
static const int kPropertyDeleterIndex = 4
static const int kPropertyQueryIndex = 5
static const int kPropertyFieldCount = 6
static const int kIndexPropertyGetterIndex = 1
static const int kIndexPropertySetterIndex = 2
static const int kIndexPropertyEnumeratorIndex = 3
static const int kIndexPropertyDeleterIndex = 4
static const int kIndexPropertyQueryIndex = 5
static const int kIndexPropertyFieldCount = 6
static const size_t kMaxLength = 0x3fffffff
static const unsigned kReplaceInvalidUtf8 = 0
Typedef Documentation
typedef v8::Handle<v8::Value>(* NativeFunction)(const v8::Arguments &)
Definition at line 516 of file nan.h.
typedef v8::Handle<v8::Value>(* NativeGetter)(v8::Local< v8::String >, const v8::AccessorInfo &)
Definition at line 532 of file nan.h.
typedef v8::Handle<v8::Boolean>(* NativeIndexDeleter)(uint32_t, const v8::AccessorInfo &)
Definition at line 707 of file nan.h.
typedef v8::Handle<v8::Array>(* NativeIndexEnumerator)(const v8::AccessorInfo &)
Definition at line 690 of file nan.h.
typedef v8::Handle<v8::Value>(* NativeIndexGetter)(uint32_t, const v8::AccessorInfo &)
Definition at line 654 of file nan.h.
typedef v8::Handle<v8::Integer>(* NativeIndexQuery)(uint32_t, const v8::AccessorInfo &)
Definition at line 724 of file nan.h.
typedef v8::Handle<v8::Value>(* NativeIndexSetter)(uint32_t, v8::Local< v8::Value >, const v8::AccessorInfo &)
Definition at line 673 of file nan.h.
typedef v8::Handle<v8::Array>(* NativePropertyEnumerator)(const v8::AccessorInfo &)
Definition at line 602 of file nan.h.
typedef v8::Handle<v8::Value>(* NativePropertyGetter)(v8::Local< v8::String >, const v8::AccessorInfo &)
Definition at line 566 of file nan.h.
typedef v8::Handle<v8::Integer>(* NativePropertyQuery)(v8::Local< v8::String >, const v8::AccessorInfo &)
Definition at line 637 of file nan.h.
typedef v8::Handle<v8::Value>(* NativePropertySetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::AccessorInfo &)
Definition at line 585 of file nan.h.
typedef void(* NativeSetter)(v8::Local< v8::String >, v8::Local< v8::Value >, const v8::AccessorInfo &)
Definition at line 549 of file nan.h.
typedef v8::Local<v8::AccessorSignature> Sig
Definition at line 192 of file nan.h.
Function Documentation
static size_t Nan::imp::base64_encode (const char * src, size_t slen, char * dst, size_t dlen) [static]
Definition at line 3667 of file nan.h.
static bool Nan::imp::contains_non_ascii (const char * src, size_t len) [static]
Definition at line 3576 of file nan.h.
static bool Nan::imp::contains_non_ascii_slow (const char * buf, size_t len) [static]
Definition at line 3568 of file nan.h.
static Local<Value> Nan::imp::Encode (const char * buf, size_t buflen, enum Encoding encoding) [static]
Definition at line 3749 of file nan.h.
static void Nan::imp::force_ascii (const char * src, char * dst, size_t len) [static]
Definition at line 3622 of file nan.h.
static void Nan::imp::force_ascii_slow (const char * src, char * dst, size_t len) [static]
Definition at line 3615 of file nan.h.
static v8::Handle<v8::Value> Nan::imp::FunctionCallbackWrapper (const v8::Arguments & args) [static]
Definition at line 505 of file nan.h.
ExternalOneByteStringResource const* Nan::imp::GetExternalResource (v8::Local< v8::String > str) [inline]
Definition at line 3503 of file nan.h.
static v8::Handle<v8::Value> Nan::imp::GetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo & info) [static]
Definition at line 519 of file nan.h.
static size_t Nan::imp::hex_encode (const char * src, size_t slen, char * dst, size_t dlen) [static]
Definition at line 3731 of file nan.h.
static v8::Handle<v8::Boolean> Nan::imp::IndexDeleterCallbackWrapper (uint32_t index, const v8::AccessorInfo & info) [static]
Definition at line 693 of file nan.h.
static v8::Handle<v8::Array> Nan::imp::IndexEnumeratorCallbackWrapper (const v8::AccessorInfo & info) [static]
Definition at line 676 of file nan.h.
References kMaxLength, and Nan::New().
static v8::Handle<v8::Value> Nan::imp::IndexGetterCallbackWrapper (uint32_t index, const v8::AccessorInfo & info) [static]
Definition at line 640 of file nan.h.
static v8::Handle<v8::Integer> Nan::imp::IndexQueryCallbackWrapper (uint32_t index, const v8::AccessorInfo & info) [static]
Definition at line 710 of file nan.h.
static v8::Handle<v8::Value> Nan::imp::IndexSetterCallbackWrapper (uint32_t index, v8::Local< v8::Value > value, const v8::AccessorInfo & info) [static]
Definition at line 657 of file nan.h.
References kMaxLength, and Nan::New().
bool Nan::imp::IsExternal (v8::Local< v8::String > str) [inline]
Definition at line 3513 of file nan.h.
static v8::Handle<v8::Boolean> Nan::imp::PropertyDeleterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo & info) [static]
Definition at line 605 of file nan.h.
static v8::Handle<v8::Array> Nan::imp::PropertyEnumeratorCallbackWrapper (const v8::AccessorInfo & info) [static]
Definition at line 588 of file nan.h.
static v8::Handle<v8::Value> Nan::imp::PropertyGetterCallbackWrapper (v8::Local< v8::String > property, const v8::AccessorInfo & info) [static]
Definition at line 552 of file nan.h.
static v8::Handle<v8::Value> Nan::imp::PropertySetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo & info) [static]
Definition at line 569 of file nan.h.
static void Nan::imp::SetterCallbackWrapper (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::AccessorInfo & info) [static]
Definition at line 535 of file nan.h.
References EscapableHandleScope::Escape(), Nan::False(), and Nan::New().
v8::Local<T> Nan::imp::To (v8::Local< v8::Integer > i) [inline]
v8::Local<v8::Int32> Nan::imp::To< v8::Int32 > (v8::Local< v8::Integer > i) [inline]
v8::Local<v8::Integer> Nan::imp::To< v8::Integer > (v8::Local< v8::Integer > i) [inline]
v8::Local<v8::Uint32> Nan::imp::To< v8::Uint32 > (v8::Local< v8::Integer > i) [inline]
NAN_INLINE void Nan::imp::widenString (std::vector< uint16_t > * ws, const uint8_t * s, int l)
Definition at line 2898 of file nan.h.
Variable Documentation
const int kAccessorFieldCount = 3 [static]
Definition at line 201 of file nan.h.
const int kDataIndex = 0 [static]
Definition at line 194 of file nan.h.
Referenced by PersistentBase< v8::Function >::Reset().
const int kFunctionFieldCount = 2 [static]
Definition at line 197 of file nan.h.
const int kFunctionIndex = 1 [static]
Definition at line 196 of file nan.h.
const int kGetterIndex = 1 [static]
Definition at line 199 of file nan.h.
const int kIndexPropertyDeleterIndex = 4 [static]
Definition at line 213 of file nan.h.
const int kIndexPropertyEnumeratorIndex = 3 [static]
Definition at line 212 of file nan.h.
Referenced by Persistent< v8::Object >::operator*().
const int kIndexPropertyFieldCount = 6 [static]
Definition at line 215 of file nan.h.
const int kIndexPropertyGetterIndex = 1 [static]
Definition at line 210 of file nan.h.
const int kIndexPropertyQueryIndex = 5 [static]
Definition at line 214 of file nan.h.
const int kIndexPropertySetterIndex = 2 [static]
Definition at line 211 of file nan.h.
const size_t kMaxLength = 0x3fffffff [static]
Definition at line 2125 of file nan.h.
Referenced by Nan::CallAsConstructor(), imp::Encode(), IndexEnumeratorCallbackWrapper(), IndexSetterCallbackWrapper(), and ReturnValue< v8::Array >::SetEmptyString().
const int kPropertyDeleterIndex = 4 [static]
Definition at line 206 of file nan.h.
const int kPropertyEnumeratorIndex = 3 [static]
Definition at line 205 of file nan.h.
const int kPropertyFieldCount = 6 [static]
Definition at line 208 of file nan.h.
const int kPropertyGetterIndex = 1 [static]
Definition at line 203 of file nan.h.
const int kPropertyQueryIndex = 5 [static]
Definition at line 207 of file nan.h.
const int kPropertySetterIndex = 2 [static]
Definition at line 204 of file nan.h.
Referenced by PersistentBase< v8::Function >::operator!=().
const unsigned kReplaceInvalidUtf8 = 0 [static]
Definition at line 2134 of file nan.h.
const int kSetterIndex = 2 [static]
Definition at line 200 of file nan.h.