Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_subset_map.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_subset_map.cpp File Reference
#include <string>
#include <iostream>
#include <assert.h>
#include "../subset_map.hpp"
Functions
string toString (vector< string > v)
string toString (vector< pair< string, vector< string >>> v)
void assertEqual (string sExpected, string sResult)
void setup ()
void testEqualKeys ()
void testSubsetKeys ()
void testSupersetKeys ()
void testDisjointKeys ()
void testSemiDisjointKeys ()
void testEmptyKeySet ()
void testEmptyKeyGet ()
void testMultipleSubsets ()
void testBracketBracket ()
void testKeyOrder ()
void testOrderPreserved ()
void testMultipleEqualValues ()
int main ()
Variables
Subset_Map< string, string > ssm
Function Documentation
void assertEqual (string sExpected, string sResult)
Definition at line 468 of file test_subset_map.cpp.
Referenced by testBracketBracket(), testDisjointKeys(), testEmptyKeyGet(), testEmptyKeySet(), testEqualKeys(), testKeyOrder(), testMultipleEqualValues(), testMultipleSubsets(), testOrderPreserved(), testSemiDisjointKeys(), testSubsetKeys(), and testSupersetKeys().
int main ()
Definition at line 346 of file test_subset_map.cpp.
References setup(), ssm, testBracketBracket(), testDisjointKeys(), testEmptyKeyGet(), testEmptyKeySet(), testEqualKeys(), testKeyOrder(), testMultipleEqualValues(), testMultipleSubsets(), testOrderPreserved(), testSemiDisjointKeys(), testSubsetKeys(), and testSupersetKeys().
void setup ()
Definition at line 12 of file test_subset_map.cpp.
References ssm.
Referenced by main().
void testBracketBracket ()
Definition at line 224 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testDisjointKeys ()
Definition at line 118 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testEmptyKeyGet ()
Definition at line 179 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testEmptyKeySet ()
Definition at line 166 of file test_subset_map.cpp.
References assertEqual(), and ssm.
Referenced by main().
void testEqualKeys ()
Definition at line 54 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testKeyOrder ()
Definition at line 244 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testMultipleEqualValues ()
Definition at line 308 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testMultipleSubsets ()
Definition at line 188 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testOrderPreserved ()
Definition at line 256 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testSemiDisjointKeys ()
Definition at line 142 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testSubsetKeys ()
Definition at line 72 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
void testSupersetKeys ()
Definition at line 92 of file test_subset_map.cpp.
References assertEqual(), ssm, and toString().
Referenced by main().
string toString (vector< pair< string, vector< string >>> v)
Definition at line 432 of file test_subset_map.cpp.
string toString (vector< string > v)
Definition at line 454 of file test_subset_map.cpp.
Referenced by Contextualize_Eval::operator()(), testBracketBracket(), testDisjointKeys(), testEmptyKeyGet(), testEqualKeys(), testKeyOrder(), testMultipleEqualValues(), testMultipleSubsets(), testOrderPreserved(), testSemiDisjointKeys(), testSubsetKeys(), and testSupersetKeys().
Variable Documentation
Subset_Map<string, string> ssm
Definition at line 6 of file test_subset_map.cpp.
Referenced by main(), setup(), testBracketBracket(), testDisjointKeys(), testEmptyKeyGet(), testEmptyKeySet(), testEqualKeys(), testKeyOrder(), testMultipleEqualValues(), testMultipleSubsets(), testOrderPreserved(), testSemiDisjointKeys(), testSubsetKeys(), and testSupersetKeys().