Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/debugger.hpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/debugger.hpp File Reference
#include <string>
#include <sstream>
#include "ast_fwd_decl.hpp"
Functions
string str_replace (std::string str, const std::string &oldStr, const std::string &newStr)
string prettyprint (const string &str)
string longToHex (long long t)
string pstate_source_position (AST_Node *node)
void debug_ast (AST_Node *node, string ind="", Env *env=0)
Function Documentation
void debug_ast (AST_Node * node, string ind = "", Env * env = 0) [inline]
Definition at line 46 of file debugger.hpp.
References Statement::block(), COMMA, Vectorized< T >::elements(), Nan::HEX, longToHex(), Sass::Prelexer::name(), NONE, prettyprint(), pstate_source_position(), selector(), Complex_Selector::specificity(), and Expression::type().
string longToHex (long long t) [inline]
Definition at line 29 of file debugger.hpp.
References Sass::Prelexer::hex().
Referenced by debug_ast().
string prettyprint (const string & str) [inline]
Definition at line 22 of file debugger.hpp.
References str_replace().
Referenced by debug_ast().
string pstate_source_position (AST_Node * node) [inline]
Definition at line 35 of file debugger.hpp.
References npos.
Referenced by debug_ast().
string str_replace (std::string str, const std::string & oldStr, const std::string & newStr) [inline]
Definition at line 11 of file debugger.hpp.
References npos.
Referenced by Markdown_Parser::_doAnchors_inline_callback(), Markdown_Parser::_doImages_inline_callback(), Markdown_Parser::_doImages_reference_callback(), Markdown_Parser::_stripLinkDefinitions_callback(), Geoip::by_ip_addr(), Markdown_Parser::encodeAmpsAndAngles(), Markdown_Parser::hashHTMLBlocks(), AboutController::joke(), pluralize(), MysqlAdapter::prepare(), prettyprint(), and Wikipedia::wikize().