Emeraldion Lodge (codename Zelda): CallbackBridge< T, L > Class Template Reference
CallbackBridge< T, L > Class Template Reference
#include <callback_bridge.h>
Public Member Functions
CallbackBridge (v8::Local< v8::Function >, bool)
virtual ~CallbackBridge ()
T operator() (std::vector< void * >)
Protected Member Functions
virtual T post_process_return_value (v8::Local< v8::Value >) const =0
Static Protected Member Functions
static Nan::MaybeLocal
< v8::Function > get_wrapper_constructor ()
static void async_gone (uv_handle_t *handle)
static NAN_METHOD (New)
static NAN_METHOD (ReturnCallback)
static void dispatched_async_uv_callback (uv_async_t *)
Protected Attributes
Nan::Persistent< v8::Object > wrapper
Static Protected Attributes
static Nan::Persistent
< v8::Function > wrapper_constructor
Detailed Description
template<typename T, typename L = void*>
class CallbackBridge< T, L >
Definition at line 12 of file callback_bridge.h.
Constructor & Destructor Documentation
CallbackBridge (v8::Local< v8::Function > callback, bool is_sync) [inline]
Definition at line 57 of file callback_bridge.h.
References CallbackBridge< T, L >::dispatched_async_uv_callback(), CallbackBridge< T, L >::get_wrapper_constructor(), Nan::New(), Nan::NewInstance(), PersistentBase< T >::Reset(), Nan::SetInternalFieldPointer(), and CallbackBridge< T, L >::wrapper.
~CallbackBridge () [inline, virtual]
Definition at line 77 of file callback_bridge.h.
References CallbackBridge< T, L >::async_gone(), PersistentBase< T >::Reset(), and CallbackBridge< T, L >::wrapper.
Member Function Documentation
void async_gone (uv_handle_t * handle) [inline, static, protected]
Definition at line 221 of file callback_bridge.h.
Referenced by CallbackBridge< T, L >::~CallbackBridge().
void dispatched_async_uv_callback (uv_async_t * req) [inline, static, protected]
Definition at line 141 of file callback_bridge.h.
References Nan::FatalException(), TryCatch::HasCaught(), Nan::New(), and CallbackBridge< T, L >::wrapper.
Referenced by CallbackBridge< T, L >::CallbackBridge().
Nan::MaybeLocal< v8::Function > get_wrapper_constructor () [inline, static, protected]
Definition at line 198 of file callback_bridge.h.
References Nan::GetFunction(), PersistentBase< T >::IsEmpty(), Nan::New(), New(), PersistentBase< T >::Reset(), Nan::SetPrototypeTemplate(), and CallbackBridge< T, L >::wrapper_constructor.
Referenced by CallbackBridge< T, L >::CallbackBridge().
static NAN_METHOD (ReturnCallback) [static, protected]
static NAN_METHOD (New) [static, protected]
T operator() (std::vector< void * > argv) [inline]
Definition at line 89 of file callback_bridge.h.
References Nan::FatalException(), TryCatch::HasCaught(), Nan::New(), CallbackBridge< T, L >::post_process_return_value(), and CallbackBridge< T, L >::wrapper.
virtual T post_process_return_value (v8::Local< v8::Value >) const [protected, pure virtual]
Implemented in CustomFunctionBridge, and CustomImporterBridge.
Referenced by NAN_METHOD(), and CallbackBridge< T, L >::operator()().
Field Documentation
Nan::Persistent<v8::Object> wrapper [protected]
Definition at line 28 of file callback_bridge.h.
Referenced by CallbackBridge< T, L >::CallbackBridge(), CallbackBridge< T, L >::dispatched_async_uv_callback(), CallbackBridge< T, L >::operator()(), and CallbackBridge< T, L >::~CallbackBridge().
Nan::Persistent< v8::Function > wrapper_constructor [inline, static, protected]
Definition at line 27 of file callback_bridge.h.
Referenced by CallbackBridge< T, L >::get_wrapper_constructor().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/callback_bridge.h