Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_unification.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/test/test_unification.cpp File Reference
#include "../ast.hpp"
#include "../context.hpp"
#include "../parser.hpp"
#include "../to_string.hpp"
#include <string>
Functions
Compound_Selector * selector (string src)
void unify (string lhs, string rhs)
int main ()
Variables
Context ctx = Context(Context::Data())
To_String to_string
Function Documentation
int main ()
Definition at line 21 of file test_unification.cpp.
References unify().
Compound_Selector* selector (string src)
Definition at line 12 of file test_unification.cpp.
void unify (string lhs, string rhs)
Definition at line 15 of file test_unification.cpp.
References selector(), and Compound_Selector::unify_with().
Referenced by main().
Variable Documentation
Context ctx = Context(Context::Data())
Definition at line 9 of file test_unification.cpp.
To_String to_string
Definition at line 10 of file test_unification.cpp.