Emeraldion Lodge (codename Zelda): Sass::Util Namespace Reference
Sass::Util Namespace Reference
Functions
string normalize_underscores (const string &str)
string normalize_decimals (const string &str)
string normalize_sixtuplet (const string &col)
bool isPrintable (Ruleset *r, Output_Style style)
bool isPrintable (String_Constant *s, Output_Style style)
bool isPrintable (String_Quoted *s, Output_Style style)
bool isPrintable (Declaration *d, Output_Style style)
bool isPrintable (Expression *e, Output_Style style)
bool isPrintable (Feature_Block *f, Output_Style style)
bool isPrintable (Media_Block *m, Output_Style style)
bool isPrintable (Block *b, Output_Style style)
string vecJoin (const vector< string > &vec, const string &sep)
bool isAscii (const char chr)
bool containsAnyPrintableStatements (Block *b)
Function Documentation
bool Sass::Util::containsAnyPrintableStatements (Block * b)
bool isAscii (const char chr)
Definition at line 699 of file util.cpp.
Referenced by Sass::Functions::BUILT_IN().
bool isPrintable (Block * b, Output_Style style)
Definition at line 642 of file util.cpp.
References isPrintable(), and Vectorized< T >::length().
bool isPrintable (Media_Block * m, Output_Style style)
Definition at line 605 of file util.cpp.
References Statement::block(), Statement::is_hoistable(), isPrintable(), and Vectorized< T >::length().
bool isPrintable (Feature_Block * f, Output_Style style)
Definition at line 568 of file util.cpp.
References Statement::block(), Statement::is_hoistable(), isPrintable(), and Vectorized< T >::length().
bool isPrintable (Expression * e, Output_Style style)
Definition at line 564 of file util.cpp.
References isPrintable().
bool isPrintable (Declaration * d, Output_Style style)
Definition at line 556 of file util.cpp.
References isPrintable().
bool isPrintable (String_Quoted * s, Output_Style style)
Definition at line 551 of file util.cpp.
bool isPrintable (String_Constant * s, Output_Style style)
Definition at line 546 of file util.cpp.
bool isPrintable (Ruleset * r, Output_Style style)
Definition at line 504 of file util.cpp.
References Block::block(), Statement::block(), Sass::COMPRESSED, and Vectorized< T >::length().
Referenced by isPrintable(), and Output::operator()().
string normalize_decimals (const string & str)
Definition at line 481 of file util.cpp.
Referenced by Parser::parse_ie_keyword_arg().
string normalize_sixtuplet (const string & col)
Definition at line 490 of file util.cpp.
Referenced by Sass::op_number_color().
string normalize_underscores (const string & str)
Definition at line 471 of file util.cpp.
Referenced by Sass::Functions::BUILT_IN(), Sass::make_c_function(), Sass::make_native_function(), Eval::operator()(), Parser::parse_argument(), Parser::parse_assignment(), Parser::parse_definition(), Parser::parse_each_directive(), Parser::parse_for_directive(), Parser::parse_ie_keyword_arg(), Parser::parse_mixin_call(), Parser::parse_parameter(), Parser::parse_value(), and Parser::parse_value_schema().
string vecJoin (const vector< string > & vec, const string & sep)
Definition at line 681 of file util.cpp.