Emeraldion Lodge (codename Zelda): Host Class Reference
Host Class Reference
Helper object for representing network hosts.
Static Public Member Functions
static by_ip_addr ($ip_addr, $params=NULL)
Creates a Host object for the given IP address.
Data Fields
$ip_addr
The IP address of the host.
$real_ip_addr
The real IP address of the host.
$hostname
The name of the host.
Static Private Member Functions
static real_ip_addr_from_params ($ip_addr, $params=NULL)
Obtains the real IP address using server parameters as a backup.
static lookup_host_and_cache ($ip_addr)
Obtains the hostname for the given IP address.
Detailed Description
Helper object for representing network hosts.
Definition at line 9 of file host.php.
Member Function Documentation
by_ip_addr ($ip_addr, $params = NULL) static
Creates a Host object for the given IP address.
Parameters
ip_addr The IP address.
params Parameters to initialize the receiver.
Definition at line 36 of file host.php.
References $ip_addr.
Referenced by MetaController\hits_by_host_list().
lookup_host_and_cache ($ip_addr) static private
Obtains the hostname for the given IP address.
Parameters
ip_addr The IP address.
Definition at line 84 of file host.php.
References $conn, $hostname, $ip_addr, Db\close_connection(), and Db\get_connection().
real_ip_addr_from_params ($ip_addr, $params = NULL) static private
Obtains the real IP address using server parameters as a backup.
If the IP address is private, server parameters are used to obtain the real public IP address.
Parameters
ip_addr The IP address.
params Parameters to initialize the receiver.
Definition at line 54 of file host.php.
References $ip_addr.
Field Documentation
$hostname
The name of the host.
hostname
Definition at line 28 of file host.php.
Referenced by lookup_host_and_cache().
$ip_addr
The IP address of the host.
ip_addr
Definition at line 15 of file host.php.
Referenced by by_ip_addr(), Geoip\by_ip_addr(), lookup_host_and_cache(), and real_ip_addr_from_params().
$real_ip_addr
The real IP address of the host.
real_ip_addr
This variable contains the real IP address as inferred by the server parameters.
Definition at line 22 of file host.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/host.php