Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/binding.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/binding.cpp File Reference
#include <nan.h>
#include <vector>
#include "sass_context_wrapper.h"
#include "custom_function_bridge.h"
#include "create_string.h"
#include "sass_types/factory.h"
Functions
Sass_Import_List sass_importer (const char *cur_path, Sass_Importer_Entry cb, struct Sass_Compiler *comp)
union Sass_Value * sass_custom_function (const union Sass_Value *s_args, Sass_Function_Entry cb, struct Sass_Options *opts)
int ExtractOptions (v8::Local< v8::Object > options, void *cptr, sass_context_wrapper *ctx_w, bool is_file, bool is_sync)
void GetStats (sass_context_wrapper *ctx_w, Sass_Context *ctx)
int GetResult (sass_context_wrapper *ctx_w, Sass_Context *ctx, bool is_sync=false)
void MakeCallback (uv_work_t *req)
NAN_METHOD (render)
NAN_METHOD (render_sync)
NAN_METHOD (render_file)
NAN_METHOD (render_file_sync)
NAN_METHOD (libsass_version)
NAN_MODULE_INIT (RegisterModule)
NODE_MODULE (binding, RegisterModule)
Function Documentation
int ExtractOptions (v8::Local< v8::Object > options, void * cptr, sass_context_wrapper * ctx_w, bool is_file, bool is_sync)
Definition at line 35 of file binding.cpp.
References Sass_Options::c_importers, create_string(), ctx, sass_context_wrapper::dctx, sass_context_wrapper::error_callback, sass_context_wrapper::fctx, sass_context_wrapper::file, sass_context_wrapper::function_bridges, Nan::Get(), Nan::GetOwnPropertyNames(), sass_context_wrapper::importer_bridges, sass_context_wrapper::include_path, sass_context_wrapper::indent, sass_context_wrapper::is_sync, sass_context_wrapper::linefeed, Nan::New(), sass_context_wrapper::out_file, sass_context_wrapper::request, PersistentBase< T >::Reset(), sass_context_wrapper::result, sass_context_get_options(), sass_custom_function(), sass_data_context_get_context(), sass_file_context_get_context(), sass_function_set_list_entry(), sass_importer(), sass_make_function(), sass_make_function_list(), sass_make_importer(), sass_make_importer_list(), sass_option_set_c_functions(), sass_option_set_c_importers(), sass_option_set_include_path(), sass_option_set_indent(), sass_option_set_input_path(), sass_option_set_is_indented_syntax_src(), sass_option_set_linefeed(), sass_option_set_omit_source_map_url(), sass_option_set_output_path(), sass_option_set_output_style(), sass_option_set_precision(), sass_option_set_source_comments(), sass_option_set_source_map_contents(), sass_option_set_source_map_embed(), sass_option_set_source_map_file(), sass_option_set_source_map_root(), sass_context_wrapper::source_map, sass_context_wrapper::source_map_root, and sass_context_wrapper::success_callback.
Referenced by NAN_METHOD().
int GetResult (sass_context_wrapper * ctx_w, Sass_Context * ctx, bool is_sync = false)
Definition at line 200 of file binding.cpp.
References Nan::CopyBuffer(), GetStats(), Nan::New(), sass_context_wrapper::result, sass_context_get_error_json(), sass_context_get_error_status(), sass_context_get_output_string(), sass_context_get_source_map_string(), and Nan::Set().
Referenced by MakeCallback(), and NAN_METHOD().
void GetStats (sass_context_wrapper * ctx_w, Sass_Context * ctx)
Definition at line 170 of file binding.cpp.
References Nan::Get(), Nan::New(), sass_context_wrapper::result, sass_context_get_included_files(), and Nan::Set().
Referenced by GetResult().
void MakeCallback (uv_work_t * req)
Definition at line 228 of file binding.cpp.
References Callback::Call(), ctx, sass_context_wrapper::dctx, sass_context_wrapper::error_callback, Nan::FatalException(), sass_context_wrapper::fctx, GetResult(), TryCatch::HasCaught(), sass_context_get_error_json(), sass_data_context_get_context(), sass_file_context_get_context(), sass_free_context_wrapper(), and sass_context_wrapper::success_callback.
Referenced by NAN_METHOD(), and MaybeLocal< T >::ToLocalChecked().
NAN_METHOD (libsass_version)
Definition at line 330 of file binding.cpp.
References libsass_version().
NAN_METHOD (render_file_sync)
Definition at line 310 of file binding.cpp.
References compile_file(), create_string(), ctx, ExtractOptions(), Nan::Get(), GetResult(), Sass_Options::input_path, Nan::New(), sass_file_context_get_context(), sass_free_context_wrapper(), sass_make_context_wrapper(), and sass_make_file_context().
NAN_METHOD (render_file)
Definition at line 296 of file binding.cpp.
References compile_it(), create_string(), ExtractOptions(), Nan::Get(), Sass_Options::input_path, MakeCallback(), Nan::New(), sass_context_wrapper::request, sass_make_context_wrapper(), and sass_make_file_context().
NAN_METHOD (render_sync)
Definition at line 278 of file binding.cpp.
References compile_data(), create_string(), ctx, ExtractOptions(), Nan::Get(), GetResult(), Nan::New(), sass_data_context_get_context(), sass_free_context_wrapper(), sass_make_context_wrapper(), sass_make_data_context(), and Sass_Data_Context::source_string.
NAN_METHOD (render)
Definition at line 263 of file binding.cpp.
References compile_it(), create_string(), ExtractOptions(), Nan::Get(), MakeCallback(), Nan::New(), sass_context_wrapper::request, sass_make_context_wrapper(), and sass_make_data_context().
NAN_MODULE_INIT (RegisterModule)
Definition at line 334 of file binding.cpp.
References libsass_version(), and Nan::SetMethod().
NODE_MODULE (binding , RegisterModule)
union Sass_Value* sass_custom_function (const union Sass_Value * s_args, Sass_Function_Entry cb, struct Sass_Options * opts) [write]
Definition at line 22 of file binding.cpp.
References l(), sass_function_get_cookie(), sass_list_get_length(), and sass_list_get_value().
Referenced by ExtractOptions().
Sass_Import_List sass_importer (const char * cur_path, Sass_Importer_Entry cb, struct Sass_Compiler * comp)
Definition at line 8 of file binding.cpp.
References utf8::unchecked::previous(), sass_compiler_get_last_import(), sass_import_get_path(), and sass_importer_get_cookie().
Referenced by ExtractOptions().