Emeraldion Lodge (codename Zelda): Node Class Reference
Node Class Reference
#include <node.hpp>
Public Types
enum TYPE { SELECTOR, COMBINATOR, COLLECTION, NIL }
Public Member Functions
TYPE type () const
bool isCombinator () const
bool isSelector () const
bool isCollection () const
bool isNil () const
Complex_Selector::Combinator combinator () const
Complex_Selector * selector ()
const Complex_Selector * selector () const
NodeDequePtr collection ()
const NodeDequePtr collection () const
Node clone (Context &ctx) const
bool operator== (const Node &rhs) const
bool operator!= (const Node &rhs) const
void plus (Node &rhs)
bool contains (const Node &potentialChild, bool simpleSelectorOrderDependent) const
Static Public Member Functions
static Node createCombinator (const Complex_Selector::Combinator &combinator)
static Node createSelector (Complex_Selector *pSelector, Context &ctx)
static Node createCollection ()
static Node createCollection (const NodeDeque &values)
static Node createNil ()
Data Fields
bool got_line_feed
Private Member Functions
Node (const TYPE &type, Complex_Selector::Combinator combinator, Complex_Selector *pSelector, NodeDequePtr &pCollection)
Private Attributes
TYPE mType
Complex_Selector::Combinator mCombinator
Complex_Selector * mpSelector
NodeDequePtr mpCollection
Detailed Description
Definition at line 39 of file node.hpp.
Member Enumeration Documentation
enum TYPE
Enumerator:
SELECTOR
COMBINATOR
COLLECTION
NIL
Definition at line 41 of file node.hpp.
Constructor & Destructor Documentation
Node (const TYPE & type, Complex_Selector::Combinator combinator, Complex_Selector * pSelector, NodeDequePtr & pCollection) [private]
Definition at line 44 of file node.cpp.
Referenced by Node::clone(), Node::createCollection(), Node::createCombinator(), Node::createNil(), and Node::createSelector().
Member Function Documentation
Node clone (Context & ctx) const
Definition at line 49 of file node.cpp.
References Complex_Selector::clone(), Node::clone(), Node::mCombinator, Node::mpCollection, Node::mpSelector, Node::mType, and Node::Node().
Referenced by Node::clone().
const NodeDequePtr collection () const [inline]
Definition at line 61 of file node.hpp.
References Node::mpCollection.
NodeDequePtr collection () [inline]
Definition at line 60 of file node.hpp.
References Node::mpCollection.
Referenced by Sass::chunks(), Sass::complexSelectorDequeToNode(), Sass::complexSelectorToNode(), Sass::extendCompoundSelector(), Sass::extendSelectorList(), Sass::flatten(), Sass::getAndRemoveFinalOps(), Sass::getAndRemoveInitialOps(), Sass::groupSelectors(), Sass::lcs(), Sass::lcs_backtrace(), Sass::lcs_table(), Sass::mergeFinalOps(), Sass::mergeInitialOps(), Sass::nodesEqual(), Sass::nodeToComplexSelector(), Sass::nodeToComplexSelectorDeque(), SubweaveEmptyChunker::operator()(), ParentSuperselectorChunker::operator()(), Sass::paths(), Node::plus(), Sass::subweave(), Sass::trim(), and Sass::weave().
Complex_Selector::Combinator combinator () const [inline]
Definition at line 55 of file node.hpp.
References Node::mCombinator.
Referenced by Sass::mergeFinalOps(), Sass::nodesEqual(), and Sass::nodeToComplexSelector().
bool contains (const Node & potentialChild, bool simpleSelectorOrderDependent) const
Definition at line 62 of file node.cpp.
References Node::mpCollection, and Sass::nodesEqual().
Referenced by Sass::extendCompoundSelector(), and Sass::extendSelectorList().
Node createCollection (const NodeDeque & values) [static]
Definition at line 32 of file node.cpp.
References Complex_Selector::ANCESTOR_OF, Node::COLLECTION, and Node::Node().
Node createCollection () [static]
Definition at line 26 of file node.cpp.
References Complex_Selector::ANCESTOR_OF, Node::COLLECTION, and Node::Node().
Referenced by Sass::chunks(), Sass::complexSelectorDequeToNode(), Sass::complexSelectorToNode(), Sass::extendCompoundSelector(), Sass::flatten(), Sass::groupSelectors(), Sass::lcs(), Sass::lcs_backtrace(), Sass::mergeFinalOps(), Sass::mergeInitialOps(), Sass::paths(), Sass::subweave(), Sass::trim(), and Sass::weave().
Node createCombinator (const Complex_Selector::Combinator & combinator) [static]
Definition at line 9 of file node.cpp.
References Node::COMBINATOR, and Node::Node().
Referenced by Sass::complexSelectorToNode(), and Sass::mergeFinalOps().
Node createNil () [static]
Definition at line 38 of file node.cpp.
References Complex_Selector::ANCESTOR_OF, Node::NIL, and Node::Node().
Referenced by Sass::complexSelectorToNode(), Sass::lcs(), Sass::lcs_backtrace(), Sass::lcs_table(), Sass::mergeFinalOps(), Sass::mergeInitialOps(), and Sass::subweave().
Node createSelector (Complex_Selector * pSelector, Context & ctx) [static]
Definition at line 15 of file node.cpp.
References Complex_Selector::ANCESTOR_OF, Complex_Selector::clone(), Node::Node(), and Node::SELECTOR.
Referenced by Sass::complexSelectorToNode(), and Sass::mergeFinalOps().
bool isCollection () const [inline]
Definition at line 51 of file node.hpp.
References Node::COLLECTION, and Node::mType.
Referenced by Sass::flatten(), Sass::nodesEqual(), Sass::nodeToComplexSelector(), Node::plus(), and Sass::subweave().
bool isCombinator () const [inline]
Definition at line 49 of file node.hpp.
References Node::COMBINATOR, and Node::mType.
Referenced by Sass::nodesEqual(), and Sass::nodeToComplexSelector().
bool isNil () const [inline]
Definition at line 52 of file node.hpp.
References Node::mType, and Node::NIL.
Referenced by Sass::nodesEqual(), Sass::nodeToComplexSelector(), Sass::subweave(), and Sass::weave().
bool isSelector () const [inline]
Definition at line 50 of file node.hpp.
References Node::mType, and Node::SELECTOR.
Referenced by Sass::nodesEqual(), and Sass::nodeToComplexSelector().
bool operator!= (const Node & rhs) const [inline]
Definition at line 76 of file node.hpp.
bool operator== (const Node & rhs) const
Definition at line 78 of file node.cpp.
References Sass::nodesEqual().
void plus (Node & rhs)
Definition at line 124 of file node.cpp.
References Node::collection(), and Node::isCollection().
Referenced by Sass::groupSelectors(), Sass::lcs(), Sass::paths(), Sass::subweave(), Sass::trim(), and Sass::weave().
const Complex_Selector* selector () const [inline]
Definition at line 58 of file node.hpp.
References Node::mpSelector.
Complex_Selector* selector () [inline]
Definition at line 57 of file node.hpp.
References Node::mpSelector.
Referenced by Sass::mergeFinalOps(), Sass::nodesEqual(), and Sass::nodeToComplexSelector().
TYPE type () const [inline]
Definition at line 48 of file node.hpp.
References Node::mType.
Referenced by Sass::nodesEqual().
Field Documentation
bool got_line_feed
Definition at line 53 of file node.hpp.
Referenced by Sass::nodeToComplexSelector().
Complex_Selector::Combinator mCombinator [private]
Definition at line 106 of file node.hpp.
Referenced by Node::clone(), and Node::combinator().
NodeDequePtr mpCollection [private]
Definition at line 108 of file node.hpp.
Referenced by Node::clone(), Node::collection(), and Node::contains().
Complex_Selector* mpSelector [private]
Definition at line 107 of file node.hpp.
Referenced by Node::clone(), and Node::selector().
TYPE mType [private]
Definition at line 103 of file node.hpp.
Referenced by Node::clone(), Node::isCollection(), Node::isCombinator(), Node::isNil(), Node::isSelector(), and Node::type().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/node.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/node.cpp