Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/views/diario/_tagcloud.php File Reference
_tagcloud.php File Reference
Variables
$tag_factory = new Tag()
$tags = $tag_factory->find_all(array('order_by' => '`tag` ASC'))
$max = 0
if(count($tags) > 0) else
Variable Documentation
$max = 0
Definition at line 8 of file _tagcloud.php.
Referenced by limit_3().
$tag_factory = new Tag()
Definition at line 4 of file _tagcloud.php.
Referenced by BackendController\diario_post_add().
$tags = $tag_factory->find_all(array('order_by' => '`tag` ASC'))
Definition at line 6 of file _tagcloud.php.
Referenced by Tag\cloud(), DiarioPost\comma_separated_tags(), and Tag\join().
if (count($tags) > 0) else
Initial value:
{
                echo em(l('No items'), NULL)
Definition at line 32 of file _tagcloud.php.