Emeraldion Lodge (codename Zelda): SingularLicense Class Reference
SingularLicense Class Reference
Helper class to handle Singular software licenses.
Public Member Functions
SingularLicense ($name= '', $email= '', $key= '')
Constructor for SingularLicense objects.
activation_link ($text=NULL)
Creates a hyperlink that activates a copy of Singular. An optional label for the hyperlink.
activation_url ()
Creates an activation URL that can activate a copy of Singular.
Public Member Functions inherited from License
is_valid ()
Tells if this license is valid.
Static Public Member Functions
static parse_url ($the_url)
Creates a SingularLicense object from an activation URL.
static generate_key ($username, $registration_date=NULL, $expiration_date=NULL, $license_type=SingularLicense::SINGLE_USER_LICENSE)
Singular license generator.
static valid_key ($key, $username= '', &$cleartext=NULL)
Singular license validator.
Static Public Member Functions inherited from License
static generate_key ($username, $registration_date=NULL, $expiration_date=NULL, $license_type=NULL)
Generates a key for a license.
static valid_key ($key, $username= '', &$cleartext=NULL)
Validates a key.
Data Fields
const SINGLE_USER_LICENSE = 0
Constant for single user license type.
const FAMILYPACK_LICENSE = 1
Constant for familypack license type.
const SITE_LICENSE = 2
Constant for site license type.
const DEFAULT_LICENSE_DURATION = 31536000
Constant for the default license duration (365 days).
Data Fields inherited from License
$username
The user who owns this license.
$email
The email address of the license owner.
$key
The key of the license.
$license_type
The type of the license.
$registration_date
The validity date of the license.
$expiration_date
The expiration date of the license.
Protected Member Functions
init ()
Initializes a SingularLicense object.
Detailed Description
Helper class to handle Singular software licenses.
Definition at line 12 of file singular_license.php.
Member Function Documentation
activation_link ($text = NULL)
Creates a hyperlink that activates a copy of Singular. An optional label for the hyperlink.
Definition at line 183 of file singular_license.php.
References a(), activation_url(), and l().
activation_url ()
Creates an activation URL that can activate a copy of Singular.
Definition at line 196 of file singular_license.php.
References username.
Referenced by activation_link().
generate_key ($username, $registration_date = NULL, $expiration_date = NULL, $license_type = SingularLicense::SINGLE_USER_LICENSE) static
Singular license generator.
Definition at line 90 of file singular_license.php.
References License\$expiration_date, License\$key, License\$registration_date, License\$username, DEFAULT_LICENSE_DURATION, and Base64\encode_linelength().
init () protected
Initializes a SingularLicense object.
Definition at line 51 of file singular_license.php.
References username.
Referenced by SingularLicense().
parse_url ($the_url) static
Creates a SingularLicense object from an activation URL.
Parameters
the_url The URL to parse.
Definition at line 69 of file singular_license.php.
References License\$email, License\$key, $license, and License\$username.
SingularLicense ($name = '', $email = '', $key = '')
Constructor for SingularLicense objects.
Definition at line 38 of file singular_license.php.
References License\$email, License\$key, init(), and username.
function valid_key ($key, $username = '', & $cleartext = NULL) static
Singular license validator.
Definition at line 140 of file singular_license.php.
References License\$key, License\$username, and Base64\decode().
Field Documentation
const DEFAULT_LICENSE_DURATION = 31536000
Constant for the default license duration (365 days).
Definition at line 32 of file singular_license.php.
Referenced by generate_key().
const FAMILYPACK_LICENSE = 1
Constant for familypack license type.
Definition at line 22 of file singular_license.php.
const SINGLE_USER_LICENSE = 0
Constant for single user license type.
Definition at line 17 of file singular_license.php.
const SITE_LICENSE = 2
Constant for site license type.
Definition at line 27 of file singular_license.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/helpers/singular_license.php