Emeraldion Lodge (codename Zelda): Statement Class Reference
Statement Class Reference
#include <ast.hpp>
Inherits Sass::AST_Node.
Inherited by Assignment, Block, Bubble, Comment, Content, Debug, Declaration, Error, Extension, Has_Block, If, Import, Import_Stub, Return, and Warning.
Public Types
enum Statement_Type {
NONE, RULESET, MEDIA, DIRECTIVE,
FEATURE, ATROOT, BUBBLE, KEYFRAMERULE
}
Public Member Functions
Statement (ParserState pstate, Statement_Type st=NONE, size_t t=0)
virtual ~Statement ()=0
virtual bool is_hoistable ()
virtual bool is_invisible ()
virtual bool bubbles ()
virtual Block * block ()
Private Member Functions
ADD_PROPERTY (Block *, block)
ADD_PROPERTY (Statement_Type, statement_type)
ADD_PROPERTY (size_t, tabs)
ADD_PROPERTY (bool, group_end)
Detailed Description
Definition at line 256 of file ast.hpp.
Member Enumeration Documentation
enum Statement_Type
Enumerator:
NONE
RULESET
MEDIA
DIRECTIVE
FEATURE
ATROOT
BUBBLE
KEYFRAMERULE
Definition at line 258 of file ast.hpp.
Constructor & Destructor Documentation
Statement (ParserState pstate, Statement_Type st = NONE, size_t t = 0) [inline]
Definition at line 274 of file ast.hpp.
~Statement () [inline, pure virtual]
Definition at line 284 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (bool , group_end) [private]
Reimplemented in Bubble.
ADD_PROPERTY (size_t , tabs) [private]
ADD_PROPERTY (Statement_Type , statement_type) [private]
ADD_PROPERTY (Block * , block) [private]
Reimplemented in Has_Block.
virtual Block* block () [inline, virtual]
Reimplemented in Block.
Definition at line 282 of file ast.hpp.
Referenced by debug_ast(), Media_Block::is_invisible(), Sass::Util::isPrintable(), Remove_Placeholders::operator()(), Output::operator()(), Inspect::operator()(), Extend::operator()(), Expand::operator()(), Eval::operator()(), Cssize::operator()(), and Parser::parse_media_block().
virtual bool bubbles () [inline, virtual]
Reimplemented in Bubble, Media_Block, Feature_Block, At_Rule, and At_Root_Block.
Definition at line 281 of file ast.hpp.
virtual bool is_hoistable () [inline, virtual]
Reimplemented in Ruleset, Media_Block, Feature_Block, and At_Root_Block.
Definition at line 279 of file ast.hpp.
Referenced by Block::adjust_after_pushing(), Sass::Util::isPrintable(), and Output::operator()().
virtual bool is_invisible () [inline, virtual]
Reimplemented in Ruleset, and Media_Block.
Definition at line 280 of file ast.hpp.
Referenced by Output::operator()().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp