Emeraldion Lodge (codename Zelda): Token Class Reference
Token Class Reference
#include <position.hpp>
Public Member Functions
Token ()
Token (const char *b, const char *e)
Token (const char *str)
Token (const char *p, const char *b, const char *e)
size_t length () const
string ws_before () const
string to_string () const
string time_wspace () const
operator bool ()
operator string ()
bool operator== (Token t)
Data Fields
const char * prefix
const char * begin
const char * end
Detailed Description
Definition at line 74 of file position.hpp.
Constructor & Destructor Documentation
Token () [inline]
Definition at line 80 of file position.hpp.
Token (const char * b, const char * e) [inline]
Definition at line 82 of file position.hpp.
Token (const char * str) [inline]
Definition at line 84 of file position.hpp.
Token (const char * p, const char * b, const char * e) [inline]
Definition at line 86 of file position.hpp.
Member Function Documentation
size_t length () const [inline]
Definition at line 89 of file position.hpp.
References Token::begin, and Token::end.
operator bool () [inline]
Definition at line 98 of file position.hpp.
References Token::begin, and Token::end.
operator string () [inline]
Definition at line 99 of file position.hpp.
References Token::to_string().
bool operator== (Token t) [inline]
Definition at line 101 of file position.hpp.
References Token::to_string().
string time_wspace () const [inline]
Definition at line 92 of file position.hpp.
References Token::to_string().
string to_string () const [inline]
Definition at line 91 of file position.hpp.
References Token::begin, and Token::end.
Referenced by Token::operator string(), Token::operator==(), Parser::parse_expression(), Parser::parse_interpolated_chunk(), Parser::parse_value(), and Token::time_wspace().
string ws_before () const [inline]
Definition at line 90 of file position.hpp.
References Token::begin, and Token::prefix.
Field Documentation
const char* begin
Definition at line 77 of file position.hpp.
Referenced by Parser::from_token(), Token::length(), Token::operator bool(), Parser::parse_interpolated_chunk(), Parser::parse_operators(), Parser::parse_value_schema(), Sass::Prelexer::static_string(), Token::to_string(), and Token::ws_before().
const char* end
Definition at line 78 of file position.hpp.
Referenced by Parser::from_token(), Token::length(), Token::operator bool(), Parser::parse_interpolated_chunk(), Parser::parse_value_schema(), Sass::Prelexer::static_string(), and Token::to_string().
const char* prefix
Definition at line 76 of file position.hpp.
Referenced by Token::ws_before().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/position.hpp