Emeraldion Lodge (codename Zelda): PersistentBase< T > Class Template Reference
PersistentBase< T > Class Template Reference
#include <nan_persistent_pre_12_inl.h>
Inherited by Persistent< v8::Object >.
Public Member Functions
NAN_INLINE PersistentBase ()
NAN_INLINE void Reset ()
template<typename S >
NAN_INLINE void Reset (const v8::Local< S > &other)
template<typename S >
NAN_INLINE void Reset (const PersistentBase< S > &other)
NAN_INLINE bool IsEmpty () const
NAN_INLINE void Empty ()
template<typename S >
NAN_INLINE bool operator== (const PersistentBase< S > &that)
template<typename S >
NAN_INLINE bool operator== (const v8::Local< S > &that)
template<typename S >
NAN_INLINE bool operator!= (const PersistentBase< S > &that)
template<typename S >
NAN_INLINE bool operator!= (const v8::Local< S > &that)
template<typename P >
NAN_INLINE void SetWeak (P *parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type)
NAN_INLINE void ClearWeak ()
NAN_INLINE void MarkIndependent ()
NAN_INLINE bool IsIndependent () const
NAN_INLINE bool IsNearDeath () const
NAN_INLINE bool IsWeak () const
Private Member Functions
NAN_INLINE PersistentBase (v8::Persistent< T > that)
NAN_INLINE PersistentBase (T *val)
Private Attributes
v8::Persistent< T > persistent
Friends
class ReturnValue
class Persistent
class Global
class ObjectWrap
template<typename U , typename M >
v8::Local< U > New (const Persistent< U, M > &p)
Detailed Description
template<typename T>
class PersistentBase< T >
Definition at line 13 of file nan_persistent_pre_12_inl.h.
Constructor & Destructor Documentation
NAN_INLINE PersistentBase () [inline]
Definition at line 20 of file nan_persistent_pre_12_inl.h.
NAN_INLINE PersistentBase (v8::Persistent< T > that) [inline, explicit, private]
Definition at line 99 of file nan_persistent_pre_12_inl.h.
NAN_INLINE PersistentBase (T * val) [inline, explicit, private]
Definition at line 101 of file nan_persistent_pre_12_inl.h.
Member Function Documentation
NAN_INLINE void ClearWeak () [inline]
Definition at line 88 of file nan_persistent_pre_12_inl.h.
Referenced by ObjectWrap::Ref(), and ObjectWrap::~ObjectWrap().
NAN_INLINE void Empty () [inline]
Definition at line 60 of file nan_persistent_pre_12_inl.h.
NAN_INLINE bool IsEmpty () const [inline]
Definition at line 58 of file nan_persistent_pre_12_inl.h.
Referenced by PersistentBase< T >::Reset().
NAN_INLINE bool IsIndependent () const [inline]
Definition at line 92 of file nan_persistent_pre_12_inl.h.
NAN_INLINE bool IsNearDeath () const [inline]
Definition at line 94 of file nan_persistent_pre_12_inl.h.
Referenced by ObjectWrap::WeakCallback().
NAN_INLINE bool IsWeak () const [inline]
Definition at line 96 of file nan_persistent_pre_12_inl.h.
NAN_INLINE void MarkIndependent () [inline]
Definition at line 90 of file nan_persistent_pre_12_inl.h.
Referenced by ObjectWrap::MakeWeak().
NAN_INLINE bool operator!= (const v8::Local< S > & that) [inline]
Definition at line 78 of file nan_persistent_pre_12_inl.h.
NAN_INLINE bool operator!= (const PersistentBase< S > & that) [inline]
Definition at line 73 of file nan_persistent_pre_12_inl.h.
NAN_INLINE bool operator== (const v8::Local< S > & that) [inline]
Definition at line 68 of file nan_persistent_pre_12_inl.h.
NAN_INLINE bool operator== (const PersistentBase< S > & that) [inline]
Definition at line 63 of file nan_persistent_pre_12_inl.h.
Referenced by PersistentBase< T >::operator!=().
NAN_INLINE void Reset (const PersistentBase< S > & other) [inline]
Definition at line 44 of file nan_persistent_pre_12_inl.h.
NAN_INLINE void Reset (const v8::Local< S > & other) [inline]
Reimplemented in Persistent< T, M >, Global< T >, and Persistent< v8::Object >.
Definition at line 29 of file nan_persistent_pre_12_inl.h.
NAN_INLINE void Reset () [inline]
Reimplemented in Persistent< T, M >, Global< T >, and Persistent< v8::Object >.
Definition at line 23 of file nan_persistent_pre_12_inl.h.
NAN_INLINE void SetWeak (P * parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type) [inline]
Reimplemented in Persistent< T, M >, Global< T >, and Persistent< v8::Object >.
Friends And Related Function Documentation
friend class Global [friend]
Definition at line 103 of file nan_persistent_pre_12_inl.h.
v8::Local<U> New (const Persistent< U, M > & p) [friend]
Referenced by PersistentBase< T >::Reset().
friend class ObjectWrap [friend]
Definition at line 104 of file nan_persistent_pre_12_inl.h.
friend class Persistent [friend]
Definition at line 102 of file nan_persistent_pre_12_inl.h.
friend class ReturnValue [friend]
Reimplemented in Global< T >.
Definition at line 17 of file nan_persistent_pre_12_inl.h.
Field Documentation
v8::Persistent<T> persistent [private]
Definition at line 14 of file nan_persistent_pre_12_inl.h.
Referenced by PersistentBase< T >::ClearWeak(), PersistentBase< T >::Empty(), PersistentBase< T >::IsEmpty(), PersistentBase< T >::IsIndependent(), PersistentBase< T >::IsNearDeath(), PersistentBase< T >::IsWeak(), PersistentBase< T >::MarkIndependent(), PersistentBase< T >::operator==(), PersistentBase< T >::Reset(), and PersistentBase< T >::SetWeak().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_persistent_pre_12_inl.h