Emeraldion Lodge (codename Zelda): Block Class Reference
Block Class Reference
#include <ast.hpp>
Inherits Sass::Statement, and Vectorized< Statement * >.
Public Member Functions
Block (ParserState pstate, size_t s=0, bool r=false)
Block * block ()
ATTACH_OPERATIONS ()
Protected Member Functions
void adjust_after_pushing (Statement *s)
Private Member Functions
ADD_PROPERTY (bool, is_root)
ADD_PROPERTY (bool, has_hoistable)
ADD_PROPERTY (bool, has_non_hoistable)
Detailed Description
Definition at line 289 of file ast.hpp.
Constructor & Destructor Documentation
Block (ParserState pstate, size_t s = 0, bool r = false) [inline]
Definition at line 301 of file ast.hpp.
Member Function Documentation
ADD_PROPERTY (bool , has_non_hoistable) [private]
ADD_PROPERTY (bool , has_hoistable) [private]
ADD_PROPERTY (bool , is_root) [private]
void adjust_after_pushing (Statement * s) [inline, protected, virtual]
Reimplemented from Vectorized< Statement * >.
Definition at line 295 of file ast.hpp.
References Statement::is_hoistable().
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
Block* block () [inline, virtual]
Reimplemented from Statement.
Definition at line 306 of file ast.hpp.
Referenced by Sass::Util::isPrintable(), Expand::operator()(), Cssize::operator()(), and Context::parse_file().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp