Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_functions.cpp File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/sass_functions.cpp File Reference
#include <unistd.h>
#include <cstring>
#include "util.hpp"
#include "context.hpp"
#include "sass_functions.h"
Data Structures
struct Sass_Function
struct Sass_Import
struct Sass_Importer
Functions
Sass_Function_List ADDCALL sass_make_function_list (size_t length)
Sass_Function_Entry ADDCALL sass_make_function (const char *signature, Sass_Function_Fn function, void *cookie)
Sass_Function_Entry ADDCALL sass_function_get_list_entry (Sass_Function_List list, size_t pos)
void sass_function_set_list_entry (Sass_Function_List list, size_t pos, Sass_Function_Entry cb)
const char *ADDCALL sass_function_get_signature (Sass_Function_Entry cb)
Sass_Function_Fn ADDCALL sass_function_get_function (Sass_Function_Entry cb)
void *ADDCALL sass_function_get_cookie (Sass_Function_Entry cb)
Sass_Importer_Entry ADDCALL sass_make_importer (Sass_Importer_Fn importer, double priority, void *cookie)
Sass_Importer_Fn ADDCALL sass_importer_get_function (Sass_Importer_Entry cb)
double ADDCALL sass_importer_get_priority (Sass_Importer_Entry cb)
void *ADDCALL sass_importer_get_cookie (Sass_Importer_Entry cb)
void ADDCALL sass_delete_importer (Sass_Importer_Entry cb)
Sass_Importer_List ADDCALL sass_make_importer_list (size_t length)
Sass_Importer_Entry ADDCALL sass_importer_get_list_entry (Sass_Importer_List list, size_t idx)
void ADDCALL sass_importer_set_list_entry (Sass_Importer_List list, size_t idx, Sass_Importer_Entry cb)
Sass_Import_List ADDCALL sass_make_import_list (size_t length)
Sass_Import_Entry ADDCALL sass_make_import (const char *path, const char *base, char *source, char *srcmap)
Sass_Import_Entry ADDCALL sass_make_import_entry (const char *path, char *source, char *srcmap)
Sass_Import_Entry ADDCALL sass_import_set_error (Sass_Import_Entry import, const char *error, size_t line, size_t col)
void ADDCALL sass_import_set_list_entry (Sass_Import_List list, size_t idx, Sass_Import_Entry entry)
Sass_Import_Entry ADDCALL sass_import_get_list_entry (Sass_Import_List list, size_t idx)
void ADDCALL sass_delete_import_list (Sass_Import_List list)
void ADDCALL sass_delete_import (Sass_Import_Entry import)
const char *ADDCALL sass_import_get_path (Sass_Import_Entry entry)
const char *ADDCALL sass_import_get_base (Sass_Import_Entry entry)
const char *ADDCALL sass_import_get_source (Sass_Import_Entry entry)
const char *ADDCALL sass_import_get_srcmap (Sass_Import_Entry entry)
size_t ADDCALL sass_import_get_error_line (Sass_Import_Entry entry)
size_t ADDCALL sass_import_get_error_column (Sass_Import_Entry entry)
const char *ADDCALL sass_import_get_error_message (Sass_Import_Entry entry)
char *ADDCALL sass_import_take_source (Sass_Import_Entry entry)
char *ADDCALL sass_import_take_srcmap (Sass_Import_Entry entry)
Function Documentation
void ADDCALL sass_delete_import (Sass_Import_Entry import)
Definition at line 150 of file sass_functions.cpp.
Referenced by Context::parse_file(), sass_delete_import_list(), and Context::~Context().
void ADDCALL sass_delete_import_list (Sass_Import_List list)
Definition at line 138 of file sass_functions.cpp.
References sass_delete_import().
Referenced by Parser::do_import().
void ADDCALL sass_delete_importer (Sass_Importer_Entry cb)
Definition at line 80 of file sass_functions.cpp.
void* ADDCALL sass_function_get_cookie (Sass_Function_Entry cb)
Definition at line 44 of file sass_functions.cpp.
References Sass_Function::cookie.
Referenced by custom_function(), and sass_custom_function().
Sass_Function_Fn ADDCALL sass_function_get_function (Sass_Function_Entry cb)
Definition at line 43 of file sass_functions.cpp.
References Sass_Function::function.
Referenced by Eval::operator()().
Sass_Function_Entry ADDCALL sass_function_get_list_entry (Sass_Function_List list, size_t pos)
Definition at line 39 of file sass_functions.cpp.
const char* ADDCALL sass_function_get_signature (Sass_Function_Entry cb)
Definition at line 42 of file sass_functions.cpp.
References Sass_Function::signature.
Referenced by Sass::make_c_function().
void sass_function_set_list_entry (Sass_Function_List list, size_t pos, Sass_Function_Entry cb)
Definition at line 40 of file sass_functions.cpp.
Referenced by ExtractOptions(), and libsass_load_functions().
const char* ADDCALL sass_import_get_base (Sass_Import_Entry entry)
Definition at line 162 of file sass_functions.cpp.
References Sass_Import::base.
size_t ADDCALL sass_import_get_error_column (Sass_Import_Entry entry)
Definition at line 168 of file sass_functions.cpp.
References Sass_Import::column.
Referenced by Parser::do_import().
size_t ADDCALL sass_import_get_error_line (Sass_Import_Entry entry)
Definition at line 167 of file sass_functions.cpp.
References Sass_Import::line.
Referenced by Parser::do_import().
const char* ADDCALL sass_import_get_error_message (Sass_Import_Entry entry)
Definition at line 169 of file sass_functions.cpp.
References Sass_Import::error.
Referenced by Parser::do_import().
Sass_Import_Entry ADDCALL sass_import_get_list_entry (Sass_Import_List list, size_t idx)
Definition at line 135 of file sass_functions.cpp.
const char* ADDCALL sass_import_get_path (Sass_Import_Entry entry)
Definition at line 161 of file sass_functions.cpp.
References Sass_Import::path.
Referenced by Parser::do_import(), and sass_importer().
const char* ADDCALL sass_import_get_source (Sass_Import_Entry entry)
Definition at line 163 of file sass_functions.cpp.
References Sass_Import::source.
const char* ADDCALL sass_import_get_srcmap (Sass_Import_Entry entry)
Definition at line 164 of file sass_functions.cpp.
References Sass_Import::srcmap.
Sass_Import_Entry ADDCALL sass_import_set_error (Sass_Import_Entry import, const char * error, size_t line, size_t col)
Definition at line 123 of file sass_functions.cpp.
Referenced by CustomImporterBridge::check_returned_string(), and CustomImporterBridge::post_process_return_value().
void ADDCALL sass_import_set_list_entry (Sass_Import_List list, size_t idx, Sass_Import_Entry entry)
Definition at line 134 of file sass_functions.cpp.
char* ADDCALL sass_import_take_source (Sass_Import_Entry entry)
Definition at line 173 of file sass_functions.cpp.
References Sass_Import::source.
Referenced by Parser::do_import().
char* ADDCALL sass_import_take_srcmap (Sass_Import_Entry entry)
Definition at line 174 of file sass_functions.cpp.
References Sass_Import::srcmap.
void* ADDCALL sass_importer_get_cookie (Sass_Importer_Entry cb)
Definition at line 77 of file sass_functions.cpp.
References Sass_Importer::cookie.
Referenced by custom_importer(), and sass_importer().
Sass_Importer_Fn ADDCALL sass_importer_get_function (Sass_Importer_Entry cb)
Definition at line 75 of file sass_functions.cpp.
References Sass_Importer::importer.
Referenced by Parser::do_import().
Sass_Importer_Entry ADDCALL sass_importer_get_list_entry (Sass_Importer_List list, size_t idx)
Definition at line 91 of file sass_functions.cpp.
double ADDCALL sass_importer_get_priority (Sass_Importer_Entry cb)
Definition at line 76 of file sass_functions.cpp.
References Sass_Importer::priority.
Referenced by Sass::sort_importers().
void ADDCALL sass_importer_set_list_entry (Sass_Importer_List list, size_t idx, Sass_Importer_Entry cb)
Definition at line 92 of file sass_functions.cpp.
Referenced by libsass_load_importers().
Sass_Function_Entry ADDCALL sass_make_function (const char * signature, Sass_Function_Fn function, void * cookie)
Definition at line 28 of file sass_functions.cpp.
References Sass_Function::cookie, Sass_Function::function, and Sass_Function::signature.
Referenced by ExtractOptions(), and libsass_load_functions().
Sass_Function_List ADDCALL sass_make_function_list (size_t length)
Definition at line 23 of file sass_functions.cpp.
Referenced by ExtractOptions(), and libsass_load_functions().
Sass_Import_Entry ADDCALL sass_make_import (const char * path, const char * base, char * source, char * srcmap)
Definition at line 102 of file sass_functions.cpp.
References Sass_Import::base, Sass_Import::column, Sass_Import::error, Sass_Import::line, Sass_Import::path, Sass::sass_strdup(), Sass_Import::source, and Sass_Import::srcmap.
Referenced by Context::parse_file(), and sass_make_import_entry().
Sass_Import_Entry ADDCALL sass_make_import_entry (const char * path, char * source, char * srcmap)
Definition at line 117 of file sass_functions.cpp.
References sass_make_import().
Referenced by CustomImporterBridge::check_returned_string(), custom_importer(), CustomImporterBridge::get_importer_entry(), and CustomImporterBridge::post_process_return_value().
Sass_Import_List ADDCALL sass_make_import_list (size_t length)
Definition at line 95 of file sass_functions.cpp.
Referenced by custom_importer(), and CustomImporterBridge::post_process_return_value().
Sass_Importer_Entry ADDCALL sass_make_importer (Sass_Importer_Fn importer, double priority, void * cookie)
Definition at line 65 of file sass_functions.cpp.
References Sass_Importer::cookie, Sass_Importer::importer, and Sass_Importer::priority.
Referenced by ExtractOptions(), and libsass_load_importers().
Sass_Importer_List ADDCALL sass_make_importer_list (size_t length)
Definition at line 86 of file sass_functions.cpp.
Referenced by ExtractOptions(), and libsass_load_importers().