Emeraldion Lodge (codename Zelda): TryCatch Class Reference
TryCatch Class Reference
#include <nan.h>
Public Member Functions
NAN_INLINE bool HasCaught () const
NAN_INLINE bool CanContinue () const
NAN_INLINE v8::Local< v8::Value > ReThrow ()
NAN_INLINE v8::Local< v8::Value > Exception () const
NAN_INLINE MaybeLocal< v8::Value > StackTrace () const
NAN_INLINE v8::Local< v8::Message > Message () const
NAN_INLINE void Reset ()
NAN_INLINE void SetVerbose (bool value)
NAN_INLINE void SetCaptureMessage (bool value)
Private Attributes
v8::TryCatch try_catch_
Friends
void FatalException (const TryCatch &)
Detailed Description
Definition at line 2208 of file nan.h.
Member Function Documentation
NAN_INLINE bool CanContinue () const [inline]
Definition at line 2219 of file nan.h.
NAN_INLINE v8::Local<v8::Value> Exception () const [inline]
Definition at line 2229 of file nan.h.
NAN_INLINE bool HasCaught () const [inline]
Definition at line 2217 of file nan.h.
Referenced by CallbackBridge< T, L >::dispatched_async_uv_callback(), MakeCallback(), NAN_METHOD(), and CallbackBridge< T, L >::operator()().
NAN_INLINE v8::Local<v8::Message> Message () const [inline]
Definition at line 2244 of file nan.h.
NAN_INLINE void Reset () [inline]
Definition at line 2248 of file nan.h.
NAN_INLINE v8::Local<v8::Value> ReThrow () [inline]
Definition at line 2221 of file nan.h.
NAN_INLINE void SetCaptureMessage (bool value) [inline]
Definition at line 2252 of file nan.h.
NAN_INLINE void SetVerbose (bool value) [inline]
Definition at line 2250 of file nan.h.
NAN_INLINE MaybeLocal<v8::Value> StackTrace () const [inline]
Definition at line 2239 of file nan.h.
Friends And Related Function Documentation
void FatalException (const TryCatch & try_catch) [friend]
Definition at line 2960 of file nan.h.
Field Documentation
v8::TryCatch try_catch_ [private]
Definition at line 2209 of file nan.h.
Referenced by PropertyCallbackInfo< T >::GetReturnValue(), PropertyCallbackInfo< v8::Array >::PropertyCallbackInfo(), PropertyCallbackInfo< v8::Array >::~PropertyCallbackInfo(), and PropertyCallbackInfo< T >::~PropertyCallbackInfo().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan.h