Emeraldion Lodge (codename Zelda): Number Class Reference
Number Class Reference
#include <number.h>
Inherits SassValueWrapper< Number >.
Public Member Functions
Number (Sass_Value *)
Static Public Member Functions
static char const * get_constructor_name ()
static Sass_Value * construct (const std::vector< v8::Local< v8::Value >>, Sass_Value **out)
static void initPrototype (v8::Local< v8::FunctionTemplate >)
static NAN_METHOD (GetValue)
static NAN_METHOD (GetUnit)
static NAN_METHOD (SetValue)
static NAN_METHOD (SetUnit)
Detailed Description
Definition at line 10 of file number.h.
Constructor & Destructor Documentation
Number (Sass_Value * v)
Definition at line 7 of file number.cpp.
Member Function Documentation
Sass_Value * construct (const std::vector< v8::Local< v8::Value >> raw_val, Sass_Value ** out) [static]
Definition at line 9 of file number.cpp.
References create_string(), SassValueWrapper< Number >::fail(), sass_make_number(), and SassValueWrapper< Number >::value.
static char const* get_constructor_name () [inline, static]
Reimplemented from SassValueWrapper< Number >.
Definition at line 13 of file number.h.
void initPrototype (v8::Local< v8::FunctionTemplate > proto) [static]
Definition at line 32 of file number.cpp.
References Nan::SetPrototypeMethod().
static NAN_METHOD (SetUnit) [static]
static NAN_METHOD (SetValue) [static]
static NAN_METHOD (GetUnit) [static]
static NAN_METHOD (GetValue) [static]
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/number.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/sass_types/number.cpp