Emeraldion Lodge (codename Zelda): CustomImporterBridge Class Reference
CustomImporterBridge Class Reference
#include <custom_importer_bridge.h>
Inherits CallbackBridge< SassImportList >.
Public Member Functions
CustomImporterBridge (v8::Local< v8::Function > cb, bool is_sync)
Private Member Functions
SassImportList post_process_return_value (v8::Local< v8::Value >) const
Sass_Import * check_returned_string (Nan::MaybeLocal< v8::Value > value, const char *msg) const
Sass_Import * get_importer_entry (const v8::Local< v8::Object > &) const
Detailed Description
Definition at line 10 of file custom_importer_bridge.h.
Constructor & Destructor Documentation
CustomImporterBridge (v8::Local< v8::Function > cb, bool is_sync) [inline]
Definition at line 12 of file custom_importer_bridge.h.
Member Function Documentation
Sass_Import * check_returned_string (Nan::MaybeLocal< v8::Value > value, const char * msg) const [private]
Definition at line 55 of file custom_importer_bridge.cpp.
References sass_import_set_error(), sass_make_import_entry(), and MaybeLocal< T >::ToLocal().
Referenced by get_importer_entry().
Sass_Import * get_importer_entry (const v8::Local< v8::Object > & object) const [private]
Definition at line 71 of file custom_importer_bridge.cpp.
References check_returned_string(), create_string(), Get(), and sass_make_import_entry().
Referenced by post_process_return_value().
SassImportList post_process_return_value (v8::Local< v8::Value > returned_value) const [private, virtual]
Implements CallbackBridge< SassImportList >.
Definition at line 6 of file custom_importer_bridge.cpp.
References create_string(), Nan::Get(), Get(), get_importer_entry(), sass_import_set_error(), sass_make_import_entry(), and sass_make_import_list().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/custom_importer_bridge.h
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/custom_importer_bridge.cpp