Emeraldion Lodge (codename Zelda): Compound_Selector Class Reference
Compound_Selector Class Reference
#include <ast.hpp>
Inherits Sass::Selector, and Vectorized< Simple_Selector * >.
Public Member Functions
Compound_Selector (ParserState pstate, size_t s=0)
Compound_Selector * unify_with (Compound_Selector *rhs, Context &ctx)
Simple_Selector * base ()
const Simple_Selector * base () const
bool is_superselector_of (Compound_Selector *sub)
virtual unsigned long specificity ()
bool is_empty_reference ()
vector< string > to_str_vec ()
bool operator< (const Compound_Selector &rhs) const
bool operator== (const Compound_Selector &rhs) const
bool operator!= (const Compound_Selector &rhs) const
SourcesSet & sources ()
void clearSources ()
void mergeSources (SourcesSet &sources, Context &ctx)
Compound_Selector * clone (Context &) const
Compound_Selector * minus (Compound_Selector *rhs, Context &ctx)
ATTACH_OPERATIONS ()
Protected Member Functions
void adjust_after_pushing (Simple_Selector *s)
Private Attributes
SourcesSet sources_
Detailed Description
Definition at line 1919 of file ast.hpp.
Constructor & Destructor Documentation
Compound_Selector (ParserState pstate, size_t s = 0) [inline]
Definition at line 1929 of file ast.hpp.
Referenced by Compound_Selector::clone(), and Compound_Selector::minus().
Member Function Documentation
void adjust_after_pushing (Simple_Selector * s) [inline, protected, virtual]
Reimplemented from Vectorized< Simple_Selector * >.
Definition at line 1923 of file ast.hpp.
ATTACH_OPERATIONS ()
Reimplemented from AST_Node.
const Simple_Selector* base () const [inline]
Definition at line 1941 of file ast.hpp.
References Vectorized< Simple_Selector * >::length().
Simple_Selector* base () [inline]
Definition at line 1936 of file ast.hpp.
Referenced by Compound_Selector::is_superselector_of(), and Compound_Selector::operator==().
void clearSources () [inline]
Definition at line 1970 of file ast.hpp.
References Compound_Selector::sources_.
Referenced by Complex_Selector::clearSources().
Compound_Selector * clone (Context & ctx) const
Definition at line 493 of file ast.cpp.
References Compound_Selector::Compound_Selector(), and Context::mem.
bool is_empty_reference () [inline]
Definition at line 1956 of file ast.hpp.
References Vectorized< Simple_Selector * >::length(), and selector().
Referenced by Listize::operator()(), and Inspect::operator()().
bool is_superselector_of (Compound_Selector * sub)
Definition at line 208 of file ast.cpp.
References Compound_Selector::base(), Vectorized< T >::length(), Vectorized< Simple_Selector * >::length(), and Sass::to_string.
Referenced by check_compound(), and Complex_Selector::is_superselector_of().
void mergeSources (SourcesSet & sources, Context & ctx)
Definition at line 635 of file ast.cpp.
References Compound_Selector::sources_.
Referenced by Complex_Selector::addSources().
Compound_Selector * minus (Compound_Selector * rhs, Context & ctx)
Definition at line 611 of file ast.cpp.
References Compound_Selector::Compound_Selector(), Vectorized< T >::length(), Vectorized< Simple_Selector * >::length(), Context::mem, Sass::pstate, and Sass::to_string.
Referenced by diff(), and Sass::extendCompoundSelector().
bool operator!= (const Compound_Selector & rhs) const [inline]
Definition at line 1967 of file ast.hpp.
bool operator< (const Compound_Selector & rhs) const
Definition at line 13 of file ast.cpp.
References Sass::to_string.
bool operator== (const Compound_Selector & rhs) const
Definition at line 283 of file ast.cpp.
References Compound_Selector::base(), Vectorized< T >::length(), Vectorized< Simple_Selector * >::length(), and Sass::to_string.
SourcesSet& sources () [inline]
Definition at line 1969 of file ast.hpp.
References Compound_Selector::sources_.
Referenced by Sass::extendCompoundSelector(), and Complex_Selector::sources().
virtual unsigned long specificity () [inline, virtual]
Reimplemented from Selector.
Definition at line 1949 of file ast.hpp.
References Vectorized< Simple_Selector * >::length().
Referenced by spec(), and Selector_Reference::specificity().
vector< string > to_str_vec ()
Definition at line 601 of file ast.cpp.
References Vectorized< Simple_Selector * >::length(), and Sass::to_string.
Referenced by Sass::complexSelectorHasExtension(), Sass::extendCompoundSelector(), and Expand::operator()().
Compound_Selector * unify_with (Compound_Selector * rhs, Context & ctx)
Definition at line 58 of file ast.cpp.
References Vectorized< Simple_Selector * >::length(), and Compound_Selector::unify_with().
Referenced by Sass::extendCompoundSelector(), unify(), and Compound_Selector::unify_with().
Field Documentation
SourcesSet sources_ [private]
Definition at line 1921 of file ast.hpp.
Referenced by Compound_Selector::clearSources(), Compound_Selector::mergeSources(), and Compound_Selector::sources().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/ast.cpp