Emeraldion Lodge (codename Zelda): LoginController Class Reference
LoginController Class Reference
Controller that manages all authentication related tasks such as login, logout and password retrieval.
Public Member Functions
init ()
login ()
Action method to perform a login.
logout ()
Action method that logs out a user.
lost_password ()
Action method to request a new password.
request_password ()
Action method to send a new password to a registered user.
request_sent ()
Action method to show the results of a password request.
Public Member Functions inherited from EmeController
index ()
Public Member Functions inherited from BaseController
BaseController ()
Default constructor for controller objects.
link_to ($text, $params=array())
Links to another action.
link_to_remote ($text, $params=array())
Links to another action, with AJAX support.
button_to ($text, $params=array())
Creates a button that links to another action.
url_to ($params)
Creates a URL to an action.
url_to_myself ($relative=TRUE)
Creates a URL to the current action.
make_relative_url ($params)
Creates a URL to an action.
render ($params)
Requests the rendering of the response.
render_as_string ($params)
Requests the rendering of the response as a string.
render_page ()
Renders the page as a response for the current request.
render_component ($params)
Renders a view from a controller other than self.
set_title ($title)
Sets the title for the current page.
flash ($message, $type= 'error')
Shows a message to the user, with an optional type qualifier.
index ()
This is the default action method.
Additional Inherited Members
Data Fields inherited from EmeController
const LOG_VISITS = TRUE
Flag that determines if the controller must log the visits.
Data Fields inherited from BaseController
$name
The name of the controller.
$action
The name of the action.
$title
A title for the page.
Protected Member Functions inherited from EmeController
init ()
set_credentials ($realname= '', $email= '', $url= '')
Stores a set of credentials into a cookie using Base64 encoding.
get_credentials ()
Returns a set of credentials previously stored into a cookie with Base64 encoding.
check_auth ()
Filter method that checks authorization before accessing actions.
log_visit ()
Filter method that saves a Visit object for current request.
block_ip ()
Filter method that interrupts response generation if the client IP is blacklisted.
add_acronyms ()
Filter method that adds common acronyms.
morse_encode ()
Filter method that converts response contents to Morse code.
shrink_html ()
Filter method that removes all unnecessary spaces from HTML output.
sanskrit_ambra ()
Filter method that converts response contents to Ambra Angiolini's "sanskrit".
spot_people ()
Filter method to identify visits from known people.
load_part_contents ($filename)
Loads localized part contents from file.
include_localized ($filename)
Includes a localized version of the requested filename if possible.
Protected Member Functions inherited from BaseController
initialize ()
Initializes the controller object.
init ()
Custom initialization for the controller object.
before_filter ($filter, $params=NULL)
Registers a function as a filter to be executed before the action is invoked.
after_filter ($filter, $params=NULL)
Registers a function as a filter to be executed after the action is invoked.
caches_page ($page)
Requests that a page be cached.
conditionally_caches_page ($page, $condition=TRUE)
Requests that a page be cached when a condition is verified.
caches_action ($page)
Requests that an action be cached.
cached_page_exists ()
Checks if a cached version of the current action exists.
cached_page_filename ()
Returns a name for the cached page of current action.
expire_cached_page ($params)
Requests that the page(s) defined by params be removed from the caches.
redirect_to ($params)
Redirects the response to another action, or URL.
refresh ($amount=10)
Refreshes current page after a given amount of time.
redirect_to_referrer ($or_else=NULL)
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
unknown_action ()
render_layout ($params)
Renders the layout for the current view.
load_part_contents ($filename)
Loads the contents of the desired view file.
strip_external_php_tags ($php_code)
Strips beginning and ending delimiters from the given PHP code.
compress ()
Compresses the response with gzip encoding.
Protected Attributes inherited from EmeController
$credentials
User credentials.
$keywords = array()
Keywords for the "Keywords" meta header.
$description
Description for the "Description" meta header.
Protected Attributes inherited from BaseController
$type = 'html'
An extension for action pages.
$mimetype = 'text/html'
A MIME type for the response.
Detailed Description
Controller that manages all authentication related tasks such as login, logout and password retrieval.
Definition at line 17 of file login_controller.php.
Member Function Documentation
init ()
Definition at line 19 of file login_controller.php.
References BaseController\before_filter().
login ()
Action method to perform a login.
Definition at line 31 of file login_controller.php.
References $conn, Db\close_connection(), BaseController\flash(), Db\get_connection(), l(), Login\magic_phrase, Time\next_year(), BaseController\redirect_to(), Cookie\set(), and Time\tomorrow().
logout ()
Action method that logs out a user.
Definition at line 84 of file login_controller.php.
References Cookie\delete(), BaseController\flash(), l(), and BaseController\redirect_to().
lost_password ()
Action method to request a new password.
Definition at line 97 of file login_controller.php.
References Antispam\init_math_test(), l(), and BaseController\set_title().
request_password ()
Action method to send a new password to a registered user.
Definition at line 108 of file login_controller.php.
References Antispam\check_math(), BaseController\flash(), l(), Antispam\random_comment(), and BaseController\redirect_to().
request_sent ()
Action method to show the results of a password request.
Definition at line 137 of file login_controller.php.
References BaseController\redirect_to().
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/controllers/login_controller.php