Emeraldion Lodge (codename Zelda): MaybeLocal< T > Class Template Reference
MaybeLocal< T > Class Template Reference
#include <nan.h>
Public Member Functions
NAN_INLINE MaybeLocal ()
template<typename S >
NAN_INLINE MaybeLocal (v8::Local< S > that)
NAN_INLINE bool IsEmpty () const
template<typename S >
NAN_INLINE bool ToLocal (v8::Local< S > *out) const
NAN_INLINE v8::Local< T > ToLocalChecked () const
template<typename S >
NAN_INLINE v8::Local< S > FromMaybe (v8::Local< S > default_value) const
Private Attributes
v8::Local< T > val_
Detailed Description
template<typename T>
class Nan::MaybeLocal< T >
Definition at line 788 of file nan.h.
Constructor & Destructor Documentation
NAN_INLINE MaybeLocal () [inline]
Definition at line 790 of file nan.h.
NAN_INLINE MaybeLocal (v8::Local< S > that) [inline]
Definition at line 796 of file nan.h.
Member Function Documentation
NAN_INLINE v8::Local<S> FromMaybe (v8::Local< S > default_value) const [inline]
Definition at line 816 of file nan.h.
NAN_INLINE bool IsEmpty () const [inline]
Definition at line 800 of file nan.h.
NAN_INLINE bool ToLocal (v8::Local< S > * out) const [inline]
Definition at line 803 of file nan.h.
Referenced by CustomImporterBridge::check_returned_string(), and create_string().
NAN_INLINE v8::Local<T> ToLocalChecked () const [inline]
Definition at line 808 of file nan.h.
References Nan::MakeCallback(), MakeCallback(), and Nan::New().
Field Documentation
v8::Local<T> val_ [private]
Definition at line 821 of file nan.h.
The documentation for this class was generated from the following file:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan.h