Emeraldion Lodge (codename Zelda): To_C Class Reference
To_C Class Reference
#include <to_c.hpp>
Inherits Operation_CRTP< Sass_Value *, To_C >.
Public Member Functions
To_C ()
virtual ~To_C ()
Sass_Value * operator() (Boolean *)
Sass_Value * operator() (Number *)
Sass_Value * operator() (Color *)
Sass_Value * operator() (String_Constant *)
Sass_Value * operator() (List *)
Sass_Value * operator() (Map *)
Sass_Value * operator() (Null *)
Sass_Value * operator() (Arguments *)
Sass_Value * operator() (Argument *)
template<typename U >
Sass_Value * fallback (U x)
Private Member Functions
Sass_Value * fallback_impl (AST_Node *n)
Detailed Description
Definition at line 18 of file to_c.hpp.
Constructor & Destructor Documentation
To_C () [inline]
Definition at line 24 of file to_c.hpp.
virtual ~To_C () [inline, virtual]
Definition at line 25 of file to_c.hpp.
Member Function Documentation
Sass_Value* fallback (U x) [inline]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 39 of file to_c.hpp.
References To_C::fallback_impl().
Sass_Value * fallback_impl (AST_Node * n) [private]
Definition at line 9 of file to_c.cpp.
References sass_make_null().
Referenced by To_C::fallback().
Sass_Value * operator() (Argument * a) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 54 of file to_c.cpp.
Sass_Value * operator() (Arguments * a) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 45 of file to_c.cpp.
References Vectorized< T >::length(), SASS_COMMA, sass_list_set_value(), and sass_make_list().
Sass_Value * operator() (Null * n) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 58 of file to_c.cpp.
References sass_make_null().
Sass_Value * operator() (Map * m) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 33 of file to_c.cpp.
References Hashed::at(), Hashed::keys(), Hashed::length(), sass_make_map(), sass_map_set_key(), and sass_map_set_value().
Sass_Value * operator() (List * l) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 24 of file to_c.cpp.
References List::COMMA, Vectorized< T >::length(), SASS_COMMA, sass_list_set_value(), sass_make_list(), and SASS_SPACE.
Sass_Value * operator() (String_Constant * s) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 21 of file to_c.cpp.
References sass_make_string().
Sass_Value * operator() (Color * c) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 18 of file to_c.cpp.
References sass_make_color().
Sass_Value * operator() (Number * n) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 15 of file to_c.cpp.
References sass_make_number(), and Number::unit().
Sass_Value * operator() (Boolean * b) [virtual]
Reimplemented from Operation_CRTP< Sass_Value *, To_C >.
Definition at line 12 of file to_c.cpp.
References sass_make_boolean().
The documentation for this class was generated from the following files:
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/to_c.hpp
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/src/libsass/to_c.cpp