Emeraldion Lodge (codename Zelda): Sass::Functions Namespace Reference
Sass::Functions Namespace Reference
Data Structures
struct HSL
Functions
template<typename T >
T * get_arg (const string &argname, Env &env, Signature sig, ParserState pstate, Backtrace *backtrace)
Map * get_arg_m (const string &argname, Env &env, Signature sig, ParserState pstate, Backtrace *backtrace, Context &ctx)
Number * get_arg_r (const string &argname, Env &env, Signature sig, ParserState pstate, double lo, double hi, Backtrace *backtrace)
uint64_t GetSeed ()
static mt19937 rand (static_cast< unsigned int >(GetSeed()))
double color_num (Number *n)
BUILT_IN (rgb)
BUILT_IN (rgba_4)
BUILT_IN (rgba_2)
BUILT_IN (red)
BUILT_IN (green)
BUILT_IN (blue)
BUILT_IN (mix)
HSL rgb_to_hsl (double r, double g, double b)
double h_to_rgb (double m1, double m2, double h)
Color * hsla_impl (double h, double s, double l, double a, Context &ctx, ParserState pstate)
BUILT_IN (hsl)
BUILT_IN (hsla)
BUILT_IN (hue)
BUILT_IN (saturation)
BUILT_IN (lightness)
BUILT_IN (adjust_hue)
BUILT_IN (lighten)
BUILT_IN (darken)
BUILT_IN (saturate)
BUILT_IN (desaturate)
BUILT_IN (grayscale)
BUILT_IN (complement)
BUILT_IN (invert)
BUILT_IN (alpha)
BUILT_IN (opacify)
BUILT_IN (transparentize)
BUILT_IN (adjust_color)
BUILT_IN (scale_color)
BUILT_IN (change_color)
template<size_t range>
static double cap_channel (double c)
BUILT_IN (ie_hex_str)
BUILT_IN (sass_unquote)
BUILT_IN (sass_quote)
BUILT_IN (str_length)
BUILT_IN (str_insert)
BUILT_IN (str_index)
BUILT_IN (str_slice)
BUILT_IN (to_upper_case)
BUILT_IN (to_lower_case)
BUILT_IN (percentage)
BUILT_IN (round)
BUILT_IN (ceil)
BUILT_IN (floor)
BUILT_IN (abs)
BUILT_IN (min)
BUILT_IN (max)
BUILT_IN (random)
BUILT_IN (length)
BUILT_IN (nth)
BUILT_IN (set_nth)
BUILT_IN (index)
BUILT_IN (join)
BUILT_IN (append)
BUILT_IN (zip)
BUILT_IN (list_separator)
BUILT_IN (map_get)
BUILT_IN (map_has_key)
BUILT_IN (map_keys)
BUILT_IN (map_values)
BUILT_IN (map_merge)
BUILT_IN (map_remove)
BUILT_IN (keywords)
BUILT_IN (type_of)
BUILT_IN (unit)
BUILT_IN (unitless)
BUILT_IN (comparable)
BUILT_IN (variable_exists)
BUILT_IN (global_variable_exists)
BUILT_IN (function_exists)
BUILT_IN (mixin_exists)
BUILT_IN (feature_exists)
BUILT_IN (call)
BUILT_IN (sass_not)
BUILT_IN (sass_if)
BUILT_IN (image_url)
BUILT_IN (inspect)
BUILT_IN (is_superselector)
BUILT_IN (unique_id)
Variables
static random_device rd
static set< string > features
global variable shadowing
static set< string > features
global variable at error
static set< string > features
global variable at units level
Signature rgb_sig = "rgb($red, $green, $blue)"
Signature rgba_4_sig = "rgba($red, $green, $blue, $alpha)"
Signature rgba_2_sig = "rgba($color, $alpha)"
Signature red_sig = "red($color)"
Signature green_sig = "green($color)"
Signature blue_sig = "blue($color)"
Signature mix_sig = "mix($color-1, $color-2, $weight: 50%)"
Signature hsl_sig = "hsl($hue, $saturation, $lightness)"
Signature hsla_sig = "hsla($hue, $saturation, $lightness, $alpha)"
Signature hue_sig = "hue($color)"
Signature saturation_sig = "saturation($color)"
Signature lightness_sig = "lightness($color)"
Signature adjust_hue_sig = "adjust-hue($color, $degrees)"
Signature lighten_sig = "lighten($color, $amount)"
Signature darken_sig = "darken($color, $amount)"
Signature saturate_sig = "saturate($color, $amount: false)"
Signature desaturate_sig = "desaturate($color, $amount)"
Signature grayscale_sig = "grayscale($color)"
Signature complement_sig = "complement($color)"
Signature invert_sig = "invert($color)"
Signature alpha_sig = "alpha($color)"
Signature opacity_sig = "opacity($color)"
Signature opacify_sig = "opacify($color, $amount)"
Signature fade_in_sig = "fade-in($color, $amount)"
Signature transparentize_sig = "transparentize($color, $amount)"
Signature fade_out_sig = "fade-out($color, $amount)"
Signature adjust_color_sig = "adjust-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)"
Signature scale_color_sig = "scale-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)"
Signature change_color_sig = "change-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)"
Signature ie_hex_str_sig = "ie-hex-str($color)"
Signature unquote_sig = "unquote($string)"
Signature quote_sig = "quote($string)"
Signature str_length_sig = "str-length($string)"
Signature str_insert_sig = "str-insert($string, $insert, $index)"
Signature str_index_sig = "str-index($string, $substring)"
Signature str_slice_sig = "str-slice($string, $start-at, $end-at:-1)"
Signature to_upper_case_sig = "to-upper-case($string)"
Signature to_lower_case_sig = "to-lower-case($string)"
Signature percentage_sig = "percentage($number)"
Signature round_sig = "round($number)"
Signature ceil_sig = "ceil($number)"
Signature floor_sig = "floor($number)"
Signature abs_sig = "abs($number)"
Signature min_sig = "min($numbers...)"
Signature max_sig = "max($numbers...)"
Signature random_sig = "random($limit:false)"
Signature length_sig = "length($list)"
Signature nth_sig = "nth($list, $n)"
Signature set_nth_sig = "set-nth($list, $n, $value)"
Signature index_sig = "index($list, $value)"
Signature join_sig = "join($list1, $list2, $separator: auto)"
Signature append_sig = "append($list, $val, $separator: auto)"
Signature zip_sig = "zip($lists...)"
Signature list_separator_sig = "list_separator($list)"
Signature map_get_sig = "map-get($map, $key)"
Signature map_has_key_sig = "map-has-key($map, $key)"
Signature map_keys_sig = "map-keys($map)"
Signature map_values_sig = "map-values($map)"
Signature map_merge_sig = "map-merge($map1, $map2)"
Signature map_remove_sig = "map-remove($map, $keys...)"
Signature keywords_sig = "keywords($args)"
Signature type_of_sig = "type-of($value)"
Signature unit_sig = "unit($number)"
Signature unitless_sig = "unitless($number)"
Signature comparable_sig = "comparable($number-1, $number-2)"
Signature variable_exists_sig = "variable-exists($name)"
Signature global_variable_exists_sig = "global-variable-exists($name)"
Signature function_exists_sig = "function-exists($name)"
Signature mixin_exists_sig = "mixin-exists($name)"
Signature feature_exists_sig = "feature-exists($name)"
Signature call_sig = "call($name, $args...)"
Signature not_sig = "not($value)"
Signature if_sig = "if($condition, $if-true, $if-false)"
Signature image_url_sig = "image-url($path, $only-path: false, $cache-buster: false)"
Signature inspect_sig = "inspect($value)"
Signature is_superselector_sig = "is-superselector($super, $sub)"
Signature unique_id_sig = "unique-id()"
Function Documentation
BUILT_IN (unique_id)
Definition at line 1582 of file functions.cpp.
References Sass::ctx, Sass::Prelexer::hex(), Context::mem, Sass::pstate, and rand().
BUILT_IN (is_superselector)
Definition at line 1568 of file functions.cpp.
References ARG, Sass::ctx, Selector_List::is_superselector_of(), Context::mem, Parser::parse_selector(), Sass::pstate, and Sass::to_string.
BUILT_IN (inspect)
Definition at line 1541 of file functions.cpp.
References ARG, Expression::BOOLEAN, Sass::ctx, Expression::LIST, Expression::MAP, Context::mem, Sass::NESTED, Expression::NULL_VAL, Context::output_style, Sass::pstate, Expression::STRING, and Sass::to_string.
BUILT_IN (image_url)
Definition at line 1530 of file functions.cpp.
References error, and Sass::pstate.
BUILT_IN (sass_if)
Definition at line 1511 of file functions.cpp.
References ARG, and Sass::ctx.
BUILT_IN (sass_not)
Definition at line 1505 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (call)
Definition at line 1473 of file functions.cpp.
References gyp::msvs_emulation::arg, ARG, Sass::ctx, Vectorized< T >::length(), Context::mem, Sass::Prelexer::name(), Sass::Util::normalize_underscores(), Sass::pstate, Sass::unquote(), and List::value_at_index().
BUILT_IN (feature_exists)
Definition at line 1460 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::pstate, s(), and Sass::unquote().
BUILT_IN (mixin_exists)
Definition at line 1447 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::Util::normalize_underscores(), Sass::pstate, s(), and Sass::unquote().
BUILT_IN (function_exists)
Definition at line 1434 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::Util::normalize_underscores(), Sass::pstate, s(), and Sass::unquote().
BUILT_IN (global_variable_exists)
Definition at line 1421 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::Util::normalize_underscores(), Sass::pstate, s(), and Sass::unquote().
BUILT_IN (variable_exists)
Definition at line 1408 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::Util::normalize_underscores(), Sass::pstate, s(), and Sass::unquote().
BUILT_IN (comparable)
Definition at line 1395 of file functions.cpp.
References ARG, Sass::ctx, Number::find_convertible_unit(), Number::is_unitless(), Context::mem, Number::normalize(), Sass::pstate, and Number::unit().
BUILT_IN (unitless)
Definition at line 1391 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (unit)
Definition at line 1387 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::pstate, and Sass::quote().
BUILT_IN (type_of)
Definition at line 1373 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Context::names_to_colors, Sass::pstate, Expression::STRING, and Sass::to_string.
BUILT_IN (keywords)
Definition at line 1355 of file functions.cpp.
References ARG, Sass::ctx, Vectorized< T >::length(), Context::mem, Sass::Prelexer::name(), Sass::pstate, and List::size().
BUILT_IN (map_remove)
Definition at line 1338 of file functions.cpp.
References ARG, ARGM, Hashed::at(), Sass::ctx, Sass::eq(), Hashed::keys(), Vectorized< T >::length(), Context::mem, Sass::pstate, and List::value_at_index().
BUILT_IN (map_merge)
Definition at line 1325 of file functions.cpp.
References ARGM, Sass::ctx, Hashed::length(), Context::mem, and Sass::pstate.
BUILT_IN (map_values)
Definition at line 1314 of file functions.cpp.
References ARGM, Hashed::at(), List::COMMA, Sass::ctx, Hashed::keys(), Hashed::length(), Context::mem, and Sass::pstate.
BUILT_IN (map_keys)
Definition at line 1303 of file functions.cpp.
References ARGM, List::COMMA, Sass::ctx, Hashed::keys(), Hashed::length(), Context::mem, and Sass::pstate.
BUILT_IN (map_has_key)
Definition at line 1295 of file functions.cpp.
References ARG, ARGM, Sass::ctx, Hashed::has(), Context::mem, and Sass::pstate.
BUILT_IN (map_get)
Definition at line 1282 of file functions.cpp.
References ARG, ARGM, Hashed::at(), Sass::ctx, Context::mem, Nan::Null(), and Sass::pstate.
BUILT_IN (list_separator)
Definition at line 1266 of file functions.cpp.
References ARG, List::COMMA, Sass::ctx, l(), Context::mem, and Sass::pstate.
BUILT_IN (zip)
Definition at line 1236 of file functions.cpp.
References ARG, List::COMMA, Sass::ctx, Vectorized< T >::length(), Context::mem, Sass::pstate, and List::value_at_index().
BUILT_IN (append)
Definition at line 1205 of file functions.cpp.
References ARG, List::COMMA, Sass::ctx, error, l(), Vectorized< T >::length(), Context::mem, Sass::pstate, List::SPACE, and Sass::unquote().
BUILT_IN (join)
Definition at line 1178 of file functions.cpp.
References ARG, List::COMMA, Sass::ctx, error, Vectorized< T >::length(), Context::mem, Sass::pstate, List::SPACE, and Sass::unquote().
BUILT_IN (index)
Definition at line 1163 of file functions.cpp.
References ARG, Sass::ctx, Sass::eq(), l(), Vectorized< T >::length(), Context::mem, Nan::Null(), Sass::pstate, and List::value_at_index().
BUILT_IN (set_nth)
Definition at line 1143 of file functions.cpp.
References ARG, Sass::ctx, Vectorized< T >::empty(), error, l(), Vectorized< T >::length(), Context::mem, and Sass::pstate.
BUILT_IN (nth)
Definition at line 1114 of file functions.cpp.
References ARG, Hashed::at(), Sass::ctx, Vectorized< T >::empty(), Hashed::empty(), error, Hashed::keys(), l(), Vectorized< T >::length(), Hashed::length(), Context::mem, Sass::pstate, and List::value_at_index().
BUILT_IN (length)
Definition at line 1099 of file functions.cpp.
References ARG, Sass::ctx, Hashed::length(), Expression::MAP, Context::mem, Sass::pstate, and List::size().
BUILT_IN (random)
Definition at line 1078 of file functions.cpp.
References Sass::ctx, error, l(), Context::mem, Sass::pstate, and rand().
BUILT_IN (max)
Definition at line 1063 of file functions.cpp.
References ARG, Sass::ctx, error, Vectorized< T >::length(), Sass::lt(), Sass::pstate, and List::value_at_index().
BUILT_IN (min)
Definition at line 1048 of file functions.cpp.
References ARG, Sass::ctx, error, Vectorized< T >::length(), Sass::lt(), Sass::pstate, and List::value_at_index().
BUILT_IN (abs)
Definition at line 1038 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (floor)
Definition at line 1028 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (ceil)
Definition at line 1018 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (round)
Definition at line 1008 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (percentage)
Definition at line 1000 of file functions.cpp.
References ARG, Sass::ctx, error, Number::is_unitless(), Context::mem, and Sass::pstate.
BUILT_IN (to_lower_case)
Definition at line 978 of file functions.cpp.
References ARG, Sass::ctx, Sass::Util::isAscii(), Context::mem, Sass::pstate, Sass::quote(), and s().
BUILT_IN (to_upper_case)
Definition at line 960 of file functions.cpp.
References ARG, Sass::ctx, Sass::Util::isAscii(), Context::mem, Sass::pstate, Sass::quote(), and s().
BUILT_IN (str_slice)
Definition at line 914 of file functions.cpp.
References utf8::unchecked::advance(), ARG, Sass::ctx, utf8::unchecked::distance(), error, Context::mem, Sass::pstate, Sass::quote(), s(), and Sass::unquote().
BUILT_IN (str_index)
Definition at line 879 of file functions.cpp.
References ARG, Sass::UTF_8::code_point_count(), Sass::ctx, error, Context::mem, npos, Nan::Null(), Sass::pstate, s(), and Sass::unquote().
BUILT_IN (str_insert)
Definition at line 823 of file functions.cpp.
References ARG, Sass::UTF_8::code_point_count(), Sass::ctx, error, Context::mem, Sass::UTF_8::offset_at_position(), Sass::pstate, Sass::quote(), s(), and Sass::unquote().
BUILT_IN (str_length)
Definition at line 797 of file functions.cpp.
References ARG, Sass::UTF_8::code_point_count(), Sass::ctx, error, Context::mem, npos, Sass::pstate, and s().
BUILT_IN (sass_quote)
Definition at line 785 of file functions.cpp.
References gyp::msvs_emulation::arg, Sass::ctx, String_Constant::double_quote(), Context::mem, Sass::pstate, Sass::quote(), and Sass::to_string.
BUILT_IN (sass_unquote)
Definition at line 768 of file functions.cpp.
References gyp::msvs_emulation::arg, Sass::ctx, Context::mem, Nan::Null(), Sass::pstate, Sass::to_string, and Sass::unquote().
BUILT_IN (ie_hex_str)
Definition at line 741 of file functions.cpp.
References a(), ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (change_color)
Definition at line 688 of file functions.cpp.
References a(), Sass::Prelexer::alpha(), ARG, ARGR, Sass::ctx, error, HSL::h, h(), hsla_impl(), HSL::l, l(), Context::mem, Sass::pstate, rgb_to_hsl(), HSL::s, and s().
BUILT_IN (scale_color)
Definition at line 634 of file functions.cpp.
References a(), Sass::Prelexer::alpha(), ARG, ARGR, Sass::ctx, error, HSL::h, h(), hsla_impl(), HSL::l, l(), Context::mem, Sass::pstate, rgb_to_hsl(), HSL::s, and s().
BUILT_IN (adjust_color)
Definition at line 588 of file functions.cpp.
References a(), ARG, Sass::ctx, error, HSL::h, h(), hsla_impl(), HSL::l, l(), Context::mem, Sass::pstate, rgb_to_hsl(), HSL::s, and s().
BUILT_IN (transparentize)
Definition at line 571 of file functions.cpp.
References Sass::Prelexer::alpha(), ARG, ARGR, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (opacify)
Definition at line 557 of file functions.cpp.
References Sass::Prelexer::alpha(), ARG, ARGR, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (alpha)
Definition at line 538 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::pstate, and Sass::to_string.
BUILT_IN (invert)
Definition at line 516 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::pstate, and Sass::to_string.
BUILT_IN (complement)
Definition at line 501 of file functions.cpp.
References ARG, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Sass::pstate, rgb_to_hsl(), and HSL::s.
BUILT_IN (grayscale)
Definition at line 479 of file functions.cpp.
References ARG, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Context::mem, Sass::pstate, rgb_to_hsl(), and Sass::to_string.
BUILT_IN (desaturate)
Definition at line 452 of file functions.cpp.
References ARG, ARGR, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Sass::pstate, rgb_to_hsl(), and HSL::s.
BUILT_IN (saturate)
Definition at line 418 of file functions.cpp.
References ARG, ARGR, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Context::mem, Sass::pstate, rgb_to_hsl(), HSL::s, and Sass::to_string.
BUILT_IN (darken)
Definition at line 395 of file functions.cpp.
References ARG, ARGR, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Sass::pstate, rgb_to_hsl(), and HSL::s.
BUILT_IN (lighten)
Definition at line 373 of file functions.cpp.
References ARG, ARGR, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Sass::pstate, rgb_to_hsl(), and HSL::s.
BUILT_IN (adjust_hue)
Definition at line 357 of file functions.cpp.
References ARG, Sass::ctx, HSL::h, hsla_impl(), HSL::l, Sass::pstate, rgb_to_hsl(), and HSL::s.
BUILT_IN (lightness)
Definition at line 347 of file functions.cpp.
References ARG, Sass::ctx, HSL::l, Context::mem, Sass::pstate, and rgb_to_hsl().
BUILT_IN (saturation)
Definition at line 337 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, Sass::pstate, rgb_to_hsl(), and HSL::s.
BUILT_IN (hue)
Definition at line 327 of file functions.cpp.
References ARG, Sass::ctx, HSL::h, Context::mem, Sass::pstate, and rgb_to_hsl().
BUILT_IN (hsla)
Definition at line 316 of file functions.cpp.
References ARG, ARGR, Sass::ctx, hsla_impl(), and Sass::pstate.
BUILT_IN (hsl)
Definition at line 305 of file functions.cpp.
References ARG, ARGR, Sass::ctx, hsla_impl(), and Sass::pstate.
BUILT_IN (mix)
Definition at line 210 of file functions.cpp.
References a(), ARG, ARGR, Sass::ctx, Context::mem, p(), and Sass::pstate.
BUILT_IN (blue)
Definition at line 206 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (green)
Definition at line 202 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (red)
Definition at line 198 of file functions.cpp.
References ARG, Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (rgba_2)
Definition at line 188 of file functions.cpp.
References ARG, ARGR, Sass::ctx, and Context::mem.
BUILT_IN (rgba_4)
Definition at line 178 of file functions.cpp.
References ARGR, color_num(), Sass::ctx, Context::mem, and Sass::pstate.
BUILT_IN (rgb)
Definition at line 169 of file functions.cpp.
References ARGR, color_num(), Sass::ctx, Context::mem, and Sass::pstate.
static double Sass::Functions::cap_channel (double c) [inline, static]
Definition at line 734 of file functions.cpp.
double Sass::Functions::color_num (Number * n) [inline]
Definition at line 160 of file functions.cpp.
References Number::unit().
Referenced by BUILT_IN().
T* Sass::Functions::get_arg (const string & argname, Env & env, Signature sig, ParserState pstate, Backtrace * backtrace) [inline]
Definition at line 77 of file functions.cpp.
References error.
Map* Sass::Functions::get_arg_m (const string & argname, Env & env, Signature sig, ParserState pstate, Backtrace * backtrace, Context & ctx)
Definition at line 93 of file functions.cpp.
References Vectorized< T >::length(), and Context::mem.
Number* Sass::Functions::get_arg_r (const string & argname, Env & env, Signature sig, ParserState pstate, double lo, double hi, Backtrace * backtrace)
Definition at line 107 of file functions.cpp.
References error.
uint64_t Sass::Functions::GetSeed ()
Definition at line 137 of file functions.cpp.
References rd.
double Sass::Functions::h_to_rgb (double m1, double m2, double h)
Definition at line 269 of file functions.cpp.
Referenced by hsla_impl().
Color* Sass::Functions::hsla_impl (double h, double s, double l, double a, Context & ctx, ParserState pstate)
Definition at line 278 of file functions.cpp.
References h_to_rgb(), and Context::mem.
Referenced by BUILT_IN().
static mt19937 Sass::Functions::rand (static_cast< unsigned int > GetSeed()) [static]
Referenced by BUILT_IN(), Antispam::init_math_test(), and Antispam::random_comment().
HSL Sass::Functions::rgb_to_hsl (double r, double g, double b)
Definition at line 236 of file functions.cpp.
References HSL::h, h(), HSL::l, l(), HSL::s, and s().
Referenced by BUILT_IN().
Variable Documentation
Signature abs_sig = "abs($number)"
Definition at line 1037 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature adjust_color_sig = "adjust-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)"
Definition at line 587 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature adjust_hue_sig = "adjust-hue($color, $degrees)"
Definition at line 356 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature alpha_sig = "alpha($color)"
Definition at line 536 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature append_sig = "append($list, $val, $separator: auto)"
Definition at line 1204 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature blue_sig = "blue($color)"
Definition at line 205 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature call_sig = "call($name, $args...)"
Definition at line 1472 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature ceil_sig = "ceil($number)"
Definition at line 1017 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature change_color_sig = "change-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)"
Definition at line 687 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature comparable_sig = "comparable($number-1, $number-2)"
Definition at line 1394 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature complement_sig = "complement($color)"
Definition at line 500 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature darken_sig = "darken($color, $amount)"
Definition at line 394 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature desaturate_sig = "desaturate($color, $amount)"
Definition at line 451 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
set<string> features global variable at error [static]
Definition at line 151 of file functions.cpp.
Referenced by BUILT_IN(), get_arg(), and get_arg_r().
Signature fade_in_sig = "fade-in($color, $amount)"
Definition at line 556 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature fade_out_sig = "fade-out($color, $amount)"
Definition at line 570 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature feature_exists_sig = "feature-exists($name)"
Definition at line 1459 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature floor_sig = "floor($number)"
Definition at line 1027 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature function_exists_sig = "function-exists($name)"
Definition at line 1433 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature global_variable_exists_sig = "global-variable-exists($name)"
Definition at line 1420 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature grayscale_sig = "grayscale($color)"
Definition at line 478 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature green_sig = "green($color)"
Definition at line 201 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature hsl_sig = "hsl($hue, $saturation, $lightness)"
Definition at line 304 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature hsla_sig = "hsla($hue, $saturation, $lightness, $alpha)"
Definition at line 315 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature hue_sig = "hue($color)"
Definition at line 326 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature ie_hex_str_sig = "ie-hex-str($color)"
Definition at line 740 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature if_sig = "if($condition, $if-true, $if-false)"
Definition at line 1508 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature image_url_sig = "image-url($path, $only-path: false, $cache-buster: false)"
Definition at line 1529 of file functions.cpp.
Signature index_sig = "index($list, $value)"
Definition at line 1162 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature inspect_sig = "inspect($value)"
Definition at line 1540 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature invert_sig = "invert($color)"
Definition at line 515 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature is_superselector_sig = "is-superselector($super, $sub)"
Definition at line 1567 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature join_sig = "join($list1, $list2, $separator: auto)"
Definition at line 1177 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature keywords_sig = "keywords($args)"
Definition at line 1354 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature length_sig = "length($list)"
Definition at line 1098 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
set<string> features global variable at units level [static]
Definition at line 151 of file functions.cpp.
Referenced by Markdown_Parser::hashHTMLBlocks(), and Sass::Prelexer::skip_over_scopes().
Signature lighten_sig = "lighten($color, $amount)"
Definition at line 372 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature lightness_sig = "lightness($color)"
Definition at line 346 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature list_separator_sig = "list_separator($list)"
Definition at line 1265 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature map_get_sig = "map-get($map, $key)"
Definition at line 1281 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature map_has_key_sig = "map-has-key($map, $key)"
Definition at line 1294 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature map_keys_sig = "map-keys($map)"
Definition at line 1302 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature map_merge_sig = "map-merge($map1, $map2)"
Definition at line 1324 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature map_remove_sig = "map-remove($map, $keys...)"
Definition at line 1337 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature map_values_sig = "map-values($map)"
Definition at line 1313 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature max_sig = "max($numbers...)"
Definition at line 1062 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature min_sig = "min($numbers...)"
Definition at line 1047 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature mix_sig = "mix($color-1, $color-2, $weight: 50%)"
Definition at line 209 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature mixin_exists_sig = "mixin-exists($name)"
Definition at line 1446 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature not_sig = "not($value)"
Definition at line 1504 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature nth_sig = "nth($list, $n)"
Definition at line 1113 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature opacify_sig = "opacify($color, $amount)"
Definition at line 555 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature opacity_sig = "opacity($color)"
Definition at line 537 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature percentage_sig = "percentage($number)"
Definition at line 999 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature quote_sig = "quote($string)"
Definition at line 784 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature random_sig = "random($limit:false)"
Definition at line 1077 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
random_device rd [static]
Definition at line 136 of file functions.cpp.
Referenced by GetSeed().
Signature red_sig = "red($color)"
Definition at line 197 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature rgb_sig = "rgb($red, $green, $blue)"
Definition at line 168 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature rgba_2_sig = "rgba($color, $alpha)"
Definition at line 187 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature rgba_4_sig = "rgba($red, $green, $blue, $alpha)"
Definition at line 177 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature round_sig = "round($number)"
Definition at line 1007 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature saturate_sig = "saturate($color, $amount: false)"
Definition at line 417 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature saturation_sig = "saturation($color)"
Definition at line 336 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature scale_color_sig = "scale-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)"
Definition at line 633 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature set_nth_sig = "set-nth($list, $n, $value)"
Definition at line 1142 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
set<string> features global variable shadowing [static]
Definition at line 151 of file functions.cpp.
Signature str_index_sig = "str-index($string, $substring)"
Definition at line 878 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature str_insert_sig = "str-insert($string, $insert, $index)"
Definition at line 822 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature str_length_sig = "str-length($string)"
Definition at line 796 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature str_slice_sig = "str-slice($string, $start-at, $end-at:-1)"
Definition at line 913 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature to_lower_case_sig = "to-lower-case($string)"
Definition at line 977 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature to_upper_case_sig = "to-upper-case($string)"
Definition at line 959 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature transparentize_sig = "transparentize($color, $amount)"
Definition at line 569 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature type_of_sig = "type-of($value)"
Definition at line 1372 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature unique_id_sig = "unique-id()"
Definition at line 1581 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature unit_sig = "unit($number)"
Definition at line 1386 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature unitless_sig = "unitless($number)"
Definition at line 1390 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature unquote_sig = "unquote($string)"
Definition at line 767 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature variable_exists_sig = "variable-exists($name)"
Definition at line 1407 of file functions.cpp.
Referenced by Sass::register_built_in_functions().
Signature zip_sig = "zip($lists...)"
Definition at line 1235 of file functions.cpp.
Referenced by Sass::register_built_in_functions().