Emeraldion Lodge (codename Zelda): /Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_maybe_43_inl.h File Reference
/Users/delphine/Development/SVN/emeraldion.it/zelda/node_modules/gulp-sass/node_modules/node-sass/node_modules/nan/nan_maybe_43_inl.h File Reference
Functions
template<typename T >
NAN_INLINE Maybe< T > Nothing ()
template<typename T >
NAN_INLINE Maybe< T > Just (const T &t)
v8::Local< v8::Context > GetCurrentContext ()
NAN_INLINE MaybeLocal< v8::String > ToDetailString (v8::Local< v8::Value > val)
NAN_INLINE MaybeLocal< v8::Uint32 > ToArrayIndex (v8::Local< v8::Value > val)
NAN_INLINE Maybe< bool > Equals (v8::Local< v8::Value > a, v8::Local< v8::Value >(b))
NAN_INLINE MaybeLocal< v8::Object > NewInstance (v8::Local< v8::Function > h)
NAN_INLINE MaybeLocal< v8::Object > NewInstance (v8::Local< v8::Function > h, int argc, v8::Local< v8::Value > argv[])
NAN_INLINE MaybeLocal< v8::Object > NewInstance (v8::Local< v8::ObjectTemplate > h)
NAN_INLINE MaybeLocal
< v8::Function > GetFunction (v8::Local< v8::FunctionTemplate > t)
NAN_INLINE Maybe< bool > Set (v8::Local< v8::Object > obj, v8::Local< v8::Value > key, v8::Local< v8::Value > value)
NAN_INLINE Maybe< bool > Set (v8::Local< v8::Object > obj, uint32_t index, v8::Local< v8::Value > value)
NAN_INLINE Maybe< bool > ForceSet (v8::Local< v8::Object > obj, v8::Local< v8::Value > key, v8::Local< v8::Value > value, v8::PropertyAttribute attribs=v8::None)
NAN_INLINE MaybeLocal< v8::Value > Get (v8::Local< v8::Object > obj, v8::Local< v8::Value > key)
NAN_INLINE MaybeLocal< v8::Value > Get (v8::Local< v8::Object > obj, uint32_t index)
NAN_INLINE v8::PropertyAttribute GetPropertyAttributes (v8::Local< v8::Object > obj, v8::Local< v8::Value > key)
NAN_INLINE Maybe< bool > Has (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE Maybe< bool > Has (v8::Local< v8::Object > obj, uint32_t index)
NAN_INLINE Maybe< bool > Delete (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE Maybe< bool > Delete (v8::Local< v8::Object > obj, uint32_t index)
NAN_INLINE MaybeLocal< v8::Array > GetPropertyNames (v8::Local< v8::Object > obj)
NAN_INLINE MaybeLocal< v8::Array > GetOwnPropertyNames (v8::Local< v8::Object > obj)
NAN_INLINE Maybe< bool > SetPrototype (v8::Local< v8::Object > obj, v8::Local< v8::Value > prototype)
NAN_INLINE MaybeLocal< v8::String > ObjectProtoToString (v8::Local< v8::Object > obj)
NAN_INLINE Maybe< bool > HasOwnProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE Maybe< bool > HasRealNamedProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE Maybe< bool > HasRealIndexedProperty (v8::Local< v8::Object > obj, uint32_t index)
NAN_INLINE Maybe< bool > HasRealNamedCallbackProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE MaybeLocal< v8::Value > GetRealNamedPropertyInPrototypeChain (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE MaybeLocal< v8::Value > GetRealNamedProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
NAN_INLINE MaybeLocal< v8::Value > CallAsFunction (v8::Local< v8::Object > obj, v8::Local< v8::Object > recv, int argc, v8::Local< v8::Value > argv[])
NAN_INLINE MaybeLocal< v8::Value > CallAsConstructor (v8::Local< v8::Object > obj, int argc, v8::Local< v8::Value > argv[])
NAN_INLINE MaybeLocal< v8::String > GetSourceLine (v8::Local< v8::Message > msg)
NAN_INLINE Maybe< int > GetLineNumber (v8::Local< v8::Message > msg)
NAN_INLINE Maybe< int > GetStartColumn (v8::Local< v8::Message > msg)
NAN_INLINE Maybe< int > GetEndColumn (v8::Local< v8::Message > msg)
NAN_INLINE MaybeLocal< v8::Object > CloneElementAt (v8::Local< v8::Array > array, uint32_t index)
Function Documentation
NAN_INLINE MaybeLocal<v8::Value> CallAsConstructor (v8::Local< v8::Object > obj, int argc, v8::Local< v8::Value > argv[])
Definition at line 195 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Value> CallAsFunction (v8::Local< v8::Object > obj, v8::Local< v8::Object > recv, int argc, v8::Local< v8::Value > argv[])
Definition at line 187 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Object> CloneElementAt (v8::Local< v8::Array > array, uint32_t index)
Definition at line 218 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Delete (v8::Local< v8::Object > obj, uint32_t index)
Definition at line 126 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Delete (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 119 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Equals (v8::Local< v8::Value > a, v8::Local< v8::Value > b)
Definition at line 41 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> ForceSet (v8::Local< v8::Object > obj, v8::Local< v8::Value > key, v8::Local< v8::Value > value, v8::PropertyAttribute attribs = v8::None)
Definition at line 84 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Value> Get (v8::Local< v8::Object > obj, uint32_t index)
Definition at line 99 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Value> Get (v8::Local< v8::Object > obj, v8::Local< v8::Value > key)
Definition at line 92 of file nan_maybe_43_inl.h.
References GetCurrentContext().
Referenced by CustomImporterBridge::get_importer_entry(), and CustomImporterBridge::post_process_return_value().
v8::Local<v8::Context> GetCurrentContext ()
Definition at line 2763 of file nan.h.
Referenced by CallAsConstructor(), CallAsFunction(), CloneElementAt(), Delete(), Equals(), ForceSet(), Get(), GetEndColumn(), GetFunction(), GetLineNumber(), GetOwnPropertyNames(), GetPropertyAttributes(), GetPropertyNames(), GetRealNamedProperty(), GetRealNamedPropertyInPrototypeChain(), PropertyCallbackInfo< T >::GetReturnValue(), GetSourceLine(), GetStartColumn(), Has(), HasOwnProperty(), HasRealIndexedProperty(), HasRealNamedCallbackProperty(), HasRealNamedProperty(), NewInstance(), ObjectProtoToString(), Set(), SetPrototype(), ToArrayIndex(), and ToDetailString().
NAN_INLINE Maybe<int> GetEndColumn (v8::Local< v8::Message > msg)
Definition at line 214 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Function> GetFunction (v8::Local< v8::FunctionTemplate > t)
Definition at line 65 of file nan_maybe_43_inl.h.
References GetCurrentContext().
Referenced by Null::get_constructor(), and Boolean::get_constructor().
NAN_INLINE Maybe<int> GetLineNumber (v8::Local< v8::Message > msg)
Definition at line 206 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Array> GetOwnPropertyNames (v8::Local< v8::Object > obj)
Definition at line 136 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE v8::PropertyAttribute GetPropertyAttributes (v8::Local< v8::Object > obj, v8::Local< v8::Value > key)
Definition at line 103 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Array> GetPropertyNames (v8::Local< v8::Object > obj)
Definition at line 131 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Value> GetRealNamedProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 181 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Value> GetRealNamedPropertyInPrototypeChain (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 175 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::String> GetSourceLine (v8::Local< v8::Message > msg)
Definition at line 202 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<int> GetStartColumn (v8::Local< v8::Message > msg)
Definition at line 210 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Has (v8::Local< v8::Object > obj, uint32_t index)
Definition at line 115 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Has (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 109 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> HasOwnProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 151 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> HasRealIndexedProperty (v8::Local< v8::Object > obj, uint32_t index)
Definition at line 163 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> HasRealNamedCallbackProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 169 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> HasRealNamedProperty (v8::Local< v8::Object > obj, v8::Local< v8::String > key)
Definition at line 157 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<T> Just (const T & t) [inline]
Definition at line 24 of file nan_maybe_43_inl.h.
NAN_INLINE MaybeLocal<v8::Object> NewInstance (v8::Local< v8::ObjectTemplate > h)
Definition at line 60 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Object> NewInstance (v8::Local< v8::Function > h, int argc, v8::Local< v8::Value > argv[])
Definition at line 51 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Object> NewInstance (v8::Local< v8::Function > h)
Definition at line 46 of file nan_maybe_43_inl.h.
References GetCurrentContext().
Referenced by SassValueWrapper< T >::get_js_object(), Factory< v8::FunctionTemplate >::New(), and Factory< v8::Function >::New().
NAN_INLINE Maybe<T> Nothing () [inline]
Definition at line 19 of file nan_maybe_43_inl.h.
NAN_INLINE MaybeLocal<v8::String> ObjectProtoToString (v8::Local< v8::Object > obj)
Definition at line 146 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Set (v8::Local< v8::Object > obj, uint32_t index, v8::Local< v8::Value > value)
Definition at line 77 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE Maybe<bool> Set (v8::Local< v8::Object > obj, v8::Local< v8::Value > key, v8::Local< v8::Value > value)
Definition at line 70 of file nan_maybe_43_inl.h.
References GetCurrentContext().
Referenced by Null::get_constructor(), Boolean::get_constructor(), and SassTypes::NAN_MODULE_INIT().
NAN_INLINE Maybe<bool> SetPrototype (v8::Local< v8::Object > obj, v8::Local< v8::Value > prototype)
Definition at line 140 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::Uint32> ToArrayIndex (v8::Local< v8::Value > val)
Definition at line 36 of file nan_maybe_43_inl.h.
References GetCurrentContext().
NAN_INLINE MaybeLocal<v8::String> ToDetailString (v8::Local< v8::Value > val)
Definition at line 31 of file nan_maybe_43_inl.h.
References GetCurrentContext().